// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/sysinfo", new string[]
        {
            "cpuinfo_bsd.go",
            "cpuinfo_linux.go",
            "cpuinfo_stub.go",
            "export_test.go",
            "sysinfo.go",
            "sysinfo_test.go",
        });
        registry.Add("TestCPUName", sysinfo_test_package.TestCPUName, "sysinfo_test.go", 12);
        return TestHost.Run(registry, args);
    }
}
