// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("expvar", new string[]
        {
            "expvar.go",
            "expvar_test.go",
        });
        registry.Add("TestAppendJSONQuote", expvar_internal_test_package.TestAppendJSONQuote, "expvar_test.go", 654);
        registry.Add("TestFloat", expvar_internal_test_package.TestFloat, "expvar_test.go", 87);
        registry.Add("TestFunc", expvar_internal_test_package.TestFunc, "expvar_test.go", 457);
        registry.Add("TestHandler", expvar_internal_test_package.TestHandler, "expvar_test.go", 474);
        registry.Add("TestInt", expvar_internal_test_package.TestInt, "expvar_test.go", 41);
        registry.Add("TestMapCounter", expvar_internal_test_package.TestMapCounter, "expvar_test.go", 230);
        registry.Add("TestMapDelete", expvar_internal_test_package.TestMapDelete, "expvar_test.go", 187);
        registry.Add("TestMapInit", expvar_internal_test_package.TestMapInit, "expvar_test.go", 165);
        registry.Add("TestMapNil", expvar_internal_test_package.TestMapNil, "expvar_test.go", 270);
        registry.Add("TestNil", expvar_internal_test_package.TestNil, "expvar_test.go", 33);
        registry.Add("TestString", expvar_internal_test_package.TestString, "expvar_test.go", 133);
        return TestHost.Run(registry, args);
    }
}
