// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
namespace go.@internal;

using Δtrace = go.@internal.trace_package;
using testtrace = go.@internal.trace.testtrace_package;
using io = io_package;
using os = os_package;
using filepath = path.filepath_package;
using testing = testing_package;
using go.@internal;
using go.@internal.trace;
using path;
using static go.@internal.trace_internal_test_package;

partial class trace_test_package {

// Go runs an imported package's `init` before this package's own; .NET would never load
// an assembly nothing has touched yet, so that initialization is forced here.
[GoInit] internal static void initᴛᴛimportꓸos() {
    builtin.initPackage(typeof(os_package));
}

// Go runs an imported package's `init` before this package's own; .NET would never load
// an assembly nothing has touched yet, so that initialization is forced here.
[GoInit] internal static void initᴛᴛimportꓸpathꓸfilepath() {
    builtin.initPackage(typeof(path.filepath_package));
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string internalOldtraceTestdataˢ = "./internal/oldtrace/testdata/*_good"u8;
internal static readonly @string internalOldtraceTestdataˢ2 = "./internal/oldtrace/testdata"u8;
internal static readonly object didnTSeeExpectedTestCaseˢ = (@string)"didn't see expected test case user_task_region_1_21_good"u8;

public static void TestOldtrace(ж<testing.T> Ꮡt) {
    ref var t = ref Ꮡt.DerefOrNull();

    var (traces, err) = filepath.Glob(internalOldtraceTestdataˢ);
    if (err != default!) {
        Ꮡt.Fatalf("failed to glob for tests: %s"u8, err);
    }
    bool testedUserRegions = default!;
    foreach (var (_, p) in traces) {
        @string pΔ1 = p;
        var (testName, errΔ1) = filepath.Rel(internalOldtraceTestdataˢ2, pΔ1);
        if (errΔ1 != default!) {
            Ꮡt.Fatalf("failed to relativize testdata path: %s"u8, errΔ1);
        }
        Ꮡt.Run(testName, (ж<testing.T> tΔ1) => {
            GoFrame ᒐ = default;
            try {
                var (f, errΔ2) = os.Open(pΔ1);
                if (errΔ2 != default!) {
                    tΔ1.Fatalf("failed to open test %q: %s"u8, pΔ1, errΔ2);
                }
                var fʗ1 = f;
                defer(() => fʗ1.Close(), ref ᒐ);
                (var tr, errΔ2) = Δtrace.NewReader(new trace_test_package.os_FileжReader(f));
                if (errΔ2 != default!) {
                    tΔ1.Fatalf("failed to create reader: %s"u8, errΔ2);
                }
                var v = testtrace.NewValidator();
                v.Value.Go121 = true;
                while (ᐧ) {
                    var (ev, errΔ3) = tr.ReadEvent();
                    if (errΔ3 != default!) {
                        if (AreEqual(errΔ3, io.EOF)) {
                            break;
                        }
                        tΔ1.Fatalf("couldn't read converted event: %s"u8, errΔ3);
                    }
                    {
                        var errΔ4 = v.Event(ev); if (errΔ4 != default!) {
                            tΔ1.Fatalf("converted event did not validate; event: \n%s\nerror: %s"u8, ev, errΔ4);
                        }
                    }
                    if (testName == "user_task_region_1_21_good"u8) {
                        testedUserRegions = true;
                        var validRegions = new map<@string, EmptyStruct>{
                            ["post-existing region"u8] = new EmptyStruct(),
                            ["region0"u8] = new EmptyStruct(),
                            ["region1"u8] = new EmptyStruct()
                        };
                        // Check that we correctly convert user regions. These
                        // strings were generated by
                        // runtime/trace.TestUserTaskRegion, which is the basis for
                        // the user_task_region_* test cases. We only check for the
                        // Go 1.21 traces because earlier traces used different
                        // strings.
                        var exprᴛ1 = ev.Kind();
                        if (exprᴛ1 == Δtrace.EventRegionBegin || exprᴛ1 == Δtrace.EventRegionEnd) {
                            {
                                var (_, ok) = validRegions[ev.Region().Type, ꟷ]; if (!ok) {
                                    tΔ1.Fatalf("converted event has unexpected region type:\n%s"u8, ev);
                                }
                            }
                        }
                        else if (exprᴛ1 == Δtrace.EventTaskBegin || exprᴛ1 == Δtrace.EventTaskEnd) {
                            if (ev.Task().Type != "task0"u8) {
                                tΔ1.Fatalf("converted event has unexpected task type name:\n%s"u8, ev);
                            }
                        }
                        else if (exprᴛ1 == Δtrace.EventLog) {
                            var l = ev.Log();
                            if (l.Task != 1 || l.Category != "key0"u8 || l.Message != "0123456789abcdef"u8) {
                                tΔ1.Fatalf("converted event has unexpected user log:\n%s"u8, ev);
                            }
                        }

                    }
                }
            }
            catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
            finally { ᒐ.Run(); }
        });
    }
    if (!testedUserRegions) {
        Ꮡt.Fatal(didnTSeeExpectedTestCaseˢ);
    }
}

} // end trace_test_package
