// Code generated by go2cs. DO NOT EDIT.
// Test-variant package-level variable initialization ordered to match Go's
// dependency order (types.Info.InitOrder) — see package_init.cs. Each initᴛ
// method lives beside its variable's declaration in the converted test file.
namespace go.@internal;

partial class trace_internal_test_package {
    static trace_internal_test_package() {
        initᴛBandsPerSeries();
    }
} // end trace_internal_test_package
