package main

import "fmt"

// A generic struct satisfying an interface by VALUE. Two things about this shape are
// load-bearing, and both were broken until 2026-08-14:
//
//  1. The type name is a SINGLE letter. "G<T>" carries its '<' at index 1, and the
//     generator's drop-the-type-arguments helper admitted only index > 1, so the
//     argument list survived and the struct template wrote its constructor as
//     `public G<T>(NilType _)`. C# does not read that as a constructor, so the
//     `partial struct G<T>` scope never opened and every member the template emitted
//     — operators, Equals, GetHashCode, ToString — landed in the containing STATIC
//     package class (CS0715 + CS0708).
//
//  2. The same open generic is stored in the interface at SEVERAL instantiations.
//     Each is recorded separately, but a partial declaration can only extend the OPEN
//     definition: emitting `partial struct G<int>` reads `int` as a type-PARAMETER
//     name (CS0264) and spills the same way. One partial now serves them all, which
//     is also what Go means — a method on a generic type is declared for every
//     instantiation.
//
// Measured on internal/reflectlite (`B[T any]`) and runtime/debug (`G[T any]`); every
// multi-letter generic in the corpus cleared the guard, which is why it held so long.
type G[T any] struct {
	v T
}

type I interface {
	M() string
}

func (g G[T]) M() string { return fmt.Sprint(g.v) }

// A sibling type named exactly like the type PARAMETER. runtime/debug has this
// (`type T int` in stack_test.go beside `type G[T any]`), and it is what made the
// spilled members render as `debug_test_package.T` instead of naming a parameter.
type T int

func (t T) M() string { return fmt.Sprint(int(t)) }

func main() {
	// Three instantiations of one open generic, all held as the interface.
	var a I = G[int]{7}
	var b I = G[string]{"x"}
	var c I = G[G[int]]{G[int]{9}}
	var d I = T(3)
	fmt.Println(a.M(), b.M(), c.M(), d.M())

	// Struct equality operators, generated on the open form.
	fmt.Println(G[int]{7} == G[int]{7}, G[int]{7} == G[int]{8})
	fmt.Println(G[string]{"x"} == G[string]{"x"}, G[string]{"x"} == G[string]{"y"})

	// Struct/interface comparison operators, generated by the interface-impl partial.
	fmt.Println(a == G[int]{7}, a == G[int]{8}, b == G[string]{"x"}, d == T(3))

	// Dispatch through the interface for a slice of mixed instantiations.
	for _, item := range []I{a, b, c, d} {
		fmt.Print(item.M(), ";")
	}
	fmt.Println()
}
