// BehavioralPackages.cs - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// Use of this source code is governed by an MIT-style license
// that can be found in the LICENSE file.

// The ONE definition of "which Go packages does this behavioral project own, and in what order does
// the converter have to be invoked on them". LINKED by path into every instrument that transpiles a
// behavioral project, for the same reason ConverterBuildInputs.cs and PlatformExclusive.cs are: those
// instruments take no assembly dependency on one another, so a shared assembly is not available.
//
// It is hoisted here because the invariant it encodes is the one FALSE-GREEN ROUTE #3 was made of.
// Twenty-odd behavioral projects carry NESTED sub-library packages (IoLike\FsLike, VersionedImport\vlib,
// CrossPackageArrayZeroValue\bufpkg, ...). A sub-library's generated package_info.cs is an INPUT to its
// parent's transpile -- the parent reads the sibling's [assembly: GoImplement] records when deciding
// whether to mint a local value adapter -- so the walk must be DEEPEST-FIRST or the parent consumes
// stale-but-plausible records and its golden loses the ability to fail on a regression in that area.
// A top-level-only walk left those sub-libraries un-regenerated by any gate for months, and the damage
// was invisible precisely because each enumerator carried its own copy of the rule. Two copies existed
// when this file was written (BehavioralRunner and BehavioralTestBase); a golden-minting utility that
// re-derived it would have been a third.

using System;
using System.IO;
using System.Linq;

internal static class BehavioralPackages
{
    // A path fragment matching a build-output directory at any depth, built from the host's own
    // separator. The literal @"\bin\" these replaced does not ERROR off Windows -- it simply never
    // matches, so bin/ and obj/ enumerate as behavioral packages and get transpiled.
    private static readonly string s_binFragment = $"{Path.DirectorySeparatorChar}bin{Path.DirectorySeparatorChar}";
    private static readonly string s_objFragment = $"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}";

    /// <summary>
    /// The PRODUCTION Go sources in one package directory.
    /// </summary>
    /// <remarks>
    /// A production transpile converts the package's production sources only -- go/packages excludes
    /// <c>_test.go</c> -- so an in-package test file has no <c>.cs</c> and no golden, by design. It is
    /// still a real input: the converter scans the sibling test half for declarator names and for
    /// globals whose address it takes (SiblingTestAddressedGlobal guards the latter), which is why such
    /// a file exists in this corpus at all. Every per-<c>.go</c> loop in every enumerator therefore
    /// walks production sources, and a filter that forgot the exclusion would pin an up-to-date check
    /// permanently out of date.
    /// </remarks>
    public static string[] ProductionGoFiles(string packageDir) =>
        Directory.GetFiles(packageDir, "*.go")
            .Where(fileName => !fileName.EndsWith("_test.go", StringComparison.OrdinalIgnoreCase))
            .ToArray();

    /// <summary>
    /// Every Go package directory a behavioral project owns, DEEPEST-FIRST -- the order the converter
    /// must be invoked in.
    /// </summary>
    public static string[] GoPackageDirs(string projectDir) =>
        new[] { projectDir }
            .Concat(Directory.GetDirectories(projectDir, "*", SearchOption.AllDirectories)
                .Where(dirName => !dirName.Contains(s_binFragment, StringComparison.OrdinalIgnoreCase) &&
                                  !dirName.Contains(s_objFragment, StringComparison.OrdinalIgnoreCase))
                .Where(dirName => ProductionGoFiles(dirName).Length > 0))
            .OrderByDescending(dirName => dirName.Count(c => c == Path.DirectorySeparatorChar))
            .ThenBy(dirName => dirName, StringComparer.OrdinalIgnoreCase)
            .ToArray();
}
