// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("weak", new string[]
        {
            "doc.go",
            "pointer.go",
            "pointer_test.go",
        });
        registry.Add("TestIssue69210", weak_test_package.TestIssue69210, "pointer_test.go", 175);
        registry.Add("TestIssue70739", weak_test_package.TestIssue70739, "pointer_test.go", 247);
        registry.Add("TestPointer", weak_test_package.TestPointer, "pointer_test.go", 25);
        registry.Add("TestPointerEquality", weak_test_package.TestPointerEquality, "pointer_test.go", 54);
        registry.Add("TestPointerFinalizer", weak_test_package.TestPointerFinalizer, "pointer_test.go", 124);
        registry.Add("TestPointerSize", weak_test_package.TestPointerSize, "pointer_test.go", 160);
        return TestHost.Run(registry, args);
    }
}
