// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto.@internal.fips140;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/internal/fips140/aes", new string[]
        {
            "aes.go",
            "aes_asm.go",
            "aes_generic.go",
            "aes_noasm.go",
            "aes_s390x.go",
            "aes_test.go",
            "cast.go",
            "cbc.go",
            "cbc_noasm.go",
            "cbc_ppc64x.go",
            "cbc_s390x.go",
            "const.go",
            "ctr.go",
            "ctr_arm64_gen.go",
            "ctr_asm.go",
            "ctr_noasm.go",
            "ctr_s390x.go",
            "interface_test.go",
        }, new string[]
        {
            "_asm",
            "gcm",
        });
        registry.Add("TestMul", aes_internal_test_package.TestMul, "aes_test.go", 50);
        registry.Add("TestPowx", aes_internal_test_package.TestPowx, "aes_test.go", 13);
        registry.Add("TestSboxes", aes_internal_test_package.TestSboxes, "aes_test.go", 73);
        registry.Add("TestTd", aes_internal_test_package.TestTd, "aes_test.go", 104);
        registry.Add("TestTe", aes_internal_test_package.TestTe, "aes_test.go", 86);
        return TestHost.Run(registry, args);
    }
}
