// Code generated by "go test -run=Generate -write=all"; DO NOT EDIT.
// Source: ../../cmd/compile/internal/types2/context_test.go
// Copyright 2021 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
namespace go.go;

using testing = testing_package;
using static global::go.go.types_package;
using token = global::go.go.token_package;

partial class types_internal_test_package {

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly object hashCollisionsAreˢ = (@string)"hash collisions are expected, and would fail debug assertions"u8;
internal static readonly object badˢ = (@string)"bad"u8;

public static void TestContextHashCollisions(ж<testing.T> Ꮡt) {
    ref var t = ref Ꮡt.DerefOrNull();

    if (debug) {
        Ꮡt.Skip(hashCollisionsAreˢ);
    }
    // Unit test the de-duplication fall-back logic in Context.
    //
    // We can't test this via Instantiate because this is only a fall-back in
    // case our hash is imperfect.
    //
    // These lookups and updates use reasonable looking types in an attempt to
    // make them robust to internal type assertions, but could equally well use
    // arbitrary types.
    // Create some distinct origin types. nullaryP and nullaryQ have no
    // parameters and are identical (but have different type parameter names).
    // unaryP has a parameter.
    global::go.go.types_package.ΔType nullaryP = default!;
    global::go.go.types_package.ΔType nullaryQ = default!;
    global::go.go.types_package.ΔType unaryP = default!;
    {
        // type nullaryP = func[P any]()
        var tparam = NewTypeParam(NewTypeName(nopos, nil, "P"u8, default!), new global::go.go.types_package.InterfaceжΔType(ᏑemptyInterface));
        nullaryP = new types_test_package.types_ΔSignatureжΔType(NewSignatureType(nil, default!, new ж<global::go.go.types_package.TypeParam>[]{tparam}.slice(), nil, nil, false));
    }
    {
        // type nullaryQ = func[Q any]()
        var tparam = NewTypeParam(NewTypeName(nopos, nil, "Q"u8, default!), new global::go.go.types_package.InterfaceжΔType(ᏑemptyInterface));
        nullaryQ = new types_test_package.types_ΔSignatureжΔType(NewSignatureType(nil, default!, new ж<global::go.go.types_package.TypeParam>[]{tparam}.slice(), nil, nil, false));
    }
    {
        // type unaryP = func[P any](_ P)
        var tparam = NewTypeParam(NewTypeName(nopos, nil, "P"u8, default!), new global::go.go.types_package.InterfaceжΔType(ᏑemptyInterface));
        var @params = NewTuple(NewVar(nopos, nil, "_"u8, new global::go.go.types_package.TypeParamжΔType(tparam)));
        unaryP = new types_test_package.types_ΔSignatureжΔType(NewSignatureType(nil, default!, new ж<global::go.go.types_package.TypeParam>[]{tparam}.slice(), @params, nil, false));
    }
    var ctxt = NewContext();
    // Update the context with an instantiation of nullaryP.
    var inst = NewSignatureType(nil, default!, default!, nil, nil, false);
    {
        var got = ctxt.update(""u8, nullaryP, new global::go.go.types_package.ΔType[]{new global::go.go.types_package.BasicжΔType(Typ[Int])}.slice(), new types_test_package.types_ΔSignatureжΔType(inst)); if (!AreEqual(got, inst)) {
            Ꮡt.Error(badˢ);
        }
    }
    // unaryP is not identical to nullaryP, so we should not get inst when
    // instantiated with identical type arguments.
    {
        var got = ctxt.lookup(""u8, unaryP, new global::go.go.types_package.ΔType[]{new global::go.go.types_package.BasicжΔType(Typ[Int])}.slice()); if (got != default!) {
            Ꮡt.Error(badˢ);
        }
    }
    // nullaryQ is identical to nullaryP, so we *should* get inst when
    // instantiated with identical type arguments.
    {
        var got = ctxt.lookup(""u8, nullaryQ, new global::go.go.types_package.ΔType[]{new global::go.go.types_package.BasicжΔType(Typ[Int])}.slice()); if (!AreEqual(got, inst)) {
            Ꮡt.Error(badˢ);
        }
    }
    // ...but verify we don't get inst with different type arguments.
    {
        var got = ctxt.lookup(""u8, nullaryQ, new global::go.go.types_package.ΔType[]{new global::go.go.types_package.BasicжΔType(Typ[ΔString])}.slice()); if (got != default!) {
            Ꮡt.Error(badˢ);
        }
    }
}

} // end types_internal_test_package
