// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("html", new string[]
        {
            "entity.go",
            "entity_test.go",
            "escape.go",
            "escape_test.go",
            "example_test.go",
            "fuzz_test.go",
        }, new string[]
        {
            "template",
        });
        registry.Add("TestEntityLength", html_internal_test_package.TestEntityLength, "entity_test.go", 16);
        registry.Add("TestUnescape", html_internal_test_package.TestUnescape, "escape_test.go", 90);
        registry.Add("TestUnescapeEscape", html_internal_test_package.TestUnescapeEscape, "escape_test.go", 99);
        return TestHost.Run(registry, args);
    }
}
