// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal.runtime;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/runtime/math", new string[]
        {
            "math.go",
            "math_test.go",
        });
        registry.Add("TestMulUintptr", math_test_package.TestMulUintptr, "math_test.go", 39);
        return TestHost.Run(registry, args);
    }
}
