// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/hkdf", new string[]
        {
            "example_test.go",
            "hkdf.go",
            "hkdf_test.go",
        });
        registry.Add("TestFIPSServiceIndicator", hkdf_internal_test_package.TestFIPSServiceIndicator, "hkdf_test.go", 380);
        registry.Add("TestHKDF", hkdf_internal_test_package.TestHKDF, "hkdf_test.go", 299);
        registry.Add("TestHKDFLimit", hkdf_internal_test_package.TestHKDFLimit, "hkdf_test.go", 329);
        return TestHost.Run(registry, args);
    }
}
