// Copyright 2024 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Package hkdf implements the HMAC-based Extract-and-Expand Key Derivation
// Function (HKDF) as defined in RFC 5869.
//
// HKDF is a cryptographic key derivation function (KDF) with the goal of
// expanding limited input keying material into one or more cryptographically
// strong secret keys.
namespace go.crypto;

using hkdf = go.crypto.@internal.fips140.hkdf_package;
using fips140hash = go.crypto.@internal.fips140hash_package;
using fips140only = go.crypto.@internal.fips140only_package;
using errors = errors_package;
using hash = hash_package;
using fips140 = go.crypto.@internal.fips140_package;
using go.crypto.@internal;
using go.crypto.@internal.fips140;

partial class hkdf_package {

// Extract generates a pseudorandom key for use with [Expand] from an input
// secret and an optional independent salt.
//
// Only use this function if you need to reuse the extracted key with multiple
// Expand invocations and different context values. Most common scenarios,
// including the generation of multiple keys, should use [Key] instead.
public static (slice<byte>, error) Extract<H>(Func<H> h, slice<byte> secret, slice<byte> salt)
    where H : hash.Hash
{
    var fh = fips140hash.UnwrapNew(h);
    {
        var err = checkFIPS140Only(fh, secret); if (err != default!) {
            return (default!, err);
        }
    }
    return (hkdf.Extract(widen<hash.Hash, fips140.Hash>(fh, elemᴛ0 => new hash_HashᴠHash(elemᴛ0)), secret, salt), default!);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string hkdfRequestedKeyLengthˢ = "hkdf: requested key length too large"u8;

// Expand derives a key from the given hash, key, and optional context info,
// returning a []byte of length keyLength that can be used as cryptographic key.
// The extraction step is skipped.
//
// The key should have been generated by [Extract], or be a uniformly
// random or pseudorandom cryptographically strong key. See RFC 5869, Section
// 3.3. Most common scenarios will want to use [Key] instead.
public static (slice<byte>, error) Expand<H>(Func<H> h, slice<byte> pseudorandomKey, @string info, nint keyLength)
    where H : hash.Hash
{
    var fh = fips140hash.UnwrapNew(h);
    {
        var err = checkFIPS140Only(fh, pseudorandomKey); if (err != default!) {
            return (default!, err);
        }
    }
    nint limit = fh().Size() * 255;
    if (keyLength > limit) {
        return (default!, errors.New(hkdfRequestedKeyLengthˢ));
    }
    return (hkdf.Expand(widen<hash.Hash, fips140.Hash>(fh, elemᴛ0 => new hash_HashᴠHash(elemᴛ0)), pseudorandomKey, info, keyLength), default!);
}

// Key derives a key from the given hash, secret, salt and context info,
// returning a []byte of length keyLength that can be used as cryptographic key.
// Salt and info can be nil.
public static (slice<byte>, error) Key<Hash>(Func<Hash> h, slice<byte> secret, slice<byte> salt, @string info, nint keyLength)
    where Hash : hash.Hash
{
    var fh = fips140hash.UnwrapNew(h);
    {
        var err = checkFIPS140Only(fh, secret); if (err != default!) {
            return (default!, err);
        }
    }
    nint limit = fh().Size() * 255;
    if (keyLength > limit) {
        return (default!, errors.New(hkdfRequestedKeyLengthˢ));
    }
    return (hkdf.Key(widen<hash.Hash, fips140.Hash>(fh, elemᴛ0 => new hash_HashᴠHash(elemᴛ0)), secret, salt, info, keyLength), default!);
}

// Hoisted @string literals (single allocation; Go keeps these in RODATA)
internal static readonly @string cryptoHkdfUseOfKeysˢ = "crypto/hkdf: use of keys shorter than 112 bits is not allowed in FIPS 140-only mode"u8;
internal static readonly @string cryptoHkdfUseOfHashˢ = "crypto/hkdf: use of hash functions other than SHA-2 or SHA-3 is not allowed in FIPS 140-only mode"u8;

internal static error checkFIPS140Only<Hash>(Func<Hash> h, slice<byte> key)
    where Hash : hash.Hash
{
    if (!fips140only.Enabled) {
        return default!;
    }
    if (len(key) < 112 / 8) {
        return errors.New(cryptoHkdfUseOfKeysˢ);
    }
    if (!fips140only.ApprovedHash(h())) {
        return errors.New(cryptoHkdfUseOfHashˢ);
    }
    return default!;
}

} // end hkdf_package
