// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto.@internal.boring;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/internal/boring/bcache", new string[]
        {
            "cache.go",
            "cache_test.go",
        });
        registry.Add("TestCache", bcache_internal_test_package.TestCache, "cache_test.go", 36);
        return TestHost.Run(registry, args);
    }
}
