// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/mlkem", new string[]
        {
            "example_test.go",
            "mlkem.go",
            "mlkem_test.go",
        });
        registry.Add("TestAccumulated", mlkem_internal_test_package.TestAccumulated, "mlkem_test.go", 164);
        registry.Add("TestBadLengths", mlkem_internal_test_package.TestBadLengths, "mlkem_test.go", 98);
        registry.Add("TestConstantSizes", mlkem_internal_test_package.TestConstantSizes, "mlkem_test.go", 309);
        registry.Add("TestRoundTrip", mlkem_internal_test_package.TestRoundTrip, "mlkem_test.go", 28);
        return TestHost.Run(registry, args);
    }
}
