// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal;

using global::go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/pkgbits", new string[]
        {
            "codes.go",
            "decoder.go",
            "doc.go",
            "encoder.go",
            "flags.go",
            "pkgbits_test.go",
            "reloc.go",
            "support.go",
            "sync.go",
            "syncmarker_string.go",
            "version.go",
        });
        registry.Add("TestRoundTrip", pkgbits_test_package.TestRoundTrip, "pkgbits_test.go", 13);
        registry.Add("TestVersions", pkgbits_test_package.TestVersions, "pkgbits_test.go", 40);
        return TestHost.Run(registry, args);
    }
}
