// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.net;

using global::go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("net/http", new string[]
        {
            "alpn_test.go",
            "client.go",
            "client_test.go",
            "clientserver_test.go",
            "clone.go",
            "cookie.go",
            "cookie_test.go",
            "doc.go",
            "example_filesystem_test.go",
            "example_handle_test.go",
            "example_test.go",
            "export_test.go",
            "filetransport.go",
            "filetransport_test.go",
            "fs.go",
            "fs_test.go",
            "h2_bundle.go",
            "h2_error.go",
            "h2_error_test.go",
            "header.go",
            "header_test.go",
            "http.go",
            "http_test.go",
            "jar.go",
            "main_test.go",
            "mapping.go",
            "mapping_test.go",
            "method.go",
            "omithttp2.go",
            "pattern.go",
            "pattern_test.go",
            "proxy_test.go",
            "range_test.go",
            "readrequest_test.go",
            "request.go",
            "request_test.go",
            "requestwrite_test.go",
            "response.go",
            "response_test.go",
            "responsecontroller.go",
            "responsecontroller_test.go",
            "responsewrite_test.go",
            "roundtrip.go",
            "roundtrip_js.go",
            "routing_index.go",
            "routing_index_test.go",
            "routing_tree.go",
            "routing_tree_test.go",
            "serve_test.go",
            "servemux121.go",
            "server.go",
            "server_test.go",
            "sniff.go",
            "sniff_test.go",
            "socks_bundle.go",
            "status.go",
            "testdata/file",
            "testdata/index.html",
            "testdata/style.css",
            "transfer.go",
            "transfer_test.go",
            "transport.go",
            "transport_default_other.go",
            "transport_default_wasm.go",
            "transport_dial_test.go",
            "transport_internal_test.go",
            "transport_test.go",
            "triv.go",
        }, new string[]
        {
            "cgi",
            "cookiejar",
            "fcgi",
            "httptest",
            "httptrace",
            "httputil",
            "internal",
            "pprof",
            "testdata",
        }, new string[]
        {
            "pprof/testdata",
        });
        registry.Add("Test304Responses", http_test_package.Test304Responses, "clientserver_test.go", 577);
        registry.Add("TestAcceptMaxFds", http_test_package.TestAcceptMaxFds, "serve_test.go", 3886);
        registry.Add("TestAddCookie", http_internal_test_package.TestAddCookie, "cookie_test.go", 245);
        registry.Add("TestAltProtoCancellation", http_test_package.TestAltProtoCancellation, "transport_test.go", 6700);
        registry.Add("TestAppendTime", http_test_package.TestAppendTime, "serve_test.go", 4275);
        registry.Add("TestAutomaticHTTP2_ListenAndServe", http_test_package.TestAutomaticHTTP2_ListenAndServe, "serve_test.go", 1745);
        registry.Add("TestAutomaticHTTP2_ListenAndServe_GetCertificate", http_test_package.TestAutomaticHTTP2_ListenAndServe_GetCertificate, "serve_test.go", 1755);
        registry.Add("TestAutomaticHTTP2_ListenAndServe_GetConfigForClient", http_test_package.TestAutomaticHTTP2_ListenAndServe_GetConfigForClient, "serve_test.go", 1767);
        registry.Add("TestAutomaticHTTP2_Serve_H2TLSConfig", http_test_package.TestAutomaticHTTP2_Serve_H2TLSConfig, "serve_test.go", 1705);
        registry.Add("TestAutomaticHTTP2_Serve_NoTLSConfig", http_test_package.TestAutomaticHTTP2_Serve_NoTLSConfig, "serve_test.go", 1697);
        registry.Add("TestAutomaticHTTP2_Serve_NonH2TLSConfig", http_test_package.TestAutomaticHTTP2_Serve_NonH2TLSConfig, "serve_test.go", 1701);
        registry.Add("TestAutomaticHTTP2_Serve_WithTLSConfig", http_test_package.TestAutomaticHTTP2_Serve_WithTLSConfig, "serve_test.go", 1725);
        registry.Add("TestBadResponseAfterReadingBody", http_test_package.TestBadResponseAfterReadingBody, "clientserver_test.go", 1457);
        registry.Add("TestBasicAuth", http_test_package.TestBasicAuth, "client_test.go", 1052);
        registry.Add("TestBasicAuthHeadersPreserved", http_test_package.TestBasicAuthHeadersPreserved, "client_test.go", 1086);
        registry.Add("TestBidiStreamReverseProxy", http_test_package.TestBidiStreamReverseProxy, "clientserver_test.go", 1576);
        registry.Add("TestBodyReadBadTrailer", http_internal_test_package.TestBodyReadBadTrailer, "transfer_test.go", 19);
        registry.Add("TestCacheKeys", http_internal_test_package.TestCacheKeys, "proxy_test.go", 28);
        registry.Add("TestCancelRequestMidBody", http_test_package.TestCancelRequestMidBody, "clientserver_test.go", 643);
        registry.Add("TestCancelRequestWhenSharingConnection", http_test_package.TestCancelRequestWhenSharingConnection, "transport_test.go", 6872);
        registry.Add("TestCaseSensitiveMethod", http_test_package.TestCaseSensitiveMethod, "serve_test.go", 3339);
        registry.Add("TestChunkedNoContent", http_test_package.TestChunkedNoContent, "transport_test.go", 2288);
        registry.Add("TestChunkedResponseHeaders", http_test_package.TestChunkedResponseHeaders, "clientserver_test.go", 255);
        registry.Add("TestCleanPath", http_internal_test_package.TestCleanPath, "server_test.go", 253);
        registry.Add("TestClient", http_test_package.TestClient, "client_test.go", 63);
        registry.Add("TestClientAltersCookiesOnRedirect", http_test_package.TestClientAltersCookiesOnRedirect, "client_test.go", 1664);
        registry.Add("TestClientCallsCloseOnlyOnce", http_test_package.TestClientCallsCloseOnlyOnce, "client_test.go", 2097);
        registry.Add("TestClientCanClose", http_test_package.TestClientCanClose, "serve_test.go", 1311);
        registry.Add("TestClientCloseIdleConnections", http_test_package.TestClientCloseIdleConnections, "client_test.go", 1974);
        registry.Add("TestClientCopyHeadersOnRedirect", http_test_package.TestClientCopyHeadersOnRedirect, "client_test.go", 1476);
        registry.Add("TestClientCopyHostOnRedirect", http_test_package.TestClientCopyHostOnRedirect, "client_test.go", 1592);
        registry.Add("TestClientDoCanceledVsTimeout", http_test_package.TestClientDoCanceledVsTimeout, "client_test.go", 2014);
        registry.Add("TestClientErrorWithRequestURI", http_test_package.TestClientErrorWithRequestURI, "client_test.go", 853);
        registry.Add("TestClientHead", http_test_package.TestClientHead, "client_test.go", 81);
        registry.Add("TestClientHeadContentLength", http_test_package.TestClientHeadContentLength, "client_test.go", 984);
        registry.Add("TestClientInsecureTransport", http_test_package.TestClientInsecureTransport, "client_test.go", 819);
        registry.Add("TestClientPopulatesNilResponseBody", http_test_package.TestClientPopulatesNilResponseBody, "client_test.go", 2072);
        registry.Add("TestClientPropagatesTimeoutToContext", http_test_package.TestClientPropagatesTimeoutToContext, "client_test.go", 1995);
        registry.Add("TestClientRedirect308NoGetBody", http_test_package.TestClientRedirect308NoGetBody, "client_test.go", 543);
        registry.Add("TestClientRedirectEatsBody_h1", http_test_package.TestClientRedirectEatsBody_h1, "client_test.go", 1357);
        registry.Add("TestClientRedirectNoLocation", http_test_package.TestClientRedirectNoLocation, "client_test.go", 518);
        registry.Add("TestClientRedirectResponseWithoutRequest", http_test_package.TestClientRedirectResponseWithoutRequest, "client_test.go", 1463);
        registry.Add("TestClientRedirectTypes", http_test_package.TestClientRedirectTypes, "client_test.go", 1810);
        registry.Add("TestClientRedirectUseResponse", http_test_package.TestClientRedirectUseResponse, "client_test.go", 478);
        registry.Add("TestClientRedirects", http_test_package.TestClientRedirects, "client_test.go", 189);
        registry.Add("TestClientRedirectsContext", http_test_package.TestClientRedirectsContext, "client_test.go", 286);
        registry.Add("TestClientSendsCookieFromJar", http_test_package.TestClientSendsCookieFromJar, "client_test.go", 588);
        registry.Add("TestClientStripHeadersOnRepeatedRedirect", http_test_package.TestClientStripHeadersOnRepeatedRedirect, "client_test.go", 1541);
        registry.Add("TestClientTimeout", http_test_package.TestClientTimeout, "client_test.go", 1166);
        registry.Add("TestClientTimeoutCancel", http_test_package.TestClientTimeoutCancel, "client_test.go", 1311);
        registry.Add("TestClientTimeoutDoesNotExpire", http_test_package.TestClientTimeoutDoesNotExpire, "client_test.go", 1337);
        registry.Add("TestClientTimeoutKillsConn_AfterHeaders", http_test_package.TestClientTimeoutKillsConn_AfterHeaders, "transport_test.go", 5925);
        registry.Add("TestClientTimeoutKillsConn_BeforeHeaders", http_test_package.TestClientTimeoutKillsConn_BeforeHeaders, "transport_test.go", 5861);
        registry.Add("TestClientTimeout_Headers", http_test_package.TestClientTimeout_Headers, "client_test.go", 1267);
        registry.Add("TestClientWithCorrectTLSServerName", http_test_package.TestClientWithCorrectTLSServerName, "client_test.go", 866);
        registry.Add("TestClientWithIncorrectTLSServerName", http_test_package.TestClientWithIncorrectTLSServerName, "client_test.go", 884);
        registry.Add("TestClientWriteShutdown", http_test_package.TestClientWriteShutdown, "serve_test.go", 3222);
        registry.Add("TestClientWrites", http_test_package.TestClientWrites, "client_test.go", 785);
        registry.Add("TestCloneOrMakeHeader", http_internal_test_package.TestCloneOrMakeHeader, "header_test.go", 240);
        registry.Add("TestCloseIdleConnections", http_test_package.TestCloseIdleConnections, "clientserver_test.go", 1362);
        registry.Add("TestCloseNotifier", http_test_package.TestCloseNotifier, "serve_test.go", 3391);
        registry.Add("TestCloseNotifierChanLeak", http_test_package.TestCloseNotifierChanLeak, "serve_test.go", 3483);
        registry.Add("TestCloseNotifierPipelined", http_test_package.TestCloseNotifierPipelined, "serve_test.go", 3433);
        registry.Add("TestCloseWrite", http_test_package.TestCloseWrite, "serve_test.go", 4538);
        registry.Add("TestCmdGoNoHTTPServer", http_internal_test_package.TestCmdGoNoHTTPServer, "http_test.go", 54);
        registry.Add("TestCodesPreventingContentTypeAndBody", http_test_package.TestCodesPreventingContentTypeAndBody, "serve_test.go", 4064);
        registry.Add("TestCommonPath", http_internal_test_package.TestCommonPath, "pattern_test.go", 441);
        registry.Add("TestCompareMethods", http_internal_test_package.TestCompareMethods, "pattern_test.go", 174);
        registry.Add("TestComparePaths", http_internal_test_package.TestComparePaths, "pattern_test.go", 202);
        registry.Add("TestConcurrentReadWriteReqBody", http_test_package.TestConcurrentReadWriteReqBody, "clientserver_test.go", 837);
        registry.Add("TestConcurrentServerServe", http_test_package.TestConcurrentServerServe, "serve_test.go", 5570);
        registry.Add("TestConflictsWith", http_internal_test_package.TestConflictsWith, "pattern_test.go", 358);
        registry.Add("TestConnClosedBeforeRequestIsWritten", http_test_package.TestConnClosedBeforeRequestIsWritten, "transport_test.go", 4331);
        registry.Add("TestConnContextNotModifyingAllContexts", http_test_package.TestConnContextNotModifyingAllContexts, "serve_test.go", 6343);
        registry.Add("TestConnectRequest", http_test_package.TestConnectRequest, "clientserver_test.go", 887);
        registry.Add("TestConsumingBodyOnNextConn", http_test_package.TestConsumingBodyOnNextConn, "serve_test.go", 169);
        registry.Add("TestContentEncodingNoSniffing", http_test_package.TestContentEncodingNoSniffing, "serve_test.go", 6419);
        registry.Add("TestContentLengthZero", http_test_package.TestContentLengthZero, "serve_test.go", 3361);
        registry.Add("TestContentTypeOkayOn204", http_test_package.TestContentTypeOkayOn204, "serve_test.go", 4096);
        registry.Add("TestContentTypeWithVariousSources", http_test_package.TestContentTypeWithVariousSources, "sniff_test.go", 169);
        registry.Add("TestCookieSanitizePath", http_internal_test_package.TestCookieSanitizePath, "cookie_test.go", 545);
        registry.Add("TestCookieSanitizeValue", http_internal_test_package.TestCookieSanitizeValue, "cookie_test.go", 510);
        registry.Add("TestCookieValid", http_internal_test_package.TestCookieValid, "cookie_test.go", 568);
        registry.Add("TestDeleteRedirects", http_test_package.TestDeleteRedirects, "client_test.go", 363);
        registry.Add("TestDescribeConflict", http_internal_test_package.TestDescribeConflict, "pattern_test.go", 421);
        registry.Add("TestDetectContentType", http_test_package.TestDetectContentType, "sniff_test.go", 82);
        registry.Add("TestDetectInMemoryReaders", http_internal_test_package.TestDetectInMemoryReaders, "transfer_test.go", 71);
        registry.Add("TestDifferencePath", http_internal_test_package.TestDifferencePath, "pattern_test.go", 469);
        registry.Add("TestDirJoin", http_test_package.TestDirJoin, "fs_test.go", 451);
        registry.Add("TestDirectoryIfNotModified", http_test_package.TestDirectoryIfNotModified, "fs_test.go", 824);
        registry.Add("TestDisableContentLength", http_test_package.TestDisableContentLength, "serve_test.go", 7123);
        registry.Add("TestDisableKeepAliveUpgrade", http_test_package.TestDisableKeepAliveUpgrade, "serve_test.go", 6645);
        registry.Add("TestDontCacheBrokenHTTP2Conn", http_test_package.TestDontCacheBrokenHTTP2Conn, "transport_test.go", 6583);
        registry.Add("TestDoubleHijack", http_test_package.TestDoubleHijack, "serve_test.go", 3936);
        registry.Add("TestEarlyHints", http_test_package.TestEarlyHints, "serve_test.go", 6968);
        registry.Add("TestEarlyHintsRequest", http_test_package.TestEarlyHintsRequest, "clientserver_test.go", 1689);
        registry.Add("TestEmptyDirOpenCWD", http_test_package.TestEmptyDirOpenCWD, "fs_test.go", 487);
        registry.Add("TestEmptyPasswordAuth", http_test_package.TestEmptyPasswordAuth, "client_test.go", 1018);
        registry.Add("TestEmptyServeMux", http_internal_test_package.TestEmptyServeMux, "server_test.go", 121);
        registry.Add("TestErrNotSupported", http_test_package.TestErrNotSupported, "request_test.go", 1512);
        registry.Add("TestError", http_test_package.TestError, "serve_test.go", 7182);
        registry.Add("TestErrorContentLength", http_test_package.TestErrorContentLength, "serve_test.go", 7161);
        registry.Add("TestErrorWriteLoopRace", http_test_package.TestErrorWriteLoopRace, "transport_test.go", 6849);
        registry.Add("TestEscapedPathsAndPatterns", http_internal_test_package.TestEscapedPathsAndPatterns, "server_test.go", 191);
        registry.Add("TestExactMatch", http_internal_test_package.TestExactMatch, "server_test.go", 164);
        registry.Add("TestFSRedirect", http_test_package.TestFSRedirect, "fs_test.go", 278);
        registry.Add("TestFileServerCleanPath", http_test_package.TestFileServerCleanPath, "fs_test.go", 1436);
        registry.Add("TestFileServerCleans", http_test_package.TestFileServerCleans, "fs_test.go", 302);
        registry.Add("TestFileServerDirWithRootFile", http_test_package.TestFileServerDirWithRootFile, "fs_test.go", 1703);
        registry.Add("TestFileServerErrorMessages", http_test_package.TestFileServerErrorMessages, "fs_test.go", 1226);
        registry.Add("TestFileServerEscapesNames", http_test_package.TestFileServerEscapesNames, "fs_test.go", 327);
        registry.Add("TestFileServerFS", http_test_package.TestFileServerFS, "fs_test.go", 1597);
        registry.Add("TestFileServerImplicitLeadingSlash", http_test_package.TestFileServerImplicitLeadingSlash, "fs_test.go", 424);
        registry.Add("TestFileServerMethods", http_test_package.TestFileServerMethods, "fs_test.go", 1548);
        registry.Add("TestFileServerNamesEscape", http_test_package.TestFileServerNamesEscape, "fs_test.go", 736);
        registry.Add("TestFileServerNotDirError", http_test_package.TestFileServerNotDirError, "fs_test.go", 1382);
        registry.Add("TestFileServerSortsNames", http_test_package.TestFileServerSortsNames, "fs_test.go", 375);
        registry.Add("TestFileServerZeroByte", http_test_package.TestFileServerZeroByte, "fs_test.go", 712);
        registry.Add("TestFileTransport", http_internal_test_package.TestFileTransport, "filetransport_test.go", 24);
        registry.Add("TestFileTransportFS", http_internal_test_package.TestFileTransportFS, "filetransport_test.go", 67);
        registry.Add("TestFinalChunkedBodyReadEOF", http_internal_test_package.TestFinalChunkedBodyReadEOF, "transfer_test.go", 45);
        registry.Add("TestFindHandler", http_internal_test_package.TestFindHandler, "server_test.go", 73);
        registry.Add("TestForeachHeaderElement", http_internal_test_package.TestForeachHeaderElement, "http_test.go", 21);
        registry.Add("TestFormFileCallsParseMultipartForm", http_test_package.TestFormFileCallsParseMultipartForm, "request_test.go", 430);
        registry.Add("TestFormFileOrder", http_test_package.TestFormFileOrder, "request_test.go", 468);
        registry.Add("TestFormValueCallsParseMultipartForm", http_test_package.TestFormValueCallsParseMultipartForm, "request_test.go", 417);
        registry.Add("TestGetBasicAuth", http_test_package.TestGetBasicAuth, "request_test.go", 689);
        registry.Add("TestGetBody", http_test_package.TestGetBody, "serve_test.go", 7070);
        registry.Add("TestGetRequestFormat", http_test_package.TestGetRequestFormat, "client_test.go", 102);
        registry.Add("TestH12_200NoBody", http_test_package.TestH12_200NoBody, "clientserver_test.go", 419);
        registry.Add("TestH12_AutoGzip", http_test_package.TestH12_AutoGzip, "clientserver_test.go", 546);
        registry.Add("TestH12_AutoGzipWithDumpResponse", http_test_package.TestH12_AutoGzipWithDumpResponse, "clientserver_test.go", 1334);
        registry.Add("TestH12_AutoGzip_Disabled", http_test_package.TestH12_AutoGzip_Disabled, "clientserver_test.go", 560);
        registry.Add("TestH12_ExplicitContentLength", http_test_package.TestH12_ExplicitContentLength, "clientserver_test.go", 439);
        registry.Add("TestH12_FlushBeforeBody", http_test_package.TestH12_FlushBeforeBody, "clientserver_test.go", 446);
        registry.Add("TestH12_FlushMidBody", http_test_package.TestH12_FlushMidBody, "clientserver_test.go", 453);
        registry.Add("TestH12_HandlerWritesTooLittle", http_test_package.TestH12_HandlerWritesTooLittle, "clientserver_test.go", 485);
        registry.Add("TestH12_HeadContentLengthLargeBody", http_test_package.TestH12_HeadContentLengthLargeBody, "clientserver_test.go", 407);
        registry.Add("TestH12_HeadContentLengthNoBody", http_test_package.TestH12_HeadContentLengthNoBody, "clientserver_test.go", 390);
        registry.Add("TestH12_HeadContentLengthSmallBody", http_test_package.TestH12_HeadContentLengthSmallBody, "clientserver_test.go", 398);
        registry.Add("TestH12_Head_ExplicitLen", http_test_package.TestH12_Head_ExplicitLen, "clientserver_test.go", 461);
        registry.Add("TestH12_Head_ImplicitLen", http_test_package.TestH12_Head_ImplicitLen, "clientserver_test.go", 473);
        registry.Add("TestH12_RequestContentLength_Known_NonZero", http_test_package.TestH12_RequestContentLength_Known_NonZero, "clientserver_test.go", 612);
        registry.Add("TestH12_RequestContentLength_Known_Zero", http_test_package.TestH12_RequestContentLength_Known_Zero, "clientserver_test.go", 616);
        registry.Add("TestH12_RequestContentLength_Unknown", http_test_package.TestH12_RequestContentLength_Unknown, "clientserver_test.go", 620);
        registry.Add("TestH12_ServerEmptyContentLength", http_test_package.TestH12_ServerEmptyContentLength, "clientserver_test.go", 603);
        registry.Add("TestH12_SmallBody", http_test_package.TestH12_SmallBody, "clientserver_test.go", 433);
        registry.Add("TestH12_WebSocketUpgrade", http_test_package.TestH12_WebSocketUpgrade, "clientserver_test.go", 1640);
        registry.Add("TestH2_204NoBody", http_test_package.TestH2_204NoBody, "clientserver_test.go", 423);
        registry.Add("TestH2_304NoBody", http_test_package.TestH2_304NoBody, "clientserver_test.go", 424);
        registry.Add("TestH2_404NoBody", http_test_package.TestH2_404NoBody, "clientserver_test.go", 425);
        registry.Add("TestHTTP10ConnectionHeader", http_test_package.TestHTTP10ConnectionHeader, "serve_test.go", 3967);
        registry.Add("TestHTTP10KeepAlive204Response", http_test_package.TestHTTP10KeepAlive204Response, "serve_test.go", 1342);
        registry.Add("TestHTTP10KeepAlive304Response", http_test_package.TestHTTP10KeepAlive304Response, "serve_test.go", 1350);
        registry.Add("TestHTTP11KeepAlive204Response", http_test_package.TestHTTP11KeepAlive204Response, "serve_test.go", 1346);
        registry.Add("TestHTTP2UpgradeClosesConnection", http_test_package.TestHTTP2UpgradeClosesConnection, "serve_test.go", 1331);
        registry.Add("TestHTTPSClientDetectsHTTPServer", http_test_package.TestHTTPSClientDetectsHTTPServer, "client_test.go", 970);
        registry.Add("TestHandlerAbortRacesBodyRead", http_test_package.TestHandlerAbortRacesBodyRead, "transport_test.go", 6958);
        registry.Add("TestHandlerBodyClose", http_test_package.TestHandlerBodyClose, "serve_test.go", 2162);
        registry.Add("TestHandlerFinishSkipBigContentLengthRead", http_test_package.TestHandlerFinishSkipBigContentLengthRead, "serve_test.go", 4777);
        registry.Add("TestHandlerPanic", http_test_package.TestHandlerPanic, "serve_test.go", 2904);
        registry.Add("TestHandlerPanicNil", http_test_package.TestHandlerPanicNil, "serve_test.go", 2898);
        registry.Add("TestHandlerPanicWithHijack", http_test_package.TestHandlerPanicWithHijack, "serve_test.go", 2910);
        registry.Add("TestHandlerSetTransferEncodingChunked", http_test_package.TestHandlerSetTransferEncodingChunked, "serve_test.go", 5091);
        registry.Add("TestHandlerSetTransferEncodingGzip", http_test_package.TestHandlerSetTransferEncodingGzip, "serve_test.go", 5106);
        registry.Add("TestHandlerSetsBodyNil", http_test_package.TestHandlerSetsBodyNil, "serve_test.go", 4800);
        registry.Add("TestHandlerWritesTooMuch", http_test_package.TestHandlerWritesTooMuch, "clientserver_test.go", 513);
        registry.Add("TestHandlersCanSetConnectionClose10", http_test_package.TestHandlersCanSetConnectionClose10, "serve_test.go", 1325);
        registry.Add("TestHandlersCanSetConnectionClose11", http_test_package.TestHandlersCanSetConnectionClose11, "serve_test.go", 1319);
        registry.Add("TestHasToken", http_internal_test_package.TestHasToken, "header_test.go", 186);
        registry.Add("TestHeadBody", http_test_package.TestHeadBody, "serve_test.go", 7061);
        registry.Add("TestHeadResponses", http_test_package.TestHeadResponses, "serve_test.go", 1503);
        registry.Add("TestHeaderToWire", http_test_package.TestHeaderToWire, "serve_test.go", 3696);
        registry.Add("TestHeaderWrite", http_internal_test_package.TestHeaderWrite, "header_test.go", 108);
        registry.Add("TestHeaderWriteSubsetAllocs", http_internal_test_package.TestHeaderWriteSubsetAllocs, "header_test.go", 219);
        registry.Add("TestHijackAfterCloseNotifier", http_test_package.TestHijackAfterCloseNotifier, "serve_test.go", 3514);
        registry.Add("TestHijackBeforeRequestBodyRead", http_test_package.TestHijackBeforeRequestBodyRead, "serve_test.go", 3561);
        registry.Add("TestHostHandlers", http_test_package.TestHostHandlers, "serve_test.go", 251);
        registry.Add("TestIdentityResponse", http_test_package.TestIdentityResponse, "serve_test.go", 1167);
        registry.Add("TestIdentityTransferEncoding", http_test_package.TestIdentityTransferEncoding, "clientserver_test.go", 1661);
        registry.Add("TestIdleConnChannelLeak", http_test_package.TestIdleConnChannelLeak, "transport_test.go", 3432);
        registry.Add("TestIdleConnH2Crash", http_test_package.TestIdleConnH2Crash, "transport_test.go", 5398);
        registry.Add("TestIndex", http_internal_test_package.TestIndex, "routing_index_test.go", 14);
        registry.Add("TestInterruptWithPanic", http_test_package.TestInterruptWithPanic, "clientserver_test.go", 1251);
        registry.Add("TestInvalidChunkedBodies", http_test_package.TestInvalidChunkedBodies, "serve_test.go", 7288);
        registry.Add("TestInvalidHeaderResponse", http_test_package.TestInvalidHeaderResponse, "transport_test.go", 6437);
        registry.Add("TestInvalidTrailerClosesConnection", http_test_package.TestInvalidTrailerClosesConnection, "serve_test.go", 2273);
        registry.Add("TestIs408", http_test_package.TestIs408, "transport_test.go", 6361);
        registry.Add("TestIssue10884_MaxBytesEOF", http_test_package.TestIssue10884_MaxBytesEOF, "request_test.go", 879);
        registry.Add("TestIssue11549_Expect100", http_test_package.TestIssue11549_Expect100, "serve_test.go", 4732);
        registry.Add("TestIssue13893_Expect100", http_test_package.TestIssue13893_Expect100, "serve_test.go", 4705);
        registry.Add("TestIssue32441", http_test_package.TestIssue32441, "transport_test.go", 6730);
        registry.Add("TestIssue3595", http_test_package.TestIssue3595, "transport_test.go", 2240);
        registry.Add("TestIssue3644", http_test_package.TestIssue3644, "transport_test.go", 2214);
        registry.Add("TestIssue4191_InfiniteGetTimeout", http_test_package.TestIssue4191_InfiniteGetTimeout, "transport_test.go", 2373);
        registry.Add("TestIssue4191_InfiniteGetToPutTimeout", http_test_package.TestIssue4191_InfiniteGetToPutTimeout, "transport_test.go", 2409);
        registry.Add("TestIssue58237", http_test_package.TestIssue58237, "responsecontroller_test.go", 330);
        registry.Add("TestJarCalls", http_test_package.TestJarCalls, "client_test.go", 675);
        registry.Add("TestKeepAliveFinalChunkWithEOF", http_test_package.TestKeepAliveFinalChunkWithEOF, "serve_test.go", 1357);
        registry.Add("TestLinuxSendfile", http_test_package.TestLinuxSendfile, "fs_test.go", 1281);
        registry.Add("TestLinuxSendfileChild", http_test_package.TestLinuxSendfileChild, "fs_test.go", 1359);
        registry.Add("TestLocationResponse", http_internal_test_package.TestLocationResponse, "response_test.go", 769);
        registry.Add("TestMapping", http_internal_test_package.TestMapping, "mapping_test.go", 15);
        registry.Add("TestMappingEachPair", http_internal_test_package.TestMappingEachPair, "mapping_test.go", 43);
        registry.Add("TestMatchingMethods", http_internal_test_package.TestMatchingMethods, "routing_tree_test.go", 216);
        registry.Add("TestMaxBytesHandler", http_test_package.TestMaxBytesHandler, "serve_test.go", 6863);
        registry.Add("TestMaxBytesReaderDifferentLimits", http_test_package.TestMaxBytesReaderDifferentLimits, "request_test.go", 932);
        registry.Add("TestMaxBytesReaderStickyError", http_test_package.TestMaxBytesReaderStickyError, "request_test.go", 892);
        registry.Add("TestMaxInt64ForMultipartFormMaxMemoryOverflow", http_test_package.TestMaxInt64ForMultipartFormMaxMemoryOverflow, "request_test.go", 294);
        registry.Add("TestMissingFileMultipartRequest", http_test_package.TestMissingFileMultipartRequest, "request_test.go", 409);
        registry.Add("TestMissingStatusNoPanic", http_test_package.TestMissingStatusNoPanic, "transport_test.go", 5735);
        registry.Add("TestMultipartReader", http_test_package.TestMultipartReader, "request_test.go", 159);
        registry.Add("TestMultipartReaderOrder", http_test_package.TestMultipartReaderOrder, "request_test.go", 455);
        registry.Add("TestMultipartRequest", http_test_package.TestMultipartRequest, "request_test.go", 369);
        registry.Add("TestMultipartRequestAuto", http_test_package.TestMultipartRequestAuto, "request_test.go", 397);
        registry.Add("TestMuxNoSlash405WithTrailingSlash", http_test_package.TestMuxNoSlash405WithTrailingSlash, "serve_test.go", 619);
        registry.Add("TestMuxNoSlashRedirectWithTrailingSlash", http_test_package.TestMuxNoSlashRedirectWithTrailingSlash, "serve_test.go", 603);
        registry.Add("TestMuxRedirectLeadingSlashes", http_test_package.TestMuxRedirectLeadingSlashes, "serve_test.go", 460);
        registry.Add("TestMuxRedirectRelative", http_test_package.TestMuxRedirectRelative, "serve_test.go", 6773);
        registry.Add("TestNewClientServerTest", http_test_package.TestNewClientServerTest, "clientserver_test.go", 215);
        registry.Add("TestNewRequestContentLength", http_test_package.TestNewRequestContentLength, "request_test.go", 599);
        registry.Add("TestNewRequestGetBody", http_test_package.TestNewRequestGetBody, "request_test.go", 1104);
        registry.Add("TestNewRequestHost", http_test_package.TestNewRequestHost, "request_test.go", 563);
        registry.Add("TestNextProtoUpgrade", http_test_package.TestNextProtoUpgrade, "alpn_test.go", 20);
        registry.Add("TestNilHeaderClone", http_internal_test_package.TestNilHeaderClone, "header_test.go", 194);
        registry.Add("TestNoBodyOnChunked304Response", http_test_package.TestNoBodyOnChunked304Response, "transport_test.go", 5800);
        registry.Add("TestNoContentLengthIfTransferEncoding", http_test_package.TestNoContentLengthIfTransferEncoding, "serve_test.go", 4645);
        registry.Add("TestNoCrashReturningTransportAltConn", http_test_package.TestNoCrashReturningTransportAltConn, "transport_test.go", 4684);
        registry.Add("TestNoPanicOnRoundTripWithBasicAuth", http_test_package.TestNoPanicOnRoundTripWithBasicAuth, "request_test.go", 1085);
        registry.Add("TestNoSniffExpectRequestBody", http_test_package.TestNoSniffExpectRequestBody, "clientserver_test.go", 1404);
        registry.Add("TestNoUnicodeStrings", http_internal_test_package.TestNoUnicodeStrings, "http_test.go", 153);
        registry.Add("TestNoWriteDeadline", http_test_package.TestNoWriteDeadline, "serve_test.go", 1055);
        registry.Add("TestOmitHTTP2", http_internal_test_package.TestOmitHTTP2, "http_test.go", 85);
        registry.Add("TestOmitHTTP2Vet", http_internal_test_package.TestOmitHTTP2Vet, "http_test.go", 100);
        registry.Add("TestOnProxyConnectResponse", http_test_package.TestOnProxyConnectResponse, "transport_test.go", 1551);
        registry.Add("TestOnlyWriteTimeout", http_test_package.TestOnlyWriteTimeout, "serve_test.go", 1101);
        registry.Add("TestOptions", http_test_package.TestOptions, "serve_test.go", 3609);
        registry.Add("TestOptionsHandler", http_test_package.TestOptionsHandler, "serve_test.go", 3661);
        registry.Add("TestParseBasicAuth", http_test_package.TestParseBasicAuth, "request_test.go", 731);
        registry.Add("TestParseContentLength", http_internal_test_package.TestParseContentLength, "transfer_test.go", 336);
        registry.Add("TestParseCookie", http_internal_test_package.TestParseCookie, "cookie_test.go", 687);
        registry.Add("TestParseFormCleanup", http_test_package.TestParseFormCleanup, "serve_test.go", 7000);
        registry.Add("TestParseFormInitializeOnError", http_test_package.TestParseFormInitializeOnError, "request_test.go", 142);
        registry.Add("TestParseFormQuery", http_test_package.TestParseFormQuery, "request_test.go", 55);
        registry.Add("TestParseFormQueryMethods", http_test_package.TestParseFormQueryMethods, "request_test.go", 93);
        registry.Add("TestParseFormSemicolonSeparator", http_test_package.TestParseFormSemicolonSeparator, "request_test.go", 40);
        registry.Add("TestParseFormUnknownContentType", http_test_package.TestParseFormUnknownContentType, "request_test.go", 108);
        registry.Add("TestParseHTTPVersion", http_test_package.TestParseHTTPVersion, "request_test.go", 658);
        registry.Add("TestParseMultipartForm", http_test_package.TestParseMultipartForm, "request_test.go", 250);
        registry.Add("TestParseMultipartFormFilename", http_test_package.TestParseMultipartFormFilename, "request_test.go", 269);
        registry.Add("TestParseMultipartFormOrder", http_test_package.TestParseMultipartFormOrder, "request_test.go", 443);
        registry.Add("TestParseMultipartFormPopulatesPostForm", http_test_package.TestParseMultipartFormPopulatesPostForm, "request_test.go", 189);
        registry.Add("TestParseMultipartFormSemicolonSeparator", http_test_package.TestParseMultipartFormSemicolonSeparator, "request_test.go", 387);
        registry.Add("TestParsePattern", http_internal_test_package.TestParsePattern, "pattern_test.go", 13);
        registry.Add("TestParsePatternError", http_internal_test_package.TestParsePatternError, "pattern_test.go", 126);
        registry.Add("TestParseRange", http_internal_test_package.TestParseRange, "range_test.go", 59);
        registry.Add("TestParseSetCookie", http_internal_test_package.TestParseSetCookie, "cookie_test.go", 737);
        registry.Add("TestParseTime", http_internal_test_package.TestParseTime, "header_test.go", 131);
        registry.Add("TestParseTransferEncoding", http_internal_test_package.TestParseTransferEncoding, "transfer_test.go", 287);
        registry.Add("TestPathValueAndPattern", http_test_package.TestPathValueAndPattern, "request_test.go", 1530);
        registry.Add("TestPathValueNoMatch", http_test_package.TestPathValueNoMatch, "request_test.go", 1518);
        registry.Add("TestPostFormRequestFormat", http_test_package.TestPostFormRequestFormat, "client_test.go", 147);
        registry.Add("TestPostRedirects", http_test_package.TestPostRedirects, "client_test.go", 320);
        registry.Add("TestPostRequestFormat", http_test_package.TestPostRequestFormat, "client_test.go", 120);
        registry.Add("TestProbeZeroLengthBody", http_test_package.TestProbeZeroLengthBody, "client_test.go", 2151);
        registry.Add("TestProcessing", http_test_package.TestProcessing, "serve_test.go", 6987);
        registry.Add("TestProxyAuthHeader", http_test_package.TestProxyAuthHeader, "transport_test.go", 7003);
        registry.Add("TestProxyFromEnvironment", http_test_package.TestProxyFromEnvironment, "transport_test.go", 3402);
        registry.Add("TestProxyFromEnvironmentLowerCase", http_test_package.TestProxyFromEnvironmentLowerCase, "transport_test.go", 3417);
        registry.Add("TestQuery", http_test_package.TestQuery, "request_test.go", 30);
        registry.Add("TestQuerySemicolon", http_test_package.TestQuerySemicolon, "serve_test.go", 6791);
        registry.Add("TestReadCookies", http_internal_test_package.TestReadCookies, "cookie_test.go", 475);
        registry.Add("TestReadRequest", http_internal_test_package.TestReadRequest, "readrequest_test.go", 421);
        registry.Add("TestReadRequestErrors", http_test_package.TestReadRequestErrors, "request_test.go", 526);
        registry.Add("TestReadRequest_Bad", http_internal_test_package.TestReadRequest_Bad, "readrequest_test.go", 483);
        registry.Add("TestReadResponse", http_internal_test_package.TestReadResponse, "response_test.go", 589);
        registry.Add("TestReadResponseCloseInMiddle", http_internal_test_package.TestReadResponseCloseInMiddle, "response_test.go", 646);
        registry.Add("TestReadResponseErrors", http_internal_test_package.TestReadResponseErrors, "response_test.go", 849);
        registry.Add("TestReadSetCookies", http_internal_test_package.TestReadSetCookies, "cookie_test.go", 406);
        registry.Add("TestRedirect", http_test_package.TestRedirect, "serve_test.go", 2762);
        registry.Add("TestRedirectBadPath", http_test_package.TestRedirectBadPath, "serve_test.go", 2744);
        registry.Add("TestRedirectContentTypeAndBody", http_test_package.TestRedirectContentTypeAndBody, "serve_test.go", 2809);
        registry.Add("TestRedirectCookiesJar", http_test_package.TestRedirectCookiesJar, "client_test.go", 640);
        registry.Add("TestReferer", http_test_package.TestReferer, "client_test.go", 1404);
        registry.Add("TestRegisterConflict", http_internal_test_package.TestRegisterConflict, "pattern_test.go", 401);
        registry.Add("TestRegisterErr", http_internal_test_package.TestRegisterErr, "server_test.go", 135);
        registry.Add("TestRequestBadHostHeader", http_test_package.TestRequestBadHostHeader, "request_test.go", 773);
        registry.Add("TestRequestBadUserAgent", http_test_package.TestRequestBadUserAgent, "request_test.go", 793);
        registry.Add("TestRequestBodyCloseDoesntBlock", http_test_package.TestRequestBodyCloseDoesntBlock, "serve_test.go", 4210);
        registry.Add("TestRequestBodyLimit", http_test_package.TestRequestBodyLimit, "serve_test.go", 3170);
        registry.Add("TestRequestBodyReadErrorClosesConnection", http_test_package.TestRequestBodyReadErrorClosesConnection, "serve_test.go", 2242);
        registry.Add("TestRequestBodyTimeoutClosesConnection", http_test_package.TestRequestBodyTimeoutClosesConnection, "serve_test.go", 2398);
        registry.Add("TestRequestClonePathValue", http_test_package.TestRequestClonePathValue, "request_test.go", 1059);
        registry.Add("TestRequestCloneTransferEncoding", http_test_package.TestRequestCloneTransferEncoding, "request_test.go", 1038);
        registry.Add("TestRequestCookie", http_test_package.TestRequestCookie, "request_test.go", 1221);
        registry.Add("TestRequestCookiesByName", http_test_package.TestRequestCookiesByName, "request_test.go", 1260);
        registry.Add("TestRequestInvalidMethod", http_test_package.TestRequestInvalidMethod, "request_test.go", 576);
        registry.Add("TestRequestLimit", http_test_package.TestRequestLimit, "serve_test.go", 3093);
        registry.Add("TestRequestRedirect", http_test_package.TestRequestRedirect, "request_test.go", 335);
        registry.Add("TestRequestSanitization", http_test_package.TestRequestSanitization, "transport_test.go", 6984);
        registry.Add("TestRequestWrite", http_internal_test_package.TestRequestWrite, "requestwrite_test.go", 612);
        registry.Add("TestRequestWriteBufferedWriter", http_test_package.TestRequestWriteBufferedWriter, "request_test.go", 758);
        registry.Add("TestRequestWriteClosesBody", http_internal_test_package.TestRequestWriteClosesBody, "requestwrite_test.go", 812);
        registry.Add("TestRequestWriteError", http_internal_test_package.TestRequestWriteError, "requestwrite_test.go", 853);
        registry.Add("TestRequestWriteTransport", http_internal_test_package.TestRequestWriteTransport, "requestwrite_test.go", 667);
        registry.Add("TestResponseBodyReadAfterClose", http_test_package.TestResponseBodyReadAfterClose, "clientserver_test.go", 820);
        registry.Add("TestResponseContentLengthShortBody", http_internal_test_package.TestResponseContentLengthShortBody, "response_test.go", 819);
        registry.Add("TestResponseControllerEnableFullDuplex", http_test_package.TestResponseControllerEnableFullDuplex, "responsecontroller_test.go", 282);
        registry.Add("TestResponseControllerFlush", http_test_package.TestResponseControllerFlush, "responsecontroller_test.go", 18);
        registry.Add("TestResponseControllerHijack", http_test_package.TestResponseControllerHijack, "responsecontroller_test.go", 51);
        registry.Add("TestResponseControllerSetFutureReadDeadline", http_test_package.TestResponseControllerSetFutureReadDeadline, "responsecontroller_test.go", 222);
        registry.Add("TestResponseControllerSetFutureWriteDeadline", http_test_package.TestResponseControllerSetFutureWriteDeadline, "responsecontroller_test.go", 122);
        registry.Add("TestResponseControllerSetPastReadDeadline", http_test_package.TestResponseControllerSetPastReadDeadline, "responsecontroller_test.go", 158);
        registry.Add("TestResponseControllerSetPastWriteDeadline", http_test_package.TestResponseControllerSetPastWriteDeadline, "responsecontroller_test.go", 80);
        registry.Add("TestResponseSetsTLSConnectionState", http_test_package.TestResponseSetsTLSConnectionState, "client_test.go", 939);
        registry.Add("TestResponseStatusStutter", http_internal_test_package.TestResponseStatusStutter, "response_test.go", 805);
        registry.Add("TestResponseWrite", http_internal_test_package.TestResponseWrite, "responsewrite_test.go", 18);
        registry.Add("TestResponseWriterWriteString", http_test_package.TestResponseWriterWriteString, "serve_test.go", 4258);
        registry.Add("TestResponseWritesOnlySingleConnectionClose", http_internal_test_package.TestResponseWritesOnlySingleConnectionClose, "response_test.go", 978);
        registry.Add("TestRetryRequestsOnError", http_test_package.TestRetryRequestsOnError, "transport_test.go", 3769);
        registry.Add("TestReuseRequest", http_test_package.TestReuseRequest, "transport_test.go", 140);
        registry.Add("TestRoundTripGzip", http_test_package.TestRoundTripGzip, "transport_test.go", 1030);
        registry.Add("TestRoundTripReturnsProxyError", http_test_package.TestRoundTripReturnsProxyError, "transport_test.go", 4097);
        registry.Add("TestRoutingAddPattern", http_internal_test_package.TestRoutingAddPattern, "routing_tree_test.go", 65);
        registry.Add("TestRoutingFirstSegment", http_internal_test_package.TestRoutingFirstSegment, "routing_tree_test.go", 17);
        registry.Add("TestRoutingNodeMatch", http_internal_test_package.TestRoutingNodeMatch, "routing_tree_test.go", 103);
        registry.Add("TestSOCKS5Proxy", http_test_package.TestSOCKS5Proxy, "transport_test.go", 1326);
        registry.Add("TestScanETag", http_test_package.TestScanETag, "fs_test.go", 1475);
        registry.Add("TestServeContent", http_test_package.TestServeContent, "fs_test.go", 898);
        registry.Add("TestServeContentHeadersWithError", http_test_package.TestServeContentHeadersWithError, "fs_test.go", 1728);
        registry.Add("TestServeContentWithEmptyContentIgnoreRanges", http_test_package.TestServeContentWithEmptyContentIgnoreRanges, "fs_test.go", 250);
        registry.Add("TestServeDirWithoutTrailingSlash", http_test_package.TestServeDirWithoutTrailingSlash, "fs_test.go", 561);
        registry.Add("TestServeFile", http_test_package.TestServeFile, "fs_test.go", 75);
        registry.Add("TestServeFileContentType", http_test_package.TestServeFileContentType, "fs_test.go", 501);
        registry.Add("TestServeFileDirPanicEmptyPath", http_test_package.TestServeFileDirPanicEmptyPath, "fs_test.go", 238);
        registry.Add("TestServeFileFS", http_test_package.TestServeFileFS, "fs_test.go", 1620);
        registry.Add("TestServeFileFromCWD", http_test_package.TestServeFileFromCWD, "fs_test.go", 545);
        registry.Add("TestServeFileMimeType", http_test_package.TestServeFileMimeType, "fs_test.go", 529);
        registry.Add("TestServeFileNotModified", http_test_package.TestServeFileNotModified, "fs_test.go", 606);
        registry.Add("TestServeFileRejectsInvalidSuffixLengths", http_test_package.TestServeFileRejectsInvalidSuffixLengths, "fs_test.go", 1500);
        registry.Add("TestServeFileWithContentEncoding", http_test_package.TestServeFileWithContentEncoding, "fs_test.go", 579);
        registry.Add("TestServeFileZippingResponseWriter", http_test_package.TestServeFileZippingResponseWriter, "fs_test.go", 1645);
        registry.Add("TestServeFile_DotDot", http_test_package.TestServeFile_DotDot, "fs_test.go", 207);
        registry.Add("TestServeHTTP10Close", http_test_package.TestServeHTTP10Close, "serve_test.go", 1304);
        registry.Add("TestServeIndexHtml", http_test_package.TestServeIndexHtml, "fs_test.go", 655);
        registry.Add("TestServeIndexHtmlFS", http_test_package.TestServeIndexHtmlFS, "fs_test.go", 690);
        registry.Add("TestServeMuxHandleFuncWithNilHandler", http_test_package.TestServeMuxHandleFuncWithNilHandler, "serve_test.go", 392);
        registry.Add("TestServeMuxHandler", http_test_package.TestServeMuxHandler, "serve_test.go", 367);
        registry.Add("TestServeMuxHandlerRedirects", http_test_package.TestServeMuxHandlerRedirects, "serve_test.go", 417);
        registry.Add("TestServeTLS", http_test_package.TestServeTLS, "serve_test.go", 1617);
        registry.Add("TestServeWithSlashRedirectForHostPatterns", http_test_package.TestServeWithSlashRedirectForHostPatterns, "serve_test.go", 546);
        registry.Add("TestServeWithSlashRedirectKeepsQueryString", http_test_package.TestServeWithSlashRedirectKeepsQueryString, "serve_test.go", 489);
        registry.Add("TestServerAllowsBlockingRemoteAddr", http_test_package.TestServerAllowsBlockingRemoteAddr, "serve_test.go", 1433);
        registry.Add("TestServerBufferedChunking", http_test_package.TestServerBufferedChunking, "serve_test.go", 3249);
        registry.Add("TestServerCancelsReadHeaderTimeoutWhenIdle", http_test_package.TestServerCancelsReadHeaderTimeoutWhenIdle, "serve_test.go", 5957);
        registry.Add("TestServerCancelsReadTimeoutWhenIdle", http_test_package.TestServerCancelsReadTimeoutWhenIdle, "serve_test.go", 5905);
        registry.Add("TestServerCloseDeadlock", http_test_package.TestServerCloseDeadlock, "serve_test.go", 5847);
        registry.Add("TestServerCloseListenerOnce", http_test_package.TestServerCloseListenerOnce, "serve_test.go", 6244);
        registry.Add("TestServerConnState", http_test_package.TestServerConnState, "serve_test.go", 4288);
        registry.Add("TestServerConnStateNew", http_test_package.TestServerConnStateNew, "serve_test.go", 4507);
        registry.Add("TestServerContentType", http_test_package.TestServerContentType, "serve_test.go", 3016);
        registry.Add("TestServerContentTypeSniff", http_test_package.TestServerContentTypeSniff, "sniff_test.go", 91);
        registry.Add("TestServerContext_LocalAddrContextKey", http_test_package.TestServerContext_LocalAddrContextKey, "serve_test.go", 5069);
        registry.Add("TestServerContext_ServerContextKey", http_test_package.TestServerContext_ServerContextKey, "serve_test.go", 5051);
        registry.Add("TestServerContexts", http_test_package.TestServerContexts, "serve_test.go", 6307);
        registry.Add("TestServerDuplicateBackgroundRead", http_test_package.TestServerDuplicateBackgroundRead, "serve_test.go", 6025);
        registry.Add("TestServerEmptyBodyRace", http_test_package.TestServerEmptyBodyRace, "serve_test.go", 4470);
        registry.Add("TestServerExpect", http_test_package.TestServerExpect, "serve_test.go", 1889);
        registry.Add("TestServerFileStatError", http_test_package.TestServerFileStatError, "fs_test.go", 1205);
        registry.Add("TestServerFlushAndHijack", http_test_package.TestServerFlushAndHijack, "serve_test.go", 4557);
        registry.Add("TestServerGracefulClose", http_test_package.TestServerGracefulClose, "serve_test.go", 3271);
        registry.Add("TestServerHandlersCanHandleH2PRI", http_test_package.TestServerHandlersCanHandleH2PRI, "serve_test.go", 4894);
        registry.Add("TestServerHijackGetsBackgroundByte", http_test_package.TestServerHijackGetsBackgroundByte, "serve_test.go", 6082);
        registry.Add("TestServerHijackGetsBackgroundByte_big", http_test_package.TestServerHijackGetsBackgroundByte_big, "serve_test.go", 6138);
        registry.Add("TestServerIdleTimeout", http_test_package.TestServerIdleTimeout, "serve_test.go", 5581);
        registry.Add("TestServerIssue5953", http_test_package.TestServerIssue5953, "sniff_test.go", 133);
        registry.Add("TestServerKeepAliveAfterWriteError", http_test_package.TestServerKeepAliveAfterWriteError, "serve_test.go", 4591);
        registry.Add("TestServerKeepAlivesEnabled", http_test_package.TestServerKeepAlivesEnabled, "serve_test.go", 5855);
        registry.Add("TestServerKeepAlivesEnabledResultClose", http_test_package.TestServerKeepAlivesEnabledResultClose, "serve_test.go", 4451);
        registry.Add("TestServerListenNotComparableListener", http_test_package.TestServerListenNotComparableListener, "serve_test.go", 6224);
        registry.Add("TestServerNoDate", http_test_package.TestServerNoDate, "serve_test.go", 3010);
        registry.Add("TestServerNoReadTimeout", http_test_package.TestServerNoReadTimeout, "serve_test.go", 811);
        registry.Add("TestServerNoWriteTimeout", http_test_package.TestServerNoWriteTimeout, "serve_test.go", 920);
        registry.Add("TestServerReadAfterHandlerAbort100Continue", http_test_package.TestServerReadAfterHandlerAbort100Continue, "serve_test.go", 7261);
        registry.Add("TestServerReadAfterHandlerDone100Continue", http_test_package.TestServerReadAfterHandlerDone100Continue, "serve_test.go", 7234);
        registry.Add("TestServerReadAfterWriteHeader100Continue", http_test_package.TestServerReadAfterWriteHeader100Continue, "serve_test.go", 7203);
        registry.Add("TestServerReadTimeout", http_test_package.TestServerReadTimeout, "serve_test.go", 770);
        registry.Add("TestServerReaderFromOrder", http_test_package.TestServerReaderFromOrder, "serve_test.go", 4020);
        registry.Add("TestServerRequestContextCancel_ConnClose", http_test_package.TestServerRequestContextCancel_ConnClose, "serve_test.go", 5029);
        registry.Add("TestServerRequestContextCancel_ServeHTTPDone", http_test_package.TestServerRequestContextCancel_ServeHTTPDone, "serve_test.go", 4998);
        registry.Add("TestServerSetKeepAlivesEnabledClosesConns", http_test_package.TestServerSetKeepAlivesEnabledClosesConns, "serve_test.go", 5672);
        registry.Add("TestServerShutdown", http_test_package.TestServerShutdown, "serve_test.go", 5718);
        registry.Add("TestServerShutdownStateNew", http_test_package.TestServerShutdownStateNew, "serve_test.go", 5779);
        registry.Add("TestServerShutdownThenServe", http_test_package.TestServerShutdownThenServe, "serve_test.go", 6271);
        registry.Add("TestServerTLSHandshakeTimeout", http_internal_test_package.TestServerTLSHandshakeTimeout, "server_test.go", 17);
        registry.Add("TestServerTimeouts", http_test_package.TestServerTimeouts, "serve_test.go", 683);
        registry.Add("TestServerUndeclaredTrailers", http_test_package.TestServerUndeclaredTrailers, "clientserver_test.go", 1429);
        registry.Add("TestServerUnreadRequestBodyLarge", http_test_package.TestServerUnreadRequestBodyLarge, "serve_test.go", 2028);
        registry.Add("TestServerUnreadRequestBodyLittle", http_test_package.TestServerUnreadRequestBodyLittle, "serve_test.go", 1987);
        registry.Add("TestServerValidatesHeaders", http_test_package.TestServerValidatesHeaders, "serve_test.go", 4940);
        registry.Add("TestServerValidatesHostHeader", http_test_package.TestServerValidatesHostHeader, "serve_test.go", 4826);
        registry.Add("TestServerValidatesMethod", http_test_package.TestServerValidatesMethod, "serve_test.go", 6190);
        registry.Add("TestServerWriteHijackZeroBytes", http_test_package.TestServerWriteHijackZeroBytes, "serve_test.go", 2979);
        registry.Add("TestServerWriteTimeout", http_test_package.TestServerWriteTimeout, "serve_test.go", 855);
        registry.Add("TestSetBasicAuth", http_test_package.TestSetBasicAuth, "request_test.go", 361);
        registry.Add("TestSetCookie", http_internal_test_package.TestSetCookie, "cookie_test.go", 199);
        registry.Add("TestSetCookieDoubleQuotes", http_internal_test_package.TestSetCookieDoubleQuotes, "cookie_test.go", 486);
        registry.Add("TestSetPathValue", http_test_package.TestSetPathValue, "request_test.go", 1593);
        registry.Add("TestSetsRemoteAddr", http_test_package.TestSetsRemoteAddr, "serve_test.go", 1385);
        registry.Add("TestShouldCopyHeaderOnRedirect", http_test_package.TestShouldCopyHeaderOnRedirect, "client_test.go", 1755);
        registry.Add("TestShouldRedirectConcurrency", http_test_package.TestShouldRedirectConcurrency, "serve_test.go", 632);
        registry.Add("TestSniffWriteSize", http_test_package.TestSniffWriteSize, "sniff_test.go", 257);
        registry.Add("TestStarRequest", http_test_package.TestStarRequest, "request_test.go", 812);
        registry.Add("TestStarRequestMethod", http_test_package.TestStarRequestMethod, "clientserver_test.go", 1000);
        registry.Add("TestStatus", http_test_package.TestStatus, "request_test.go", 1619);
        registry.Add("TestStreamError", http_internal_test_package.TestStreamError, "h2_error_test.go", 27);
        registry.Add("TestStreamingGet", http_test_package.TestStreamingGet, "client_test.go", 735);
        registry.Add("TestStressSurpriseServerCloses", http_test_package.TestStressSurpriseServerCloses, "transport_test.go", 891);
        registry.Add("TestStripPasswordFromError", http_test_package.TestStripPasswordFromError, "client_test.go", 1127);
        registry.Add("TestStripPortFromHost", http_test_package.TestStripPortFromHost, "serve_test.go", 6286);
        registry.Add("TestStripPrefix", http_test_package.TestStripPrefix, "serve_test.go", 3037);
        registry.Add("TestStripPrefixNotModifyRequest", http_test_package.TestStripPrefixNotModifyRequest, "serve_test.go", 3084);
        registry.Add("TestTLSHandshakeTimeout", http_test_package.TestTLSHandshakeTimeout, "serve_test.go", 1539);
        registry.Add("TestTLSHandshakeTrace", http_test_package.TestTLSHandshakeTrace, "transport_test.go", 5204);
        registry.Add("TestTLSServer", http_test_package.TestTLSServer, "serve_test.go", 1569);
        registry.Add("TestTLSServerClosesConnection", http_test_package.TestTLSServerClosesConnection, "transport_test.go", 3564);
        registry.Add("TestTLSServerRejectHTTPRequests", http_test_package.TestTLSServerRejectHTTPRequests, "serve_test.go", 1670);
        registry.Add("TestTimeoutHandler", http_test_package.TestTimeoutHandler, "serve_test.go", 2452);
        registry.Add("TestTimeoutHandlerContextCanceled", http_test_package.TestTimeoutHandlerContextCanceled, "serve_test.go", 2673);
        registry.Add("TestTimeoutHandlerEmptyResponse", http_test_package.TestTimeoutHandlerEmptyResponse, "serve_test.go", 2714);
        registry.Add("TestTimeoutHandlerPanicRecovery", http_test_package.TestTimeoutHandlerPanicRecovery, "serve_test.go", 2735);
        registry.Add("TestTimeoutHandlerRace", http_test_package.TestTimeoutHandlerRace, "serve_test.go", 2509);
        registry.Add("TestTimeoutHandlerRaceHeader", http_test_package.TestTimeoutHandlerRaceHeader, "serve_test.go", 2551);
        registry.Add("TestTimeoutHandlerRaceHeaderTimeout", http_test_package.TestTimeoutHandlerRaceHeaderTimeout, "serve_test.go", 2588);
        registry.Add("TestTimeoutHandlerStartTimerWhenServing", http_test_package.TestTimeoutHandlerStartTimerWhenServing, "serve_test.go", 2643);
        registry.Add("TestTimeoutHandlerSuperfluousLogs", http_test_package.TestTimeoutHandlerSuperfluousLogs, "serve_test.go", 6513);
        registry.Add("TestTolerateCRLFBeforeRequestLine", http_test_package.TestTolerateCRLFBeforeRequestLine, "serve_test.go", 4683);
        registry.Add("TestTrailersClientToServer", http_test_package.TestTrailersClientToServer, "clientserver_test.go", 689);
        registry.Add("TestTrailersServerToClient", http_test_package.TestTrailersServerToClient, "clientserver_test.go", 740);
        registry.Add("TestTrailersServerToClientFlush", http_test_package.TestTrailersServerToClientFlush, "clientserver_test.go", 745);
        registry.Add("TestTransferWriterWriteBodyReaderTypes", http_internal_test_package.TestTransferWriterWriteBodyReaderTypes, "transfer_test.go", 114);
        registry.Add("TestTransportAltProto", http_test_package.TestTransportAltProto, "transport_test.go", 2998);
        registry.Add("TestTransportAndServerSharedBodyRace", http_test_package.TestTransportAndServerSharedBodyRace, "serve_test.go", 4117);
        registry.Add("TestTransportAutomaticHTTP2", http_test_package.TestTransportAutomaticHTTP2, "transport_test.go", 4581);
        registry.Add("TestTransportAutomaticHTTP2_DefaultTransport", http_test_package.TestTransportAutomaticHTTP2_DefaultTransport, "transport_test.go", 4593);
        registry.Add("TestTransportAutomaticHTTP2_Dial", http_test_package.TestTransportAutomaticHTTP2_Dial, "transport_test.go", 4615);
        registry.Add("TestTransportAutomaticHTTP2_DialContext", http_test_package.TestTransportAutomaticHTTP2_DialContext, "transport_test.go", 4622);
        registry.Add("TestTransportAutomaticHTTP2_DialTLS", http_test_package.TestTransportAutomaticHTTP2_DialTLS, "transport_test.go", 4629);
        registry.Add("TestTransportAutomaticHTTP2_DialerAndTLSConfigSupportsHTTP2AndTLSConfig", http_test_package.TestTransportAutomaticHTTP2_DialerAndTLSConfigSupportsHTTP2AndTLSConfig, "transport_test.go", 4585);
        registry.Add("TestTransportAutomaticHTTP2_ExpectContinueTimeout", http_test_package.TestTransportAutomaticHTTP2_ExpectContinueTimeout, "transport_test.go", 4609);
        registry.Add("TestTransportAutomaticHTTP2_TLSConfig", http_test_package.TestTransportAutomaticHTTP2_TLSConfig, "transport_test.go", 4603);
        registry.Add("TestTransportAutomaticHTTP2_TLSNextProto", http_test_package.TestTransportAutomaticHTTP2_TLSNextProto, "transport_test.go", 4597);
        registry.Add("TestTransportBodyAltRewind", http_internal_test_package.TestTransportBodyAltRewind, "transport_internal_test.go", 200);
        registry.Add("TestTransportBodyReadError", http_test_package.TestTransportBodyReadError, "client_test.go", 1915);
        registry.Add("TestTransportCONNECTBidi", http_test_package.TestTransportCONNECTBidi, "transport_test.go", 6042);
        registry.Add("TestTransportCancelRequest", http_test_package.TestTransportCancelRequest, "transport_test.go", 2644);
        registry.Add("TestTransportCancelRequestBeforeDo", http_test_package.TestTransportCancelRequestBeforeDo, "transport_test.go", 2865);
        registry.Add("TestTransportCancelRequestBeforeResponseHeaders", http_test_package.TestTransportCancelRequestBeforeResponseHeaders, "transport_test.go", 2894);
        registry.Add("TestTransportCancelRequestInDial", http_test_package.TestTransportCancelRequestInDial, "transport_test.go", 2746);
        registry.Add("TestTransportCancelRequestInDo", http_test_package.TestTransportCancelRequestInDo, "transport_test.go", 2734);
        registry.Add("TestTransportCancelRequestWithBody", http_test_package.TestTransportCancelRequestWithBody, "transport_test.go", 2810);
        registry.Add("TestTransportCancelRequestWithBodyInDo", http_test_package.TestTransportCancelRequestWithBodyInDo, "transport_test.go", 2740);
        registry.Add("TestTransportCheckContextDoneEarly", http_test_package.TestTransportCheckContextDoneEarly, "transport_test.go", 5845);
        registry.Add("TestTransportClone", http_test_package.TestTransportClone, "transport_test.go", 6306);
        registry.Add("TestTransportCloseIdleConnsThenReturn", http_test_package.TestTransportCloseIdleConnsThenReturn, "transport_test.go", 4114);
        registry.Add("TestTransportCloseResponseBody", http_test_package.TestTransportCloseResponseBody, "transport_test.go", 2939);
        registry.Add("TestTransportClosesBodyOnError", http_test_package.TestTransportClosesBodyOnError, "transport_test.go", 3927);
        registry.Add("TestTransportClosesBodyOnInvalidRequests", http_test_package.TestTransportClosesBodyOnInvalidRequests, "transport_test.go", 6476);
        registry.Add("TestTransportClosesRequestBody", http_test_package.TestTransportClosesRequestBody, "transport_test.go", 3491);
        registry.Add("TestTransportConcurrency", http_test_package.TestTransportConcurrency, "transport_test.go", 2310);
        registry.Add("TestTransportConnectionCloseOnRequest", http_test_package.TestTransportConnectionCloseOnRequest, "transport_test.go", 256);
        registry.Add("TestTransportConnectionCloseOnRequestDisableKeepAlive", http_test_package.TestTransportConnectionCloseOnRequestDisableKeepAlive, "transport_test.go", 321);
        registry.Add("TestTransportConnectionCloseOnResponse", http_test_package.TestTransportConnectionCloseOnResponse, "transport_test.go", 199);
        registry.Add("TestTransportContentEncodingCaseInsensitive", http_test_package.TestTransportContentEncodingCaseInsensitive, "transport_test.go", 4297);
        registry.Add("TestTransportDecrementConnWhenIdleConnRemoved", http_test_package.TestTransportDecrementConnWhenIdleConnRemoved, "transport_test.go", 6648);
        registry.Add("TestTransportDialContext", http_test_package.TestTransportDialContext, "transport_test.go", 4005);
        registry.Add("TestTransportDialPreservesNetOpProxyError", http_test_package.TestTransportDialPreservesNetOpProxyError, "transport_test.go", 1750);
        registry.Add("TestTransportDialTLS", http_test_package.TestTransportDialTLS, "transport_test.go", 3967);
        registry.Add("TestTransportDialTLSContext", http_test_package.TestTransportDialTLSContext, "transport_test.go", 4047);
        registry.Add("TestTransportDiscardsUnneededConns", http_test_package.TestTransportDiscardsUnneededConns, "clientserver_test.go", 1073);
        registry.Add("TestTransportEmptyMethod", http_test_package.TestTransportEmptyMethod, "transport_test.go", 3033);
        registry.Add("TestTransportEventTrace", http_test_package.TestTransportEventTrace, "transport_test.go", 4856);
        registry.Add("TestTransportEventTraceRealDNS", http_test_package.TestTransportEventTraceRealDNS, "transport_test.go", 5134);
        registry.Add("TestTransportEventTraceTLSVerify", http_test_package.TestTransportEventTraceTLSVerify, "transport_test.go", 5051);
        registry.Add("TestTransportEventTrace_NoHooks", http_test_package.TestTransportEventTrace_NoHooks, "transport_test.go", 4863);
        registry.Add("TestTransportExpect100Continue200ResponseNoConnClose", http_test_package.TestTransportExpect100Continue200ResponseNoConnClose, "transport_test.go", 1296);
        registry.Add("TestTransportExpect100Continue200ResponseWithConnClose", http_test_package.TestTransportExpect100Continue200ResponseWithConnClose, "transport_test.go", 1304);
        registry.Add("TestTransportExpect100Continue500ResponseNoConnClose", http_test_package.TestTransportExpect100Continue500ResponseNoConnClose, "transport_test.go", 1311);
        registry.Add("TestTransportExpect100Continue500ResponseTimeout", http_test_package.TestTransportExpect100Continue500ResponseTimeout, "transport_test.go", 1319);
        registry.Add("TestTransportExpect100ContinueSent", http_test_package.TestTransportExpect100ContinueSent, "transport_test.go", 1287);
        registry.Add("TestTransportFlushesBodyChunks", http_test_package.TestTransportFlushesBodyChunks, "transport_test.go", 4401);
        registry.Add("TestTransportFlushesRequestHeader", http_test_package.TestTransportFlushesRequestHeader, "transport_test.go", 4462);
        registry.Add("TestTransportGzip", http_test_package.TestTransportGzip, "transport_test.go", 1092);
        registry.Add("TestTransportGzipRecursive", http_test_package.TestTransportGzipRecursive, "transport_test.go", 1833);
        registry.Add("TestTransportGzipShort", http_test_package.TestTransportGzipShort, "transport_test.go", 1860);
        registry.Add("TestTransportHeadChunkedResponse", http_test_package.TestTransportHeadChunkedResponse, "transport_test.go", 978);
        registry.Add("TestTransportHeadResponses", http_test_package.TestTransportHeadResponses, "transport_test.go", 945);
        registry.Add("TestTransportIDNA", http_test_package.TestTransportIDNA, "transport_test.go", 5489);
        registry.Add("TestTransportIdleCacheKeys", http_test_package.TestTransportIdleCacheKeys, "transport_test.go", 393);
        registry.Add("TestTransportIdleConnCrash", http_test_package.TestTransportIdleConnCrash, "transport_test.go", 2184);
        registry.Add("TestTransportIdleConnTimeout", http_test_package.TestTransportIdleConnTimeout, "transport_test.go", 5304);
        registry.Add("TestTransportIgnore1xxResponses", http_test_package.TestTransportIgnore1xxResponses, "transport_test.go", 3228);
        registry.Add("TestTransportIgnores408", http_test_package.TestTransportIgnores408, "transport_test.go", 6382);
        registry.Add("TestTransportIssue10457", http_test_package.TestTransportIssue10457, "transport_test.go", 3718);
        registry.Add("TestTransportKeepAlives", http_test_package.TestTransportKeepAlives, "transport_test.go", 169);
        registry.Add("TestTransportLimits1xxResponses", http_test_package.TestTransportLimits1xxResponses, "transport_test.go", 3262);
        registry.Add("TestTransportMaxConnsPerHost", http_test_package.TestTransportMaxConnsPerHost, "transport_test.go", 632);
        registry.Add("TestTransportMaxConnsPerHostDialCancellation", http_test_package.TestTransportMaxConnsPerHostDialCancellation, "transport_test.go", 733);
        registry.Add("TestTransportMaxConnsPerHostIncludeDialInProgress", http_test_package.TestTransportMaxConnsPerHostIncludeDialInProgress, "transport_test.go", 564);
        registry.Add("TestTransportMaxIdleConns", http_test_package.TestTransportMaxIdleConns, "transport_test.go", 5250);
        registry.Add("TestTransportMaxPerHostIdleConns", http_test_package.TestTransportMaxPerHostIdleConns, "transport_test.go", 475);
        registry.Add("TestTransportNoHost", http_test_package.TestTransportNoHost, "transport_test.go", 3017);
        registry.Add("TestTransportNoReuseAfterEarlyResponse", http_test_package.TestTransportNoReuseAfterEarlyResponse, "transport_test.go", 3648);
        registry.Add("TestTransportPersistConnContextLeakMaxConnsPerHost", http_test_package.TestTransportPersistConnContextLeakMaxConnsPerHost, "transport_test.go", 2123);
        registry.Add("TestTransportPersistConnLeak", http_test_package.TestTransportPersistConnLeak, "transport_test.go", 1894);
        registry.Add("TestTransportPersistConnLeakNeverIdle", http_test_package.TestTransportPersistConnLeakNeverIdle, "transport_test.go", 2051);
        registry.Add("TestTransportPersistConnLeakShortBody", http_test_package.TestTransportPersistConnLeakShortBody, "transport_test.go", 1968);
        registry.Add("TestTransportPersistConnReadLoopEOF", http_internal_test_package.TestTransportPersistConnReadLoopEOF, "transport_internal_test.go", 22);
        registry.Add("TestTransportPoolConnCannotReuseConnectionInUse", http_test_package.TestTransportPoolConnCannotReuseConnectionInUse, "transport_dial_test.go", 32);
        registry.Add("TestTransportPoolConnConnectionBecomesAvailableDuringDial", http_test_package.TestTransportPoolConnConnectionBecomesAvailableDuringDial, "transport_dial_test.go", 49);
        registry.Add("TestTransportPoolConnReusePriorConnection", http_test_package.TestTransportPoolConnReusePriorConnection, "transport_dial_test.go", 16);
        registry.Add("TestTransportPrefersResponseOverWriteError", http_test_package.TestTransportPrefersResponseOverWriteError, "transport_test.go", 4506);
        registry.Add("TestTransportProxy", http_test_package.TestTransportProxy, "transport_test.go", 1434);
        registry.Add("TestTransportProxyConnectHeader", http_test_package.TestTransportProxyConnectHeader, "transport_test.go", 5559);
        registry.Add("TestTransportProxyDialDoesNotMutateProxyConnectHeader", http_test_package.TestTransportProxyDialDoesNotMutateProxyConnectHeader, "transport_test.go", 1795);
        registry.Add("TestTransportProxyGetConnectHeader", http_test_package.TestTransportProxyGetConnectHeader, "transport_test.go", 5601);
        registry.Add("TestTransportProxyHTTPSConnectLeak", http_test_package.TestTransportProxyHTTPSConnectLeak, "transport_test.go", 1676);
        registry.Add("TestTransportRangeAndGzip", http_test_package.TestTransportRangeAndGzip, "transport_test.go", 4238);
        registry.Add("TestTransportReadToEndReusesConn", http_test_package.TestTransportReadToEndReusesConn, "transport_test.go", 428);
        registry.Add("TestTransportReading100Continue", http_test_package.TestTransportReading100Continue, "transport_test.go", 3126);
        registry.Add("TestTransportRejectsAlphaPort", http_test_package.TestTransportRejectsAlphaPort, "transport_test.go", 5185);
        registry.Add("TestTransportRejectsInvalidHeaders", http_test_package.TestTransportRejectsInvalidHeaders, "clientserver_test.go", 1201);
        registry.Add("TestTransportRejectsSignInContentLength", http_test_package.TestTransportRejectsSignInContentLength, "transport_test.go", 6752);
        registry.Add("TestTransportRemovesDeadIdleConnections", http_test_package.TestTransportRemovesDeadIdleConnections, "transport_test.go", 783);
        registry.Add("TestTransportRemovesH2ConnsAfterIdle", http_test_package.TestTransportRemovesH2ConnsAfterIdle, "transport_test.go", 4184);
        registry.Add("TestTransportReqCancelerCleanupOnRequestBodyWriteError", http_test_package.TestTransportReqCancelerCleanupOnRequestBodyWriteError, "transport_test.go", 7037);
        registry.Add("TestTransportRequestReplayable", http_test_package.TestTransportRequestReplayable, "transport_test.go", 6106);
        registry.Add("TestTransportRequestWriteRoundTrip", http_test_package.TestTransportRequestWriteRoundTrip, "transport_test.go", 6172);
        registry.Add("TestTransportRespectRequestWantsClose", http_test_package.TestTransportRespectRequestWantsClose, "transport_test.go", 342);
        registry.Add("TestTransportResponseBodyWritableOnProtocolSwitch", http_test_package.TestTransportResponseBodyWritableOnProtocolSwitch, "transport_test.go", 5991);
        registry.Add("TestTransportResponseCancelRace", http_test_package.TestTransportResponseCancelRace, "transport_test.go", 4260);
        registry.Add("TestTransportResponseHeaderLength", http_test_package.TestTransportResponseHeaderLength, "transport_test.go", 4821);
        registry.Add("TestTransportResponseHeaderTimeout", http_test_package.TestTransportResponseHeaderTimeout, "transport_test.go", 2475);
        registry.Add("TestTransportReturnsPeekError", http_test_package.TestTransportReturnsPeekError, "transport_test.go", 5461);
        registry.Add("TestTransportReuseConnEmptyResponseBody", http_test_package.TestTransportReuseConnEmptyResponseBody, "transport_test.go", 4655);
        registry.Add("TestTransportReuseConnection_Gzip_Chunked", http_test_package.TestTransportReuseConnection_Gzip_Chunked, "transport_test.go", 4766);
        registry.Add("TestTransportReuseConnection_Gzip_ContentLength", http_test_package.TestTransportReuseConnection_Gzip_ContentLength, "transport_test.go", 4772);
        registry.Add("TestTransportServerClosingUnexpectedly", http_test_package.TestTransportServerClosingUnexpectedly, "transport_test.go", 834);
        registry.Add("TestTransportShouldRetryRequest", http_internal_test_package.TestTransportShouldRetryRequest, "transport_internal_test.go", 116);
        registry.Add("TestTransportSocketLateBinding", http_test_package.TestTransportSocketLateBinding, "transport_test.go", 3045);
        registry.Add("TestTransportTLSHandshakeTimeout", http_test_package.TestTransportTLSHandshakeTimeout, "transport_test.go", 3513);
        registry.Add("TestTransportTraceGotConnH2IdleConns", http_test_package.TestTransportTraceGotConnH2IdleConns, "transport_test.go", 4154);
        registry.Add("TestTransportTreat101Terminal", http_test_package.TestTransportTreat101Terminal, "transport_test.go", 3290);
        registry.Add("TestTransportUserAgent", http_test_package.TestTransportUserAgent, "clientserver_test.go", 942);
        registry.Add("TestTransportUsesTLSConfigServerName", http_test_package.TestTransportUsesTLSConfigServerName, "client_test.go", 918);
        registry.Add("TestUnsupportedTransferEncodingsReturn501", http_test_package.TestUnsupportedTransferEncodingsReturn501, "serve_test.go", 6377);
        registry.Add("TestValidateClientRequestTrailers", http_test_package.TestValidateClientRequestTrailers, "transport_test.go", 7098);
        registry.Add("TestWithContextNilURL", http_test_package.TestWithContextNilURL, "request_test.go", 1022);
        registry.Add("TestWrappedResponseController", http_test_package.TestWrappedResponseController, "responsecontroller_test.go", 259);
        registry.Add("TestWriteAfterHijack", http_test_package.TestWriteAfterHijack, "serve_test.go", 3904);
        registry.Add("TestWriteDeadlineEnforcedPerStream", http_test_package.TestWriteDeadlineEnforcedPerStream, "serve_test.go", 996);
        registry.Add("TestWriteDeadlineExtendedOnNewRequest", http_test_package.TestWriteDeadlineExtendedOnNewRequest, "serve_test.go", 948);
        registry.Add("TestWriteHeader0", http_test_package.TestWriteHeader0, "clientserver_test.go", 1485);
        registry.Add("TestWriteHeaderNoCodeCheck", http_test_package.TestWriteHeaderNoCodeCheck, "clientserver_test.go", 1521);
        registry.Add("TestWriteHeaderNoCodeCheck_h1hijack", http_test_package.TestWriteHeaderNoCodeCheck_h1hijack, "clientserver_test.go", 1526);
        registry.Add("TestWriteHeaderSwitchingProtocols", http_test_package.TestWriteHeaderSwitchingProtocols, "serve_test.go", 6711);
        registry.Add("TestWriteResponse", http_internal_test_package.TestWriteResponse, "response_test.go", 615);
        registry.Add("TestWriteSetCookies", http_internal_test_package.TestWriteSetCookies, "cookie_test.go", 169);
        registry.Add("TestZeroLengthPostAndResponse", http_test_package.TestZeroLengthPostAndResponse, "serve_test.go", 2859);
        registry.SetTestMain(http_test_package.TestMain);
        return TestHost.Run(registry, args);
    }
}
