// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.net.http;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("net/http/internal", new string[]
        {
            "chunked.go",
            "chunked_test.go",
        }, new string[]
        {
            "ascii",
            "testcert",
        });
        registry.Add("TestChunk", internal_internal_test_package.TestChunk, "chunked_test.go", 17);
        registry.Add("TestChunkEndReadError", internal_internal_test_package.TestChunkEndReadError, "chunked_test.go", 235);
        registry.Add("TestChunkInvalidInputs", internal_internal_test_package.TestChunkInvalidInputs, "chunked_test.go", 283);
        registry.Add("TestChunkReadMultiple", internal_internal_test_package.TestChunkReadMultiple, "chunked_test.go", 42);
        registry.Add("TestChunkReadPartial", internal_internal_test_package.TestChunkReadPartial, "chunked_test.go", 192);
        registry.Add("TestChunkReaderAllocs", internal_internal_test_package.TestChunkReaderAllocs, "chunked_test.go", 109);
        registry.Add("TestChunkReaderByteAtATime", internal_internal_test_package.TestChunkReaderByteAtATime, "chunked_test.go", 265);
        registry.Add("TestChunkReaderTooMuchOverhead", internal_internal_test_package.TestChunkReaderTooMuchOverhead, "chunked_test.go", 244);
        registry.Add("TestChunkReadingIgnoresExtensions", internal_internal_test_package.TestChunkReadingIgnoresExtensions, "chunked_test.go", 175);
        registry.Add("TestIncompleteChunk", internal_internal_test_package.TestIncompleteChunk, "chunked_test.go", 218);
        registry.Add("TestParseHexUint", internal_internal_test_package.TestParseHexUint, "chunked_test.go", 141);
        return TestHost.Run(registry, args);
    }
}
