// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/poll", new string[]
        {
            "copy_file_range_linux.go",
            "errno_unix.go",
            "errno_windows.go",
            "error_linux_test.go",
            "error_stub_test.go",
            "error_test.go",
            "export_linux_test.go",
            "export_posix_test.go",
            "export_test.go",
            "export_windows_test.go",
            "fd.go",
            "fd_fsync_darwin.go",
            "fd_fsync_posix.go",
            "fd_fsync_windows.go",
            "fd_io_plan9.go",
            "fd_mutex.go",
            "fd_mutex_test.go",
            "fd_opendir_darwin.go",
            "fd_plan9.go",
            "fd_poll_js.go",
            "fd_poll_runtime.go",
            "fd_posix.go",
            "fd_posix_test.go",
            "fd_unix.go",
            "fd_unixjs.go",
            "fd_wasip1.go",
            "fd_windows.go",
            "fd_windows_test.go",
            "fd_writev_libc.go",
            "fd_writev_unix.go",
            "file_plan9.go",
            "hook_cloexec.go",
            "hook_unix.go",
            "hook_windows.go",
            "iovec_solaris.go",
            "iovec_unix.go",
            "read_test.go",
            "sendfile.go",
            "sendfile_bsd.go",
            "sendfile_linux.go",
            "sendfile_solaris.go",
            "sendfile_windows.go",
            "sock_cloexec.go",
            "sock_cloexec_accept.go",
            "sock_cloexec_solaris.go",
            "sockopt.go",
            "sockopt_linux.go",
            "sockopt_unix.go",
            "sockopt_windows.go",
            "sockoptip.go",
            "splice_linux.go",
            "splice_linux_test.go",
            "sys_cloexec.go",
            "writev.go",
            "writev_test.go",
        });
        registry.Add("TestConsume", poll_test_package.TestConsume, "writev_test.go", 13);
        registry.Add("TestEOFError", poll_test_package.TestEOFError, "fd_posix_test.go", 36);
        registry.Add("TestFileFdsAreInitialised", poll_test_package.TestFileFdsAreInitialised, "fd_windows_test.go", 69);
        registry.Add("TestMutexClose", poll_test_package.TestMutexClose, "fd_mutex_test.go", 41);
        registry.Add("TestMutexCloseUnblock", poll_test_package.TestMutexCloseUnblock, "fd_mutex_test.go", 61);
        registry.Add("TestMutexLock", poll_test_package.TestMutexLock, "fd_mutex_test.go", 16);
        registry.Add("TestMutexOverflowPanic", poll_test_package.TestMutexOverflowPanic, "fd_mutex_test.go", 125);
        registry.Add("TestMutexPanic", poll_test_package.TestMutexPanic, "fd_mutex_test.go", 97);
        registry.Add("TestMutexStress", poll_test_package.TestMutexStress, "fd_mutex_test.go", 146);
        registry.Add("TestRead", poll_test_package.TestRead, "read_test.go", 15);
        registry.Add("TestReadError", poll_test_package.TestReadError, "error_test.go", 16);
        registry.Add("TestSerialFdsAreInitialised", poll_test_package.TestSerialFdsAreInitialised, "fd_windows_test.go", 86);
        registry.Add("TestWSASocketConflict", poll_test_package.TestWSASocketConflict, "fd_windows_test.go", 118);
        return TestHost.Run(registry, args);
    }
}
