// Code generated by 'go generate'; DO NOT EDIT.
namespace go.@internal.syscall.windows;

using sysdll = go.@internal.syscall.windows.sysdll_package;
using syscall = syscall_package;
using @unsafe = unsafe_package;
using go.@internal.syscall.windows;

partial class registry_package {

// Go runs an imported package's `init` before this package's own; .NET would never load
// an assembly nothing has touched yet, so that initialization is forced here.
[GoInit] internal static void initᴛᴛimportꓸinternalꓸsyscallꓸwindowsꓸsysdll() {
    builtin.initPackage(typeof(go.@internal.syscall.windows.sysdll_package));
}

internal static @unsafe.Pointer _ᴛ1ʗ;

// Do the interface allocations only once for common
// Errno values.
internal static UntypedInt errnoERROR_IO_PENDING => 997;

internal static error errERROR_IO_PENDING = ((syscall.Errno)errnoERROR_IO_PENDING);
internal static error errERROR_EINVAL = ((syscall.Errno)syscall.EINVAL);

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
internal static error errnoErr(syscall.Errno e) {
    var exprᴛ1 = e;
    if (exprᴛ1 == (syscall.Errno)(0)) {
        return errERROR_EINVAL;
    }
    if (exprᴛ1 == errnoERROR_IO_PENDING) {
        return errERROR_IO_PENDING;
    }

    // TODO: add more here, after collecting data on the common
    // error values see on Windows. (perhaps when running
    // all.bat?)
    return e;
}

internal static ж<syscall.LazyDLL> modadvapi32 = syscall.NewLazyDLL(sysdll.Add("advapi32.dll"u8));
internal static ж<syscall.LazyDLL> modkernel32 = syscall.NewLazyDLL(sysdll.Add("kernel32.dll"u8));
internal static ж<syscall.LazyProc> procRegCreateKeyExW = modadvapi32.NewProc("RegCreateKeyExW"u8);
internal static ж<syscall.LazyProc> procRegDeleteKeyW = modadvapi32.NewProc("RegDeleteKeyW"u8);
internal static ж<syscall.LazyProc> procRegDeleteValueW = modadvapi32.NewProc("RegDeleteValueW"u8);
internal static ж<syscall.LazyProc> procRegEnumValueW = modadvapi32.NewProc("RegEnumValueW"u8);
internal static ж<syscall.LazyProc> procRegLoadMUIStringW = modadvapi32.NewProc("RegLoadMUIStringW"u8);
internal static ж<syscall.LazyProc> procRegSetValueExW = modadvapi32.NewProc("RegSetValueExW"u8);
internal static ж<syscall.LazyProc> procExpandEnvironmentStringsW = modkernel32.NewProc("ExpandEnvironmentStringsW"u8);

internal static error /*regerrno*/ regCreateKeyEx(syscallꓸHandle key, ж<uint16> Ꮡsubkey, uint32 reserved, ж<uint16> Ꮡclass, uint32 options, uint32 desired, ж<syscall.SecurityAttributes> Ꮡsa, ж<syscallꓸHandle> Ꮡresult, ж<uint32> Ꮡdisposition) {
    error regerrno = default!;

    var ᴋ0 = Ꮡsubkey;
    var ᴋ1 = Ꮡclass;
    var ᴋ2 = Ꮡsa;
    var ᴋ3 = Ꮡresult;
    var ᴋ4 = Ꮡdisposition;
        var (r0, _, _) = syscall.Syscall9(procRegCreateKeyExW.Addr(), 9, (uintptr)key, (uintptr)ᴋ0, (uintptr)reserved, (uintptr)ᴋ1, (uintptr)options, (uintptr)desired, (uintptr)ᴋ2, (uintptr)ᴋ3, (uintptr)ᴋ4);
    System.GC.KeepAlive(ᴋ0);
    System.GC.KeepAlive(ᴋ1);
    System.GC.KeepAlive(ᴋ2);
    System.GC.KeepAlive(ᴋ3);
    System.GC.KeepAlive(ᴋ4);
    if (r0 != 0) {
        regerrno = ((syscall.Errno)r0);
    }
    return regerrno;
}

internal static error /*regerrno*/ regDeleteKey(syscallꓸHandle key, ж<uint16> Ꮡsubkey) {
    error regerrno = default!;

    var ᴋ0 = Ꮡsubkey;
        var (r0, _, _) = syscall.Syscall(procRegDeleteKeyW.Addr(), 2, (uintptr)key, (uintptr)ᴋ0, 0);
    System.GC.KeepAlive(ᴋ0);
    if (r0 != 0) {
        regerrno = ((syscall.Errno)r0);
    }
    return regerrno;
}

internal static error /*regerrno*/ regDeleteValue(syscallꓸHandle key, ж<uint16> Ꮡname) {
    error regerrno = default!;

    var ᴋ0 = Ꮡname;
        var (r0, _, _) = syscall.Syscall(procRegDeleteValueW.Addr(), 2, (uintptr)key, (uintptr)ᴋ0, 0);
    System.GC.KeepAlive(ᴋ0);
    if (r0 != 0) {
        regerrno = ((syscall.Errno)r0);
    }
    return regerrno;
}

internal static error /*regerrno*/ regEnumValue(syscallꓸHandle key, uint32 index, ж<uint16> Ꮡname, ж<uint32> ᏑnameLen, ж<uint32> Ꮡreserved, ж<uint32> Ꮡvaltype, ж<byte> Ꮡbuf, ж<uint32> Ꮡbuflen) {
    error regerrno = default!;

    var ᴋ0 = Ꮡname;
    var ᴋ1 = ᏑnameLen;
    var ᴋ2 = Ꮡreserved;
    var ᴋ3 = Ꮡvaltype;
    var ᴋ4 = Ꮡbuf;
    var ᴋ5 = Ꮡbuflen;
        var (r0, _, _) = syscall.Syscall9(procRegEnumValueW.Addr(), 8, (uintptr)key, (uintptr)index, (uintptr)ᴋ0, (uintptr)ᴋ1, (uintptr)ᴋ2, (uintptr)ᴋ3, (uintptr)ᴋ4, (uintptr)ᴋ5, 0);
    System.GC.KeepAlive(ᴋ0);
    System.GC.KeepAlive(ᴋ1);
    System.GC.KeepAlive(ᴋ2);
    System.GC.KeepAlive(ᴋ3);
    System.GC.KeepAlive(ᴋ4);
    System.GC.KeepAlive(ᴋ5);
    if (r0 != 0) {
        regerrno = ((syscall.Errno)r0);
    }
    return regerrno;
}

internal static error /*regerrno*/ regLoadMUIString(syscallꓸHandle key, ж<uint16> Ꮡname, ж<uint16> Ꮡbuf, uint32 buflen, ж<uint32> ᏑbuflenCopied, uint32 flags, ж<uint16> Ꮡdir) {
    error regerrno = default!;

    var ᴋ0 = Ꮡname;
    var ᴋ1 = Ꮡbuf;
    var ᴋ2 = ᏑbuflenCopied;
    var ᴋ3 = Ꮡdir;
        var (r0, _, _) = syscall.Syscall9(procRegLoadMUIStringW.Addr(), 7, (uintptr)key, (uintptr)ᴋ0, (uintptr)ᴋ1, (uintptr)buflen, (uintptr)ᴋ2, (uintptr)flags, (uintptr)ᴋ3, 0, 0);
    System.GC.KeepAlive(ᴋ0);
    System.GC.KeepAlive(ᴋ1);
    System.GC.KeepAlive(ᴋ2);
    System.GC.KeepAlive(ᴋ3);
    if (r0 != 0) {
        regerrno = ((syscall.Errno)r0);
    }
    return regerrno;
}

internal static error /*regerrno*/ regSetValueEx(syscallꓸHandle key, ж<uint16> ᏑvalueName, uint32 reserved, uint32 vtype, ж<byte> Ꮡbuf, uint32 bufsize) {
    error regerrno = default!;

    var ᴋ0 = ᏑvalueName;
    var ᴋ1 = Ꮡbuf;
        var (r0, _, _) = syscall.Syscall6(procRegSetValueExW.Addr(), 6, (uintptr)key, (uintptr)ᴋ0, (uintptr)reserved, (uintptr)vtype, (uintptr)ᴋ1, (uintptr)bufsize);
    System.GC.KeepAlive(ᴋ0);
    System.GC.KeepAlive(ᴋ1);
    if (r0 != 0) {
        regerrno = ((syscall.Errno)r0);
    }
    return regerrno;
}

internal static (uint32 n, error err) expandEnvironmentStrings(ж<uint16> Ꮡsrc, ж<uint16> Ꮡdst, uint32 size) {
    uint32 n = default!;
    error err = default!;

    var ᴋ0 = Ꮡsrc;
    var ᴋ1 = Ꮡdst;
        var (r0, _, e1) = syscall.Syscall(procExpandEnvironmentStringsW.Addr(), 3, (uintptr)ᴋ0, (uintptr)ᴋ1, (uintptr)size);
    System.GC.KeepAlive(ᴋ0);
    System.GC.KeepAlive(ᴋ1);
    n = (uint32)r0;
    if (n == 0) {
        err = errnoErr(e1);
    }
    return (n, err);
}

} // end registry_package
