// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/sha256", new string[]
        {
            "example_test.go",
            "fallback_test.go",
            "sha256.go",
            "sha256_test.go",
            "sha256block.go",
            "sha256block_amd64.go",
            "sha256block_arm64.go",
            "sha256block_decl.go",
            "sha256block_generic.go",
            "sha256block_s390x.go",
        });
        registry.Add("TestAllocations", sha256_package.TestAllocations, "sha256_test.go", 297);
        registry.Add("TestBlockGeneric", sha256_package.TestBlockGeneric, "sha256_test.go", 220);
        registry.Add("TestBlockSize", sha256_package.TestBlockSize, "sha256_test.go", 212);
        registry.Add("TestCgo", sha256_package.TestCgo, "sha256_test.go", 319);
        registry.Add("TestGolden", sha256_package.TestGolden, "sha256_test.go", 95);
        registry.Add("TestGoldenMarshal", sha256_package.TestGoldenMarshal, "sha256_test.go", 142);
        registry.Add("TestLargeHashes", sha256_package.TestLargeHashes, "sha256_test.go", 276);
        registry.Add("TestMarshalTypeMismatch", sha256_package.TestMarshalTypeMismatch, "sha256_test.go", 187);
        registry.Add("TestSHA256Hash", sha256_package.TestSHA256Hash, "sha256_test.go", 329);
        registry.Add("TestSize", sha256_package.TestSize, "sha256_test.go", 201);
        return TestHost.Run(registry, args);
    }
}
