// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.go;

using global::go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("go/parser", new string[]
        {
            "error_test.go",
            "example_test.go",
            "interface.go",
            "parser.go",
            "parser_test.go",
            "performance_test.go",
            "resolver.go",
            "resolver_test.go",
            "short_test.go",
            "testdata/chans.go2",
            "testdata/commas.src",
            "testdata/goversion/t01.go",
            "testdata/goversion/t02.go",
            "testdata/goversion/t03.go",
            "testdata/goversion/t04.go",
            "testdata/goversion/t05.go",
            "testdata/goversion/t06.go",
            "testdata/interface.go2",
            "testdata/issue11377.src",
            "testdata/issue23434.src",
            "testdata/issue3106.src",
            "testdata/issue34946.src",
            "testdata/issue42951/not_a_file.go/invalid.go",
            "testdata/issue44504.src",
            "testdata/issue49174.go2",
            "testdata/issue49175.go2",
            "testdata/issue49482.go2",
            "testdata/issue50427.go2",
            "testdata/issue64534.src",
            "testdata/linalg.go2",
            "testdata/map.go2",
            "testdata/metrics.go2",
            "testdata/resolution/issue45136.src",
            "testdata/resolution/issue45160.src",
            "testdata/resolution/resolution.src",
            "testdata/resolution/typeparams.go2",
            "testdata/set.go2",
            "testdata/slices.go2",
            "testdata/sort.go2",
            "testdata/tparams.go2",
            "testdata/typeset.go2",
        }, new string[]
        {
            "testdata",
        });
        registry.Add("TestColonEqualsScope", parser_internal_test_package.TestColonEqualsScope, "parser_test.go", 161);
        registry.Add("TestCommentGroups", parser_internal_test_package.TestCommentGroups, "parser_test.go", 312);
        registry.Add("TestErrors", parser_internal_test_package.TestErrors, "error_test.go", 185);
        registry.Add("TestFileStartEndPos", parser_internal_test_package.TestFileStartEndPos, "parser_test.go", 491);
        registry.Add("TestGoVersion", parser_internal_test_package.TestGoVersion, "parser_test.go", 785);
        registry.Add("TestIncompleteSelection", parser_internal_test_package.TestIncompleteSelection, "parser_test.go", 522);
        registry.Add("TestInvalid", parser_internal_test_package.TestInvalid, "short_test.go", 209);
        registry.Add("TestIssue42951", parser_internal_test_package.TestIssue42951, "parser_test.go", 84);
        registry.Add("TestIssue57490", parser_internal_test_package.TestIssue57490, "parser_test.go", 805);
        registry.Add("TestIssue59180", parser_internal_test_package.TestIssue59180, "parser_test.go", 770);
        registry.Add("TestIssue9979", parser_internal_test_package.TestIssue9979, "parser_test.go", 445);
        registry.Add("TestLastLineComment", parser_internal_test_package.TestLastLineComment, "parser_test.go", 558);
        registry.Add("TestLeadAndLineComments", parser_internal_test_package.TestLeadAndLineComments, "parser_test.go", 406);
        registry.Add("TestObjects", parser_internal_test_package.TestObjects, "parser_test.go", 204);
        registry.Add("TestParse", parser_internal_test_package.TestParse, "parser_test.go", 23);
        registry.Add("TestParseDepthLimit", parser_internal_test_package.TestParseDepthLimit, "parser_test.go", 647);
        registry.Add("TestParseDir", parser_internal_test_package.TestParseDir, "parser_test.go", 60);
        registry.Add("TestParseExpr", parser_internal_test_package.TestParseExpr, "parser_test.go", 92);
        registry.Add("TestParseExprFrom", parser_internal_test_package.TestParseExprFrom, "parser_test.go", 52);
        registry.Add("TestParseFile", parser_internal_test_package.TestParseFile, "parser_test.go", 44);
        registry.Add("TestRangePos", parser_internal_test_package.TestRangePos, "parser_test.go", 740);
        registry.Add("TestResolution", parser_internal_test_package.TestResolution, "resolver_test.go", 30);
        registry.Add("TestScopeDepthLimit", parser_internal_test_package.TestScopeDepthLimit, "parser_test.go", 693);
        registry.Add("TestSingle", parser_internal_test_package.TestSingle, "short_test.go", 126);
        registry.Add("TestUnresolved", parser_internal_test_package.TestUnresolved, "parser_test.go", 251);
        registry.Add("TestValid", parser_internal_test_package.TestValid, "short_test.go", 119);
        registry.Add("TestVarScope", parser_internal_test_package.TestVarScope, "parser_test.go", 183);
        return TestHost.Run(registry, args);
    }
}
