// Code generated by go tool dist; DO NOT EDIT.
namespace go.@internal;

using Δruntime = runtime_package;

partial class buildcfg_package {

public static readonly @string DefaultGO386 = @"sse2"u8;

public static readonly @string DefaultGOAMD64 = @"v1"u8;

public static readonly @string DefaultGOARM = @"7"u8;

public static readonly @string DefaultGOARM64 = @"v8.0"u8;

public static readonly @string DefaultGOMIPS = @"hardfloat"u8;

public static readonly @string DefaultGOMIPS64 = @"hardfloat"u8;

public static readonly @string DefaultGOPPC64 = @"power8"u8;

public static readonly @string DefaultGORISCV64 = @"rva20u64"u8;

internal static readonly @string defaultGOEXPERIMENT = @""u8;

internal static readonly @string defaultGO_EXTLINK_ENABLED = @""u8;

internal static readonly @string defaultGO_LDSO = @""u8;

internal static readonly @string version = @"go1.24.13"u8;

internal static readonly @string defaultGOOS = "darwin";

internal static readonly @string defaultGOARCH = "amd64";

public static readonly @string DefaultGOFIPS140 = @"off"u8;

} // end buildcfg_package
