// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.mime;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("mime/quotedprintable", new string[]
        {
            "example_test.go",
            "reader.go",
            "reader_test.go",
            "writer.go",
            "writer_test.go",
        });
        registry.Add("TestExhaustive", quotedprintable_internal_test_package.TestExhaustive, "reader_test.go", 108);
        registry.Add("TestReader", quotedprintable_internal_test_package.TestReader, "reader_test.go", 21);
        registry.Add("TestRoundTrip", quotedprintable_internal_test_package.TestRoundTrip, "writer_test.go", 120);
        registry.Add("TestWriter", quotedprintable_internal_test_package.TestWriter, "writer_test.go", 14);
        registry.Add("TestWriterBinary", quotedprintable_internal_test_package.TestWriterBinary, "writer_test.go", 18);
        return TestHost.Run(registry, args);
    }
}
