// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.html;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("html/template", new string[]
        {
            "attr.go",
            "attr_string.go",
            "clone_test.go",
            "content.go",
            "content_test.go",
            "context.go",
            "css.go",
            "css_test.go",
            "delim_string.go",
            "doc.go",
            "element_string.go",
            "error.go",
            "escape.go",
            "escape_test.go",
            "example_test.go",
            "examplefiles_test.go",
            "exec_test.go",
            "html.go",
            "html_test.go",
            "js.go",
            "js_test.go",
            "jsctx_string.go",
            "multi_test.go",
            "state_string.go",
            "template.go",
            "template_test.go",
            "testdata/file1.tmpl",
            "testdata/file2.tmpl",
            "testdata/fs.zip",
            "testdata/tmpl1.tmpl",
            "testdata/tmpl2.tmpl",
            "transition.go",
            "transition_test.go",
            "url.go",
            "url_test.go",
            "urlpart_string.go",
        }, new string[]
        {
            "testdata",
        });
        registry.Add("TestAddParseTreeHTML", template_internal_test_package.TestAddParseTreeHTML, "clone_test.go", 17);
        registry.Add("TestAddParseTreeToUnparsedTemplate", template_internal_test_package.TestAddParseTreeToUnparsedTemplate, "multi_test.go", 158);
        registry.Add("TestAddrOfIndex", template_internal_test_package.TestAddrOfIndex, "exec_test.go", 1523);
        registry.Add("TestAliasedParseTreeDoesNotOverescape", template_internal_test_package.TestAliasedParseTreeDoesNotOverescape, "escape_test.go", 2171);
        registry.Add("TestBadFuncNames", template_internal_test_package.TestBadFuncNames, "exec_test.go", 1387);
        registry.Add("TestBlock", template_internal_test_package.TestBlock, "exec_test.go", 1413);
        registry.Add("TestCSSEscaper", template_internal_test_package.TestCSSEscaper, "css_test.go", 151);
        registry.Add("TestCSSValueFilter", template_internal_test_package.TestCSSValueFilter, "css_test.go", 185);
        registry.Add("TestClone", template_internal_test_package.TestClone, "clone_test.go", 34);
        registry.Add("TestCloneCrash", template_internal_test_package.TestCloneCrash, "clone_test.go", 156);
        registry.Add("TestCloneGrowth", template_internal_test_package.TestCloneGrowth, "clone_test.go", 234);
        registry.Add("TestClonePipe", template_internal_test_package.TestClonePipe, "clone_test.go", 267);
        registry.Add("TestCloneRedefinedName", template_internal_test_package.TestCloneRedefinedName, "clone_test.go", 247);
        registry.Add("TestCloneThenParse", template_internal_test_package.TestCloneThenParse, "clone_test.go", 165);
        registry.Add("TestComparison", template_internal_test_package.TestComparison, "exec_test.go", 1211);
        registry.Add("TestDecodeCSS", template_internal_test_package.TestDecodeCSS, "css_test.go", 70);
        registry.Add("TestDelims", template_internal_test_package.TestDelims, "exec_test.go", 836);
        registry.Add("TestEmptyTemplate", template_internal_test_package.TestEmptyTemplate, "multi_test.go", 221);
        registry.Add("TestEmptyTemplateCloneCrash", template_internal_test_package.TestEmptyTemplateCloneCrash, "multi_test.go", 184);
        registry.Add("TestEmptyTemplateHTML", template_internal_test_package.TestEmptyTemplateHTML, "escape_test.go", 2051);
        registry.Add("TestEndsWithCSSKeyword", template_internal_test_package.TestEndsWithCSSKeyword, "css_test.go", 13);
        registry.Add("TestEnsurePipelineContains", template_internal_test_package.TestEnsurePipelineContains, "escape_test.go", 1835);
        registry.Add("TestErrorOnUndefined", template_internal_test_package.TestErrorOnUndefined, "escape_test.go", 2093);
        registry.Add("TestErrors", template_internal_test_package.TestErrors, "escape_test.go", 945);
        registry.Add("TestEscape", template_internal_test_package.TestEscape, "escape_test.go", 31);
        registry.Add("TestEscapeErrorsNotIgnorable", template_internal_test_package.TestEscapeErrorsNotIgnorable, "escape_test.go", 1968);
        registry.Add("TestEscapeMalformedPipelines", template_internal_test_package.TestEscapeMalformedPipelines, "escape_test.go", 1948);
        registry.Add("TestEscapeMap", template_internal_test_package.TestEscapeMap, "escape_test.go", 768);
        registry.Add("TestEscapeRace", template_internal_test_package.TestEscapeRace, "exec_test.go", 1732);
        registry.Add("TestEscapeSet", template_internal_test_package.TestEscapeSet, "escape_test.go", 802);
        registry.Add("TestEscapeSetErrorsNotIgnorable", template_internal_test_package.TestEscapeSetErrorsNotIgnorable, "escape_test.go", 1979);
        registry.Add("TestEscapeText", template_internal_test_package.TestEscapeText, "escape_test.go", 1197);
        registry.Add("TestEscapersOnLower7AndSelectHighCodepoints", template_internal_test_package.TestEscapersOnLower7AndSelectHighCodepoints, "js_test.go", 282);
        registry.Add("TestEscapingNilNonemptyInterfaces", template_internal_test_package.TestEscapingNilNonemptyInterfaces, "content_test.go", 443);
        registry.Add("TestEvalFieldErrors", template_internal_test_package.TestEvalFieldErrors, "exec_test.go", 1446);
        registry.Add("TestExecError", template_internal_test_package.TestExecError, "exec_test.go", 900);
        registry.Add("TestExecute", template_internal_test_package.TestExecute, "exec_test.go", 825);
        registry.Add("TestExecuteError", template_internal_test_package.TestExecuteError, "exec_test.go", 873);
        registry.Add("TestExecuteGivesExecError", template_internal_test_package.TestExecuteGivesExecError, "exec_test.go", 1331);
        registry.Add("TestExecuteOnNewTemplate", template_internal_test_package.TestExecuteOnNewTemplate, "exec_test.go", 1025);
        registry.Add("TestExecutePanicDuringCall", template_internal_test_package.TestExecutePanicDuringCall, "exec_test.go", 1620);
        registry.Add("TestFinalForPrintf", template_internal_test_package.TestFinalForPrintf, "exec_test.go", 1074);
        registry.Add("TestFindEndTag", template_internal_test_package.TestFindEndTag, "transition_test.go", 13);
        registry.Add("TestFuncMapWorksAfterClone", template_internal_test_package.TestFuncMapWorksAfterClone, "clone_test.go", 180);
        registry.Add("TestGoodFuncNames", template_internal_test_package.TestGoodFuncNames, "exec_test.go", 1367);
        registry.Add("TestHTMLNospaceEscaper", template_internal_test_package.TestHTMLNospaceEscaper, "html_test.go", 13);
        registry.Add("TestHexDecode", template_internal_test_package.TestHexDecode, "css_test.go", 114);
        registry.Add("TestIdempotentExecute", template_internal_test_package.TestIdempotentExecute, "escape_test.go", 2105);
        registry.Add("TestIndirectPrint", template_internal_test_package.TestIndirectPrint, "escape_test.go", 2027);
        registry.Add("TestInterfaceValues", template_internal_test_package.TestInterfaceValues, "exec_test.go", 1546);
        registry.Add("TestIsCSSNmchar", template_internal_test_package.TestIsCSSNmchar, "css_test.go", 36);
        registry.Add("TestIsJsMimeType", template_internal_test_package.TestIsJsMimeType, "js_test.go", 350);
        registry.Add("TestIssue19294", template_internal_test_package.TestIssue19294, "multi_test.go", 262);
        registry.Add("TestIssue31810", template_internal_test_package.TestIssue31810, "exec_test.go", 1682);
        registry.Add("TestJSEscaping", template_internal_test_package.TestJSEscaping, "exec_test.go", 917);
        registry.Add("TestJSRegexpEscaper", template_internal_test_package.TestJSRegexpEscaper, "js_test.go", 238);
        registry.Add("TestJSStrEscaper", template_internal_test_package.TestJSStrEscaper, "js_test.go", 183);
        registry.Add("TestJSValEscaper", template_internal_test_package.TestJSValEscaper, "js_test.go", 113);
        registry.Add("TestMaxExecDepth", template_internal_test_package.TestMaxExecDepth, "exec_test.go", 1507);
        registry.Add("TestMessageForExecuteEmpty", template_internal_test_package.TestMessageForExecuteEmpty, "exec_test.go", 1038);
        registry.Add("TestMissingMapKey", template_internal_test_package.TestMissingMapKey, "exec_test.go", 1252);
        registry.Add("TestMultiExecute", template_internal_test_package.TestMultiExecute, "multi_test.go", 44);
        registry.Add("TestNextJsCtx", template_internal_test_package.TestNextJsCtx, "js_test.go", 14);
        registry.Add("TestNumbers", template_test_package.TestNumbers, "template_test.go", 120);
        registry.Add("TestOrphanedTemplate", template_internal_test_package.TestOrphanedTemplate, "escape_test.go", 2149);
        registry.Add("TestParse", template_internal_test_package.TestParse, "multi_test.go", 206);
        registry.Add("TestParseFS", template_internal_test_package.TestParseFS, "multi_test.go", 87);
        registry.Add("TestParseFiles", template_internal_test_package.TestParseFiles, "multi_test.go", 57);
        registry.Add("TestParseFilesWithData", template_internal_test_package.TestParseFilesWithData, "multi_test.go", 122);
        registry.Add("TestParseGlob", template_internal_test_package.TestParseGlob, "multi_test.go", 70);
        registry.Add("TestParseGlobWithData", template_internal_test_package.TestParseGlobWithData, "multi_test.go", 130);
        registry.Add("TestParseZipFS", template_internal_test_package.TestParseZipFS, "multi_test.go", 138);
        registry.Add("TestPipeToMethodIsEscaped", template_internal_test_package.TestPipeToMethodIsEscaped, "escape_test.go", 2068);
        registry.Add("TestRecursiveExecute", template_internal_test_package.TestRecursiveExecute, "exec_test.go", 1762);
        registry.Add("TestRecursiveExecuteViaMethod", template_internal_test_package.TestRecursiveExecuteViaMethod, "exec_test.go", 1804);
        registry.Add("TestRedefineAfterNamedExecution", template_test_package.TestRedefineAfterNamedExecution, "template_test.go", 62);
        registry.Add("TestRedefineAfterNonExecution", template_test_package.TestRedefineAfterNonExecution, "template_test.go", 54);
        registry.Add("TestRedefineEmptyAfterExecution", template_test_package.TestRedefineEmptyAfterExecution, "template_test.go", 46);
        registry.Add("TestRedefineNestedByNameAfterExecution", template_test_package.TestRedefineNestedByNameAfterExecution, "template_test.go", 70);
        registry.Add("TestRedefineNestedByTemplateAfterExecution", template_test_package.TestRedefineNestedByTemplateAfterExecution, "template_test.go", 78);
        registry.Add("TestRedefineNonEmptyAfterExecution", template_test_package.TestRedefineNonEmptyAfterExecution, "template_test.go", 39);
        registry.Add("TestRedefineOtherParsers", template_test_package.TestRedefineOtherParsers, "template_test.go", 105);
        registry.Add("TestRedefineSafety", template_test_package.TestRedefineSafety, "template_test.go", 86);
        registry.Add("TestRedefineTopUse", template_test_package.TestRedefineTopUse, "template_test.go", 97);
        registry.Add("TestRedefinition", template_internal_test_package.TestRedefinition, "multi_test.go", 169);
        registry.Add("TestRedundantFuncs", template_internal_test_package.TestRedundantFuncs, "escape_test.go", 1993);
        registry.Add("TestSkipCSSSpace", template_internal_test_package.TestSkipCSSSpace, "css_test.go", 127);
        registry.Add("TestSkipEscapeComments", template_test_package.TestSkipEscapeComments, "template_test.go", 164);
        registry.Add("TestSrcsetFilter", template_internal_test_package.TestSrcsetFilter, "url_test.go", 90);
        registry.Add("TestStringer", template_internal_test_package.TestStringer, "content_test.go", 420);
        registry.Add("TestStringsInScriptsWithJsonContentTypeAreCorrectlyEscaped", template_test_package.TestStringsInScriptsWithJsonContentTypeAreCorrectlyEscaped, "template_test.go", 126);
        registry.Add("TestStripTags", template_internal_test_package.TestStripTags, "html_test.go", 50);
        registry.Add("TestTemplateClone", template_test_package.TestTemplateClone, "template_test.go", 16);
        registry.Add("TestTemplateCloneExecuteRace", template_internal_test_package.TestTemplateCloneExecuteRace, "clone_test.go", 201);
        registry.Add("TestTemplateCloneLookup", template_internal_test_package.TestTemplateCloneLookup, "clone_test.go", 224);
        registry.Add("TestTemplateFuncsAfterClone", template_internal_test_package.TestTemplateFuncsAfterClone, "exec_test.go", 1824);
        registry.Add("TestTemplateLookUp", template_internal_test_package.TestTemplateLookUp, "multi_test.go", 190);
        registry.Add("TestTemplates", template_internal_test_package.TestTemplates, "clone_test.go", 129);
        registry.Add("TestTree", template_internal_test_package.TestTree, "exec_test.go", 961);
        registry.Add("TestTypedContent", template_internal_test_package.TestTypedContent, "content_test.go", 14);
        registry.Add("TestURLFilters", template_internal_test_package.TestURLFilters, "url_test.go", 38);
        registry.Add("TestURLNormalizer", template_internal_test_package.TestURLNormalizer, "url_test.go", 11);
        registry.Add("TestUnterminatedStringError", template_internal_test_package.TestUnterminatedStringError, "exec_test.go", 1310);
        return TestHost.Run(registry, args);
    }
}
