// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/hmac", new string[]
        {
            "hmac.go",
            "hmac_test.go",
        });
        registry.Add("TestEqual", hmac_package.TestEqual, "hmac_test.go", 605);
        registry.Add("TestHMAC", hmac_package.TestHMAC, "hmac_test.go", 550);
        registry.Add("TestHMACHash", hmac_package.TestHMACHash, "hmac_test.go", 624);
        registry.Add("TestNonUniqueHash", hmac_package.TestNonUniqueHash, "hmac_test.go", 586);
        return TestHost.Run(registry, args);
    }
}
