// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal.trace.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/trace/internal/oldtrace", new string[]
        {
            "order.go",
            "parser.go",
            "parser_test.go",
            "testdata/fmt_1_21_pprof_good",
            "testdata/http_1_19_good",
            "testdata/http_1_21_good",
            "testdata/stress_1_11_good",
            "testdata/stress_1_19_good",
            "testdata/stress_1_21_good",
            "testdata/stress_start_stop_1_11_good",
            "testdata/stress_start_stop_1_19_good",
            "testdata/stress_start_stop_1_21_good",
            "testdata/user_task_region_1_11_good",
            "testdata/user_task_region_1_19_good",
            "testdata/user_task_region_1_21_good",
        }, new string[]
        {
            "testdata",
        });
        registry.Add("TestBuckets", oldtrace_internal_test_package.TestBuckets, "parser_test.go", 89);
        registry.Add("TestCorruptedInputs", oldtrace_internal_test_package.TestCorruptedInputs, "parser_test.go", 16);
        registry.Add("TestParseCanned", oldtrace_internal_test_package.TestParseCanned, "parser_test.go", 36);
        return TestHost.Run(registry, args);
    }
}
