// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.net;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("net/textproto", new string[]
        {
            "header.go",
            "header_test.go",
            "pipeline.go",
            "reader.go",
            "reader_test.go",
            "textproto.go",
            "writer.go",
            "writer_test.go",
        });
        registry.Add("TestCanonicalMIMEHeaderKey", textproto_internal_test_package.TestCanonicalMIMEHeaderKey, "header_test.go", 36);
        registry.Add("TestCommonHeaders", textproto_internal_test_package.TestCommonHeaders, "reader_test.go", 429);
        registry.Add("TestDotWriter", textproto_internal_test_package.TestDotWriter, "writer_test.go", 22);
        registry.Add("TestDotWriterCloseEmptyWrite", textproto_internal_test_package.TestDotWriterCloseEmptyWrite, "writer_test.go", 37);
        registry.Add("TestDotWriterCloseNoWrite", textproto_internal_test_package.TestDotWriterCloseNoWrite, "writer_test.go", 52);
        registry.Add("TestIssue46363", textproto_internal_test_package.TestIssue46363, "reader_test.go", 448);
        registry.Add("TestLargeReadMIMEHeader", textproto_internal_test_package.TestLargeReadMIMEHeader, "reader_test.go", 191);
        registry.Add("TestMIMEHeaderMultipleValues", textproto_internal_test_package.TestMIMEHeaderMultipleValues, "header_test.go", 45);
        registry.Add("TestPrintfLine", textproto_internal_test_package.TestPrintfLine, "writer_test.go", 13);
        registry.Add("TestRFC959Lines", textproto_internal_test_package.TestRFC959Lines, "reader_test.go", 383);
        registry.Add("TestReadCodeLine", textproto_internal_test_package.TestReadCodeLine, "reader_test.go", 72);
        registry.Add("TestReadContinuedLine", textproto_internal_test_package.TestReadContinuedLine, "reader_test.go", 52);
        registry.Add("TestReadDotBytes", textproto_internal_test_package.TestReadDotBytes, "reader_test.go", 110);
        registry.Add("TestReadDotLines", textproto_internal_test_package.TestReadDotLines, "reader_test.go", 95);
        registry.Add("TestReadLine", textproto_internal_test_package.TestReadLine, "reader_test.go", 24);
        registry.Add("TestReadLineLongLine", textproto_internal_test_package.TestReadLineLongLine, "reader_test.go", 40);
        registry.Add("TestReadMIMEHeader", textproto_internal_test_package.TestReadMIMEHeader, "reader_test.go", 125);
        registry.Add("TestReadMIMEHeaderAllocations", textproto_internal_test_package.TestReadMIMEHeaderAllocations, "reader_test.go", 326);
        registry.Add("TestReadMIMEHeaderBytes", textproto_internal_test_package.TestReadMIMEHeaderBytes, "reader_test.go", 253);
        registry.Add("TestReadMIMEHeaderMalformed", textproto_internal_test_package.TestReadMIMEHeaderMalformed, "reader_test.go", 230);
        registry.Add("TestReadMIMEHeaderNoKey", textproto_internal_test_package.TestReadMIMEHeaderNoKey, "reader_test.go", 182);
        registry.Add("TestReadMIMEHeaderNonCompliant", textproto_internal_test_package.TestReadMIMEHeaderNonCompliant, "reader_test.go", 210);
        registry.Add("TestReadMIMEHeaderSingle", textproto_internal_test_package.TestReadMIMEHeaderSingle, "reader_test.go", 137);
        registry.Add("TestReadMIMEHeaderTrimContinued", textproto_internal_test_package.TestReadMIMEHeaderTrimContinued, "reader_test.go", 300);
        registry.Add("TestReadMultiLineError", textproto_internal_test_package.TestReadMultiLineError, "reader_test.go", 401);
        registry.Add("TestReaderUpcomingHeaderKeys", textproto_internal_test_package.TestReaderUpcomingHeaderKeys, "reader_test.go", 148);
        return TestHost.Run(registry, args);
    }
}
