// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.encoding;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("encoding/base32", new string[]
        {
            "base32.go",
            "base32_test.go",
            "example_test.go",
        });
        registry.Add("TestBig", base32_package.TestBig, "base32_test.go", 396);
        registry.Add("TestBufferedDecodingPadding", base32_package.TestBufferedDecodingPadding, "base32_test.go", 680);
        registry.Add("TestBufferedDecodingSameError", base32_package.TestBufferedDecodingSameError, "base32_test.go", 600);
        registry.Add("TestDecode", base32_package.TestDecode, "base32_test.go", 132);
        registry.Add("TestDecodeCorrupt", base32_package.TestDecodeCorrupt, "base32_test.go", 349);
        registry.Add("TestDecodeReadAll", base32_package.TestDecodeReadAll, "base32_test.go", 843);
        registry.Add("TestDecodeSmallBuffer", base32_package.TestDecodeSmallBuffer, "base32_test.go", 868);
        registry.Add("TestDecodeWithPadding", base32_package.TestDecodeWithPadding, "base32_test.go", 561);
        registry.Add("TestDecodeWithWrongPadding", base32_package.TestDecodeWithWrongPadding, "base32_test.go", 586);
        registry.Add("TestDecodedLen", base32_package.TestDecodedLen, "base32_test.go", 776);
        registry.Add("TestDecoder", base32_package.TestDecoder, "base32_test.go", 160);
        registry.Add("TestDecoderBuffering", base32_package.TestDecoderBuffering, "base32_test.go", 331);
        registry.Add("TestDecoderBufferingWithPadding", base32_package.TestDecoderBufferingWithPadding, "base32_test.go", 95);
        registry.Add("TestDecoderBufferingWithoutPadding", base32_package.TestDecoderBufferingWithoutPadding, "base32_test.go", 113);
        registry.Add("TestDecoderError", base32_package.TestDecoderError, "base32_test.go", 298);
        registry.Add("TestDecoderIssue4779", base32_package.TestDecoderIssue4779, "base32_test.go", 465);
        registry.Add("TestEncode", base32_package.TestEncode, "base32_test.go", 56);
        registry.Add("TestEncodedLen", base32_package.TestEncodedLen, "base32_test.go", 732);
        registry.Add("TestEncoder", base32_package.TestEncoder, "base32_test.go", 65);
        registry.Add("TestEncoderBuffering", base32_package.TestEncoderBuffering, "base32_test.go", 75);
        registry.Add("TestIssue20044", base32_package.TestIssue20044, "base32_test.go", 213);
        registry.Add("TestNewLineCharacters", base32_package.TestNewLineCharacters, "base32_test.go", 442);
        registry.Add("TestReaderEOF", base32_package.TestReaderEOF, "base32_test.go", 314);
        registry.Add("TestWithCustomPadding", base32_package.TestWithCustomPadding, "base32_test.go", 531);
        registry.Add("TestWithoutPadding", base32_package.TestWithoutPadding, "base32_test.go", 546);
        registry.Add("TestWithoutPaddingClose", base32_package.TestWithoutPaddingClose, "base32_test.go", 815);
        return TestHost.Run(registry, args);
    }
}
