// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.runtime;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("runtime/debug", new string[]
        {
            "example_monitor_test.go",
            "garbage.go",
            "garbage_test.go",
            "heapdump_test.go",
            "mod.go",
            "mod_test.go",
            "panic_test.go",
            "stack.go",
            "stack_test.go",
            "stubs.go",
            "testdata/fuzz/FuzzParseBuildInfoRoundTrip/5501685e611fa764",
            "testdata/fuzz/FuzzParseBuildInfoRoundTrip/71634114e78567cf",
            "testdata/fuzz/FuzzParseBuildInfoRoundTrip/c73dce23c1f2494c",
        }, new string[]
        {
            "testdata",
        });
        registry.Add("TestFreeOSMemory", debug_test_package.TestFreeOSMemory, "garbage_test.go", 93);
        registry.Add("TestReadGCStats", debug_test_package.TestReadGCStats, "garbage_test.go", 16);
        registry.Add("TestSetCrashOutput", debug_test_package.TestSetCrashOutput, "stack_test.go", 139);
        registry.Add("TestSetGCPercent", debug_test_package.TestSetGCPercent, "garbage_test.go", 158);
        registry.Add("TestSetMaxThreadsOvf", debug_test_package.TestSetMaxThreadsOvf, "garbage_test.go", 227);
        registry.Add("TestStack", debug_test_package.TestStack, "stack_test.go", 71);
        registry.Add("TestWriteHeapDumpFinalizers", debug_test_package.TestWriteHeapDumpFinalizers, "heapdump_test.go", 43);
        registry.Add("TestWriteHeapDumpNonempty", debug_test_package.TestWriteHeapDumpNonempty, "heapdump_test.go", 14);
        registry.Add("TestWriteHeapDumpTypeName", debug_test_package.TestWriteHeapDumpTypeName, "heapdump_test.go", 82);
        registry.SetTestMain(debug_test_package.TestMain);
        return TestHost.Run(registry, args);
    }
}
