// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("slices", new string[]
        {
            "example_test.go",
            "iter.go",
            "iter_test.go",
            "slices.go",
            "slices_test.go",
            "sort.go",
            "sort_benchmark_test.go",
            "sort_test.go",
            "zsortanyfunc.go",
            "zsortordered.go",
        });
        registry.Add("TestAll", slices_test_package.TestAll, "iter_test.go", 14);
        registry.Add("TestAppendSeq", slices_test_package.TestAppendSeq, "iter_test.go", 89);
        registry.Add("TestBackward", slices_test_package.TestBackward, "iter_test.go", 36);
        registry.Add("TestBinarySearch", slices_test_package.TestBinarySearch, "sort_test.go", 284);
        registry.Add("TestBinarySearchFloats", slices_test_package.TestBinarySearchFloats, "sort_test.go", 396);
        registry.Add("TestBinarySearchFunc", slices_test_package.TestBinarySearchFunc, "sort_test.go", 422);
        registry.Add("TestBinarySearchInts", slices_test_package.TestBinarySearchInts, "sort_test.go", 362);
        registry.Add("TestChunk", slices_test_package.TestChunk, "iter_test.go", 186);
        registry.Add("TestChunkPanics", slices_test_package.TestChunkPanics, "iter_test.go", 257);
        registry.Add("TestChunkRange", slices_test_package.TestChunkRange, "iter_test.go", 275);
        registry.Add("TestClip", slices_test_package.TestClip, "slices_test.go", 972);
        registry.Add("TestClone", slices_test_package.TestClone, "slices_test.go", 726);
        registry.Add("TestCollect", slices_test_package.TestCollect, "iter_test.go", 97);
        registry.Add("TestCompact", slices_test_package.TestCompact, "slices_test.go", 782);
        registry.Add("TestCompactClearTail", slices_test_package.TestCompactClearTail, "slices_test.go", 843);
        registry.Add("TestCompactFunc", slices_test_package.TestCompactFunc, "slices_test.go", 827);
        registry.Add("TestCompactFuncClearTail", slices_test_package.TestCompactFuncClearTail, "slices_test.go", 864);
        registry.Add("TestCompare", slices_test_package.TestCompare, "slices_test.go", 251);
        registry.Add("TestCompareFunc", slices_test_package.TestCompareFunc, "slices_test.go", 290);
        registry.Add("TestConcat", slices_test_package.TestConcat, "slices_test.go", 1282);
        registry.Add("TestConcat_too_large", slices_test_package.TestConcat_too_large, "slices_test.go", 1324);
        registry.Add("TestContains", slices_test_package.TestContains, "slices_test.go", 428);
        registry.Add("TestContainsFunc", slices_test_package.TestContainsFunc, "slices_test.go", 436);
        registry.Add("TestDelete", slices_test_package.TestDelete, "slices_test.go", 603);
        registry.Add("TestDeleteClearTail", slices_test_package.TestDeleteClearTail, "slices_test.go", 693);
        registry.Add("TestDeleteFunc", slices_test_package.TestDeleteFunc, "slices_test.go", 649);
        registry.Add("TestDeleteFuncClearTail", slices_test_package.TestDeleteFuncClearTail, "slices_test.go", 708);
        registry.Add("TestDeletePanics", slices_test_package.TestDeletePanics, "slices_test.go", 668);
        registry.Add("TestEqual", slices_test_package.TestEqual, "slices_test.go", 62);
        registry.Add("TestEqualFunc", slices_test_package.TestEqualFunc, "slices_test.go", 91);
        registry.Add("TestGrow", slices_test_package.TestGrow, "slices_test.go", 926);
        registry.Add("TestIndex", slices_test_package.TestIndex, "slices_test.go", 378);
        registry.Add("TestIndexFunc", slices_test_package.TestIndexFunc, "slices_test.go", 401);
        registry.Add("TestInference", slices_test_package.TestInference, "slices_test.go", 1267);
        registry.Add("TestInsert", slices_test_package.TestInsert, "slices_test.go", 487);
        registry.Add("TestInsertGrowthRate", slices_test_package.TestInsertGrowthRate, "slices_test.go", 1226);
        registry.Add("TestInsertOverlap", slices_test_package.TestInsertOverlap, "slices_test.go", 514);
        registry.Add("TestInsertPanics", slices_test_package.TestInsertPanics, "slices_test.go", 539);
        registry.Add("TestMinMax", slices_test_package.TestMinMax, "sort_test.go", 174);
        registry.Add("TestMinMaxNaNs", slices_test_package.TestMinMaxNaNs, "sort_test.go", 236);
        registry.Add("TestMinMaxPanics", slices_test_package.TestMinMaxPanics, "sort_test.go", 263);
        registry.Add("TestRepeat", slices_test_package.TestRepeat, "slices_test.go", 1380);
        registry.Add("TestRepeatPanics", slices_test_package.TestRepeatPanics, "slices_test.go", 1438);
        registry.Add("TestReplace", slices_test_package.TestReplace, "slices_test.go", 1025);
        registry.Add("TestReplaceClearTail", slices_test_package.TestReplaceClearTail, "slices_test.go", 1115);
        registry.Add("TestReplaceEndClearTail", slices_test_package.TestReplaceEndClearTail, "slices_test.go", 1164);
        registry.Add("TestReplaceGrow", slices_test_package.TestReplaceGrow, "slices_test.go", 1087);
        registry.Add("TestReplaceGrowthRate", slices_test_package.TestReplaceGrowthRate, "slices_test.go", 1244);
        registry.Add("TestReplaceOverlap", slices_test_package.TestReplaceOverlap, "slices_test.go", 1137);
        registry.Add("TestReplacePanics", slices_test_package.TestReplacePanics, "slices_test.go", 1065);
        registry.Add("TestReverse", slices_test_package.TestReverse, "slices_test.go", 990);
        registry.Add("TestSortFloat64Slice", slices_test_package.TestSortFloat64Slice, "sort_test.go", 40);
        registry.Add("TestSortFuncIntSlice", slices_test_package.TestSortFuncIntSlice, "sort_test.go", 31);
        registry.Add("TestSortIntSlice", slices_test_package.TestSortIntSlice, "sort_test.go", 22);
        registry.Add("TestSortLarge_Random", slices_test_package.TestSortLarge_Random, "sort_test.go", 58);
        registry.Add("TestSortStringSlice", slices_test_package.TestSortStringSlice, "sort_test.go", 49);
        registry.Add("TestSorted", slices_test_package.TestSorted, "iter_test.go", 134);
        registry.Add("TestSortedFunc", slices_test_package.TestSortedFunc, "iter_test.go", 142);
        registry.Add("TestSortedStableFunc", slices_test_package.TestSortedStableFunc, "iter_test.go", 150);
        registry.Add("TestStability", slices_test_package.TestStability, "sort_test.go", 118);
        registry.Add("TestValues", slices_test_package.TestValues, "iter_test.go", 58);
        registry.Add("TestValuesAppendSeq", slices_test_package.TestValuesAppendSeq, "iter_test.go", 113);
        registry.Add("TestValuesCollect", slices_test_package.TestValuesCollect, "iter_test.go", 125);
        return TestHost.Run(registry, args);
    }
}
