// go2cs metadata anchor for the INTERNAL (white-box bridge) test class: GoImplement /
// GoImplicitConv attributes whose GENERATED code must merge with a bridge-declared type
// anchor here — the source generators host output in the first class of the
// attribute-bearing file, and only this file's first class is the bridge. Records for
// production and external-test types stay in package_test_info.cs.

// <ImportedTypeAliases>
using testing = go.testing_package;
// </ImportedTypeAliases>

using go;
using static go.crypto.tls_package;
using static go.crypto.tls_internal_test_package;

// <ExportedTypeAliases>
// </ExportedTypeAliases>

// <InterfaceImplementations>
[assembly: GoImplement<brokenConn, net_package.Conn>(Pointer = true)]
[assembly: GoImplement<brokenConn, net_package.Conn>(Promoted = true)]
[assembly: GoImplement<brokenSigner, crypto_package.Signer>(Promoted = true)]
[assembly: GoImplement<changeImplConn, net_package.Conn>(Pointer = true)]
[assembly: GoImplement<changeImplConn, net_package.Conn>(Promoted = true)]
[assembly: GoImplement<discardConn, net_package.Conn>(Pointer = true)]
[assembly: GoImplement<discardConn, net_package.Conn>(Promoted = true)]
[assembly: GoImplement<go.crypto.tls_internal_test_package.zeroSource, io_package.Reader>]
[assembly: GoImplement<hairpinConn, net_package.Conn>(Pointer = true)]
[assembly: GoImplement<hairpinConn, net_package.Conn>(Promoted = true)]
[assembly: GoImplement<opensslInput, io_package.Reader>]
[assembly: GoImplement<opensslOutputSink, io_package.Writer>(Pointer = true)]
[assembly: GoImplement<readerFunc, io_package.Reader>]
[assembly: GoImplement<recordingConn, net_package.Conn>(Pointer = true)]
[assembly: GoImplement<recordingConn, net_package.Conn>(Promoted = true)]
[assembly: GoImplement<replayingConn, net_package.Conn>(Pointer = true)]
[assembly: GoImplement<serializingClientCache, global::go.crypto.tls_package.ClientSessionCache>(Pointer = true)]
[assembly: GoImplement<slowConn, net_package.Conn>(Pointer = true)]
[assembly: GoImplement<slowConn, net_package.Conn>(Promoted = true)]
[assembly: GoImplement<stringSlice, flag_package.Value>(Pointer = true)]
[assembly: GoImplement<writeCountingConn, net_package.Conn>(Pointer = true)]
[assembly: GoImplement<writeCountingConn, net_package.Conn>(Promoted = true)]
// </InterfaceImplementations>

// <ImplicitConversions>
[assembly: GoImplicitConv<clientTest, ж<clientTest>>(Indirect = true)]
[assembly: GoImplicitConv<serverTest, ж<serverTest>>(Indirect = true)]
[assembly: GoImplicitConv<testQUICConn, ж<testQUICConn>>]
// </ImplicitConversions>

// Go source positions are recorded here, one `GoPositionMap` attribute per converted
// source file in this compilation, so that `runtime.Caller` and the tracebacks built on it
// can name the GO file and line a frame was converted from rather than the emitted C# one.
// Each record carries the Go file's identity and an encoded C#-line to Go-line table
// TOGETHER: a frame either has a record and reports a position that exists in the Go tree,
// or has none - golib, the BCL and hand-written conversions - and reports its own C# position.

// <GoSourcePositionMaps>
[assembly: go.GoPositionMap("crypto/tls/auth_test.go", "auth_test.cs", "ABsYgrjKuLoAEDiCgoKUgpSCgpSClIKozAAYPIKCgsqCgoKUgIKkgIKmgoKUgIKkgIK4goK8ooKCgpSClII=")]
[assembly: go.GoPositionMap("crypto/tls/bogo_shim_test.go", "bogo_shim_test.cs", "AFK6AYKCgqaCpoKCAA0GooKClgAFEoKCgoKCgoLagoKCgoKCzIKCgoKCqIKWgpaCloKCgpSUgoKCgpSCgoKUgpaClIKWgoKClIKWgoKCgpSogoKCgpSWgoKUpoKCgIKmgoKUloKAgriCgoKCgpSCgpSAgraCgoKUgpSCgoKUgqaWgoKClIKUgpSCpKSkloKWgpaCloKogoKClIIAFgyigoKChIKUgt6AgqaCgpSCgoKUhoCCpJaCgpaEAAoUgpaCgpSCgoKC3oKCgpSWgoCC3LrEooKUgIKkgoK4lIKC")]
[assembly: go.GoPositionMap("crypto/tls/cache_test.go", "cache_test.cs", "ABcegpKCgpaCgpSCgpSCloCClICCyIKCgoKktIKCpJaCAAgSgoKEuoKChKaigoKWkoKmkpKCgoKCgoKUgoKCpoKU")]
[assembly: go.GoPositionMap("crypto/tls/conn_test.go", "conn_test.cs", "ABEcgooAHjqCgoKUgoKCgpSClIIAEBaCAA0chIKCgqaWgqaAgoKUuICCpICCpICCpICCyrKEgoKEgoKQkgAICIKUgoCCgqSEgoKEgoKClIKCloKCloKCgpaWxoCCpJbMgIKkgIKmgoK6qIKCgoKUgraoguiCgoKCpoKCgoKmgoKCgqaCggAJFIKCpsaCkpSClKaWAAgGooKSlIKEooKAgoKkgpaCgIKCpoSCgg==")]
[assembly: go.GoPositionMap("crypto/tls/ech_test.go", "ech_test.cs", "ABEYgr6CgpSCgpSC/IKCgpSCgpSCgg==")]
[assembly: go.GoPositionMap("crypto/tls/handshake_client_test.go", "handshake_client_test.cs", "ADp6goKUpKSkuAAMGoIAChaCgoSCgoKWgpSClJamggArYAANAoKClIKEgoKUgoKWgoSChIKCgozShIKCgsqCgpaCgoKCgqiCqIKCgoKCgoCCrsKCyIKUlIKCgoKWqAAJBoKm4oKClJLm0oKCgoKEgoKCgpSCkoK4goKUloKClIKUgIKCpraCAAkWgpaEwoSChIKCgpSWgoKWgoKWgILogoKUloKCgpaEwoSChIKCloKC2LiClISAgoK4goCC3IKAgriCgoKCgpSSgoKCgoKUggAJDKKCgIKkgILGprSSgpSChOaC5oLmguaCpoK4goKmgrimgrimgriCgqaC3IKCpoLcpoLcpoK4poK4poLcpoKChMyCpoKChMyC1oKChMqClKimgoKEzKaCgoQABhCmgrikgrikgrimgsqmgsqChIKChMyCpoKCgoTMgoQABhCCgoQABhCmgoKChMyCgoQABhCCrsKCgpSChJS8hAAHEIKmgoKChN6mgsqmgoCSgAAfBqKClNyCgpaChAAGEJKCgoKUgpSClICSuJaSgpSSlIKCgIKkloKCgoKogoKCgqiCgoKCloKChIKEgoKCgoKUloKClIKCgqiCgoKCgoLcgoKUlIK6yoSogoKCloKogoLcgpYABhCCgoKCgoKogoKCgpSEgoSCggAHEoKClIKCgpSCgoKUpoKCgpSCgoKUgoKClKaUgoKWgpSCgILKgpSCgILKgoKAgriCgIK4goCCuIKAgqSCgIIACQqClIKChIKChIKE0oSAgoKkxoCCpoKEgoKU3IKUgqiCpoKUgoSChIKE0oSAgoKkxoCCpoKEgoKCgqiCpoKChAAHEIKUpoLWyIKEosqWgoCCpISCgIKm3ITugoSAgv6ChIKCutrKgIKkgoCCtqbsooLugpSClKamgoKE3qaCgoTepoKChO6CloKUgpSo1oK4gIKkpKaCggAZMoKyhJKWgoCCpISCgIKmgoSCgoKUgpSC+siChKK4loKAgqSEgoCCysqE7oKEgILIgoCSgAANBqKCgpSClIKUgpSClIKSlIKUlgASEIKSgoCCpIKUuJKCgIKkgpSCuIKUgpTugoKSgoCCpIKUuIKSgoCCpIKUgriClIKU7oKSgriSgu6CkoK4gpKCgIKkgpSCuIKUgpTKgoKClIKElNyCgoQABxCEooKClIKUgoKUgpSCpoK4goCSgAAMBoKSgpaChISEgoCCpIKUgpSCgIKkgpSClIKWAC4OgrqCuoKUgpSClILcgrqmgtymuoLcpoKCgILagIKkgriClIKUgtyCuoK6gpSClIKUgtyCuoKmgtyCpoK6gtyClrqCgqaClILcgoKmgpa6gpSCzLKChJTSgoKCgoKCgoKCgoKEgoKWgoKCgoKCgoKEABEogoKWgqaUsoKEooKCloKCgpSEAAoYgoKmgoCSgLaCgoSChKKCgoKCloKClIKEkoKClIKWgIKmgIL4goKEgoSWkoLKsoKCloKCloKAgqSChICCyIKClLiChJKCgIKmgoCCpoKWgoKEgqKCgpbCgoKAgqSCloKClIKUABQcgoKClIKUyoCCAAYQgoKClMqAggAGEAAHFIKClLjKgtyCgJKAAAgGgoKCloKCgoKCgoKEgoSEjITSkoKEgoKUxoKElIKCooKUxqKClAAICuoAAiyClIKClICCyIKCgqKCgpSCgoKAgra4ooCShIKCgoKCAAgGooCCpIKUgIKkgIKkgIKkgIKkgIKkgIKkgIKkgILIgoCSgLaigoKUgoLcgoKChIKCuIKmgrqCgoKClIK4gqaCzIKogoKClIKUggAJENKCgoKCsoKClKaCgpSClIKUgoIACwyiABUygpKSgsqCpoKUgoCCyKbagIIACRKCAAtsgoSEgoKCloKCggAOCIKCgpTugoKUgoKWgtyCgoKCgoQAHlaygoSygoKWgoKChIKEgqQACAyChIKEhIKCgg==")]
[assembly: go.GoPositionMap("crypto/tls/handshake_messages_test.go", "handshake_messages_test.cs", "ABxUgoKCgpSmooSCgrKCgpSCgoKCloKCgoKWgIIABxCUtKaCgpbcgoKCAAgSgoKCgoKUyoKCgIKkpoKCpqKCgoKCgoKCgpSUgoKCgqaCgoKClIKCgpSmgpSClIKUgpSCgpSClIKUgpSCgoKClJS0tIKCgoKClIKUgpamooKCgoKCgoSClIKUgpaCloKClIKUgpSClIKCgraUgoKUgpSClqaihIKUgpamooKCgoKUpqKCgoKUpqKCgoKCpqKCgqaigoKmgoKCpqKCgsqCgoKUgoKClKaigoKClJSCgoKCgpSClIKUgoKUpoKUgoKmgoKClLiClIKCgqamgKKCgoKUgqaCgqaigoKmooKCgoKCgpSmooKClIKUgpSClIKCgqamooKCpoKClIKCgrj2loKCyoSCgqiCgpaClIKWgoKWgoSC6KiCyoSCgviCgoKUgoKWgoKUgoI=")]
[assembly: go.GoPositionMap("crypto/tls/handshake_server_test.go", "handshake_server_test.cs", "ACU8gqqigqaCgpKCgIKkgIKklIKCgoLKgpSClIKm2oKUgqaCgoKCtuiC+oKCgrLKAAkOgtzWgtymgtymgtaC7sYABxCCgoKCgpSogqbGAAcQgpSogoKCgqaiAAYQgoSygoKAgqaCgoKClIKWgoSCyoSmgpaCuMYADiCCgrKCgoCCpIKCgpSmgoKCgoKAgqSCgpSAggAPCMYABhqykgAHEoKCsoKCgIKkgoKClKaCgoKCgoCCpIKClIKCpoLugoKSgpaCgoKCuIKClIKCgriCuLiCgpSCloKCgoIACAiC3IKUgpSmuIKClIK4goCSgLaCggAIEKaCgpSCgpSCgsqCgJKAtoK4AAcSgoKCqIKClIKogoKClIKogoKUgqiCgoKUggAlTAAKAriClJSEgoKClIKCgoKCgoKAgqaCooKCgpSWgrSAgqS0lqjmgqbigoKUkubCgoKEgoKCgpSCkoK4goKUlIKClISCgoKigraCpoSCgoKCgoK4loKAgriCgoKCgpSSgoKCpoKC6LSSgpSCgpSChKaCpoKmgqaCpoK4goKmgriCpoK4gqaCuKaCuKaCuKSCuKSCuKaCgoKCgoTKgoKmgoKEyoKmgoKEyoKmgoKEyoKUptqigoTKgpSm2qKCAAgSpoKChAAHEIKUpoKmgoKEAAcQgqaCgoTugpSmgqaCgoTugpSmgqyyuKqiloKCkoKUyq7ChIbKqqKEgoju2qKEgoaE3KiE3NaigoTKuIKUqIKEgoSChNyClKgACAaigoSE3MqClKiCgoKEgoKC1oLI7qaCyoCCpKSmgoKmgrim2LiChMqmgoKCgoKEyoKmooKCgoKCgoSCgpKCgoKClIKAgqSChIKCgoKAggANCoKCpoKCpoK4goKmgriCgqaCuIKClIKmgtyi1IKCgoKCgoKCgoKCgpSWgoTKgoTugoTugoTugoTuAAkGooQABhCUhIKigoKAgqSUgoKC2oKUgpSUgpaCgpaCACA6hoLugpSmgoKUgriClMqCgpamgoK4gpTKgoKChLKCloKSgoKUgoTSksaChISCgpSCgILIgqTcgoKCooKUgoKCgIK26IKCgoKCgoK4goKkAAoIggADJIKWgoKCsoKCgoKCgpSCgqaCgoKEggAHEIKClICCAAwIwoKAlABm2AGykoIADiCCgpaCAA8MwoKAlAA7gAGykoKCAAwcgoKWggAMEtKCgoKCsoKClKaCgpSClIKUgoIABhLygoKCgoKSkoLygpKCgpKAgqSCyoKCgoKU1uaCgoKSgIKkgsqCgoKU1qSAgg==")]
[assembly: go.GoPositionMap("crypto/tls/handshake_test.go", "handshake_test.cs", "ADZogoKClJaCggAKDqKCloKCgpaCgpaCgoKCgoKCgoQADBrigIKkhIKEgIKCgpSkgtbigIKkhIKEgIKCgpSkgtikgoKCkoKUgoKClIKCgoKUgoKUlNaihIKCpoKCgpTMgoKUhIKClISCgoKClKiClgAMGuKChIKCloKCgoKClKbm4oKEgoKWgoKUgoKClObCgoSCgpTWgKKAooCigKKA1pKCgpSCgoIADxqCgoKClIKClNyigoSEgoSSgpKCgoKmgpSUgoKUgrSCgraCgJKQkpSC6oIACQyCgqaCgoKWyoKCgoKCqISCgpbWxpaCgpSCgpSCgpKEgIKCpgAJFIKCgoKCgoKClIKm1sKCgoLCgoKCgoKUkJKCgoKUgILaxIKCgoKAgqSAgraClIKmgoI=")]
[assembly: go.GoPositionMap("crypto/tls/key_schedule_test.go", "key_schedule_test.cs", "ABImkoKClJSCgoKClAAfBoKCAAA2ABNCspKCgIIADwyClpaWgoKClIIAIgiCABlQspKCgILslIKCgpSCgoKUgoK4goKClIKClIKClII=")]
[assembly: go.GoPositionMap("crypto/tls/link_test.go", "link_test.cs", "ACAikoKUgoKEACRigoKCspKAgqSCgoKAgqaCgoKClIKCpoKC")]
[assembly: go.GoPositionMap("crypto/tls/prf_test.go", "prf_test.cs", "ABgwgoKCgoKCggATIoKCgoKEgoCCgqaCgoKCgoiWgoKCloKCloQ=")]
[assembly: go.GoPositionMap("crypto/tls/quic_test.go", "quic_test.cs", "ABo2griSlKaCuJKUAAcQgoCCpIKUgIKkgpSYpMiCgIKkgpSYpAAKDKKCgoKAgsiCgoKClJSCgoKUlKSkpICCxoKCtqSCgoCC2IKUpIK2pILKgoKEgoSChICCpoCCpICCpICCpICCpIKAgqSAgqSClIL6goKCgoSChIKCgoKAgqSCloKCgoKAgqSCuIKCgoKEgoSCgoKCgpSCgIKCtpSUgILIlIKCgoKCgoCCpoKCgoKCgpSAuMiUgoKCgoKCgIKmgoKClIC4yIKCgoKCgoKAgqaCgNz4goKCgoSChIKCgoKCgpSCgr6ygoKCgoKCgqKCgIKAksaCgIKAksaUgILIgoKCgoKCgoKCgoKUlIKCgoKAgqSC+IKCgoKEgoSChIKCgIKkgoCCpIKAgqaAkqSAksiCgoSCgoKCgIKmgpSClIKUgriCgoKCgoKUgoK4goKCgoKUgoK4goKCgoKEgoKEgoKCgoKAgqSCloKCgoKClKSUgIKkgpSCgpSCgpSCuIKClIK4goKCgoKChIKCgoSCgoKCgoCCpIKWgoKCgoKUgpSUgIKkgpSCgoKUgqaAgg==")]
[assembly: go.GoPositionMap("crypto/tls/tls_test.go", "tls_test.cs", "AEnaAYKCgoKCgIKkgoCCAAoKooKClICCpoKClICCpqyCgpSAggAICIKAgqSAgsiCgoKUgpSmgoKWkoKCgqKCgoKClKiCpoCCgqSm3oKmgriCgpSCloIACQiigpaClISigoKClIKAgoKkloKCgoKUlIKCqIKAgqSAgriAgqSAgriAgqSAgriAgqSCAAgMgKrSgpSCgsKCgpSSxoL+gsiCguiCgIKkrAAJDoKUgoKAgramwoKUgoKigoKCgpSCgoCCgoKklqaCgoKUlIKCloSCgoKWgoKCgoKUgpQADAaigpSCgoKC4oKCgoKClIKCgoCCgqS0AAkMgoKCgpaCtMiClIKUhIKClJKClrTIgpSCAAsIgoSCgpSAgqSAgqaCgpSAgvjCgpSCgoKigoKCgoKUgoKAgoKCpJaCgpSUqIKCgIKmgoKUhIKSgpaCgrKCgpaCsoKCloKCloKAggAKCKKClITCgoKUlIKCgIKklIKClIKWgILugsbChIKCgpSAgqSUgIKmgIKmgoKUgpTGhKCSoJSCtILG3IKClIKClJKEgIIACwqigpSygoKUlIKCgIKklIKClIKAgqbGgqCUgoKCgpSSgIKmgpaAgviCgoSkgqaCpoKmgqaCpoKmgqaCpoKohIKCgoKCgoKChIK4ooKEgoKmgKTOAAgIpKSkpKSkpKSkpKSkpKSk2IKEgoK4goKAggAMGIKClKaCgpSmwoKUiKSSgoKCppSCgoKCgIKkgILKgoKCgoSCgoKCgpSCgoKUgoKm6IKCkoKCgpSCAAsYgoKUgoKCgoKClIKCgoK4psKClISSgoKmlIKCgoCCpKiCgoSChIKCgqaAgqSAgqSAgqSAgqTogoKCgoKClILugoKCgriCgoKUgoSEgoKChLKClKSk0gAKFoKCgoSCgpaCloKWgpaCloKWgqiClIKWgpaCpJaClIKmgoKUgqiCgqaCAAYSori4goSCgoKCuIAACASiuMrKugCLAZoCgoKUtLQADwqCgoKClJaCpoKCgpSWgqiCgoKmgoKmloKCgoKWgIKkpoKCpoKogIK2goKCgpaClIKWgIK4gIKmgpSCqIKCgoKClIK6hrKCgoKCloKkloKkuoKCpIKkpoKkpoKkpoKkpoKkppSClMiClLiCpKaCpJSClILKgoCSpICSzKIAASKkAAgMlNrCgsiCgpaAgqaqgILIlICSgAATBoIAJFiCgpSChIKSooSSlIKCgoKCgoKChIKClIKClIKClIKCloKCgpaAgqaCgqaClIKUgpaCgoKClIKWgpSClIKUggAZDIKClgAJJO4ACBIACBLuAAcQzIKCsqKClJSCgpSSgqSUlIKClIKClIKClIKmgpSCpoKClIKmgpSCAA0OgoKClIKClIK4goKUhKKCgoKUgqaigoKClIKmooKClIIACAqChJKAgriCgoKClIK4goKClAALGIKCloKC3ICC")]
// </GoSourcePositionMaps>

namespace go.crypto;

[GoPackage("tls")]
public static partial class tls_internal_test_package
{
    // C# nested types declared with no access modifier are always private, and the
    // `[GoType]` declarations in this package's converted sources are deliberately
    // bare so they read more like the original Go code. The real accessibility for
    // the types - public for a Go-exported name, internal otherwise - are defined
    // via declarations below.

    // <TypeAccessibility>
    // </TypeAccessibility>
}
