// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto.@internal.edwards25519;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/internal/edwards25519/field", new string[]
        {
            "fe.go",
            "fe_alias_test.go",
            "fe_amd64.go",
            "fe_amd64_noasm.go",
            "fe_arm64.go",
            "fe_arm64_noasm.go",
            "fe_bench_test.go",
            "fe_generic.go",
            "fe_test.go",
        }, new string[]
        {
            "_asm",
        });
        registry.Add("TestAliasing", field_internal_test_package.TestAliasing, "fe_alias_test.go", 87);
        registry.Add("TestBytesBigEquivalence", field_internal_test_package.TestBytesBigEquivalence, "fe_test.go", 215);
        registry.Add("TestCarryPropagate", field_internal_test_package.TestCarryPropagate, "fe_test.go", 492);
        registry.Add("TestConsistency", field_internal_test_package.TestConsistency, "fe_test.go", 303);
        registry.Add("TestDecimalConstants", field_internal_test_package.TestDecimalConstants, "fe_test.go", 284);
        registry.Add("TestEqual", field_internal_test_package.TestEqual, "fe_test.go", 331);
        registry.Add("TestFeMul", field_internal_test_package.TestFeMul, "fe_test.go", 536);
        registry.Add("TestFeSquare", field_internal_test_package.TestFeSquare, "fe_test.go", 516);
        registry.Add("TestInvert", field_internal_test_package.TestInvert, "fe_test.go", 346);
        registry.Add("TestMul64to128", field_internal_test_package.TestMul64to128, "fe_test.go", 128);
        registry.Add("TestMult32", field_internal_test_package.TestMult32, "fe_test.go", 410);
        registry.Add("TestMultiplyDistributesOverAdd", field_internal_test_package.TestMultiplyDistributesOverAdd, "fe_test.go", 106);
        registry.Add("TestSelectSwap", field_internal_test_package.TestSelectSwap, "fe_test.go", 384);
        registry.Add("TestSetBytesRoundTrip", field_internal_test_package.TestSetBytesRoundTrip, "fe_test.go", 155);
        registry.Add("TestSetBytesRoundTripEdgeCases", field_internal_test_package.TestSetBytesRoundTripEdgeCases, "fe_test.go", 296);
        registry.Add("TestSqrtRatio", field_internal_test_package.TestSqrtRatio, "fe_test.go", 433);
        return TestHost.Run(registry, args);
    }
}
