// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/buildcfg", new string[]
        {
            "cfg.go",
            "cfg_test.go",
            "exp.go",
            "zbootstrap.go",
        });
        registry.Add("TestConfigFlags", buildcfg_internal_test_package.TestConfigFlags, "cfg_test.go", 12);
        registry.Add("TestGoarm64FeaturesSupports", buildcfg_internal_test_package.TestGoarm64FeaturesSupports, "cfg_test.go", 77);
        registry.Add("TestGogoarchTags", buildcfg_internal_test_package.TestGogoarchTags, "cfg_test.go", 101);
        return TestHost.Run(registry, args);
    }
}
