// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.go;

using global::go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("go/token", new string[]
        {
            "example_test.go",
            "position.go",
            "position_bench_test.go",
            "position_test.go",
            "serialize.go",
            "serialize_test.go",
            "token.go",
            "token_test.go",
        });
        registry.Add("TestFileAddLineColumnInfo", token_internal_test_package.TestFileAddLineColumnInfo, "position_test.go", 388);
        registry.Add("TestFileSetCacheUnlikely", token_internal_test_package.TestFileSetCacheUnlikely, "position_test.go", 206);
        registry.Add("TestFileSetPastEnd", token_internal_test_package.TestFileSetPastEnd, "position_test.go", 196);
        registry.Add("TestFileSetRace", token_internal_test_package.TestFileSetRace, "position_test.go", 223);
        registry.Add("TestFileSetRace2", token_internal_test_package.TestFileSetRace2, "position_test.go", 246);
        registry.Add("TestFiles", token_internal_test_package.TestFiles, "position_test.go", 171);
        registry.Add("TestIsIdentifier", token_internal_test_package.TestIsIdentifier, "token_test.go", 9);
        registry.Add("TestIssue57490", token_internal_test_package.TestIssue57490, "position_test.go", 482);
        registry.Add("TestLineInfo", token_internal_test_package.TestLineInfo, "position_test.go", 152);
        registry.Add("TestLineStart", token_internal_test_package.TestLineStart, "position_test.go", 332);
        registry.Add("TestNoPos", token_internal_test_package.TestNoPos, "position_test.go", 30);
        registry.Add("TestPositionFor", token_internal_test_package.TestPositionFor, "position_test.go", 273);
        registry.Add("TestPositions", token_internal_test_package.TestPositions, "position_test.go", 91);
        registry.Add("TestRemoveFile", token_internal_test_package.TestRemoveFile, "position_test.go", 347);
        registry.Add("TestSerialization", token_internal_test_package.TestSerialization, "serialize_test.go", 87);
        return TestHost.Run(registry, args);
    }
}
