// Copyright 2014 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
namespace go.debug;

using io = io_package;
using path = path_package;
using reflect = reflect_package;
using testing = testing_package;
using static go.debug.elf_package;

partial class elf_internal_test_package {

// TODO: remove duplicate code
public static void TestSymbols(ж<testing.T> Ꮡt) {
    void @do(@string @file, slice<global::go.debug.elf_package.Symbol> ts, Func<ж<global::go.debug.elf_package.File>, (slice<global::go.debug.elf_package.Symbol>, error)> getfunc) {
        GoFrame ᒐ = default;
        try {
            ж<global::go.debug.elf_package.File> f = default!;
            error err = default!;
            if (path.Ext(@file) == ".gz"u8){
                io.ReaderAt r = default!;
                {
                    (r, err) = decompress(@file); if (err == default!) {
                        (f, err) = NewFile(r);
                    }
                }
            } else {
                (f, err) = Open(@file);
            }
            if (err != default!) {
                Ꮡt.Errorf("TestSymbols: cannot open file %s: %v"u8, @file, err);
                return;
            }
            var fʗ1 = f;
            defer(() => fʗ1.Close(), ref ᒐ);
            (var fs, err) = getfunc(f);
            if (err != default! && !AreEqual(err, ErrNoSymbols)){
                Ꮡt.Error(err);
                return;
            } else 
            if (AreEqual(err, ErrNoSymbols)) {
                fs = new global::go.debug.elf_package.Symbol[]{}.slice();
            }
            if (!reflect.DeepEqual(ts, fs)) {
                Ꮡt.Errorf("%s: Symbols = %v, want %v"u8, @file, ts, fs);
            }
        }
        catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
        finally { ᒐ.Run(); }
    }
    foreach (var (@file, ts) in symbolsGolden) {
        @do(@file, ts, (Func<ж<global::go.debug.elf_package.File>, (slice<global::go.debug.elf_package.Symbol>, error)>)(global::go.debug.elf_package.Symbols));
    }
    foreach (var (@file, ts) in dynamicSymbolsGolden) {
        @do(@file, ts, (Func<ж<global::go.debug.elf_package.File>, (slice<global::go.debug.elf_package.Symbol>, error)>)(global::go.debug.elf_package.DynamicSymbols));
    }
}

// golden symbol table data generated by testdata/getgoldsym.c
internal static map<@string, slice<global::go.debug.elf_package.Symbol>> symbolsGolden = new map<@string, slice<global::go.debug.elf_package.Symbol>>{
    ["testdata/gcc-amd64-linux-exec"u8] = new global::go.debug.elf_package.Symbol[]{
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x1,
            Value: 0x400200,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x2,
            Value: 0x40021C,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x3,
            Value: 0x400240,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x4,
            Value: 0x400268,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x5,
            Value: 0x400288,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x6,
            Value: 0x4002E8,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x7,
            Value: 0x400326,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x8,
            Value: 0x400330,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x9,
            Value: 0x400350,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xA,
            Value: 0x400368,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xB,
            Value: 0x400398,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xC,
            Value: 0x4003B0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xD,
            Value: 0x4003E0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xE,
            Value: 0x400594,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xF,
            Value: 0x4005A4,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x10,
            Value: 0x4005B8,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x11,
            Value: 0x4005E0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x12,
            Value: 0x600688,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x13,
            Value: 0x600698,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x14,
            Value: 0x6006A8,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x15,
            Value: 0x6006B0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x16,
            Value: 0x600850,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x17,
            Value: 0x600858,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x18,
            Value: 0x600880,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x19,
            Value: 0x600898,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x1A,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x1B,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x1C,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x1D,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x1E,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x1F,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x20,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x21,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "init.c"u8,
            Info: 0x4,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "initfini.c"u8,
            Info: 0x4,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "call_gmon_start"u8,
            Info: 0x2,
            Other: 0x0,
            Section: 0xD,
            Value: 0x40040C,
            Size: 0x0
        ),
        new Symbol(
            Name: "crtstuff.c"u8,
            Info: 0x4,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "__CTOR_LIST__"u8,
            Info: 0x1,
            Other: 0x0,
            Section: 0x12,
            Value: 0x600688,
            Size: 0x0
        ),
        new Symbol(
            Name: "__DTOR_LIST__"u8,
            Info: 0x1,
            Other: 0x0,
            Section: 0x13,
            Value: 0x600698,
            Size: 0x0
        ),
        new Symbol(
            Name: "__JCR_LIST__"u8,
            Info: 0x1,
            Other: 0x0,
            Section: 0x14,
            Value: 0x6006A8,
            Size: 0x0
        ),
        new Symbol(
            Name: "__do_global_dtors_aux"u8,
            Info: 0x2,
            Other: 0x0,
            Section: 0xD,
            Value: 0x400430,
            Size: 0x0
        ),
        new Symbol(
            Name: "completed.6183"u8,
            Info: 0x1,
            Other: 0x0,
            Section: 0x19,
            Value: 0x600898,
            Size: 0x1
        ),
        new Symbol(
            Name: "p.6181"u8,
            Info: 0x1,
            Other: 0x0,
            Section: 0x18,
            Value: 0x600890,
            Size: 0x0
        ),
        new Symbol(
            Name: "frame_dummy"u8,
            Info: 0x2,
            Other: 0x0,
            Section: 0xD,
            Value: 0x400470,
            Size: 0x0
        ),
        new Symbol(
            Name: "crtstuff.c"u8,
            Info: 0x4,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "__CTOR_END__"u8,
            Info: 0x1,
            Other: 0x0,
            Section: 0x12,
            Value: 0x600690,
            Size: 0x0
        ),
        new Symbol(
            Name: "__DTOR_END__"u8,
            Info: 0x1,
            Other: 0x0,
            Section: 0x13,
            Value: 0x6006A0,
            Size: 0x0
        ),
        new Symbol(
            Name: "__FRAME_END__"u8,
            Info: 0x1,
            Other: 0x0,
            Section: 0x11,
            Value: 0x400680,
            Size: 0x0
        ),
        new Symbol(
            Name: "__JCR_END__"u8,
            Info: 0x1,
            Other: 0x0,
            Section: 0x14,
            Value: 0x6006A8,
            Size: 0x0
        ),
        new Symbol(
            Name: "__do_global_ctors_aux"u8,
            Info: 0x2,
            Other: 0x0,
            Section: 0xD,
            Value: 0x400560,
            Size: 0x0
        ),
        new Symbol(
            Name: "initfini.c"u8,
            Info: 0x4,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "hello.c"u8,
            Info: 0x4,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "_GLOBAL_OFFSET_TABLE_"u8,
            Info: 0x1,
            Other: 0x2,
            Section: 0x17,
            Value: 0x600858,
            Size: 0x0
        ),
        new Symbol(
            Name: "__init_array_end"u8,
            Info: 0x0,
            Other: 0x2,
            Section: 0x12,
            Value: 0x600684,
            Size: 0x0
        ),
        new Symbol(
            Name: "__init_array_start"u8,
            Info: 0x0,
            Other: 0x2,
            Section: 0x12,
            Value: 0x600684,
            Size: 0x0
        ),
        new Symbol(
            Name: "_DYNAMIC"u8,
            Info: 0x1,
            Other: 0x2,
            Section: 0x15,
            Value: 0x6006B0,
            Size: 0x0
        ),
        new Symbol(
            Name: "data_start"u8,
            Info: 0x20,
            Other: 0x0,
            Section: 0x18,
            Value: 0x600880,
            Size: 0x0
        ),
        new Symbol(
            Name: "__libc_csu_fini"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0xD,
            Value: 0x4004C0,
            Size: 0x2
        ),
        new Symbol(
            Name: "_start"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0xD,
            Value: 0x4003E0,
            Size: 0x0
        ),
        new Symbol(
            Name: "__gmon_start__"u8,
            Info: 0x20,
            Other: 0x0,
            Section: 0x0,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "_Jv_RegisterClasses"u8,
            Info: 0x20,
            Other: 0x0,
            Section: 0x0,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "puts@@GLIBC_2.2.5"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0x0,
            Value: 0x0,
            Size: 0x18C
        ),
        new Symbol(
            Name: "_fini"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0xE,
            Value: 0x400594,
            Size: 0x0
        ),
        new Symbol(
            Name: "__libc_start_main@@GLIBC_2.2.5"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0x0,
            Value: 0x0,
            Size: 0x1C2
        ),
        new Symbol(
            Name: "_IO_stdin_used"u8,
            Info: 0x11,
            Other: 0x0,
            Section: 0xF,
            Value: 0x4005A4,
            Size: 0x4
        ),
        new Symbol(
            Name: "__data_start"u8,
            Info: 0x10,
            Other: 0x0,
            Section: 0x18,
            Value: 0x600880,
            Size: 0x0
        ),
        new Symbol(
            Name: "__dso_handle"u8,
            Info: 0x11,
            Other: 0x2,
            Section: 0x18,
            Value: 0x600888,
            Size: 0x0
        ),
        new Symbol(
            Name: "__libc_csu_init"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0xD,
            Value: 0x4004D0,
            Size: 0x89
        ),
        new Symbol(
            Name: "__bss_start"u8,
            Info: 0x10,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x600898,
            Size: 0x0
        ),
        new Symbol(
            Name: "_end"u8,
            Info: 0x10,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x6008A0,
            Size: 0x0
        ),
        new Symbol(
            Name: "_edata"u8,
            Info: 0x10,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x600898,
            Size: 0x0
        ),
        new Symbol(
            Name: "main"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0xD,
            Value: 0x400498,
            Size: 0x1B
        ),
        new Symbol(
            Name: "_init"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0xB,
            Value: 0x400398,
            Size: 0x0
        )}.slice(),
    ["testdata/go-relocation-test-clang-x86.obj"u8] = new global::go.debug.elf_package.Symbol[]{
        new Symbol(
            Name: "go-relocation-test-clang.c"u8,
            Info: 0x4,
            Other: 0x0,
            Section: 0xFFF1,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ".Linfo_string0"u8,
            Info: 0x0,
            Other: 0x0,
            Section: 0xC,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ".Linfo_string1"u8,
            Info: 0x0,
            Other: 0x0,
            Section: 0xC,
            Value: 0x2C,
            Size: 0x0
        ),
        new Symbol(
            Name: ".Linfo_string2"u8,
            Info: 0x0,
            Other: 0x0,
            Section: 0xC,
            Value: 0x47,
            Size: 0x0
        ),
        new Symbol(
            Name: ".Linfo_string3"u8,
            Info: 0x0,
            Other: 0x0,
            Section: 0xC,
            Value: 0x4C,
            Size: 0x0
        ),
        new Symbol(
            Name: ".Linfo_string4"u8,
            Info: 0x0,
            Other: 0x0,
            Section: 0xC,
            Value: 0x4E,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x1,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x2,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x3,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x4,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x6,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x7,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x8,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xA,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xC,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xD,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xE,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0xF,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: ""u8,
            Info: 0x3,
            Other: 0x0,
            Section: 0x10,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "v"u8,
            Info: 0x11,
            Other: 0x0,
            Section: 0xFFF2,
            Value: 0x4,
            Size: 0x4
        )}.slice(),
    ["testdata/hello-world-core.gz"u8] = new global::go.debug.elf_package.Symbol[]{}.slice()
};

internal static map<@string, slice<global::go.debug.elf_package.Symbol>> dynamicSymbolsGolden = new map<@string, slice<global::go.debug.elf_package.Symbol>>{
    ["testdata/gcc-amd64-linux-exec"u8] = new global::go.debug.elf_package.Symbol[]{
        new Symbol(
            Name: "__gmon_start__"u8,
            Info: 0x20,
            Other: 0x0,
            Section: 0x0,
            Value: 0x0,
            Size: 0x0
        ),
        new Symbol(
            Name: "puts"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0x0,
            Value: 0x0,
            Size: 0x18C,
            Version: "GLIBC_2.2.5"u8,
            Library: "libc.so.6"u8
        ),
        new Symbol(
            Name: "__libc_start_main"u8,
            Info: 0x12,
            Other: 0x0,
            Section: 0x0,
            Value: 0x0,
            Size: 0x1C2,
            Version: "GLIBC_2.2.5"u8,
            Library: "libc.so.6"u8
        )}.slice(),
    ["testdata/go-relocation-test-clang-x86.obj"u8] = new global::go.debug.elf_package.Symbol[]{}.slice(),
    ["testdata/hello-world-core.gz"u8] = new global::go.debug.elf_package.Symbol[]{}.slice()
};

} // end elf_internal_test_package
