// Code generated by mkconsts.go. DO NOT EDIT.
//go:build !goexperiment.preemptibleloops
[assembly: go.GoPositionMap("internal/goexperiment/exp_preemptibleloops_off.go", "exp_preemptibleloops_off.cs", "")]

namespace go.@internal;

partial class goexperiment_package {

public const bool PreemptibleLoops = false;

public static UntypedInt PreemptibleLoopsInt => 0;

} // end goexperiment_package
