// Code generated by mkconsts.go. DO NOT EDIT.
//go:build !goexperiment.loopvar
[assembly: go.GoPositionMap("internal/goexperiment/exp_loopvar_off.go", "exp_loopvar_off.cs", "")]

namespace go.@internal;

partial class goexperiment_package {

public const bool LoopVar = false;

public static UntypedInt LoopVarInt => 0;

} // end goexperiment_package
