// Code generated by mkconsts.go. DO NOT EDIT.
//go:build goexperiment.synchashtriemap
namespace go.@internal;

partial class goexperiment_package {

public const bool SyncHashTrieMap = true;

public static UntypedInt SyncHashTrieMapInt => 1;

} // end goexperiment_package
