// Code generated by mkconsts.go. DO NOT EDIT.
//go:build !goexperiment.rangefunc
[assembly: go.GoPositionMap("internal/goexperiment/exp_rangefunc_off.go", "exp_rangefunc_off.cs", "")]

namespace go.@internal;

partial class goexperiment_package {

public const bool RangeFunc = false;

public static UntypedInt RangeFuncInt => 0;

} // end goexperiment_package
