// Code generated by mkconsts.go. DO NOT EDIT.
//go:build !goexperiment.staticlockranking
[assembly: go.GoPositionMap("internal/goexperiment/exp_staticlockranking_off.go", "exp_staticlockranking_off.cs", "")]

namespace go.@internal;

partial class goexperiment_package {

public const bool StaticLockRanking = false;

public static UntypedInt StaticLockRankingInt => 0;

} // end goexperiment_package
