// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.mime;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("mime/multipart", new string[]
        {
            "example_test.go",
            "formdata.go",
            "formdata_test.go",
            "multipart.go",
            "multipart_test.go",
            "readmimeheader.go",
            "testdata/nested-mime",
            "writer.go",
            "writer_test.go",
        }, new string[]
        {
            "testdata",
        });
        registry.Add("TestBoundaryLine", multipart_internal_test_package.TestBoundaryLine, "multipart_test.go", 19);
        registry.Add("TestLineContinuation", multipart_internal_test_package.TestLineContinuation, "multipart_test.go", 403);
        registry.Add("TestLineLimit", multipart_internal_test_package.TestLineLimit, "multipart_test.go", 278);
        registry.Add("TestMultipart", multipart_internal_test_package.TestMultipart, "multipart_test.go", 111);
        registry.Add("TestMultipartOnlyNewlines", multipart_internal_test_package.TestMultipartOnlyNewlines, "multipart_test.go", 116);
        registry.Add("TestMultipartSlowInput", multipart_internal_test_package.TestMultipartSlowInput, "multipart_test.go", 121);
        registry.Add("TestMultipartStreamReadahead", multipart_internal_test_package.TestMultipartStreamReadahead, "multipart_test.go", 352);
        registry.Add("TestMultipartTruncated", multipart_internal_test_package.TestMultipartTruncated, "multipart_test.go", 293);
        registry.Add("TestNameAccessors", multipart_internal_test_package.TestNameAccessors, "multipart_test.go", 51);
        registry.Add("TestNested", multipart_internal_test_package.TestNested, "multipart_test.go", 522);
        registry.Add("TestNoBoundary", multipart_internal_test_package.TestNoBoundary, "multipart_test.go", 1014);
        registry.Add("TestParse", multipart_internal_test_package.TestParse, "multipart_test.go", 898);
        registry.Add("TestParseAllSizes", multipart_internal_test_package.TestParseAllSizes, "multipart_test.go", 952);
        registry.Add("TestQuotedPrintableEncoding", multipart_internal_test_package.TestQuotedPrintableEncoding, "multipart_test.go", 430);
        registry.Add("TestRawPart", multipart_internal_test_package.TestRawPart, "multipart_test.go", 461);
        registry.Add("TestReadForm", multipart_internal_test_package.TestReadForm, "formdata_test.go", 18);
        registry.Add("TestReadFormEndlessHeaderLine", multipart_internal_test_package.TestReadFormEndlessHeaderLine, "formdata_test.go", 455);
        registry.Add("TestReadFormLimits", multipart_internal_test_package.TestReadFormLimits, "formdata_test.go", 394);
        registry.Add("TestReadFormMaxMemoryOverflow", multipart_internal_test_package.TestReadFormMaxMemoryOverflow, "formdata_test.go", 76);
        registry.Add("TestReadFormWitFileNameMaxMemoryOverflow", multipart_internal_test_package.TestReadFormWitFileNameMaxMemoryOverflow, "formdata_test.go", 59);
        registry.Add("TestReadFormWithNamelessFile", multipart_internal_test_package.TestReadFormWithNamelessFile, "formdata_test.go", 44);
        registry.Add("TestReadFormWithTextContentType", multipart_internal_test_package.TestReadFormWithTextContentType, "formdata_test.go", 93);
        registry.Add("TestReadForm_ManyFiles_Combined", multipart_internal_test_package.TestReadForm_ManyFiles_Combined, "formdata_test.go", 311);
        registry.Add("TestReadForm_ManyFiles_Distinct", multipart_internal_test_package.TestReadForm_ManyFiles_Distinct, "formdata_test.go", 318);
        registry.Add("TestReadForm_MetadataTooLarge", multipart_internal_test_package.TestReadForm_MetadataTooLarge, "formdata_test.go", 264);
        registry.Add("TestReadForm_NoReadAfterEOF", multipart_internal_test_package.TestReadForm_NoReadAfterEOF, "formdata_test.go", 187);
        registry.Add("TestReadForm_NonFileMaxMemory", multipart_internal_test_package.TestReadForm_NonFileMaxMemory, "formdata_test.go", 225);
        registry.Add("TestSortedHeader", multipart_internal_test_package.TestSortedHeader, "writer_test.go", 147);
        registry.Add("TestVariousTextLineEndings", multipart_internal_test_package.TestVariousTextLineEndings, "multipart_test.go", 215);
        registry.Add("TestWriter", multipart_internal_test_package.TestWriter, "writer_test.go", 16);
        registry.Add("TestWriterBoundaryGoroutines", multipart_internal_test_package.TestWriterBoundaryGoroutines, "writer_test.go", 132);
        registry.Add("TestWriterSetBoundary", multipart_internal_test_package.TestWriterSetBoundary, "writer_test.go", 83);
        return TestHost.Run(registry, args);
    }
}
