// Code generated by go2cs. DO NOT EDIT.
// Test-variant package-level variable initialization ordered to match Go's
// dependency order (types.Info.InitOrder) — see package_init.cs. Each initᴛ
// method lives beside its variable's declaration in the converted test file.
namespace go;

partial class net_internal_test_package {
    static net_internal_test_package() {
        initᴛdialGoogleTests();
        initᴛparseIPTests();
        initᴛipStringTests();
        initᴛipMaskTests();
        initᴛparseCIDRTests();
        initᴛipNetContainsTests();
        initᴛipNetStringTests();
        initᴛipAddrFamilyTests();
        initᴛipAddrScopeTests();
        initᴛresolveIPAddrTests();
        initᴛipConnLocalNameTests();
        initᴛaddrListTests();
        initᴛipv4MulticastListenerTests();
        initᴛorigWSASocket();
        initᴛorigConnect();
        initᴛorigListen();
        initᴛresolveTCPAddrTests();
        initᴛtcpListenerNameTests();
        initᴛresolveUDPAddrTests();
        initᴛudpConnLocalNameTests();
    }
} // end net_internal_test_package
