// Code generated by go2cs. DO NOT EDIT.
// Test-variant package-level variable initialization ordered to match Go's
// dependency order (types.Info.InitOrder) — see package_init.cs. Each initᴛ
// method lives beside its variable's declaration in the converted test file.
namespace go.regexp;

partial class syntax_internal_test_package {
    static syntax_internal_test_package() {
        initᴛparseTests();
    }
} // end syntax_internal_test_package
