// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/testenv", new string[]
        {
            "exec.go",
            "noopt.go",
            "opt.go",
            "testenv.go",
            "testenv_notunix.go",
            "testenv_notwin.go",
            "testenv_test.go",
            "testenv_unix.go",
            "testenv_windows.go",
        });
        registry.Add("TestCleanCmdEnvPWD", testenv_test_package.TestCleanCmdEnvPWD, "testenv_test.go", 167);
        registry.Add("TestGoToolLocation", testenv_test_package.TestGoToolLocation, "testenv_test.go", 17);
        registry.Add("TestHasGoBuild", testenv_test_package.TestHasGoBuild, "testenv_test.go", 57);
        registry.Add("TestMustHaveExec", testenv_test_package.TestMustHaveExec, "testenv_test.go", 141);
        return TestHost.Run(registry, args);
    }
}
