// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.debug;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("debug/dwarf", new string[]
        {
            "attr_string.go",
            "buf.go",
            "class_string.go",
            "const.go",
            "dwarf5ranges_test.go",
            "entry.go",
            "entry_test.go",
            "export_test.go",
            "line.go",
            "line_test.go",
            "open.go",
            "tag_string.go",
            "testdata/bitfields.c",
            "testdata/bitfields.elf4",
            "testdata/cppunsuptypes.cc",
            "testdata/cppunsuptypes.elf",
            "testdata/cycle.c",
            "testdata/cycle.elf",
            "testdata/debug_rnglists",
            "testdata/line-clang-dwarf5.elf",
            "testdata/line-clang.elf",
            "testdata/line-gcc-dwarf5.elf",
            "testdata/line-gcc-win.bin",
            "testdata/line-gcc-zstd.elf",
            "testdata/line-gcc.elf",
            "testdata/line1.c",
            "testdata/line1.h",
            "testdata/line2.c",
            "testdata/ranges.c",
            "testdata/ranges.elf",
            "testdata/rnglistx.c",
            "testdata/rnglistx.elf",
            "testdata/split.c",
            "testdata/split.elf",
            "testdata/typedef.c",
            "testdata/typedef.elf",
            "testdata/typedef.elf4",
            "testdata/typedef.elf5",
            "testdata/typedef.macho",
            "testdata/typedef.macho4",
            "type.go",
            "type_test.go",
            "typeunit.go",
            "unit.go",
        }, new string[]
        {
            "testdata",
        });
        registry.Add("Test64Bit", dwarf_test_package.Test64Bit, "entry_test.go", 211);
        registry.Add("TestBitFieldZeroArrayIssue50685", dwarf_test_package.TestBitFieldZeroArrayIssue50685, "type_test.go", 332);
        registry.Add("TestBitOffsetsELF", dwarf_test_package.TestBitOffsetsELF, "type_test.go", 246);
        registry.Add("TestBitOffsetsELFDwarf4", dwarf_test_package.TestBitOffsetsELFDwarf4, "type_test.go", 261);
        registry.Add("TestBitOffsetsELFDwarf5", dwarf_test_package.TestBitOffsetsELFDwarf5, "type_test.go", 266);
        registry.Add("TestBitOffsetsMachO", dwarf_test_package.TestBitOffsetsMachO, "type_test.go", 251);
        registry.Add("TestBitOffsetsMachO4", dwarf_test_package.TestBitOffsetsMachO4, "type_test.go", 256);
        registry.Add("TestDwarf5Ranges", dwarf_internal_test_package.TestDwarf5Ranges, "dwarf5ranges_test.go", 14);
        registry.Add("TestIssue51758", dwarf_test_package.TestIssue51758, "entry_test.go", 325);
        registry.Add("TestIssue52045", dwarf_test_package.TestIssue52045, "entry_test.go", 446);
        registry.Add("TestLineELFClang", dwarf_test_package.TestLineELFClang, "line_test.go", 130);
        registry.Add("TestLineELFGCC", dwarf_test_package.TestLineELFGCC, "line_test.go", 20);
        registry.Add("TestLineELFGCCZstd", dwarf_test_package.TestLineELFGCCZstd, "line_test.go", 51);
        registry.Add("TestLineGCCWindows", dwarf_test_package.TestLineGCCWindows, "line_test.go", 89);
        registry.Add("TestLineRnglists", dwarf_test_package.TestLineRnglists, "line_test.go", 158);
        registry.Add("TestLineSeek", dwarf_test_package.TestLineSeek, "line_test.go", 181);
        registry.Add("TestPathJoin", dwarf_test_package.TestPathJoin, "line_test.go", 426);
        registry.Add("TestPathLineReaderMalformed", dwarf_test_package.TestPathLineReaderMalformed, "line_test.go", 435);
        registry.Add("TestRangesRnglistx", dwarf_test_package.TestRangesRnglistx, "entry_test.go", 93);
        registry.Add("TestRangesSection", dwarf_test_package.TestRangesSection, "entry_test.go", 80);
        registry.Add("TestReaderRanges", dwarf_test_package.TestReaderRanges, "entry_test.go", 132);
        registry.Add("TestReaderSeek", dwarf_test_package.TestReaderSeek, "entry_test.go", 48);
        registry.Add("TestSplit", dwarf_test_package.TestSplit, "entry_test.go", 15);
        registry.Add("TestTypedefCycle", dwarf_test_package.TestTypedefCycle, "type_test.go", 144);
        registry.Add("TestTypedefsELF", dwarf_test_package.TestTypedefsELF, "type_test.go", 86);
        registry.Add("TestTypedefsELFDwarf4", dwarf_test_package.TestTypedefsELFDwarf4, "type_test.go", 94);
        registry.Add("TestTypedefsMachO", dwarf_test_package.TestTypedefsMachO, "type_test.go", 90);
        registry.Add("TestUnitIteration", dwarf_test_package.TestUnitIteration, "entry_test.go", 284);
        registry.Add("TestUnsupportedTypes", dwarf_test_package.TestUnsupportedTypes, "type_test.go", 184);
        return TestHost.Run(registry, args);
    }
}
