// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.go.ast.@internal;

using global::go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("go/ast/internal/tests", new string[]
        {
            "sortimports_test.go",
        });
        registry.Add("TestSortImportsUpdatesFileImportsField", tests_internal_test_package.TestSortImportsUpdatesFileImportsField, "sortimports_test.go", 15);
        return TestHost.Run(registry, args);
    }
}
