// p256_impl.cs - Gbtc
// Copyright © 2026 The go2cs Authors. All rights reserved.
//
// SPDX-License-Identifier: BSD-3-Clause
// Use of this source code is governed by a BSD-style license
// that can be found in the LICENSE file.

using go;
using go.golib;

// The marker every hand-owned companion carries. This file ADDS a surface the converted package
// does not have; it displaces no Go function, so it carries no manualConversionFuncs registration.
[module: GoManualConversion]

namespace go.crypto.@internal.fips140.nistec;

// Hand-written companion for crypto/internal/fips140/nistec/fiat (R, COORD f6acfe252d).
//
// WHY THIS EXISTS. crypto/internal/fips140/nistec ships a PRECOMPUTED table of P-256 basepoint
// multiples as embedded bytes (p256PrecomputedEmbed), and those bytes are already in the MONTGOMERY
// domain -- Go's own comment says the table "aliases into p256PrecomputedEmbed", and on a
// little-endian host Go takes the view for free with `(*[43]p256AffineTable)(unsafe.Pointer(...))`.
// The port cannot take that view (see p256_impl.cs in the parent package for the measurement), so it
// must DECODE the bytes into real elements -- and to do that it needs to set a P256Element's limbs
// WITHOUT a domain conversion.
//
// ⚠ AND THE PACKAGE'S ONLY PUBLIC LOADER IS THE WRONG ONE. `SetBytes` converts INTO the Montgomery
// domain (`p256ToMontgomery`), which is correct for a caller holding a canonical big-endian integer
// and WRONG for these bytes, which are Montgomery-domain limbs already. Feeding them to SetBytes
// double-converts and yields points that are silently wrong -- a wrong answer rather than a crash,
// which is the worse failure. There is no other reachable path: the limb field `x` is internal to
// this package, so the decode cannot be written from nistec at all. Hence this one entry point.
//
// SCOPE. This is a SITE cure for that one table, not a general "load a field element" API. It does
// no reduction and no validation: the caller is asserting that the limbs are already a valid
// Montgomery-domain representative, which is true of a table generated by Go's own generator and is
// NOT true of arbitrary input. Nothing else in the corpus should call it; if a second caller ever
// appears, that is the moment to ask for a checked public API instead.

partial class fiat_package {

// SetMontgomeryLimbs sets e to the field element whose Montgomery-domain representation is the four
// little-endian limbs l0..l3, WITHOUT a domain conversion. See the file header: this is for
// already-Montgomery embedded table data only, never for caller-supplied integers (use SetBytes).
public static void SetMontgomeryLimbs(ref P256Element e, uint64 l0, uint64 l1, uint64 l2, uint64 l3) {
    e.x[0] = l0;
    e.x[1] = l1;
    e.x[2] = l2;
    e.x[3] = l3;
}

} // end fiat_package
