// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/aes", new string[]
        {
            "aes.go",
            "aes_test.go",
        });
        registry.Add("TestAESBlock", aes_internal_test_package.TestAESBlock, "aes_test.go", 101);
        registry.Add("TestCipherDecrypt", aes_internal_test_package.TestCipherDecrypt, "aes_test.go", 78);
        registry.Add("TestCipherEncrypt", aes_internal_test_package.TestCipherEncrypt, "aes_test.go", 55);
        return TestHost.Run(registry, args);
    }
}
