// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/sha512", new string[]
        {
            "fallback_test.go",
            "sha512.go",
            "sha512_test.go",
            "sha512block.go",
            "sha512block_amd64.go",
            "sha512block_arm64.go",
            "sha512block_decl.go",
            "sha512block_generic.go",
            "sha512block_s390x.go",
        });
        registry.Add("TestAllocations", sha512_package.TestAllocations, "sha512_test.go", 896);
        registry.Add("TestBlockGeneric", sha512_package.TestBlockGeneric, "sha512_test.go", 826);
        registry.Add("TestBlockSize", sha512_package.TestBlockSize, "sha512_test.go", 818);
        registry.Add("TestGolden", sha512_package.TestGolden, "sha512_test.go", 682);
        registry.Add("TestGoldenMarshal", sha512_package.TestGoldenMarshal, "sha512_test.go", 722);
        registry.Add("TestLargeHashes", sha512_package.TestLargeHashes, "sha512_test.go", 875);
        registry.Add("TestMarshalMismatch", sha512_package.TestMarshalMismatch, "sha512_test.go", 769);
        registry.Add("TestSHA512Hash", sha512_package.TestSHA512Hash, "sha512_test.go", 913);
        registry.Add("TestSize", sha512_package.TestSize, "sha512_test.go", 799);
        return TestHost.Run(registry, args);
    }
}
