// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/internal/edwards25519", new string[]
        {
            "doc.go",
            "edwards25519.go",
            "edwards25519_test.go",
            "scalar.go",
            "scalar_alias_test.go",
            "scalar_fiat.go",
            "scalar_test.go",
            "scalarmult.go",
            "scalarmult_test.go",
            "tables.go",
            "tables_test.go",
        }, new string[]
        {
            "field",
        });
        registry.Add("TestAddSubNegOnBasePoint", edwards25519_internal_test_package.TestAddSubNegOnBasePoint, "edwards25519_test.go", 63);
        registry.Add("TestAffineLookupTable", edwards25519_internal_test_package.TestAffineLookupTable, "tables_test.go", 36);
        registry.Add("TestAllocations", edwards25519_internal_test_package.TestAllocations, "edwards25519_test.go", 282);
        registry.Add("TestBaseMultVsDalek", edwards25519_internal_test_package.TestBaseMultVsDalek, "scalarmult_test.go", 45);
        registry.Add("TestBasepointNafTableGeneration", edwards25519_internal_test_package.TestBasepointNafTableGeneration, "scalarmult_test.go", 153);
        registry.Add("TestBasepointTableGeneration", edwards25519_internal_test_package.TestBasepointTableGeneration, "scalarmult_test.go", 109);
        registry.Add("TestComparable", edwards25519_internal_test_package.TestComparable, "edwards25519_test.go", 90);
        registry.Add("TestGenerator", edwards25519_internal_test_package.TestGenerator, "edwards25519_test.go", 45);
        registry.Add("TestInvalidEncodings", edwards25519_internal_test_package.TestInvalidEncodings, "edwards25519_test.go", 96);
        registry.Add("TestNafLookupTable5", edwards25519_internal_test_package.TestNafLookupTable5, "tables_test.go", 61);
        registry.Add("TestNafLookupTable8", edwards25519_internal_test_package.TestNafLookupTable8, "tables_test.go", 91);
        registry.Add("TestNonCanonicalPoints", edwards25519_internal_test_package.TestNonCanonicalPoints, "edwards25519_test.go", 110);
        registry.Add("TestProjLookupTable", edwards25519_internal_test_package.TestProjLookupTable, "tables_test.go", 11);
        registry.Add("TestScalarAddLikeSubNeg", edwards25519_internal_test_package.TestScalarAddLikeSubNeg, "scalar_test.go", 189);
        registry.Add("TestScalarAliasing", edwards25519_internal_test_package.TestScalarAliasing, "scalar_alias_test.go", 12);
        registry.Add("TestScalarEqual", edwards25519_internal_test_package.TestScalarEqual, "scalar_test.go", 248);
        registry.Add("TestScalarGenerate", edwards25519_internal_test_package.TestScalarGenerate, "scalar_test.go", 66);
        registry.Add("TestScalarMultDistributesOverAdd", edwards25519_internal_test_package.TestScalarMultDistributesOverAdd, "scalarmult_test.go", 69);
        registry.Add("TestScalarMultMatchesBaseMult", edwards25519_internal_test_package.TestScalarMultMatchesBaseMult, "scalarmult_test.go", 139);
        registry.Add("TestScalarMultNonIdentityPoint", edwards25519_internal_test_package.TestScalarMultNonIdentityPoint, "scalarmult_test.go", 87);
        registry.Add("TestScalarMultSmallScalars", edwards25519_internal_test_package.TestScalarMultSmallScalars, "scalarmult_test.go", 19);
        registry.Add("TestScalarMultVsDalek", edwards25519_internal_test_package.TestScalarMultVsDalek, "scalarmult_test.go", 36);
        registry.Add("TestScalarMultiplyDistributesOverAdd", edwards25519_internal_test_package.TestScalarMultiplyDistributesOverAdd, "scalar_test.go", 165);
        registry.Add("TestScalarNonAdjacentForm", edwards25519_internal_test_package.TestScalarNonAdjacentForm, "scalar_test.go", 208);
        registry.Add("TestScalarSetBytesWithClamping", edwards25519_internal_test_package.TestScalarSetBytesWithClamping, "scalar_test.go", 129);
        registry.Add("TestScalarSetCanonicalBytes", edwards25519_internal_test_package.TestScalarSetCanonicalBytes, "scalar_test.go", 75);
        registry.Add("TestScalarSetUniformBytes", edwards25519_internal_test_package.TestScalarSetUniformBytes, "scalar_test.go", 111);
        registry.Add("TestVarTimeDoubleBaseMultMatchesBaseMult", edwards25519_internal_test_package.TestVarTimeDoubleBaseMultMatchesBaseMult, "scalarmult_test.go", 162);
        registry.Add("TestVarTimeDoubleBaseMultVsDalek", edwards25519_internal_test_package.TestVarTimeDoubleBaseMultVsDalek, "scalarmult_test.go", 54);
        return TestHost.Run(registry, args);
    }
}
