// go2cs code converter defines `global using` statements here for imported type
// aliases as package references are encountered via `import' statements. Exported
// type aliases that need a `global using` declaration will be loaded from the
// referenced package by parsing its 'package_info.cs' source file and reading its
// defined `GoTypeAlias` attributes.

// Package name separator "dot" used in imported type aliases is extended Unicode
// character '\uA4F8' which is a valid character in a C# identifier name. This is
// used to simulate Go's package level type aliases since C# does not yet support
// importing type aliases at a namespace level.

// <ImportedTypeAliases>
global using abiꓸArrayType = go.@internal.abi_package.ΔArrayType;
global using abiꓸChanDir = go.@internal.abi_package.ΔChanDir;
global using abiꓸFuncType = go.@internal.abi_package.ΔFuncType;
global using abiꓸInterfaceType = go.@internal.abi_package.ΔInterfaceType;
global using abiꓸKind = go.@internal.abi_package.ΔKind;
global using abiꓸMapType = go.@internal.abi_package.ΔMapType;
global using abiꓸName = go.@internal.abi_package.ΔName;
global using abiꓸStructType = go.@internal.abi_package.ΔStructType;
using abi = go.@internal.abi_package;
// </ImportedTypeAliases>

using go;
using static go.runtime_package;

// For encountered type alias declarations, e.g., `type Table = map[string]int`,
// go2cs code converter will generate a `global using` statement for the alias in
// the converted source, e.g.: `global using Table = go.map<go.@string, nint>;`.
// Although scope of `global using` is available to all files in the project, all
// converted Go code for the project targets the same package, so `global using`
// statements will effectively have package level scope.

// Additionally, `GoTypeAlias` attributes will be generated here for exported type
// aliases. This allows the type alias to be imported and used from other packages
// when referenced.

// <ExportedTypeAliases>
[assembly: GoTypeAlias("Error", "ΔError")]
// </ExportedTypeAliases>

// As types are cast to interfaces in Go source code, the go2cs code converter
// will generate an assembly level `GoImplement` attribute for each unique cast.
// This allows the interface to be implemented in the C# source code using source
// code generation (see go2cs-gen). Resolving each duck-typed cast at compile time
// this way is what keeps startup free of reflection.

// <InterfaceImplementations>
[assembly: GoImplement<PanicNilError, ΔError>(Pointer = true)]
[assembly: GoImplement<TypeAssertionError, ΔError>(Pointer = true)]
[assembly: GoImplement<boundsError, ΔError>]
[assembly: GoImplement<errorAddressString, ΔError>]
[assembly: GoImplement<errorString, ΔError>]
[assembly: GoImplement<plainError, ΔError>]
// </InterfaceImplementations>

// <ImplicitConversions>
[assembly: GoImplicitConv<_type, ж<_type>>(Indirect = true)]
[assembly: GoImplicitConv<abi.RegArgs, ж<abi.RegArgs>>(Indirect = true)]
[assembly: GoImplicitConv<abi.Type, ж<abi.Type>>(Indirect = true)]
[assembly: GoImplicitConv<abiꓸMapType, ж<maptype>>(Indirect = true)]
[assembly: GoImplicitConv<adjustinfo, ж<adjustinfo>>(Indirect = true)]
[assembly: GoImplicitConv<bmap, ж<bmap>>(Indirect = true)]
[assembly: GoImplicitConv<childInfo, ж<childInfo>>(Indirect = true)]
[assembly: GoImplicitConv<elfEhdr, ж<elfEhdr>>(Indirect = true)]
[assembly: GoImplicitConv<funcval, ж<funcval>>(Indirect = true)]
[assembly: GoImplicitConv<g, ж<g>>(Indirect = true)]
[assembly: GoImplicitConv<g, ж<g>>]
[assembly: GoImplicitConv<gQueue, ж<gQueue>>(Indirect = true)]
[assembly: GoImplicitConv<gcWork, ж<gcWork>>(Indirect = true)]
[assembly: GoImplicitConv<gsignalStack, ж<gsignalStack>>(Indirect = true)]
[assembly: GoImplicitConv<hiter, ж<hiter>>(Indirect = true)]
[assembly: GoImplicitConv<hmap, ж<hmap>>(Indirect = true)]
[assembly: GoImplicitConv<itab, ж<itab>>(Indirect = true)]
[assembly: GoImplicitConv<lfstack, Δhex>(Inverted = true, ValueType = "uint64")]
[assembly: GoImplicitConv<limiterEventStamp, limiterEventType>(Inverted = true, ValueType = "uint64")]
[assembly: GoImplicitConv<m, ж<m>>(Indirect = true)]
[assembly: GoImplicitConv<metricValue, ж<metricValue>>(Indirect = true)]
[assembly: GoImplicitConv<mspan, ж<mspan>>(Indirect = true)]
[assembly: GoImplicitConv<pollDesc, ж<pollDesc>>(Indirect = true)]
[assembly: GoImplicitConv<ptrtype, ж<ptrtype>>(Indirect = true)]
[assembly: GoImplicitConv<sigctxt, ж<sigctxt>>(Indirect = true)]
[assembly: GoImplicitConv<spanClass, traceArg>(Inverted = true, ValueType = "uint8")]
[assembly: GoImplicitConv<stackScanState, ж<stackScanState>>(Indirect = true)]
[assembly: GoImplicitConv<stkframe, ж<stkframe>>]
[assembly: GoImplicitConv<sudog, ж<sudog>>(Indirect = true)]
[assembly: GoImplicitConv<sweepClass, spanClass>(Inverted = true, ValueType = "uint32")]
[assembly: GoImplicitConv<traceGoStatus, traceArg>(Inverted = true, ValueType = "uint8")]
[assembly: GoImplicitConv<traceProcStatus, traceArg>(Inverted = true, ValueType = "uint8")]
[assembly: GoImplicitConv<vdsoVersionKey, ж<vdsoVersionKey>>(Indirect = true)]
[assembly: GoImplicitConv<Δp, ж<Δp>>(Indirect = true)]
[assembly: GoImplicitConv<Δsliceᴛ, ж<Δsliceᴛ>>(Indirect = true)]
// </ImplicitConversions>

// Go source positions are recorded here, one `GoPositionMap` attribute per converted
// source file in this compilation, so that `runtime.Caller` and the tracebacks built on it
// can name the GO file and line a frame was converted from rather than the emitted C# one.
// Each record carries the Go file's identity and an encoded C#-line to Go-line table
// TOGETHER: a frame either has a record and reports a position that exists in the Go tree,
// or has none - golib, the BCL and hand-written conversions - and reports its own C# position.

// <GoSourcePositionMaps>
[assembly: go.GoPositionMap("runtime/alg.go", "alg.cs", "ABYmgqaCpoKmgqiSgoIACDoAFhgACxgACyAADwSCggACEMKClKSkyIKClKSkyIKCpoKCpoKCgoKUgsqUgpQAAxwACgKCgoKUlJSClAADMgAXApSUpKS2lKSkpKSkgoKUpIKClKSCgoKUlKjIwoKUpqKClJSkgoKCgoKCgpSUgoKUgpaCloKUtoKCgIK2pIKCgpSAgramyrKmgqSCpIKkgqSCpIKkgqSCpIKkgqSCpIKCgqSCgoKkooKUgoKUuJSkooKUgoKClJSUAAIcAA0CpqKCpqKmoqai5qYACxaUuIKUgoKUgriClIKCupKCgpSmgoKClg==")]
[assembly: go.GoPositionMap("runtime/arena.go", "arena.cs", "AGTMAQAIAgAFEgAIAoKClIKCgoKCgqyyrLKu4oKCgpSkpKSkgpSWkpSCgoKkgoKCgoKCpIKCgoKCpAAHJIKClIKUgoKmgqaq6gAaPpKCuJSCAAIQ0gACFAAJAoKUgoKClIKClJYABRIACQSCqIK6goKCgoKCgpSmzIKCppSCgriCrsKCgoKCgpSU6rSCgsqUgoKClJaClIKCgoKClIKUgoKmgoIAHzjSgoKUlJSClKaClMyCgpSClISClIKCpoKCppSCgpSCpoKClJSCgpSClAAIFISChNyygoKUggADEOKChIKClIKUhIKCggAHEAAHEIKElLqGkoIAChaiupaWgoSqwpSCgrqCgpaCgoLegoKokoKUgoKClKrCupaCgoKUgqiCloKCgpSCqN6UgoKCpIKUgpS8ooKClJT8soIABxKWgoKUgpSGkoKUgpTMgpaUlpSWlIKCgoKCgpaAgoKCpoKUtoKWgIKmgpQABhCClgACGgAKAgAGEPKClIIADR66uszMgoKCgoKWloKWlIKCupKCgpQABhQACQKClIK6gpSClILMloKCgoKEgoKogqaCgpQABRgACwKCloKCgoKmgriUgoKU3IKCgpSUgpSClJQABhCCloKCgoKCAAcSloKEgoKWgoKWlqgACRaChJaoqIKCgoQ=")]
[assembly: go.GoPositionMap("runtime/asan0.go", "asan0.cs", "ABAmkKKAooCigKKA")]
[assembly: go.GoPositionMap("runtime/atomic_pointer.go", "atomic_pointer.cs", "AA1AABUCgoKCrLKClIKUAAIQ0gACENKClIKUAAIQ6KKClIKUqKiigpSClIKoqKKClIKU")]
[assembly: go.GoPositionMap("runtime/cgo.go", "cgo.cs", "AEGSAfAACxaCgoKU")]
[assembly: go.GoPositionMap("runtime/cgo_mmap.go", "cgo_mmap.cs", "ABc+4ozSgpSClJSmgoKAkpSoqLao")]
[assembly: go.GoPositionMap("runtime/cgo_sigaction.go", "cgo_sigaction.cs", "ABEqAAsOgpSClIIABhCEgoKUgpbKAAYUAAgCyIK4qIKUggADEA==")]
[assembly: go.GoPositionMap("runtime/cgocall.go", "cgocall.cs", "AGjcAfKSggAJKgAQAoKWgpaCloKWAA4g3oTuhKiChKiEhKiCAAsagoKEAAIS4oS4loLKABMsgoKCjNIACBKCgoKmgtyygoKCloKCgt6EqAAJFoKCgoKCgpaEgpa6goSmloKWloSWgoKCpqKEgoKWggAGEIKCgoSUgqjKuoKCqJKEgpqikoKEgrrWgqaCgt6CgoIABxKE6pLYkgAISgAfAoKWgoSCgoKClIKUgqSUlIKCtoKqgoKk+AAGFvKUlpiCgoKUgpSCgrykspSClKSCgpqylIKClIKUpIKCgoKUgpSClIKCtoKClIK2goKClIKUgoKUtoKCgqiClIKWAALJAQAE2gHygoKCgpSCgoKAgqSCgqaWgqbMAAIS4oKWgpaCgqiuwqzSgpaCgg==")]
[assembly: go.GoPositionMap("runtime/cgocallback.go", "cgocallback.cs", "AAcWog==")]
[assembly: go.GoPositionMap("runtime/cgocheck.go", "cgocheck.cs", "ABA0AAoCuJSClIK6goK6grqCzIKWgoIAAxgACgIAAhYACgKClIKUgpQAAhYACgKClIKUgpSCgoIAAxQACQSClICCpoKCqIKCgoKUgoKCqIIABxCClKiCgoKAgqSCggAEFuKCgoKCgoKCgoKClJSClIKCggAGHgAKAoKogpSAgqaCgpSYgoKClIKCgpSCgoKUtoKCgpSCgoKUgoKClAADRQ==")]
[assembly: go.GoPositionMap("runtime/chan.go", "chan.cs", "ADh6ktaCgpbmgpaClIKWgoKewpaUuLK2gsaCgoKEgpQAAhwADQKu5pSmrLIACB6ygoKUgpaCloIAESaCloKCloSCgpaApoCSppSCgpSCgoKUgoKWgoKogoKCgriCgoKCgoKCyoLKloKUgoKCgoKUgoKCgpSUAAISAAkCgoLKgoKCgpSmgoKUgoKCgoKUAAIQAAwMgpSCgoKCgoKClJSCAAIaAA8Mgqam2IKC5qKCloKCgpaCgoKWhJaCgoKUgoKUgpSCgoKClKiCgoKUgoKUgoKCgpSUloKCggADEPSCuIKUrLKosoIAAhIADAiCloKClIKWgqgACRTKypSClIKUqIKCloSCgoKUgoKUyoDKgJK4lIKClIKUgoKClIKCloKCqIKCgoK4goKEgoKCgoKC3oKWgpSClIKCgpSCgoKCAAIiABECgoKUlO6CgoKmgqaCgoKUlIKCgoKCgpSm/LjcggACJgAQAgACJgAQAqiSqJKmooKUgoKUuJSmooKUgoKCypSokqiSqJKokqaigoKCgoKClIKCpoKCgoKUgoKClIKCAAkWgpa43KaCgoKCrAANEO6CgoKUgqaClA==")]
[assembly: go.GoPositionMap("runtime/checkptr.go", "checkptr.cs", "AA4StILegrqCvKKCuoKUquaCgsyCgpaCgqgAAigAEgSAAAgSuICCuIKClIKo")]
[assembly: go.GoPositionMap("runtime/complex.go", "complex.cs", "AAcSooKClKaCuIKCgoKUgoKClqiChJSCtoKCgraCgoLI")]
[assembly: go.GoPositionMap("runtime/coro.go", "coro.cs", "ACJO0oKCgpKSgpKCqIKCgqaCgqzSgoKEgtqigoKCrsKCggAHHgAOAoKCgoIABhCCgoKCgoIACBSEppbcgriCpqiaogAKFoKClIKCgoIABhCCzILMggAHEoKWpoKogoKogqg=")]
[assembly: go.GoPositionMap("runtime/covercounter.go", "covercounter.cs", "AAsakoKCgoKUyg==")]
[assembly: go.GoPositionMap("runtime/covermeta.go", "covermeta.cs", "AA4cwoKClA==")]
[assembly: go.GoPositionMap("runtime/cpuflags_amd64.go", "cpuflags_amd64.cs", "AAwalISM")]
[assembly: go.GoPositionMap("runtime/cpuprof.go", "cpuprof.cs", "ADGIAQAIBIKUgpaCgoKCgpaCgoKCpIKCgpQAAhQACASUlpKClMqWAAIaABAOlJaCgoKClJYAAhDkgoKClJaCgriCloKCuIIAAxwACQIAAhoACgIAAigAEQKCgoKCgpSCgoKClA==")]
[assembly: go.GoPositionMap("runtime/cputicks.go", "cputicks.cs", "AAgW")]
[assembly: go.GoPositionMap("runtime/create_file_unix.go", "create_file_unix.cs", "AAoYkg==")]
[assembly: go.GoPositionMap("runtime/debug.go", "debug.cs", "AA1UAAgCAAYwkqiSAAIwABYEgoKmggADFgAIBIKCpoIABhrigoKUlA==")]
[assembly: go.GoPositionMap("runtime/debugcall.go", "debugcall.cs", "ABQwks7kgpSAyqqigoKCgpaEAAEeAAkQgIKCuIKUgpSmAAUYAAkCgoIABhCoyJKCuKiCgtyChIKCzKiolIKWgriUgoKUzLyCgoKWhAAHFKKCgoKWloKCgqiCgsyCuJSCgpSCgoKEgoKCgpS4pJKShIKCgoKmgg==")]
[assembly: go.GoPositionMap("runtime/debuglog.go", "debuglog.cs", "ACVmABECgqiWqIKCgoKCgsymgoKUgpaCgoKCggADELKCqIKWgoKCgpSWABkysoKogoKoloKoAA8osoKUgpSUqJKokqiSqJKosoKUgoKokqiSqJKokqiSqLKClIKCqLKClIKC2MKClIKClIKUpLaosoKWgoK4goKUhqKCgoKClIKCgoKmqLKClIKCqLKClIKCgpQAKmSSlO7MkoKCqJKCgoKCgoKokoKCgoKCgoKCgqiSgoKCqJKCgoKCgoK6koKClJSokoKCgoKUgoIACx6kgpSClIKClIKUgqiSqpKCgoKUrJSCgoKUgoKUgqaCgqiClIKCgoKCgoKmgpSm9oKCloKChKaCgoKCgoKCpqaCgoKClJSmgoKEnKampqamtoKCgoKUgoKClIKCyJKG6IKmpqaCgsoAA3+CAAKGAQAPCJKCvJaCloKClIKCmAABEIKCgoKUgoKCgoKCgoKCuoSYgoKCgqaCqIKCgoKUgpaCgoSCgoKUlIKChIKClJSCgqaWgoKWqqKCppaCgpSCgg==")]
[assembly: go.GoPositionMap("runtime/debuglog_off.go", "debuglog_off.cs", "AA0agqaC")]
[assembly: go.GoPositionMap("runtime/defs_linux_amd64.go", "defs_linux_amd64.cs", "AFbOAZKCAAcQgg==")]
[assembly: go.GoPositionMap("runtime/env_posix.go", "env_posix.cs", "AAwSgoKClIKCpqqikoKCgpSUlKaCgpQAGDSSgpSSqJKClJKmgoKC")]
[assembly: go.GoPositionMap("runtime/error.go", "error.cs", "ACU+1IKCgpSCgpSCgoKUgpSmlAACEtKCgoKClILMpIIABxCkggACENIABBCkggA3eKSCgoKUgoKmgoKCuIKCgoKCgpSClLTGAAYeAAgClLS0tLS0tLS0tLS0tLS0tLS0xMqygoSUgoKkpKSkpKSkpKSkpKSkpKSkpMqSgoKClIKCgpSuwoK4goKUgoKUgoKClIKUgoI=")]
[assembly: go.GoPositionMap("runtime/extern.go", "extern.cs", "AA3aBAALAoKCgpSCAAw+soKClAAMILI=")]
[assembly: go.GoPositionMap("runtime/fastlog2.go", "fastlog2.cs", "AAcc8oKEpoKChII=")]
[assembly: go.GoPositionMap("runtime/fds_unix.go", "fds_unix.cs", "AAsSgriWAAIQgoKCgpaCgpaAgoKkgg==")]
[assembly: go.GoPositionMap("runtime/float.go", "float.cs", "AAsYpKiSqJIAAhLigqqigqiyqsI=")]
[assembly: go.GoPositionMap("runtime/hash64.go", "hash64.cs", "ABAqgpKClKSCgrSCtIK0grSCtIKCgoKCgoKClJSCgpSCtqaCgqaCgqaCgqaCpoI=")]
[assembly: go.GoPositionMap("runtime/heapdump.go", "heapdump.cs", "ABEqkgAAEOK4gpYAJk6CgpSCgoKWgoKClIK4oqaCggATKpKCgoKCgpSCgqaCgpS6koKmgoKCuIKosoK6goKUgpSClILMgpSWgoKCgoCClIKCgoKCpKiSgoKCpoKCgqaigoKCgoIADByygoKC+rKWgoKCgpS4lISCgpSogoKCgoKCgoKCgpSWgqaCgrqUgoLIgoKC2pSWgoKCgoKClJSmoqKCgoKUgoKWgoKCgoKCgoKCgoKCgoaSgoKCgoKCqIKCgoKCgoKClJSUlIKCgoKCgoKC6IKWgoIAAxKtggAFFrKCgoKCgqaUqIKCgpaCgoKWgpSCgpSCgswACQ6UhIKClIKCgoKWgoKogoKClMqCgpKClJSCkoKClIKClIKClIK4goKCgqaigoKCgqaCpoKCgoKCupK6goKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKUpoKCgoKCgoKCgoKCgoKCgoKUgoKCpoKCgoKCgoKClIKClIKCpoKmlISCgoKUgoKUgoKCgv6CloKCpoKCgoKCgoKCgoKCpoKEgpaWloKCgpaosoLWlIKCgpSCgoKUpoKCgoKCgIKkgpQ=")]
[assembly: go.GoPositionMap("runtime/histogram.go", "histogram.cs", "ACvSAQAJBIKCAAESAAgCgIKClILIgoKmgqjCuIKClAAFEIKSpoKSrLKUhKamuIKUlMqmuIKC")]
[assembly: go.GoPositionMap("runtime/iface.go", "iface.cs", "ACE8lAAFGAAMAoKogoKUgpbMgoCCuIKAgoK4goLcgoKCgoKClIIABxCq+IKCgriCgpSClILsAAgKgpaC2oLMgoKmlKaq9oKCgoKCypTKgoKUggADFAAIAoKCzIKCgoKCgoKCgoKCgoKClIKCgoKCgoKUgoKCpJTctIKUpoKCgoKCpq7CqsKCgpSqogAfVgALAoKUgpSClIKCpLSClIKUgpaCgqaigoKCpoKUpqKCgoKmgpQAAhgACwKClIKUAAIYAAsCgpSClAACGAANBIKUgpSmgpSUpoKClKzigoKCppaCupSmhKaouoSmopaCgoLegpaCgoKWkoKCgoKClKaCgqaEAAYYAAgCloKWgoKCgqiCurimhLiouoSs0paCgoLegpaCgoKWkoKCgoKCgpSmgoKmhAAGIgAKAqiSpqaCgoKCACxYsg==")]
[assembly: go.GoPositionMap("runtime/lfstack.go", "lfstack.cs", "ABEwooKCgIKCpIKCgoLKgoKCgpSCgoLKguqigIKkgoKCuIKmgg==")]
[assembly: go.GoPositionMap("runtime/lock_futex.go", "lock_futex.cs", "AB1WAAgCzoIABIgBAA0CAAQw0gALpgGigoKWAAQigqY=")]
[assembly: go.GoPositionMap("runtime/lockrank.go", "lockrank.cs", "AMsBqgKCgpSClIKU")]
[assembly: go.GoPositionMap("runtime/lockrank_off.go", "lockrank_off.cs", "AA8gpoKmgqyypoKssqzYuLi4uLg=")]
[assembly: go.GoPositionMap("runtime/malloc.go", "malloc.cs", "AL8B6gWCgpamqJSUgoKUgoKUgoKUgoKUypSmgqaCgpSCgsqCgoKCpoK4gpaCqIKCgoKCgoKUlgApVIKCmoKyxrS0ppS06oKClIKCABIogoKCAAgUAAcSgoKUgpSmyoKCgoKCpoKCzIKCuAAOJgAVAoSE3IKCgrqCgoKClJS2lJSUgpSCggAHEIKUgpaCysyCgqiCgoKCgqiCgoKCpKSUpoKogpaEkoIACBKCgpSClJSWgpSCgoKCgrqCgoKClIKClIKC3ILeyIKW3OiCgoKUpKzCgoKUgoCCpJamooKCgoKUAAQiABAEzIKCgpSCqIKCgpQABxLCgoKCgoKClIKCgqYABxgADQKCgoKUgoKUgoKEloKWgoKCgpQABSoAFAKCloK6hILKloKCggAHEIKkpJSmlpTMloKClIKUhIKCgoKUgoKCpgAJFIIAHTyUggAIEKSklJSCgoKCgqaCgoKUgoKmlIKUlIKClIKClJSCgoKCgpSCgpSCgoK4poKCgoKCgpSUgqaCAAcSAAkUzIKWgpaCltyCgt6CgMqClLaCzJSWgoKWgqiClJaCgoKCutyWgoCCuAAMGpYAAhLigpSCgriEuKYAAhYACAKEkoKClKaCgpS+0gACHgAOAqiyAAIgAA8CgpSCgpQAAiQADwLWgoKClIIAAhTyypSUgIK4qsaUtAACFgAIAoKCgpSCqrSCkpSClAAZPgAJAoKClAAIDsKIgpSCgpSCppaCloKCgpSClIKCgoKClKiCgoKCppSCgoKCloKClAACENKCgoKUlAAOIILKlIKCpoKCgpSCgIKUgoKUpAAOGqKqopSkpKSkpKSk")]
[assembly: go.GoPositionMap("runtime/map.go", "map.cs", "AE/QAZIARJABpKiSqJKCgpSmgoKmsqaypqIAAhQACgiCgsqmgriigqaClMqCppSCgoKUgqaCgpSCuIKClAACIAANAoKCAAImABMCgoKogpSogoKUuoKCgoKCqAACEgAKAoKmuIKCgoKogsqCgoKUqNyCgpQABRAACAKCgoKClIKUgpSCgIKklIKUgoKCgIKUlIKCtoKCgoKCgpSUgoKUgoKClNgAAhgADAKCgoKClIKUgpSCgIKklIKUgoKCgIKUlIKCtoKCgoKCgpSUgoKUgoKClNiowoKUgoKCgIKUlIKCtoKCgoKCgpSUgoKUgoKClNimgoKClKaCgoKUAAYkABICgpSCgoKClIKUgpSClKiEgpaCgoKUgoSCgoKCgoKCgoKClIKUlIKClIKmgpSClIKClO6CgpaUgoKCqIKCgpSCgpSCgoSCgpSCgpQAAhgADAKCgoKClIKUgpSCgIKklIKWqISCgpSCgoKCgoKCgpSUgoKClIKmgqSUgoKklJTKgoKmgqaCgoKCpoKUlJSCpoKmgpTIgpQABS4AGAKCgpaCgpaClJaCgsqCgqiCgpaogIKmAAUiABACgoKClIKUgoKCgoSCgpSCgpTKgoKClIKmgpSCgoKUlIKCppSCgpSCAAcQpoKCAAkUgrjMgoKUAAgSgoKUgpSCkpSCgpSCggACHgAOAoKCgpaCloKWloKCgoKCyoKAgqaCgoKCqJaCzIKmloKU1riCgoKUgoSCgqaCgoKCgoSUgpSClIKClAADEMKs+oKmqJKokqiyqJKCgpSokqbGloK4goIADhaygoKqkoKCgoSmgoKCloKCgoKCgoKUgpSCgpSCpoIACxiClIK6gpaChIKCgoKUgoKUlIKUlMqCuIKmgoKogriCpoKClIKUpLiClAAPKAATBIKUhJSElIKUgpSClIKUgpSClIKWAAIcAAsCgpSUqJKClJQAAhgACwKCqLKCqJKokgACHgAMAgACIAANAgACGgAKAgACGgAKAgACGgAMAoKUgoKUqJKosoKUgoKUAAIQ6tKCgqrygoKWgoKogoKWgoKChIKCgoKCgsqUlIKCgoKUlIKU1rKC3JSCgpaCloKWlIKCgpaClIKCgoKCgoKCgrqCloKCgpSEgoKClpKCgpSCgoKUupSCgpaCloKCloKClIKUpqzSgoKEgpSCgoKCgpSCgoKCgpaCgoKCgoKUpqaygoKCgpSClIKClIKUgpS+0oKCgoKUgoKCgoKUgoKCgoKWgoKCgoKClKamsoKCgoKWgpaCgpSClIKU")]
[assembly: go.GoPositionMap("runtime/map_fast32.go", "map_fast32.cs", "AAwawoKClIKUgpSClJSCgoKAgpSUgoLIgoKCuAACGAANAoKClIKUgpSClJSCgoKAgpSUgoLIgoKCuAACHAAPAoKUgoKUgpSWhIKWgoKClISCgoSCgoKCgoKUgpSUgoKUgoKUgoKU7oKClpSClISUhISCgoKUggACGAANAoKUgoKUgpSWhIKWgoKClISCgoSCgoKCgoKUgpSUgoKUgoKUgoKU7oKClpSClISUhISCgoKUgqbCgoKUgpSClpaEgoKUgoKCgoKCyqaUgoKUlKaCgqaCpoKCgoKmgpSUlIKmgqaClMiClKbGloK4soKCqpKCgoKEpoKCgpaCgoKCgoKClIKUgqaCgqiChIKCgoKUlpSUloLKgriCpoKCqII=")]
[assembly: go.GoPositionMap("runtime/map_fast64.go", "map_fast64.cs", "AAwawoKClIKUgpSClJSCgoKAgpSUgoLIgoKCuAACGAANAoKClIKUgpSClJSCgoKAgpSUgoLIgoKCuAACHAAPAoKUgoKUgpSWhIKWgoKClISCgoSCgoKCgoKUgpSUgoKUgoKUgoKU7oKClpSClISUhISCgoKUggACHAAPAoKUgoKUgpSWhIKWgoKClISCgoSCgoKCgoKUgpSUgoKUgoKUgoKU7oKClpSClISUhISCgoKUgqbCgoKUgpSClpaEgoKUgoKCgoKCpoKCuKaCgpSUpoKCpoKmgoKCgqaClJSUgqaCpoKUyIKUpsaWgriygoKqkoKCgoSmgoKCloKCgoKCgoKUgpSCpoKCqIKEgoKCgpSWgpS4ppaCyoK4gqaCgqiC")]
[assembly: go.GoPositionMap("runtime/map_faststr.go", "map_faststr.cs", "AAwawoKClIKUgpSClIKUgoKCgpSUgqamgoKCgoKUlIKmgqaClJSUlIKCgqaUgoKCgoCClJSCgraCgoKCgpSCuAACGAANAoKClIKUgpSClIKUgoKCgpSUgqamgoKCgoKUlIKmgqaClJSUlIKCgqaUgoKCgoCClJSCgraCgoKCgpSCuAACHAAPAoKUgoKUgpSCloSCloKCgpSChIKChIKCgoKCgpSClJSCgpSCpoKmgpSCgpTugoKWlIKUhJSChIKCgpSCpsKCgpSClIKWgpaEgoKUgoKCgoKCgoKUgqaCgoKUlKaCgqaCpoKCgoKmgpSUlIKmgqaClMiClKbGloK4soKCqpKCgoKEpoKCgpaCgoKCgoKClIKUgqaCgqiChIKCgoKUloSCyoK4gqaCgqiC")]
[assembly: go.GoPositionMap("runtime/mbarrier.go", "mbarrier.cs", "ABXEAgCNAQKClLgACBKCggADFAALCAACEgAMCgACIAAPAoKClIKClIKClKiSAAIaAA0CuJSWgoIABB4ADAKCgpSC3oKCgoKUgoKUgoKWgpaC3oK4griCAAIgAA8CgpQAAhwADQK4lAACGAAJAqiyypSosoKmlAACJAAQBII=")]
[assembly: go.GoPositionMap("runtime/mbitmap.go", "mbitmap.cs", "AEXgAQAKBgAYTgALAoKCgpQABRYACAKCgoKWgoKUlJiSlIKUgpSmggAFGgAMAoKClIKmggACLgAVBIKWkoKUppQAAhYACAKCgqiCqIKClKiCqIKCggAEGAAIBIKClKaUgoKUuqaCgpSWpoKCloLKgpSCgpQAAhDSAAVaACwCgpSClIKmgoKCpoKCgqYACBCUhpKCloKClJSCgoKAgqSCgqaCgoCCpIKCgoIABCYAEAKClIKUgoaSgpaCgpSUgoKAgqSCggADEtKCggAHJAAOAoSCgpSC3JSUrLKCgoKCAAIS4oKCAAgUgoKCgoSClIKCgqaUAAUUAAsEloKCgpSkgoLcgoKCgpSCgoKmloKCgoKCgoKmAAYmABUChIKCgqaUuIKUgoKCgoKCgtyCgoKClqiCloK6goKUgoKCgpSCgoKmgoKUlNbEgoKClIKUgoKCgoKmgoKCgpSCgriCgoKClJSCgoKCgoKCgoCCgoKkgpTWooKCgpSCgpSCgoKCgqaCgoKCgpSCgriCgoKClJSCgoKCgoKCgIKCgqSCloKUgoKCgoKmgpSmhNjCgpS4lIKCgoKSgoKCgpSCpoKCgoKCgoKCkoKCgoKmuIKCgoKClKau+K74rvgAAhIACQgAESaSgq7CgoKCgoKCgoKCgt7CgoKClIKWhIKUgoKClJSCgriCgoKWgoTcgpSCAAIQ0oKUggAFFgAIApaEgoKUrLKmgoKCpoKCpoKokqjIqJKoyNiygoKUqJKCgpSUAAoQAAsSgoKCgoKUlJSCgoKUggACNgAcAqaCuJTcgJSCuIKUpoKCrOgABBoACgKCgoSCgoKClIKUlIKCgoKUgoKCpgAHKgATAoKUgoKUgoKUgpSCgoKCgoKUlIKCgoKCzqKCysqClKqigoKClJQADBaygoKCgoKUAAIkABEChpKEgoKmgoKCqIKCgpSUlIKCgoKCgpSAgoKCpKiCgoKCgoLMgoKCgoKCpgAHEoKClIKWgoKCgoLegoKo7oKClKaCgpSCgriCgoLegoKCgoKCgrqCgoKUzJSCgIKCgoLIgoKCgoKmgIKC6oKCgoKClAACEOSUgoKCpIKmooKCgoKCgpSCgoKCgpSClIKCgoKCgoK4goKCgoKCpoIABBbi/OKCgoSCgpSWlIKCgoKCgpSogoKCgoKClLqAgoKUuoKWgoKCgIKkzIKCzIKWlIKCgoKAgqQACxqCgoKCqIKCgpSCgoKUgoK6uoK4gIKCgoKCgqaCgoKUgoKCgoKm3A==")]
[assembly: go.GoPositionMap("runtime/mcache.go", "mcache.cs", "AD6SAbIACxaCgoKCgoKUgpSCAAISAAgCgoLOgoIAAxDUgoLKlJQABxDkhIKUlIKUloKCloKClJaClqiCgpaCupYADR6CgoSokoKUgoLMhIKCgqiCgoKWlqgABxKCgqaUgoSCgoKCgoKWgoKohNyogriCloKCgpbcAAwQgoKCpIKUgoI=")]
[assembly: go.GoPositionMap("runtime/mcentral.go", "mcentral.cs", "AC1gkoKCgoKqoqqiqqKqotikgoSCgoKCAA4ghIKWgoCCpoKUgoKClICUgoIACxaCgoKUgJSUgoKCgqbIlIKCgoKogoKogoKCgoKmgoKUgpSohN7igpaClu6mqAAHEIKUlLjMkoKCgpSC")]
[assembly: go.GoPositionMap("runtime/mcheckmark.go", "mcheckmark.cs", "ACZMspaCgoSUgoKUprjYkoKU/LKCgoKWloSCloKCgoKElJaC")]
[assembly: go.GoPositionMap("runtime/mem.go", "mem.cs", "AApiACgCgoIAAhDSggACGgAKAoKssqyyqqIAAiAADQKCggACGAAJAoIAAh4ADAKuwoI=")]
[assembly: go.GoPositionMap("runtime/mem_linux.go", "mem_linux.cs", "AA4qwoKCgoKUgoKUlAALDoK4loKClLSClILIopSCvOaCgoIACAqCgoKClIKUuIKUlISC+oKmlNaCppSCAA4ersKmgoKmgoKClNaCgoKUgoLegg==")]
[assembly: go.GoPositionMap("runtime/metrics.go", "metrics.cs", "ACl48oKWuIIACxiUhIKmgtyC3ILcgtyC3ILcgtyC3ILcgtyC3ILcgtyC3ILcgtyC3ILcgtyCpoLugtyC3IKmgu6C3ILcgsqCyoLcgtyC3ILKgtzKgtyCAAUQgtyC3ILcgtyC3ILcgtyC3ILcgtyC3ILcggAEEILKgsrKysrKyoK6goKopqKCyqKCqJKCgoKClIKCAAwqsoKClKjCgoKUqMKCgpSokoKCpqiSAB1KspaCgoKCgoKCgoKClIIAFzKygoKCgoKChIKCgoKCggAJFpIAESSSgoKCqqIADyTSgoKUgoKUlKSkpLYAGESygoKUgoKUgoKUABY0woKCgoSEgoKUhKyylpaCrtSSlpaCgpKCgriW")]
[assembly: go.GoPositionMap("runtime/mfixalloc.go", "mfixalloc.cs", "ADdwwoKUhIKCgoKCgoKCgtaCgoKWgoKCgoKUlIKCloKClIKCgqaCgoKC")]
[assembly: go.GoPositionMap("runtime/mgc.go", "mgc.cs", "AIwB2gIAEgLWgoKmuoSCgoKCgq7UgoKCgoIAKFCSggASZtaCgoKUgqYAjAHIAwAyApSCgpSUlIK6ggAXVrKClJSCpIKUgqa0AAUSAAoKgoCCgqSCAAoYupSCgt6CgqSogqiEgoKCqIKAgoK4hISCppSCgoSCgoKCqJaCuoSolrqCAA8ihILe3qjeloKCgpbegqiClgAdWgAXBoSO4oK6qJaCpt6UgoKo3IKo3oKCgoKC3gAJFoKCgoKCgriChIKUloKUgpaolqiogrqoupb6tISChIKCgrjeggAIFIKCgsqCgoKCgoKogpaChIKCgqiEgqioloKCgoKCgoKCggAIFIKozIKWhIKogoKCzJa6AAwcgoKklgAKFMyolgAMHIKCgoKCgqaU7syChIKCpoKCgpSClILulKSUlNyClIKogoKCgoKogoKogpaClpQAAxAACQyCAAgUgoKEgoKCAAcSqLwACxSCABckgrqCgoSEhAAQJKaChIAADyC4pgAGEoKEgoKWgpaCgoKCloKCgpYADhqCmILcgJKCgrrEpAACKQACLqiCgoKClIK6goKU3qi4goQABBDSgpSClIKU7LKClJaCgpamzAAGENymlJaCgoKCgpSUgpSUgtwABxKCgoKUqAAFFgAIAoSCloKCgoKCgoKEhKaCgpSCpqaCyoKCqIKCgpSCAAIaAAwGgoK6goKCgoKWggAJJgAKAqiSqKSCgoKCypSCqIKoggAMFIKSgoKUgqiGsoKClIKssoKCgoKCgoKUlIKokpSmgoKClIKCgpQAAhoACgKC6gAICoLeloKCgoKCgoKUlJaWloKCgoKUgpSCgpYACRYACAKCgoKUgIKkgoKUgqaC")]
[assembly: go.GoPositionMap("runtime/mgclimit.go", "mgclimit.cs", "AE+0AcIABhIACAKmlIKmgoIABRQACgKC3ICCpIKCAAYSoqqiqqLe4riUgpSC2LKClJSCloKCqIKClgAHEIKCgqSkgqSktLS2qIKCABYwhK7igt6WgoKCgoKUqJSmlIK6ktiSgoIACRbipqaChIKCgoKklAATQJKu5oKClKiSAAckAAoCgpSCAAIQAAkEgoKClJSCuJSCgqbssoKCgoKClIKmgu6mpKSCpKSk")]
[assembly: go.GoPositionMap("runtime/mgcmark.go", "mgcmark.cs", "ABl0wpaIgpaCgoKWgoIADiCCAAYQgoSCloKCgoLqooKCAAYQgoKCloKmlgALJAALBJKClIKCyIKCyIKCzLjogpKCgpSIgqKa+oKCggAIFIKCgpSClIKChILYgoKCpgAFEgAIApTMgoKUgoKCgqiCrtSCgoKCgqiCgoKCpqiCguwAEyKWgoKWgoKUgoKUgoIABxCogIKCtpSCuoKCmISK4pi2gsYABBIACAaClICCAA4egoKmgoKCAAcQgsqm3IKCgoKCggAHEoKCgoKClIKUhISmgoKCAAcQgsqmpoKCgqaClO6ogrqCgoKWAAcQgoIAChiCzIKCggAHEILKAAceAA4GhAAGEIIABxCChIKCgqiogoQABhCCqIKClJbKlIKCgoKClIKCgr6ygpKCrsK4goKWgoLMgoKClIKmggACGgAKAsqCloKEgoKmlILupoLKgqiUgoKUAAkoABMCgoKWmqSCy4IAAxSCnLKClJSogoKElKaWgoSCloLMgpiSgs6ippSmyoK2lAAGEIKCgoKUgoKUgpSUgoKCgoKUgpSCggAJFIKWgoKUloLMgoKCgoKCkpS4gpSClKzigpaCgoKCAAkWgoKCuoCmpsrKlJaWgoKogqi4goKCgoKUgpSUgpQACyCiqqKCgpSqogAFQgAgAoK6goKCgoSogoKCgoKkuqaCgoKUgoIADR7cgpaCgoK4gqaUlLqCgoKClIKEgoKCzISSgoKUAAYiAA8CgrqogpSCloKCgqaCqJSCgoKCuJaWgoKCAAUQAAIYAA4IgoSUgoKClIKUgoKAgqTIggAIFgAMCt6CgoKUppaCptyCggAGEIKCgpSWgoKCgIKAgv6oqAAJFICCyIIABRYACwKCgoKCgoKCgqiCgpaCgpSCgpSUloKCgoLugpSClIKolgAIEoKogoKogoKoggADEtKAgoIACBYACwSClISClKaCgoKCgqiClJaCgrqCggAGEJSCvKKCgoKClIKAgpSmgoK4lLiCgpSCgpSCgpSUggAGFgAJApKogpaCgpaCrLKEgoKClIKC")]
[assembly: go.GoPositionMap("runtime/mgcpacer.go", "mgcpacer.cs", "AKAC4gWigoKCggACFAAKAoKCgoKCgoKCgt6CgoKCypSUlKiCgqiCgpbKgtzKuoKEgoKCAAg+ABgCgqaUgoKoqMyCggAKFoIABxKCgpSUiLKWAAgUggAIEqiCpgAJFoKCgqz2lpaUgpYACBKUgoIAHTyCzoKCgoKmgoSCgoKCgoKCggADEgAOFoKmgpSCgpSCgoKClIKClIL+0oLegpSClsqoggALGJaCgoKCloK6praC3IKUgqaogoKCgoKUAAIQ8oKCgoKCloKCggAGFOKUgqSkgqTIgoKCgpSCpqaCuLiigoKUgoKCuIKokoKuAAkEloCCuoLK3AAAHAAMAoK2qLSygoKCgoIAPH6WhpKClsqouoKmlIKUpoKUAAk+AAkCzsrOggAIFIKCAAoYgoKUhpKCgpSUgoKCgoKUAAIoABMCgpamysyCgILIgpQAFzKu4oKWgoKUgoSoxIKCgoK6gpbWgoKClICCpK7igpaCgpaoxIKCgqaClIKU5oKCgpSCgoKUAAUaAAoCgoKCppSCgpSCggAEGgAIAoKCqJKCgoKCgpSCggAEFNKCgoKCgpSCggAEHAAJAoSWgrqCgoKWgoI=")]
[assembly: go.GoPositionMap("runtime/mgcscavenge.go", "mgcscavenge.cs", "AGysApIAAiAADQLOqMyClAAGEoKCpoLKpgALGrqClABm+AHSgpSChIKClAAJFgAMFpaCgoKCgoKUgqaClKiC7rKCgpSCqJKs0oKUlgAAEOKClAAFFAAJAoKCltwABxKohILcgpaCloTcgpSCqKaCgpSUugAGEIaSgriClrzCgoIABhIACgKCgpSElIIAARoACwYAABLygtyUuoKmgqbKlAACENKEgoSCgoKClIIAAxoACQKCgoKClIKUgqYAAhTyhILMgqSClIIAAiAAEw6CggAGEIKCloKmlpTMgpaEpqiCgoSCgoK6goCCpIKWgoS4goQABRYACAIADyC4lKS0tLS0tMQACxYABi4AFAKCgqSC7oKUlpSUgoKmlMyCgpKmyoKCgoKU3oLe3oKolITKgrgAO4YB0oKCgoKs9oKAgqSqwoKClIKUqIKClJSCpoKmgu6mlKaCAAIWAAgCgtyu4oKCloKC7oKCAAMS8oKCgpQAAhDSgoIACBSSqqIAGj6SAAcSkgAKPJKokqiSqqKUlJSUuLjYkoKClIKClIKU6pKCgpSCgpSmAA48AAwEgpaCuIKClIKkqIKCuIKCpqiS")]
[assembly: go.GoPositionMap("runtime/mgcstack.go", "mgcstack.cs", "AIgBkgKCgpSCAA4k1gAiTsKClIKClIKUgoKCpIKClJSCgpSCAAIQ8oKClJSClKaCgoKUpoKmgoKU2LKClIKCgpSClJSCgoKClIKCgoKUrLIAAhAACAKClJKCgoKCgpSCgoKqooKCgoKUgoKUgoKU")]
[assembly: go.GoPositionMap("runtime/mgcsweep.go", "mgcsweep.cs", "ADmAAYKmxoKCAAMS0q7CrLKCgoKCgoKUlKaCuIIAFUAACgKCgoKUggAIDqKClIKCgpSCgpSCgpQABBbigoKClILMkqyyrLKCAAUS4t4ABhCC3oKCgoIABhCEpoKEgoKCgoQAACIAEAKCgoKCppSUgriClIIAEiTCgqaCpoKU2qKoqIKCgqiCgoKCgoKUgLiCgpSkgJSCuMqUtoQADiCCgpaClpaCgqaWggACEuLcAAgIgoLMgpSAgoKCpMyCgoKUAAwS9oKCloKmloKAgoKmgoKCloSCAA8kgoKUgoKCpoKCgpSCgqa4poKCgoK4yqaCgoLKgoKCpriClpSCgoKCgoKCgoKmgqaClIKUgqaCutyCgqaCgsyCgqaCloKCgoK6gpaCqKiAgoKkggALGoSCppS4grqCqLaClIKCgpSWlMqCgoKWlNyUgqaClNoABhCCgoKWAA4ggoKUlKaSgsqUqJQABSIAEAKCgoKCgoKCgoKUlIKUlIKClIKCgoKUlIKUAAIoABEClJaCgoKogoKCgoIADyCUgoKCgpSUqIKCgry0ggADEtKWgu6CuIKUlIKCgoKUgrg=")]
[assembly: go.GoPositionMap("runtime/mgcwork.go", "mgcwork.cs", "ABI0goIAPZAB4oKCgpSuwoKmgoKCgraCgoKCgoKCqILMggADEMKCgpaCgq7CgpaCgoKCloKCgoKCgpSCgpaCAAMW8oKCgqaCgoKCgoKClIKoggACENKCgpaCAAIU8oCCgpSClISCgpSClKTKgpSCggADEMKClICCgoKigoKUxoK+sgAUMMKC6IKCAAMQwoKCgoLKgoKEkoKCgoKClJSCgpSCpoKCuIKCgoKClLiu4oIAAhDygq7CgoKClKjEgoKCgpaC3LKCgsqCgqqigoKCgpSCgoKCgpSCpoKC")]
[assembly: go.GoPositionMap("runtime/mheap.go", "mheap.cs", "AKgC8AWyrsIAYtQBgqbCgoKClAACIAANAoKEhIKCgpSCgoKClIKCgpSCgoKmggAHIIKokqiSAAIeAAwCqqIABBbippQAAxTigpQAAxTiAAIQ0oKClJSkAAQeABAMgpSCuIKmgpKUgoKUAAIS4oIAAhLi3IKUquKCgoKCqLKChIKCgoKCgoIABxKYgpYAAhIADQ6CzISCgoKWgoKUgIKClJSClLiClIKWlIKogoKmgqaCloKCgpQAAhIADQyEgoKCgpSCgpaCgoKCgrqCgoKWgoKCgIKCgoKUyu6ClIKCgpSCgpaCAAkekgACEuiypoKUlAAFKAARAoKUqqKCgoKCgoKClAAGHAAMAoKChIKCAAgSAAcSgoK4goKUlLjMgpQAAh4ADAKmgqaCggACGgAMAoSClKaCgoKUpoKCAAIaAAwChJSCgoK4AAUoABUEgoK6uoKCloKCgqiCgoKCAAcShJQACBSCgoKCgoKUgoKmgpaUgoKCgoKClIKCuKaUhAAAFgAKAoKApqaCgraAAAgSgMqCgIKkgt6y3IKWiJaCgpSoloKmgqaCgqaCgoKUpKSkpJaCgoKCpqr2goKUgoKCgriCgIKCgpSClJSUuIKCgoKWugAKGAAHFITcgpa6ruLehKaCgsiCgoKClqbKgLiUgoKmgraC3qiC3qiCgqiCgqiSlIKCgoKogpSCgpSUgoKUggADHgAOBIKCgoKogoKCAAgGsoSUgraClIKClIaCtNyCgoKmgpSkpKSklpaCAAIUAAoIgpaEhIK6koKAuMSCgoKCgoKCgoKCgoKCgoKCgoKmgqiSgtaygpSUgpSUgpSUgoKmgtaygoKUgqamlILWsoKClIKUppSCqtKCqIKogqaCgpYADzSygoKCqLKCgoIABRIACAKCgsyChIKEloKUgoKCloKC3LKCgsyChISChIKCgoKUgpSCgqzEgoKCgoKUgoKUgpSUAA8iwoKCgoKCgoKCyoKCgqaCuIKUqIKCgqiSgoKUgoIAIkiSqJKoloKoloKCgsqClIKmzAAGEIKUuoKopISCgpaWlqgAAhDSgpKC2KSApoKmgoKEgoKCgsqCgqaCAAgUgoIABxKCgoSCgt6CgtaCgoLMgoSEhpKCgpSCqIIADBaygoKCgoKCABcwoqaCpoKCqqKCgoLawpSCgoKCpIKCgoKkgoKCgqSCpoKCpIIADBaSqqIAHjrCgqaCgqaC2qKCloKAgsq4gIKCuLiApoKCgsqCgqiChIIAAhLiAAIiAA4CgoKCpoKUgqaCgoKqooKCgoKClJSCgpSmgpSU")]
[assembly: go.GoPositionMap("runtime/minmax.go", "minmax.cs", "AAkSgoKUpoKClKaAooCigKKAAAgIooKUgrimooKUgrim0pSkpKbSlKSk")]
[assembly: go.GoPositionMap("runtime/mpagealloc.go", "mpagealloc.cs", "AD6+AQAJAAAEFqKokqqiqJKmlLqSgpS8oqqiAAIQABASgoKssoIAeIACwriCgpSWlpaWlpassoKClKyy3uKogqiWuoKSgpSCyrqAggAHEIKEkoKClLiClMqUzAACIAAUEIKCgpSCgoKC3oKmAAQaAAgCloKmpoKCgpTIlqiCgpSCuu6CgrqClKiClpaCgoKCgoIABRwACAKEgpKUgpSCgoKmgoKCgoKCgoKUgoKClIIAAhLiqIKCgoLKpgAKJgAQAgAZOAANHgANHoKmgsiCggAGEIKEgpSCqJbMgoCCAAIaAAsCgoKmgrqEgriCpoKUuIKCgpTKgoKmlKaClJTMgoKCgoKClAAKFIKCpoKCgqiogoIAAh4ADwKogrqClIKAgoKCgoKUgoLagoLclJSEyoKUAAIUAAkCloCCpIKmgoKCppKUlIKmgoKCgpSCpgAJMJKClKySgpSokoKUqJKClKiSgpSu6oKUuoLe3oKUpg==")]
[assembly: go.GoPositionMap("runtime/mpagealloc_64bit.go", "mpagealloc_64bit.cs", "ADqOAdaCloKCgqiSAAYcAAwCgoLMgoLMgoKCggAHEqKCAAoYlpTMgqjegpSCpoKogoKorNKCgpQACxiCgoKWgpSCqIKCqJaCgpSClIKmrLKCgoKSgg==")]
[assembly: go.GoPositionMap("runtime/mpagecache.go", "mpagecache.cs", "ABcykgACFgAIAoKUgoKCgoKUAAIS4oKClIKCgoIAAhgACwKEgpSCqIKClpSCzICCpIIAAhgACQKogpSCgoKUgoKClAAHEIKmgpSCggAHEoKCppYACBSC")]
[assembly: go.GoPositionMap("runtime/mpallocbits.go", "mpallocbits.cs", "AA0ekqiSqJKokoKUgqaCgoKUlIKCpqiSgryiqJKokoKUgqaCgoKUlIKUqJKqoqrCgpSCgoKUgoKClIIABBayooKCgoKCgpSCloKClJSUhJKUhJS4goIABRCCkrqCgpSClIKSlKaCkpSmqIKCgoKCkpTGAAIYAAkCgoKklK7igoKCgpSUAAIaAAwCkoKCgoK4ppSCgqaCgpSUAAIaAAwCooKCgoKUppSCgoKUgoKUgoKClJSClKiyqLKosqiyqLKs0qrCrviCgoKUgqaCgpSmygAOItSCqtSC")]
[assembly: go.GoPositionMap("runtime/mprof.go", "mprof.cs", "AIUBtAKygoKCACFAsoKCqtKCgoKCgoLO2IKCgoKCgvySgpikp66CgoLawoKUlNiygpSC2LKClIKokoKClIKCgoKUlJiSgoKCpoKClIKElIKCqIKWlIKCgrqCgoKEgoKklJaChIKEgqaCgpSCgqYAAhYACAIAAhTygoKWgoKCgoKuwoKCgoKogoIAAxAACQyEgoKCgoKoksq4goSCgoSCgoLMkrqShIKEgoKCAAUW4oKCpKaCgqimgoKWgoK8ooKUAAUU8qaUgoKUgoSCgoKUpoLclJSCqIKuwoKCkoKkgpSUlISCgoKCgoKkkqTKgqiUAEOIAYKEgoKUgpaCuIKEgoKWgoIADBqCgpa4gpamgpaAuIKCgoKU/oKs0oKUgILIoqaWggAJFJSEgoKCgpaCgoKCkoKClIK4yoKEgoKAgoK4goSCgoK4loKmgoKE3JSCpIKUgpQABRjygpSCgqiSgpSCggAKGqKCgqYAIESQppKqooKCpgACMAAVAoKCAAMcAA0CuIKCgoKCgoKCgoKUgqbKgoKCgoKCgpSCuIKCgoKC7riCpqKCgoKCgpSClIKUgqiSgoK4goKCgoKUAAokAAoCgpKClIKUpoKCgoKCgqaCgoKmgr7igoKClIKCgoLugpSmgqzSgoKClIKUgtyCqJKCggADFAAJAoKSgpSClKzigoKClIKCgoLKpoKokoKCAAMU4oKCgr7igoKUgoKCgqaokoKCupKokoKWABdEgqaCpoKmosqWhISCAAcQgoKWuIKCqIKCspSClILegoK4goKCpgALGpKWgoKCgoKogpaClgAKGILewoKUrNLKloKCppSmggAGEIKCgpQABhYACQIACBKUgoKWhLgACRaQlIK4soS2loKWgpKCqIKCxoKCopSWgoKosoKWptyQkoKClKiCloIAAhIACQKCgoKUgoKUpoKmAAwWgpaCgoKC")]
[assembly: go.GoPositionMap("runtime/mranges.go", "mranges.cs", "ACBCsoKClKiSgriokt7CgqSkpJSssoKClIKssoKClIKqooKUgpQADjCSqJKqoqqiqqKotqiSAAoaooKCgpSCzqKCgoKClIIABBLCqqKqooKCgoKUABYysoKCgoKCqqKKspKCgqaUuO7cgoKmAAIQ0oKClIKUgpSokoKClNwADxiCgriCgoKmloLIyLjKgoKCgpaClIKUlKyygpSCgoKCgoKUgoKqooKUgoKUgoKUgIKCgoKUgraCqsKUgoKClIKC")]
[assembly: go.GoPositionMap("runtime/msan0.go", "msan0.cs", "ABAmkKKAooCigKKA")]
[assembly: go.GoPositionMap("runtime/msize.go", "msize.cs", "AAscwoKUkriClKaCgpQ=")]
[assembly: go.GoPositionMap("runtime/mspanset.go", "mspanset.cs", "AEKUAdSCloKCgoK4poKCgpaClIKClIKmlJaCAAkWqIKCuqqikoKCgoKUuILuyoKCgpSC/Lq6goK4ygAMHJSWlAAHFPKCgoKUgtyCgpS4lLiolqaCAAkasqyyAAcSkgALGqKAgqSokoIABBKiqJKokqiSAAcSkqiSqJKoktiSlIKClKiSAAcSkqiS")]
[assembly: go.GoPositionMap("runtime/mstats.go", "mstats.cs", "AKcCnAWCgIKCyICCggAWOrLMAAcWkpaCgoKGmoKWgoKCloKCggAHEoKYgoKEioQAESSCgoKCgpSCgoKUgoKCgoKUgoKClIKCgsqCgoKCgpSCqoKCgoKCggAQIoKCgoKmgoKCgoK4goKCgoKCgoKCgsyokoIABhDClIKohIKC3oKCgoKWgoKCggACENKEgoKClIIAAhDShIIABRzSAAUQ0oKCggAbRPKCgoKCgoSCgoKClIKCggAvgAEAEwKAgoKUgqakggACIgAQAoCCgpSCpgAEEOKEggADEMKEggAvtAHCgoIAAhDWAAgMpoKCgryCloKCgpaCgpaCAAgU")]
[assembly: go.GoPositionMap("runtime/mwbbuf.go", "mwbbuf.cs", "AD+cAZKCgriUloIAAxLSqJIAAjIAFgKClIKCqqKClIKCAAIkABEIuIK6ggADHAANBIKCqISUgpSCAA8igoKC7pSCgriCgpSWgoKWgoKUgqiE")]
[assembly: go.GoPositionMap("runtime/nbpipe_pipe2.go", "nbpipe_pipe2.cs", "AAgSgg==")]
[assembly: go.GoPositionMap("runtime/netpoll.go", "netpoll.cs", "AH2QAoCigKKAooCmkgACFAAJAoKClIKUgpSWgoK+soKCgoKUgoKCggAXNsKmgoKCgoKCgpS4gq7C6JKCgoKClIKClIKUlIKCgoKCgoKCgoKEgoKClPiygpSCgpSCgpSCptaogoKEhISCgoIAAhDSgoKUgqSUAAIS4oKCpoKUgoKC3Ki2urKCgoKUgoKCgqamgpSClIKCgoKUgriCtoKClIKmgoKCtoKClILKgpKClIKUgoKUgpTYsoKClIKCgpKCgoKCgoKUgoKUgoKUgpQAAhwADQKCkoKUgpSClIKUpoKCgpSCyoKUpoKCuJSmgu7CgoKolIKUgrqAgu6CpoKClAACEuKCgpaCgoKUppSCgpSCgqSUAAgKoqaCgpSUgpSCgoKClIKClIKCgpSCgpSCgpSClKaCpoKmgqiSqJKCuKKCgoKCgriCgoKCgoKCpoKCggACEPKCgoI=")]
[assembly: go.GoPositionMap("runtime/netpoll_epoll.go", "netpoll_epoll.cs", "ABgqgoKCgoKUgoKClLaCgoKClKaCpoKCgoKCpoKC1oLYpIKWkoKCgoKUgpSClIIABxLSgpSCgqSkpLiUgoKCgoKCuIKUlIKCgpKCloKCgpSM0oKUloKClIKUgoKCgoKCuA==")]
[assembly: go.GoPositionMap("runtime/nonwindows_stub.go", "nonwindows_stub.cs", "ABAmyA==")]
[assembly: go.GoPositionMap("runtime/os_linux.go", "os_linux.cs", "ACNKAA4yAA0MgoKWgoKs0oKCzIKWpgAAEPKCgoKUgqKCgqaClAA0UNrSuIKaooKCpoKUlISCgoKUvrKCgoKUgoKCABEkyKKWgqiWhICCgtqSiLKCgpSCgoKCgqaClIKWgoKCuIKC3IKCgoKYpqbGgpTagoKSgpSCgoKClIKCgpSUlKaCgoLagpKCgqaCAAIS4qrCgqaYorqssoKqzsKSpqampqamqKKmkpailpKmlpKCAAUUooKCuIKUkoKUpoKqooKCgpSCqqKCgqyyqOyyAAsYlIIABRLEkpaSAAIUAAkCgoKEuJYADBq63KimguaCgpaCgoKEgoKCqJQAFCyCgoSCgoKCgoKmloKCuJaCABdAAAsClAAIFAAULN7OgpSUgoKCgpYALV6ClMyCgoKUlIKogoKUgqiEgoKEAAUS4oKCloKClJSCgoKWAAYawoKssoKokoI=")]
[assembly: go.GoPositionMap("runtime/os_linux_generic.go", "os_linux_generic.cs", "ABM0oqaCqJI=")]
[assembly: go.GoPositionMap("runtime/os_linux_noauxv.go", "os_linux_noauxv.cs", "AAgS")]
[assembly: go.GoPositionMap("runtime/os_linux_x86.go", "os_linux_x86.cs", "AAgS")]
[assembly: go.GoPositionMap("runtime/os_nonopenbsd.go", "os_nonopenbsd.cs", "AAgWyg==")]
[assembly: go.GoPositionMap("runtime/os_unix.go", "os_unix.cs", "AAsikg==")]
[assembly: go.GoPositionMap("runtime/panic.go", "panic.cs", "AB1wABIClLiCggADEvaCggAGRAAeAoKokoLcsoKokoKokoKokoKssoKokoKokoKkgoKkgoKkgoKokoKkgoKokoKkgoLYkoKqspKSkpKSkpKSkpKSkpKSkuqSgvySgvqCgvqCgvqCgqaCgtqigpSWgoKCgrgABhAADxaSlKSkpKQABYwBAEMCgpSWgoKWgoKEuISChKiS2qKCgpSCgoKCgpSCuqzSgoKUgoSCgoKCpoKUgoKCgoKmggACEgAIAoKUyoKCggAMGoKChAACFPKCgoKCgoKCgoKUlICCgoKkgoSUlIKokoLKgpaCloKChKKCgoKCgoKUlJSCgoKWhISCrLKChIKCgoKUAAhA4oKC2MTGgpS0pOyigoKCpoKUgoKClAACENKCgoKCgoKUgoKCABYogKIACiIADQKCgpSogoKCgoKWgoKCgpSCgoKCgoKClIKCgoKWgoSEgoKCgpQABxKC3oSCrNLMgoSChICohIKCppaCAAcSgu7ihIKCloKCzISCggAIFIKCqJaChJaCgIKCgoKWupaEpoLMwoKWgpKCgIKmgoKCgoIABRCCloKWloKChJbWgoKCloKWgoKCloSCgoQAAhYADg6CgoKClKiSqJIAAjYAGgaCgoKWAAIYAAsGgoKClgAUKgAJAoKClgATKIKCgpaUhJKWgpS4ACBIgoLMgoK4mroACwiCAAIQ0oKChIK6koKWhLiWlgACENKCgoKmkt6Elpa4loKWAAIeAAwCgpLcqIKWpoKCgpKUgqiCgqiCgoKmggAPEsKCgoKUlJaCgoKUgoKCpIKUgoKmhMqCloSuwoK6goKmgoKUgoKClIKClIIAAhDS3AAKFqaUprgAAhTygoKU")]
[assembly: go.GoPositionMap("runtime/pinner.go", "pinner.cs", "AC22AaKClILKguaCgoKClICCpJSUrsKCppS4gpSCgoLuwoKCgri6goKEhISCgoKUgoKUppKCuLiCgpSSgpSUuLimgoIACBiypoKmgqaCqqKCgpSClAAFFsKCgqaCrLKssqaCrNKCgpaCzIKCgqiCgoKUvKKCgoKCgpSCgoKClJTawoKClIKCgoKClIKCgpSokoKCgoKUgtw=")]
[assembly: go.GoPositionMap("runtime/plugin.go", "plugin.cs", "ABEasoKCgoKUlIKUgpSCloKCgpaIgoKCgoKCgoKCpoKCgrqChIKEgoKUAAgUgoKCgoKChIKClJTmooKCgoKWgrqCgoKCgpSCpoK6kg==")]
[assembly: go.GoPositionMap("runtime/preempt.go", "preempt.cs", "AE7SAQAfAoC4qJKWgoKCgoKAAAMoAA8U0piEgszCnIKCAAAcABMKopiSmIKChoKCgoKErgAKDIKCggAG1QGMloIAC9oBgpSClIL+opSWgoAAAhCrggADEJQAAxLSAAIWAAkGkoKCgpSU7oKCgoKUggAKFoK81AAIJgASArqCqIKogqiClJQACBKUgriUgAAHELaCggAQKJSYopSmtA==")]
[assembly: go.GoPositionMap("runtime/preempt_nonwindows.go", "preempt_nonwindows.cs", "AAgUtg==")]
[assembly: go.GoPositionMap("runtime/print.go", "print.cs", "AA4gsoKCgoKCAAUi8oSUgoKCgqgABRrygoKCgpSmgoKCgryigpSC3IKCloKmgqaC5oKClAAICIKUgqSCpIKmgoKCgoKCpoKCqIKClIKCqIKClIKCgrqCgoKClIKEgoKCgpaCgoKmgqaCgoKCgoKUlKaCgoKUyoKCgoKCgoKUlIKCgoKmgqSCpoKmooKCpoKmggACENKCgoKCgoKClJaCgoKmgoKCloKCpoKC")]
[assembly: go.GoPositionMap("runtime/proc.go", "proc.cs", "AIQBjgIAFRiyqLqClMyWhIKCAAgUhIK6goKWgoKWloKCgqiEgoKCloKUgoKUgqaCqIKUqIIACBSCuoSEgoSmlIKCgoLelIKClKaClISCgoLusoKCuIKCgqaCqJLWgoKCgoKClIKUgqYABSLCAAIQ0qaClAAFPgAcAoKUgoKCgpSCgoKCgpSqogACGgAKAoLqAAkSgoKClIKCgoKUlIKmgoKCgoKUggALCLKClIKUgpSClIKUgpSCgpSCgoSigoKCgoKClJSUgoKClILYktaC1oLqooKCloKSgoKChOyi2JIADSIACAKCgoKUlIKmgoIABxKkkoIADjqCgpaCgoKUgqyy3qiSgoKokqyygoKUrsKCgoKUAAQWopSkqJSCgqamzrKCgpqCspaCgoSCgsgABxYACAKCgoKCgoKCgoKCgoKCuKiCgpaCloSCgoKCgoKCgoKCgoKEgoSCgoKCgqiCgsyCqISCgoKAgqSClJaEppSmuKKCgtiSAAgUgoKCAAYQwoSClIKCgqiyloKWhIKUloSCgrqogpaClK7CppSCrAAJDqqgppCkgoKCAAIU8oIAAhLipoIACSSSloKCgqiCgoKClIKCAAscsoIAGDKCzJSClIKUpoKCrsLu4pYAARSCAAMRgoIAAhSCgoKU2qKagoKClLiCggALGgAIAoKmgqiGkqiCgqamgpSCgqaCqJSClJSCAAYQmoKCtMSegoIACASklJaCuIKqgoLOAA0Egt7CgpQABRTygoKClIIABxLCgpSCvtKClIIAKTqCpoIAJ3IAEQKCgoKClKyykAAQIoKCgqyygqyyggAVXAAzKISCgoKUqIKWgoKCgpSCgpSCgoKCgpSCgqaCqIKCgoKUgoKUgpaClIKClKiCgoKU3oKCgpSCgpSClIKmyoKUgpaWhAAKHOKEgoKSgpSEgoKClIKCgoKUhISCgoKCgoKClIKmuoKUgoKUlIKCgsyEhKqilKSkqqKUpKSqAAMWAAkChIIACBKSgpSCuKaClriU3sKEggAHEoKChIKogpaAgqaCgpQAAhIACQiCgpSssoKCAAYaAAoChAALGIKCgoKCgpaCloLKqIKCgoKmggAAHgANAoKChIKWzIKCgoSmgsyElKjeAAIaAAoCggAQIoKCAAgaAAkCgoSCgpSCloKCpgAFEIKCgqiClqiCqIKClIKUgqS6gsqCgpSmgpSCgqiCgoIAAhwACwK4gpSCgoKClAANLgALArqEgoK6goKCpIKCgoKCgtqCyriSpqSCloKCqIKUlISCloKCAAVUACcC7oIAARYACAKCugAHEpaoqIKCupaCjtKCqIKEgoKCpqyyhIK+soKCgsi67IKCgoKCgoKCgsqCgoKUgoKCgoKCpsyWAAJIACQIjMKCqIKChIKCggAPIqi6AAcQgoKUzIKChKiCgoKCgoSEAAYuABQCgpSCgpSCAAMeAAsCAAs28oSCgoKCgpSCuIKUgpSClIK6koIAAhQACQKCgoKuwoKs0oKCACVkABEWhIKCgoAACxiCgpSCgoKClLiCpIKmooKCgpSCgoKClIKUgoKClIKCrsKSuoKCgpSCAAIeAAwCgoKChIKCgoKCgoKCgoKUlIKCggAIDKKEgpSClIKWgoKCgoKmlAAIKAAjIoKClIK4lIKCgpSCpoIADh6ChIKUlISCuIKUgpSClIKUgqaCgqauAAkKgoKmgoKmgoK4koKClIKCgoKCgpSClIKCgoKmgoKCuIKCgrqCgoSCAAYiAA8GggAGEISCgoKCgpSCgtyEhOqihIKUlIKUlIKCgoKClILuwoKClIKmgoKCguqihIKUgqaCpoKCgoKCgpSCAAIYAAsChLi6goKCgoKCgqiCgpaCgoKWAAkO4ryItIKCgpSC3paCgoKCgoKClLqCgoKUzIKCgoKCuoKAgraCqICCuIKCgoKCAAkWgoCigoKCgoKCgpQACBKCgpaClJSmloKUAAYQgoKCgoSCgoKClJTegoKCgoKClJSCAAkWpoKWgoKClIKCgpSUgoKUgpSCACRMgoKCggAKHIKCgoKCgpSCgoKmhIKCgoKogoKCloKCgoKClAAHEs6CgoKUgpSCgoKUgoKmlJSkgoKCpoKUgoKCgoKUgoKCgoKCgoKClJSClLaCgqaCrsKClIKClIKAkoKCtgACEgAIAoSEgoKEgpSUgoIADiCCgoKClAAIEoCCpLqCgIIACBIAAhDSgoKCgpSClIK6rLKCgoKCuq4ACg6ClIIAEiiCgoKCqIKCgpaCgoKCgpaErLLKgoLKkvqCgoKUgoKCygACFgAKAoK6goKCgoKCgoKCpoKYkoKChIKCgoSCgoKCloKCqIKCgoKCgpaCmIKClIKCgoKCloIADiD6ooSCloKCuoKWgoK6gpa6hAAHEILMgpa4gqaUgoKCzIKUpoKWAAIU8oSCpoKCqJKEhLi4goKWhICCgoKCgoKCgoKUttaCgoKCgpS4gpSmgoKWgoKChIKWqJKosoKUpoLs0oKCgpa4goKUgoIACBSCAA8igoKUgoKUAAIiAA4CgqaigoK4lIKClIKCqJKClIKCgpSokoLWooKEgoKClIKCgoKCgoKCgoKCgoS4goKCloSSgpaCgpSC3pK4AAcaAAgChNyWgoKCgriCAAY4ABgCkqjMgpaCgoKCgqaUgpKCpoKSgqiCkoLKloKClpSCloKCgoKCgoKClgACIgASCoKmgoKCgpSmgoKEgoKCAAkUgpSCgoCCxpQABR4ADAKEgoKCgpaCgoKCgoKCgoKCgpKCpoKCkoKmgpKCqJaEpoKCgoKUAAUuABQChIKCloKCgqa4kqaSgoLagsrKlIKCuoKClKaUhJSWlpYABhCCgqjEgqiClIKCgpSUgqiCgoKUgqYAAhDSgoK4xoKmuIKCgoKClIKCgpQAAhIACAKCgoKCgsqClIKCgoKUgoLepIKUgoKClMqClIIAAiAADQK6goLMAAIgAA0CloSEAAY2ABgKhKiEAAgWxKiCggAEELKokoKCgpKUgqaUrLKCgpKEgoSCAAkQ4oKWgoKCgoKClIKWgpaCgoKUgpSUloKCgoKCgoKCgoKCpoKU3LiCgpSWgoKCgpSCuIKClIKCgoKCqIKCgqamhKzkgpSCgpSCgpSChIKCgoLMgoLa0oKWhJSCgoKWgoKCqoKCgoKUlJSCgoKCvMKCgpSUgoKCgqaCgpSClIKClIK4koKCgqaUkpSUgpSClIKmqLKqgoKCgpSUlIKCgoKokgACENKClIKCAAZcAAkCgpSCgpSCAAlIgqaCgoK6gpSmggAMFoCigKKAooCigKKAooDc8oLMggAHEoKAgoKCtriCAAgUhIKCgoLcgoKUgqjIyJSUhKaCgraUgoKUqIiygpSEgoKCgoKUgpSUqrSCuoK6hIKUgoKUhIKChIKW2sKCgoKCgoKCgriUpoKCgpSmqKau4oKWlIKUlIKCqJaCgpSClIKCgpSCgpSUgoKClIKCgoLcgoKEgoSUgpSCAAUWAAgCgoSCgpSCgoKogoKUhJamgoKUpoKWgoKUlIKEgoKUqIKCgpSCloKUgu6CgriCgpSUgoKCgoKCgoK6loKCuoKCgoKCloKCgoKUgoKUgoKmgoKClJQAAhIACQS8hIKCggAHFAAIAoSmgqamgoKClIKmgoKokoKCgpTokoSClIKCgpSCgoKmgoKCgpQACgyyuoLegp7CgpaCgpSCgoKWgoKClIKWqIKCtpKCqIKAgpaCpoKUgqaCyoKCgoLKgoKoggATLLKCgoKEgoKEgpK0lJKUAA8igoKCgoKCgoKmgoKUgoKUgoKUgoKUgoKmlqaWgqaCgoKSAAcQgoKCpgAPIICCtpS4gpSmgIKCgoKCgqSCgpQADh6CpriCgqaUgoKCyoKCgqSmppSCgoKCyoKmyoKCgoKClIKCpJSCpoIAAhDSgoKClIKmAAIaAAoCgoKUgoKWzJaCgpbKgoKCloKCgsqCgoKCgoKClJS4goKUgoK6goKWgoKCgpSUgoKUlIKAgpSkloKCgpSUgoCClKSUAAIQ0oKCgpSCgoKCgoKCpgADEMKEgpQAAhDyhIKCggACENKEgoKClAACENKEggACENKEggACEuKEgoKqwoSCloKClIKUgpaEgoKCgpTOkoKCqJKCgqiSgoIABhwADQKEgpSClIKUgoKCgoKUAAIU8oSClIKUgoKCgpQAAhoACgKEgriClqoACAqCgoKCggAPKgAIAgAIEpSCloKCgoKUgqaWgoKCgoKClIKm2sKWgoKClIKUkpSEgoKCuoKUgoKWgoKCrvKCgoKCgoKClISChoKCqIKCgoIAAxD0uIKWgoKCgpSCks7igoKCloKCgoKClJKWkgAIFIKCgpSu8oKCgoKCgpSAggAKFoLKpoKUgraUkpSCgpSSAAcQ0oKCgpSCgoKUgoKUggAJFpKosoKCgrqygoKUlKqigpSCgpSUqqKCgoKCpqiSgoIACBSSqLKCqJKCgrqSgoKUqLKCgpKUlIKCAAIeAAwCgoSCAAIeAAwCgqqiqqKqoqqiAAIiABMMgpSAgqQAAh4ADAIAFSqCgoKCgsqC7oKmgoKmgqaCgpQAFiyCgviilKS0hMqClJaUlpKCkoKWgpSEgoSCgoKCgoKW")]
[assembly: go.GoPositionMap("runtime/profbuf.go", "profbuf.cs", "AG3oAYKmgqaCpoKmggACEOSokqiSrOKCgoKCgoKmgpSClKrCgqiUgoLcgpSC/qKAgu6ClIKUgpSEgoKCgoKqwoKWgqiCgoKmlAACEPKCloKoloKCpoKUgpaCpoKUAAUQAAgCgpSCloC4goKCgtqCgriCABAkgoLMgoKCgoKCgpSCgpSCgoKWpoKCgqaClOyigpSCrLKCgoKClIKUAA4cwoKW3oKCgoKCgoCCtpaCgoKCpoKUpoKCgoKClJSUyoK6lJSCpoKClIKClJSClIKCgqiCgpSCgt6CgoKClIKohAAJFJY=")]
[assembly: go.GoPositionMap("runtime/proflabel.go", "proflabel.cs", "AAwqABwmgpQAAhoACgI=")]
[assembly: go.GoPositionMap("runtime/race0.go", "race0.cs", "ABAmkKKAooCAooCigICigKKAooCigKKAooCigKKAooCigKKAooCigKKAooCigKKAooCigICigKKA")]
[assembly: go.GoPositionMap("runtime/rand.go", "rand.cs", "AClKooKCloKCgpSClLiCpoKCggACEAAJCoKCgoKCgpSClILqkoKClIKAgoKkvKKCgpSCrLIAAhAACQqCgsqCgpSCgrqygoKUgoIAAhDkAAIsABMCuIaCggAGEIKCgoKCAAIqABICAAImABEEAAIWAAgCqJKokg==")]
[assembly: go.GoPositionMap("runtime/rdebug.go", "rdebug.cs", "AAkUsoKCqLKCgoI=")]
[assembly: go.GoPositionMap("runtime/retry.go", "retry.cs", "AAgc0oKCgpSU")]
[assembly: go.GoPositionMap("runtime/runtime.go", "runtime.cs", "ABw+soKCggATVAAXBIKCqIKCgoKCqIKWlIKmlIKClJaU7pCmkKaQqKIADRKSgoKCqJKCggAKFqKCgoKClIKCgpSCpoKUpoKCgoCCpIKUgrqSgoKCgoK6koKCggADEMKsspaChICCAA4c7IKWABUugpQACS4ADQA=")]
[assembly: go.GoPositionMap("runtime/runtime1.go", "runtime1.cs", "AB9KAA0CgoKCgoLIlJQABRaypoKCgqaCgpSCgri4goKWgoK4ggAPDoKCgoKUgpSCgpSClIKUgoKUgpSClIKUggAwCIIADh4AABCEgpSClIKUgpSClIKUgpSClIKUgpSClIKUgpSClIKWgpaCgoKUgpaCgpSCloKClIKWgoKCloKCgpaCgpSCloKClIKWgoKUgpaCgpSCloSCloIAacwBlIKCggAIEpSEhIKCloKUgqTMloSChIKqopSUlIKCAAceAAoCgoKUgoKUuIKClIKUpoKClJKClILMgoCCtoKCgIKCpAAHEIK6koKkpKSkpLSCgoKUtIKAguqCloQAAhQACQKCgoKmpoKClJSClKyygoKokoKClAADJgAPAoKCgoKClAACHAALAgACIgAOAgACHgAMAqyyrLKssoKCgoKUgoKCgoKUgg==")]
[assembly: go.GoPositionMap("runtime/runtime_boring.go", "runtime_boring.cs", "AAkUpIKUqJA=")]
[assembly: go.GoPositionMap("runtime/rwmutex.go", "rwmutex.cs", "ABx4AB4ChILM+oKElIKClIK4goKCgoIACA6ygIKCppSCgoKUtqikgpSUgpSSgoKCpurEgoKmgoKCgoKCuIKU")]
[assembly: go.GoPositionMap("runtime/security_linux.go", "security_linux.cs", "AAkSqJI=")]
[assembly: go.GoPositionMap("runtime/security_unix.go", "security_unix.cs", "AAsagoSCAAYS5oKCgoKCpoI=")]
[assembly: go.GoPositionMap("runtime/select.go", "select.cs", "ABw6gqaCgoKCgoLKAAgSgoKClLj8uAAFFsKC7pSUgpSmggAHJAARAoK6goSCgoKcsoKClJKClJaCggAJGIKCloKCloKWgoKClIKogpSCgoKClJSCgoKCgoKCgpSClIKCgpSUloKCgoLMhAAHGJKCgoKCgoKChIKCgpSClIKmgpSClIKClIK6goKCqIKClIKCgoKCgoKmgoKClJSChIKUloK6yoKChISCgsyCgoKUgoKClISCgoKUlIKCgoKmgoKUpoKCgpaCloSCloKCppaCgqSmgoKkpoKCpKiChISSgpSUgpSClIKCgpSCgoKUgoKEhJKClIKUgpSCgoKUgoKEhLCSgpSChISSgoKUgpSEhJKUgpSClKCSgpSEgoKUhISSpqIAEi6SgpSCgpKCgoKUgqSCpIKmgqiCqIKCloKCgoKClJaWgpSUpqKCgoKUgoKCgqaCgoKUlIKCgrqCgg==")]
[assembly: go.GoPositionMap("runtime/sema.go", "sema.cs", "ADtwggACGgAKAqiSAAIaAAoCqJKokqiSqJKmgoKUAAcWktaCgoKoggAHEoKCgoKCgoKClIKClJSClJSCgoK4goKCpoKUpoLWgoK6gqiCpoKUgoKUgpKCAA8ggoKCgpSUgpSClIIAECLKgoKCgpSCzNKCgoKChIKCgpSUgoKCgoKCgpSCpoKCgpSCgpSCgoKmgpSUgoKCppSCgpQADR6CgpaCgpSClAAEGAAMAoKCgoKUgpSmhIKCgpSAlIKCgoKClIKClIKUlIKCyoKCgoKmgoKUuIKClKaUpIKCgoKC2tSCgoSCgoKCloKCpJSClOzUgoKEgoKCgpaCgqSUgpQAGDqiAAIQ9q7iloKCqIKCgoKCgoKUgpSUgoKClKz2grqCgoLMgpaCgoKCvvaClpaCgoKoAA0egoKCgpSUgpSCgoKm2JKCgrqS")]
[assembly: go.GoPositionMap("runtime/signal_amd64.go", "signal_amd64.cs", "AA0eooKCgoKCgoKCgoKCgoKCgoKCgoKCqqCkgKKAooCigKbogoKCkrSUgqiCuoKmuJSCgoKC")]
[assembly: go.GoPositionMap("runtime/signal_linux_amd64.go", "signal_linux_amd64.cs", "ABAmoqaAooCigKKAooCigKKAooCigKKAooCigKKAooCigKKAqKCkgKKAooCigKKAooCkgKKAooCigg==")]
[assembly: go.GoPositionMap("runtime/signal_unix.go", "signal_unix.cs", "ABo2kqaCgpQAPn6mgoIABRbSlLqCloKCgrqEpoKklJaCvNiUgri4loKCuoKWrLKCqIKWgoKCgoKCggAEELKCqIKWgoKCgrqCggAEELKCqIKWgoKCAAMW8oKCAAQSwpSCAA0cgpSCloKCgoKU3oKCggAFErKmgoKUqOaCgJTKgoSCAAUYAAgGgpaCggAGEJaCAAMS8pTugoKCgpS2AAIcAAsCgpSCgoKCpoKUlAAHEIKUlMqClJSClJaGkoKCloKWgoKCggALLAAMAoKmgoKClKgAAhLigrgAAxYACQKCgpaCgoKCgpYAChaSgoKogoKClJSCABIikqiSAAIcAA8GgoIAChiEpoKUloKWgpbKgpaUzIKClO6UppQABxKCgoKEgpaCgqiCloKWgt6CloKEgpaEgoKCgpSCpIKUloKChIKClJQADBqClLiCgoKChICUgsiCgoKCgqaCloSmsoKUloKWgoKUgoKmlIrC7oKClIKCgpSUggAHKAARAoKClpSClpKUgqSClpKUuJSUpJSkpKaUlAACEuKUgt6CgpaChIKClqzSlJaCgoKUgqiCAAkWggAKGIKWugAGEKiSqqKClIKCgsaCypKCgqaCgrSCxoK2ggAKELKC3LKCgoIABRDSggAFENK4goKUgqaUqAACEvKClIKWlIK4goKCloLMgqiClsqC7oKCqIKWAAIWAAgCAAIWAAoCABcMmgAAHIKClgACGgAKAoKClAACFPKCgqqiggACGgAKAoKCgoKClIIAAxgACAKSgoKmrsKCkgAHEAADGgAJAoKClIKUgpQACygACgKCgoKCgpSCgoKCAAIQ8oKCgoKs0pKCAAIS4oKCgoI=")]
[assembly: go.GoPositionMap("runtime/sigqueue.go", "sigqueue.cs", "AEWOAbKCgpaWgIKCuIKCgoKUgrqCgpiCuKSSgoKUggADHQAFKILewpSCgoK6goKYgoKClIKCtoIAAxkABiaCAAQcAA4MgsyCvrKUgoKUqIKWgoKEgoKErLKClISCgqyygpSEgoKEgoIAAhDSgoKssoI=")]
[assembly: go.GoPositionMap("runtime/sigqueue_note.go", "sigqueue_note.cs", "AA8cgtaC1oI=")]
[assembly: go.GoPositionMap("runtime/slice.go", "slice.cs", "AB84gtaCqsKSgoKCgpTKgpaCgoKCuILuqIKCgpSClIKWhAACGAALAoLcgoKUlqaCgoKWgoKWAAVeAC4CgoKClIKUgpaClqaWhILqgpSCgoKCtIKCgoK0gpSUlIKCgoKCtIKCgoKCABAggpaCgsqmgu6mhKiSgoKCloKClLjMgsyClAACGAANBoLKgoKClIKmgqiSgpaCgpaCloKCgoKClIKClIKClqSUlKiSgpSC")]
[assembly: go.GoPositionMap("runtime/softfloat64.go", "softfloat64.cs", "ABc64oKChJSCgpSCqJKCgoLMgrSm4oKChJSCgpSCqJKCgoLMgrSmgqKClIKClIKCgpSCgoKCgqaClIKUgoKmgoKCgpSClIKCgqamgqKClIKClIKCgpSCgoKCgqaClIKUgoKmgoKCgpSClIKCgqamgoKWlKampqam4pSmuIKWgoKCgoKClIKCpoKUpoKmgqaCgpaUpqampgAICIKCgoKmgoKWlKampqb0xoKCpoKCgpSCgpSCpoKCgoKUgoKUpoKChJSmpqaspgAKCKaihJSmpsKUgpSmgoKUgoKUgoKUpoKCgoKUpIKCgoLKgoKCgoKWqqKYgoKCgoKCgoKCqqKEgqiCgoKWgoKCgoKCgoSCgoKCgqiCgoSCgoKCgqimgqaCppSmgoKmgoKmgoKmgoKmgoKmgoKmgqaCpoKmgqaCgqaCgqaCgqaCgqaCgoKUgoKmgoKClIKCpoKCpoKCgoKmgoKmgoKCgg==")]
[assembly: go.GoPositionMap("runtime/stack.go", "stack.cs", "AIEBzgKCgpSCgpSCgrqSgoKClPqigoKClIKClIKUgpSCgoKCgpSUgoKUgoKUlNiSgoKUlJSCgoIADyCCgoIAAxDCgpqigoKCgoKClIKCqJKClIKCgoKCgoKUgoKokoKUgoKCgoKClIKCAAgUAAkIgoKUgpSCloKCgoKUnLKCgoKCgpSCyoKClIKCgoKUgpSUgoKWgoKClISElIKClIKUloKCgoKmgpSClIKUgpQABxLigoKCgpSClIKClIKClJSUgoKCgqaClIKUgoKCgoKUgoKCgpSCgpSCgqaCgoKUpoLugoKCADRyooKCgpSCgoIACyDCgtrCgoKC3IKCgoKmgoKCgoKCgqaCgpSCgpSCgoKmAAkQspSUgoKogoKUpoKCgoLulraCgqiCgpS6goKCgoKClIK4lIKCgpSClIKCpoIACAyigoKUgoKCgoKmgoK4goLK2IKCgoK4pqamgriCgriCgoKCgqassoKYkoIACRSUqIqygoKCgqiCgoKUlvrCgpSCgpTKloKClIKYkoKWgoLKlAAIEqiouoKCgoKogoKChpKCqIKUqJKCgpQADR4ADAKUgpSCgoKCloSUgoKCkoKCgpS6goKWgoKCgroADByCgqaCqIKUgpSUgriCgoKWgoKUgpamgpaCqKiCuoCCgoKCgri4loKClJSCuqiCgpSCqJKqwoKClJSuAAoKgsqCyoIACRSClAAIDuKClIC4lLaCyoKWgpSCppaCpoLugoCCpoKWqKSCgoKCgoKCgoKUlKiCgoKCgoKCpgAOHoKmgoKClKiygoKCgoLcgt7CAAgSgoIAARgACgKCgoKUgpSCgpSmgpSCpg==")]
[assembly: go.GoPositionMap("runtime/stkframe.go", "stkframe.cs", "AESQAZKCuIIABR4ADwKCgoKmmoSC1pQACxiCgpSUgoiCsoKUgqaCgsjq4oKUloKCyoKUuKiCgpSkpIKCgoKCpoKUgpSCgraqkoKmgoKClJSClIKUusyUgoKCgoIABxIACQqCooKCuIKCgoKCpoKU")]
[assembly: go.GoPositionMap("runtime/string.go", "string.cs", "ABcy8oKCgoKCgpSClIKClILMgpSCgoKUpoKmgqaCpoIAAiYAEwK4lILKgpSClIKCgpSWgoKUlIKqooKCpsKCgpSUAAIiAA4CgsqClIKUpqKCgoKUlIKmxoKCloKCgpSWgoKClKaCgsqClIKUgoKClIKClIKUlAANHIKmsoKCgpSUgpSCrsKCqLKCgoKWgqiygpSCgoKWgtiygpaCloKEgqyygoKUgoKssqaCgpSCggAFFrKCloKCgpaCgoKClJSUgoKUlJaClIKWgoKWqqKAgqSqooCCpAACIAAOBIKmgoKCgpTKgqaAlIKClKTIgpSClLS0tLa0goKUgoKUgpSUgpSUqLKCzIKCgoKUnsSCyJSClICCtoKCuIKClIKCgpSokpKCpoKCgoKClIKClIKUlII=")]
[assembly: go.GoPositionMap("runtime/stubs.go", "stubs.cs", "AAswAAwCrAAEIAAPKAAWCKIAAkoAIwaSAAJEACAGkgAFJAANLAAUAoKuwoIAAhgACgSUkpIAAVwALRoADxwACyIAEDYAGgYAAioAFgakAAEWAAoEnurCkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpKSkpSasqyyqLaopJbWAAIQ5gACGAALBJKSkpKSkpKWrA==")]
[assembly: go.GoPositionMap("runtime/stubs2.go", "stubs2.cs", "AAwgtJSSlpKu1qas")]
[assembly: go.GoPositionMap("runtime/stubs3.go", "stubs3.cs", "AAgU")]
[assembly: go.GoPositionMap("runtime/stubs_amd64.go", "stubs_amd64.cs", "AAkUopKSkpKSlqamwpKSkpKSkpKSkpKSkpKWpqzSmA==")]
[assembly: go.GoPositionMap("runtime/stubs_linux.go", "stubs_linux.cs", "AAoWnuKS")]
[assembly: go.GoPositionMap("runtime/symtab.go", "symtab.cs", "AEWeAbKCggAE/AEALwIAAiAADQKClIKCAAIgAA8GgpSChIKUloKUzJaEgoKmlJasspKElJaCggAJFIKU3oKEAA0cgqaCptiCgoKClIKCgqYAavwBAAoCgoKUAAIqABICgoKClIKCgoKCggALGoKCgoKoABs6goIADB4ADASChKaogpSCgoKCgpSCgpSClKiCgoKCloKCggAHLgASAoKCgpSCgqaSgqYAAhLigoKClJSUgpSCgriokoKUAAImABACgoLcgoKUgpIACBCokoKUgpKClKiSgpKClK7ygpKCuIKqooKSgpQAAhLigoKmAAcQgqaCqJIAAhgACQKoAAIkABACgoKUhIKCloKChIKWgpaCAAwagoKUAAIU8oKUqAAPKML4lqSCnLKCgoKCyoKC3IKCgoKClIKC/pSCloKCgpSUgoKSgpKCgoKClO6CgoKmgoKCgoKCgu6ClpS6gpaEgoKCgoKCgpSWgqaCgpSmgoKCgoKmgoKmpoKCgqaAgrYAAhgADAKCgpSCgpSUgqaC1oKCgoKUqJKCgpKSgoKCgoKUuIKmgoKUgqaCgpSCAAIcAAsCgpSqooKUgoKGooKUgoIAAhwAEAaCgpSCgpSChIKCgpSCgqiSooKCgoKClJQACyYADwiClA==")]
[assembly: go.GoPositionMap("runtime/symtabinl.go", "symtabinl.cs", "ADOGAQAQAoKClIKCpoIABxCCqJKCgpSCqJIAAhwACwKClIIABxIAAhAACAKC")]
[assembly: go.GoPositionMap("runtime/sys_nonppc64x.go", "sys_nonppc64x.cs", "AAgS")]
[assembly: go.GoPositionMap("runtime/sys_x86.go", "sys_x86.cs", "AAwgooKCgoKC")]
[assembly: go.GoPositionMap("runtime/tagptr_64bit.go", "tagptr_64bit.cs", "ABpyooKClJSClKiSppSClIKUqJI=")]
[assembly: go.GoPositionMap("runtime/test_amd64.go", "test_amd64.cs", "/g==")]
[assembly: go.GoPositionMap("runtime/time.go", "time.cs", "AFK4AeKCggAhUIKmAAkQhAAMOoKCuKKClIKCgqaClKaCguqSgtiypoKqwoLKAAUUAAkCgoKCgpSClIKCgpaUgoKCgpYACSTygpaCgoKCgpSCkpSCruKCAA8g4oKCgoKUgoKCgoKmgoKuwgACENKClKyyAAUQAAgCpoKWgpSCgoKCAAMS8oIABxCAgoKUAAgS4oKCloKCgpSCgoKCpoKEpt6CpoKCgoKo2sKCgoKUgoKClIKCgpSClAAIEOKClIKUhIKWgoKUgoKCgoKCloKCgoKCpoK4gIKmgriEpt6CpoKCgpSWgpSClurCgoKClJQABSoAHRSCgoKCgoKCgoKCgoKClIKCgoK+su7igoKCgoLegt6CgIKCgoKCgoKUgqaCgpaUloKCgpQABxQACAKCgriCgoKClIKmgoKCgoIABhLygtyCgoKClAA0bIKEgoKCgoKWlJaClLaCgoKCgoKCgraCgrSWgpSEggADFAALDIKCgpQABRoADgKmgpSWgsyCgpSElJaCgoKUgIKClKQABhCCgqaEAAUWAAoCgoKCgpSCgoKWlJaCgoKWgpaUgpaCggAIEgAIAoKCgpS4goKUloKWgoKCgoKUgpKmlIKCgoKCgpSWgpSCqISUgoKUloKWABImhLiCqIK4hIKWgpaCgv7SgoKUqIKCgqaAgoLMwoKClLyigoKClIIABBCyloKCppaAgraEAAQeAAoCgoKUgoKClIKCgpSClIK8ooKCgpSClIKCgpSCgoKUgoKCgoKmgpSClIK8xoKUggAGEMIABhDyppaCgoKUgpSCggAGEMKCgoKClrqCggAHEoKCggAGFOKCgoKClIK4gpQ=")]
[assembly: go.GoPositionMap("runtime/time_nofake.go", "time_nofake.cs", "ABBAAA8CABAosoKU")]
[assembly: go.GoPositionMap("runtime/timeasm.go", "timeasm.cs", "AAsc")]
[assembly: go.GoPositionMap("runtime/tls_stub.go", "tls_stub.cs", "AAgU")]
[assembly: go.GoPositionMap("runtime/trace.go", "trace.cs", "AIkBtALSgqaCqJbelpaCgpYAJlCWqJaCAA8igpSCgpQADR6CzIKCloKogqiWgpSEgoSChIKqogASGAAJArqClILehgAAFO6UgqaSgqYAChaCgoKClIKCgpSClIKolAAIFIKWgoLKgoKCqKYABxKCgoLegoKC3oIAESaCkoKUgoKUAAAQ4pSChIKCgpSCgtyCgoKClJaCgqaClqaCgoKCpgAHFIKClNyClJbegoKCloKCggAJFoKClISUlt6CggAJFIKCgoKUlKiCgrqCgoKUgoKUgqaCgoKmgpSWAAsYgoKCgoKUAAYQhLiCuIK4lKyygpSClIIABhLSgoKCgpSCgqaWgLikgoKmlJbeAAgClIKUpoDchLiCgqaAgoKCtoKCgqqClIKCgqiC7oKCzLiUqMqCzJSUloIAChaCgqaCgoIABhLigoKUrAARHoKUAAsYxIKCgpSWlLqSgoKCABIqkoKCgoKClIIAAhDygoKClIKClIKCrPaCgpTcAAgKgpQAAhQACgSCgpSCloSClII=")]
[assembly: go.GoPositionMap("runtime/traceallocfree.go", "traceallocfree.cs", "ABUwwoiigoKUqIKCgpaWkoKogoKmloKogoKCgpS6kpSmooKUqLKosqiSqLKssqyyqJKokqiSgqiSgqiSqJLYkoKU")]
[assembly: go.GoPositionMap("runtime/traceback.go", "traceback.cs", "AEr0AQAKDubEgAANHKaSgoKCgqaCgoK6goKCgrqCgoKUggAGENyCloKCgoKUgpSClJYABhCCpoIABTAAFwKChIKmgqiCypS4utyCnoKCgoKCgoKCuAAOEIKUgoKCgsaClLqUABs2goKUlIKCgoKmgoK6gpQAEiiClgAJFoKCggAKFgAICqKCgpaCgpSCyoKCypSCgpSClIKClpSCgpaCgpSogoKCgoKogoKCgoKCpKjcsgAoVIKCgoIAAxwACgKUpq7CppaCgoKCgqYAAhgACwKCgoKCloKCtgAHEIKUuIKmqJKCgpaCgoKCloKClIKUgpaSlIKCgpSmgoKogoKCpoKCgoKCgpSkgoKCpKSCpIKkgoKCgoK23sSCgpSCgpSClKiSgqqigoKUgqa0goKCuIKCgoKUgoKClIKCgpSmggACFgAKApSClKa07oKCgoSWlIKClKaCggAtXoKCgoKCgpTKkoKCgoLIlLiClISClIIAAxIACwaClJSCgpSCpoKWgoKCgoKCgoKCgoKWgIKkpoLKgoKClIKUgoKCgpSCpqiAgoKCgoKCgIKktoKCgriUgpSCyKqigoKCgqaCpoKmAAMQwoKCgoKCgpQABDSCgoKqooKClKqigpSWgpbegpaqtIKClIKogoKUgoKUgrqqxgANHKKEhIKGkoKUqIKYkoKUgoKCgpSmgoKUgpSClKaCloKCgoIACBSSgpSCyoKClAAEENKClJSClIKmlIKUgqaClIKogoKUpKSkAAMYAAkEgoKUgpSmppSUAALIAgChAQKCloaWgoKoggAhQpKCgoKUlJaAkoKCgpSUgqzSgoKAgqSmgriUlIKClIKCzJKCppSClIKUqJKClIKmlNqClIKU")]
[assembly: go.GoPositionMap("runtime/tracebuf.go", "tracebuf.cs", "AB0+kgACFPKokqaUrLKCgpSokoKCgpSUgtyygoKClIKCgpSCgoLKgoKUgoKWgoKogpSClIKCgoIABxKygoKUlKiSgoKUgoKUgqaCABMqkoKokoKCgoKCgpSClKyygoKokqaC3sKCgpSUgpSCAAMS8gAIFIKogg==")]
[assembly: go.GoPositionMap("runtime/tracecpu.go", "tracecpu.cs", "AA8YsoK4ggAHEILewoKmgoKSAAoWhJKUlIKCgqaU3LKCAAgUgoKCgpaWgoKCAAIgAA0ChIKCgpSClIKogoKCgIKkgoKolsqEpqiCgoKohpKSlKiWgoKCgoKElKq0gIKSgoKCAAUQ8qaUpgAGEIKCgpSCpoKUlorCppSUgpSWlJaAuKaWgg==")]
[assembly: go.GoPositionMap("runtime/traceevent.go", "traceevent.cs", "AE3yAQANAoKAgqSAgrSqwoKosoKokqjEloKClIKWgoKClKyyAAIQ5AAFErKssqiS")]
[assembly: go.GoPositionMap("runtime/traceexp.go", "traceexp.cs", "AA8s8qyygoKU")]
[assembly: go.GoPositionMap("runtime/tracemap.go", "tracemap.cs", "ADZyogACEuKClISCgoKCggAPIIKUgsqUgoKmgriUypaCgoKCrsKCgg==")]
[assembly: go.GoPositionMap("runtime/traceregion.go", "traceregion.cs", "AC5WsoKClIKogoKCgrqogoKCgoKogqiCgrqCloKCruKCgoKClICCgqQ=")]
[assembly: go.GoPositionMap("runtime/traceruntime.go", "traceruntime.cs", "ABEokgAbQLaCgoKCgoKCggACEuIANI4Bsq7CqJIAES7SgpQAAhgACQKClAAFFAAKCJYABhCCggAJFoKCgoKUAAIUAAoIloKUAAIQ0gAFENKCgoKUrLKokqiSrLK4qLauwqauwqauwqaotqi2AAUUAAkGgoKUAAIWAAgCgoKCgpQABhLSgoKUgoKUqJKokqiygoKClKyygoKCgoKUrLKokqiSqJKuwqjEpoKq1KaCgoKUqsK4lKzEgoIAAhgACQKCgoKClJQAAhAACASCAAYQgoKCgpTeppSokqiSgpSUAAISAAoGggACEgAIBgACEuKClJSCrLKClJSCAAIS4oKUlIKUtLSkgqyygpSUggACEgAIAgAHEoKClIKCgqaCppSCgoI=")]
[assembly: go.GoPositionMap("runtime/tracestack.go", "tracestack.cs", "ABVMAAwChpKCgqiClMq0gpS0gsqmlILugoKkuIKCABIkgoKUgriClIKUggAIFqKClIKssoKCgIKkgqaiqIKojtKCgqiCgoKCgoKCqIKCgpSUqqKCgoKCgoIACxqSgoSCgoKUgoKCgpSCqqKu4pSUlKiSAAIYAAkCgsiW3oKkgpSYgoKCgqaAgqSWgoKCpJKkxqyygoKUgoKU")]
[assembly: go.GoPositionMap("runtime/tracestatus.go", "tracestatus.cs", "AB5ipIKCqIKUqIKU3uKClIKUgqa2isK2pKSC3tSCgqiWgpTstJKUpKQAAhKC8rakpAAWMpKClIKokoKCqJKqoqiSgg==")]
[assembly: go.GoPositionMap("runtime/tracestring.go", "tracestring.cs", "ABcyxIKClIKmqKSCgpQAAhAACASCloKGkpKUqIKCgpaCruKCgoKClKg=")]
[assembly: go.GoPositionMap("runtime/tracetime.go", "tracetime.cs", "ACtwAAoCgpSqopS4rLKWpoKWkoKC")]
[assembly: go.GoPositionMap("runtime/tracetype.go", "tracetype.cs", "ABUy4oKmgqyygoCCpIKmooKWjtKClKiCgoKCgpaCgoKUlA==")]
[assembly: go.GoPositionMap("runtime/type.go", "type.cs", "ACAygoKClKaCpoKClIKCgoKUtLSUrsKAgqSUgqSCpAAZLoKCgriCgpQABhgACQKClIKCgoKCgpS6goKCgoKClJSmggAGGAAJAqaUgoKCgoKmgoKCgoKCgpSUlICCpIKCgpSmgtaCppSCgoKCgqaCgoKCgoKClJSUggACLoKClIKCgoKUgoKCqqKClISCgpSCgoKClKaCgoKmtriCgoKCgoKCgoKmqAAIEoIABR4ADwKCgILchIKUgoKUgoKUgoKCgpSCgoKmgpSUpIKCpIKCpIKCgpSCgoKmgoKCpqSCgoKUgpSCgqaCgoKUgpSCgoKmpIKCpIKCpIKCpIKCgpSClIKCgoKUgpSClIKUgqakgoI=")]
[assembly: go.GoPositionMap("runtime/typekind.go", "typekind.cs", "AAoUkg==")]
[assembly: go.GoPositionMap("runtime/unsafe.go", "unsafe.cs", "AAsYgoKWgoKUupKCgpTWgqiC6ILWgqiSgpaCgqiCgoKUupKCgpTWgqiCuKbYkoKmptiSgqiS")]
[assembly: go.GoPositionMap("runtime/utf8.go", "utf8.cs", "ACNWkoKClAACGAAMAoSCloSWkoKCgtqSgoKC2pKCgoLaqrSApIKkgoKCpIKkgoKCgqSCgoKCgg==")]
[assembly: go.GoPositionMap("runtime/vdso_linux.go", "vdso_linux.cs", "ACqCAZCigAAiSLKChIiigoKClIKCuLiCqpKCgoKCgoKClKSkpKSkuIKWgpaUgoKCgoKmgoKCqKaigpaCgoKCgqiClJamooKWgoKClIKUgqaCloKWlIKCgoLKqIKCgpSCgpSCppTcgpSUlIaCos6ygoKCpg==")]
[assembly: go.GoPositionMap("runtime/write_err.go", "write_err.cs", "AAgUkoI=")]
// </GoSourcePositionMaps>

namespace go;

[GoPackage("runtime")]
public static partial class runtime_package
{
    // C# nested types declared with no access modifier are always private, and the
    // `[GoType]` declarations in this package's converted sources are deliberately
    // bare so they read more like the original Go code. The real accessibility for
    // the types - public for a Go-exported name, internal otherwise - are defined
    // via declarations below.

    // <TypeAccessibility>
    internal partial interface floaty<ΔT> {}
    internal partial interface ifaceHash_i {}
    internal partial interface stringer {}
    internal partial struct _typePair {}
    internal partial struct activeSweep {}
    internal partial struct addrRange {}
    internal partial struct addrRanges {}
    internal partial struct adjustinfo {}
    internal partial struct arenaHint {}
    internal partial struct arenaIdx {}
    internal partial struct argset {}
    internal partial struct atomicHeadTailIndex {}
    internal partial struct atomicMSpanPointer {}
    internal partial struct atomicOffAddr {}
    internal partial struct atomicScavChunkData {}
    internal partial struct atomicSpanSetSpinePointer {}
    internal partial struct bitvector {}
    internal partial struct blockRecord {}
    [GoValueClone("tophash")] internal partial struct bmap {}
    internal partial struct boundsError {}
    internal partial struct boundsErrorCode {}
    internal partial struct bucket {}
    internal partial struct bucketType {}
    internal partial struct buckhashArray {}
    internal partial struct cgoContextArg {}
    internal partial struct cgoSymbolizerArg {}
    internal partial struct cgoTracebackArg {}
    internal partial struct cgothreadstart {}
    [GoLocalName("x1t")] internal partial struct check_x1t {}
    [GoLocalName("y1t")] internal partial struct check_y1t {}
    [GoValueClone("b")] internal partial struct checkmarksMap {}
    internal partial struct childInfo {}
    internal partial struct chunkIdx {}
    [GoValueClone("stats")] internal partial struct consistentHeapStats {}
    internal partial struct coro {}
    [GoValueClone("extra")] internal partial struct cpuProfile {}
    internal partial struct cpuStats {}
    internal partial struct cpuStatsAggregate {}
    internal partial struct dbgVar {}
    internal partial struct debugCallWrapArgs {}
    [GoValueClone("b")] internal partial struct debugLogBuf {}
    internal partial struct debugLogReader {}
    [GoValueClone("data", "buf")] internal partial struct debugLogWriter {}
    internal partial struct debugPtrmaskᴛ1 {}
    internal partial struct debugᴛ1 {}
    internal partial struct dlogPerM {}
    [GoValueClone("w")] internal partial struct dlogger {}
    internal partial struct elfDyn {}
    [GoValueClone("e_ident")] internal partial struct elfEhdr {}
    internal partial struct elfPhdr {}
    internal partial struct elfShdr {}
    internal partial struct elfSym {}
    internal partial struct elfVerdaux {}
    internal partial struct elfVerdef {}
    internal partial struct errorAddressString {}
    internal partial struct errorString {}
    internal partial struct evacDst {}
    internal partial struct find_firstFree {}
    [GoValueClone("subbuckets")] internal partial struct findfuncbucket {}
    internal partial struct fixalloc {}
    [GoValueClone("significand")] internal partial struct fpreg1 {}
    [GoValueClone("_st", "_xmm", "padding")] internal partial struct fpstate {}
    [GoValueClone("_st", "_xmm", "padding")] internal partial struct fpstate1 {}
    [GoValueClone("significand", "padding")] internal partial struct fpxreg {}
    [GoValueClone("significand", "padding")] internal partial struct fpxreg1 {}
    internal partial struct functab {}
    internal partial struct gList {}
    internal partial struct gQueue {}
    internal partial struct gTraceState {}
    internal partial struct gcBgMarkWorkerNode {}
    internal partial struct gcBits {}
    [GoValueClone("bits")] internal partial struct gcBitsArena {}
    internal partial struct gcBitsArenasᴛ1 {}
    internal partial struct gcBitsHeader {}
    internal partial struct gcCPULimiterState {}
    internal partial struct gcCPULimiterState_bucket {}
    [GoValueClone("lastConsMark")] internal partial struct gcControllerState {}
    internal partial struct gcDebugMarkDoneᴛ1 {}
    internal partial struct gcDrainFlags {}
    internal partial struct gcMarkWorkerMode {}
    internal partial struct gcMode {}
    internal partial struct gcStatsAggregate {}
    internal partial struct gcTrigger {}
    internal partial struct gcTriggerKind {}
    internal partial struct gcWork {}
    internal partial struct gclink {}
    internal partial struct gclinkptr {}
    internal partial struct globalAllocᴛ1 {}
    [GoValueClone("seed", "state")] internal partial struct globalRandᴛ1 {}
    internal partial struct godebugInc {}
    internal partial struct goroutineProfileState {}
    internal partial struct goroutineProfileStateHolder {}
    internal partial struct goroutineProfileᴛ1 {}
    internal partial struct gsignalStack {}
    internal partial struct headTailIndex {}
    [GoValueClone("spans", "pageInUse", "pageMarks", "pageSpecials")] internal partial struct heapArena {}
    internal partial struct heapStatsAggregate {}
    [GoValueClone("smallAllocCount", "smallFreeCount")] internal partial struct heapStatsDelta {}
    internal partial struct hiter {}
    internal partial struct hmap {}
    internal partial struct initTask {}
    internal partial struct inlineFrame {}
    internal partial struct inlineUnwinder {}
    internal partial struct inlinedCall {}
    [GoValueClone("entries")] internal partial struct itabTableType {}
    internal partial struct itimerspec {}
    internal partial struct itimerval {}
    internal partial struct lfstack {}
    internal partial struct limiterEvent {}
    internal partial struct limiterEventStamp {}
    internal partial struct limiterEventType {}
    internal partial struct linearAlloc {}
    internal partial struct liveUserArenaChunk {}
    internal partial struct lockRank {}
    internal partial struct lockRankStruct {}
    internal partial struct lockTimer {}
    internal partial struct mLockProfile {}
    internal partial struct mOS {}
    internal partial struct mProfCycleHolder {}
    internal partial struct mSpanList {}
    internal partial struct mSpanState {}
    internal partial struct mSpanStateBox {}
    [GoValueClone("buf")] internal partial struct mTraceState {}
    internal partial struct mapextra {}
    internal partial struct markBits {}
    [GoValueClone("alloc", "stackcache")] internal partial struct mcache {}
    [GoValueClone("partial", "full")] internal partial struct mcentral {}
    [GoValueClone("gregs", "__reserved1")] internal partial struct mcontext {}
    [GoValueClone("future")] internal partial struct memRecord {}
    internal partial struct memRecordCycle {}
    [GoValueClone("deps")] internal partial struct metricData {}
    internal partial struct metricFloat64Histogram {}
    internal partial struct metricKind {}
    internal partial struct metricName {}
    internal partial struct metricSample {}
    internal partial struct metricValue {}
    [GoValueClone("pages", "arenas", "central")] internal partial struct mheap {}
    [GoValueClone("mcentral", "pad")] internal partial struct mheap_central {}
    internal partial struct mheap_curArena {}
    internal partial struct mheap_userArena {}
    internal partial struct mlink {}
    internal partial struct moduledata {}
    internal partial struct modulehash {}
    internal partial struct mspan {}
    [GoValueClone("heapStats", "pause_ns", "pause_end")] internal partial struct mstats {}
    internal partial struct neverCallThisFunction {}
    internal partial struct newmHandoffᴛ1 {}
    internal partial struct notInHeap {}
    internal partial struct notInHeapSlice {}
    internal partial struct notifyList {}
    internal partial struct offAddr {}
    internal partial struct pMask {}
    internal partial struct pTraceState {}
    [GoValueClone("summary", "chunks")] internal partial struct pageAlloc {}
    internal partial struct pageAlloc_scav {}
    internal partial struct pageBits {}
    internal partial struct pageCache {}
    internal partial struct pallocBits {}
    [GoValueClone("scavenged")] internal partial struct pallocData {}
    internal partial struct pallocSum {}
    internal partial struct pcHeader {}
    [GoValueClone("entries")] internal partial struct pcvalueCache {}
    internal partial struct pcvalueCacheEnt {}
    internal partial struct perThreadSyscallArgs {}
    internal partial struct persistentAlloc {}
    internal partial struct piController {}
    internal partial struct pinState {}
    [GoValueClone("refStore")] internal partial struct pinner {}
    internal partial struct pinnerBits {}
    internal partial struct plainError {}
    internal partial struct pollCache {}
    internal partial struct pollDesc {}
    internal partial struct pollInfo {}
    internal partial struct printDebugLog_best {}
    [GoLocalName("readState")] internal partial struct printDebugLog_readState {}
    internal partial struct profAtomic {}
    internal partial struct profBuf {}
    internal partial struct profBufReadMode {}
    internal partial struct profIndex {}
    internal partial struct profᴛ1 {}
    internal partial struct ptabEntry {}
    internal partial struct randomEnum {}
    internal partial struct randomOrder {}
    internal partial struct reflectMethodValue {}
    internal partial struct reflectOffsᴛ1 {}
    internal partial struct runtimeSelect {}
    internal partial struct rwmutex {}
    internal partial struct scase {}
    internal partial struct scavChunkData {}
    internal partial struct scavChunkFlags {}
    internal partial struct scavengeIndex {}
    internal partial struct scavengerState {}
    internal partial struct selectDir {}
    internal partial struct semTable {}
    [GoValueClone("pad")] internal partial struct semTableᴛ1 {}
    internal partial struct semaProfileFlags {}
    internal partial struct semaRoot {}
    internal partial struct sigTabT {}
    internal partial struct sigactiont {}
    [GoValueClone("__reserved1")] internal partial struct sigcontext {}
    internal partial struct sigctxt {}
    internal partial struct sigevent {}
    internal partial struct sigeventFields {}
    internal partial struct siginfo {}
    internal partial struct siginfoFields {}
    internal partial struct sigset {}
    [GoValueClone("mask", "wanted", "ignored", "recv")] internal partial struct sigᴛ1 {}
    internal partial struct sliceInterfacePtr {}
    [GoValueClone("path")] internal partial struct sockaddr_un {}
    internal partial struct spanAllocType {}
    internal partial struct spanClass {}
    internal partial struct spanSet {}
    [GoValueClone("spans")] internal partial struct spanSetBlock {}
    internal partial struct spanSetBlockAlloc {}
    internal partial struct spanSetSpinePointer {}
    internal partial struct special {}
    internal partial struct specialPinCounter {}
    internal partial struct specialReachable {}
    internal partial struct specialWeakHandle {}
    internal partial struct specialfinalizer {}
    internal partial struct specialprofile {}
    internal partial struct specialsIter {}
    [GoValueClone("free")] internal partial struct stackLargeᴛ1 {}
    internal partial struct stackObject {}
    [GoValueClone("obj")] internal partial struct stackObjectBuf {}
    internal partial struct stackObjectBufHdr {}
    internal partial struct stackObjectRecord {}
    internal partial struct stackScanState {}
    [GoValueClone("obj")] internal partial struct stackWorkBuf {}
    internal partial struct stackWorkBufHdr {}
    internal partial struct stackfreelist {}
    [GoValueClone("bytedata")] internal partial struct stackmap {}
    internal partial struct stackpoolItem {}
    internal partial struct stackpoolᴛ1 {}
    [GoValueClone("pad_cgo_0")] internal partial struct stackt {}
    [GoValueClone("ensured")] internal partial struct statAggregate {}
    internal partial struct statDep {}
    internal partial struct statDepSet {}
    internal partial struct stkframe {}
    internal partial struct stringInterfacePtr {}
    internal partial struct stringStruct {}
    internal partial struct stringStructDWARF {}
    internal partial struct stwReason {}
    internal partial struct suspendGState {}
    internal partial struct sweepClass {}
    internal partial struct sweepLocked {}
    internal partial struct sweepLocker {}
    internal partial struct sweepdata {}
    internal partial struct sysMemStat {}
    internal partial struct sysStatsAggregate {}
    internal partial struct sysmontick {}
    internal partial struct taggedPointer {}
    internal partial struct textsect {}
    internal partial struct throwType {}
    internal partial struct ticksType {}
    [GoValueClone("counts")] internal partial struct timeHistogram {}
    internal partial struct timeTimer {}
    internal partial struct timer {}
    internal partial struct timerWhen {}
    internal partial struct timers {}
    internal partial struct timespec {}
    internal partial struct timeval {}
    internal partial struct tmpBuf {}
    [GoLocalName("untracedG")] internal partial struct traceAdvance_untracedG {}
    internal partial struct traceAdvancerState {}
    internal partial struct traceArg {}
    internal partial struct traceBlockReason {}
    [GoValueClone("arr")] internal partial struct traceBuf {}
    internal partial struct traceBufHeader {}
    internal partial struct traceBufQueue {}
    internal partial struct traceEv {}
    internal partial struct traceEventWriter {}
    internal partial struct traceExpWriter {}
    internal partial struct traceExperiment {}
    internal partial struct traceFrame {}
    internal partial struct traceGoStatus {}
    internal partial struct traceGoStopReason {}
    internal partial struct traceLocker {}
    internal partial struct traceMap {}
    [GoValueClone("children")] internal partial struct traceMapNode {}
    internal partial struct traceProcStatus {}
    internal partial struct traceRegionAlloc {}
    [GoValueClone("data")] internal partial struct traceRegionAllocBlock {}
    internal partial struct traceRegionAllocBlockHeader {}
    [GoValueClone("statusTraced", "seq")] internal partial struct traceSchedResourceState {}
    internal partial struct traceStackTable {}
    internal partial struct traceStringTable {}
    internal partial struct traceTime {}
    internal partial struct traceTypeTable {}
    internal partial struct traceWriter {}
    internal partial struct tracestat {}
    [GoValueClone("t")] internal partial struct typeCacheBucket {}
    internal partial struct typePointers {}
    [GoValueClone("uc_stack", "uc_mcontext", "uc_sigmask", "__fpregs_mem")] internal partial struct ucontext {}
    internal partial struct uint16InterfacePtr {}
    internal partial struct uint32InterfacePtr {}
    internal partial struct uint64InterfacePtr {}
    internal partial struct unwindFlags {}
    internal partial struct unwinder {}
    internal partial struct userArena {}
    internal partial struct userArenaStateᴛ1 {}
    [GoValueClone("__val")] internal partial struct usigset {}
    internal partial struct vdsoInfo {}
    internal partial struct vdsoSymbolKey {}
    internal partial struct vdsoVersionKey {}
    internal partial struct waitq {}
    internal partial struct wakeableSleep {}
    [GoValueClone("buf")] internal partial struct wbBuf {}
    internal partial struct winlibcall {}
    internal partial struct workType {}
    internal partial struct workType_assistQueue {}
    internal partial struct workType_strongFromWeak {}
    internal partial struct workType_sweepWaiters {}
    internal partial struct workType_wbufSpans {}
    [GoValueClone("obj")] internal partial struct workbuf {}
    internal partial struct workbufhdr {}
    internal partial struct worldStop {}
    [GoValueClone("pad")] internal partial struct writeBarrierᴛ1 {}
    [GoValueClone("element")] internal partial struct xmmreg {}
    [GoValueClone("element")] internal partial struct xmmreg1 {}
    public partial interface ΔError {}
    public partial struct BlockProfileRecord {}
    public partial struct Frame {}
    [GoValueClone("frameStore")] public partial struct Frames {}
    public partial struct Func {}
    [GoValueClone("Stack0")] public partial struct MemProfileRecord {}
    [GoValueClone("PauseNs", "PauseEnd", "BySize")] public partial struct MemStats {}
    public partial struct MemStats_BySize {}
    public partial struct PanicNilError {}
    public partial struct Pinner {}
    [GoValueClone("Stack0")] public partial struct StackRecord {}
    public partial struct TypeAssertionError {}
    public partial struct ΔcgoCallers {}
    public partial struct ΔfuncInfo {}
    public partial struct Δhchan {}
    public partial struct Δhex {}
    public partial struct Δrtype {}
    public partial struct Δscavengeᴛ1 {}
    public partial struct Δsliceᴛ {}
    public partial struct ΔsrcFunc {}
    [GoValueClone("full", "doneSema", "stackTab", "stringTab", "typeTab", "cpuLogRead", "cpuLogWrite", "cpuBuf", "markWorkerLabels", "goStopReasons", "goBlockReasons")] public partial struct Δtraceᴛ1 {}
    public partial struct ΔwriteUserArenaHeapBits {}
    // </TypeAccessibility>
}
