// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto.@internal.fips140;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/internal/fips140/nistec", new string[]
        {
            "benchmark_test.go",
            "generate.go",
            "nistec.go",
            "p224.go",
            "p224_sqrt.go",
            "p256.go",
            "p256_asm.go",
            "p256_asm_test.go",
            "p256_ordinv.go",
            "p256_ordinv_noasm.go",
            "p256_table.go",
            "p256_table_test.go",
            "p384.go",
            "p521.go",
        }, new string[]
        {
            "_asm",
            "fiat",
        });
        registry.Add("TestP256PrecomputedTable", nistec_internal_test_package.TestP256PrecomputedTable, "p256_table_test.go", 16);
        return TestHost.Run(registry, args);
    }
}
