// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.testing;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("testing/slogtest", new string[]
        {
            "example_test.go",
            "run_test.go",
            "slogtest.go",
        });
        registry.Add("TestRun", slogtest_test_package.TestRun, "run_test.go", 15);
        return TestHost.Run(registry, args);
    }
}
