// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.regexp;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("regexp/syntax", new string[]
        {
            "compile.go",
            "doc.go",
            "op_string.go",
            "parse.go",
            "parse_test.go",
            "perl_groups.go",
            "prog.go",
            "prog_test.go",
            "regexp.go",
            "simplify.go",
            "simplify_test.go",
        });
        registry.Add("TestAppendRangeCollapse", syntax_package.TestAppendRangeCollapse, "parse_test.go", 442);
        registry.Add("TestCompile", syntax_package.TestCompile, "prog_test.go", 109);
        registry.Add("TestFoldConstants", syntax_package.TestFoldConstants, "parse_test.go", 426);
        registry.Add("TestParseFoldCase", syntax_package.TestParseFoldCase, "parse_test.go", 236);
        registry.Add("TestParseInvalidRegexps", syntax_package.TestParseInvalidRegexps, "parse_test.go", 525);
        registry.Add("TestParseLiteral", syntax_package.TestParseLiteral, "parse_test.go", 244);
        registry.Add("TestParseMatchNL", syntax_package.TestParseMatchNL, "parse_test.go", 255);
        registry.Add("TestParseNoMatchNL", syntax_package.TestParseNoMatchNL, "parse_test.go", 266);
        registry.Add("TestParseSimple", syntax_package.TestParseSimple, "parse_test.go", 220);
        registry.Add("TestSimplify", syntax_package.TestSimplify, "simplify_test.go", 141);
        registry.Add("TestString", syntax_package.TestString, "parse_test.go", 616);
        registry.Add("TestToStringEquivalentParse", syntax_package.TestToStringEquivalentParse, "parse_test.go", 552);
        return TestHost.Run(registry, args);
    }
}
