// Code generated by go2cs. DO NOT EDIT.
// Test-variant package-level variable initialization ordered to match Go's
// dependency order (types.Info.InitOrder) — see package_init.cs. Each initᴛ
// method lives beside its variable's declaration in the converted test file.
namespace go.encoding;

partial class gob_internal_test_package {
    static gob_internal_test_package() {
        initᴛbasicTypes();
    }
} // end gob_internal_test_package
