// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.net;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("net/netip", new string[]
        {
            "export_test.go",
            "fuzz_test.go",
            "inlining_test.go",
            "netip.go",
            "netip_pkg_test.go",
            "netip_test.go",
            "slow_test.go",
            "uint128.go",
            "uint128_test.go",
        });
        registry.Add("TestAddrAppendText", netip_test_package.TestAddrAppendText, "netip_test.go", 355);
        registry.Add("TestAddrFrom16", netip_test_package.TestAddrFrom16, "netip_test.go", 652);
        registry.Add("TestAddrFromSlice", netip_test_package.TestAddrFromSlice, "netip_test.go", 314);
        registry.Add("TestAddrLessCompare", netip_test_package.TestAddrLessCompare, "netip_test.go", 972);
        registry.Add("TestAddrMarshalUnmarshal", netip_test_package.TestAddrMarshalUnmarshal, "netip_test.go", 629);
        registry.Add("TestAddrMarshalUnmarshalBinary", netip_test_package.TestAddrMarshalUnmarshalBinary, "netip_test.go", 381);
        registry.Add("TestAddrPortCompare", netip_test_package.TestAddrPortCompare, "netip_test.go", 1057);
        registry.Add("TestAddrPortMarshalTextString", netip_test_package.TestAddrPortMarshalTextString, "netip_test.go", 439);
        registry.Add("TestAddrPortMarshalUnmarshal", netip_package.TestAddrPortMarshalUnmarshal, "netip_pkg_test.go", 302);
        registry.Add("TestAddrPortMarshalUnmarshalBinary", netip_test_package.TestAddrPortMarshalUnmarshalBinary, "netip_test.go", 477);
        registry.Add("TestAddrPortString", netip_test_package.TestAddrPortString, "netip_test.go", 2286);
        registry.Add("TestAddrStringAllocs", netip_test_package.TestAddrStringAllocs, "netip_test.go", 2239);
        registry.Add("TestAddrWellKnown", netip_test_package.TestAddrWellKnown, "netip_test.go", 927);
        registry.Add("TestAs4", netip_test_package.TestAs4, "netip_test.go", 2015);
        registry.Add("TestAsSlice", netip_test_package.TestAsSlice, "netip_test.go", 2305);
        registry.Add("TestBitsClearedFrom", netip_package.TestBitsClearedFrom, "uint128_test.go", 69);
        registry.Add("TestBitsSetFrom", netip_package.TestBitsSetFrom, "uint128_test.go", 47);
        registry.Add("TestIPBitLen", netip_package.TestIPBitLen, "netip_pkg_test.go", 130);
        registry.Add("TestIPNextPrev", netip_package.TestIPNextPrev, "netip_pkg_test.go", 77);
        registry.Add("TestIPProperties", netip_test_package.TestIPProperties, "netip_test.go", 679);
        registry.Add("TestIPStringExpanded", netip_test_package.TestIPStringExpanded, "netip_test.go", 1160);
        registry.Add("TestIPv4Constructors", netip_test_package.TestIPv4Constructors, "netip_test.go", 349);
        registry.Add("TestIPv6Accessor", netip_package.TestIPv6Accessor, "netip_pkg_test.go", 354);
        registry.Add("TestInlining", netip_package.TestInlining, "inlining_test.go", 16);
        registry.Add("TestIs4AndIs6", netip_test_package.TestIs4AndIs6, "netip_test.go", 1374);
        registry.Add("TestIs4In6", netip_test_package.TestIs4In6, "netip_test.go", 1401);
        registry.Add("TestNoAllocs", netip_test_package.TestNoAllocs, "netip_test.go", 2135);
        registry.Add("TestParseAddr", netip_test_package.TestParseAddr, "netip_test.go", 33);
        registry.Add("TestParseAddrPort", netip_package.TestParseAddrPort, "netip_pkg_test.go", 237);
        registry.Add("TestParseIPError", netip_package.TestParseIPError, "netip_pkg_test.go", 193);
        registry.Add("TestParsePrefixAllocs", netip_test_package.TestParsePrefixAllocs, "netip_test.go", 1586);
        registry.Add("TestParsePrefixError", netip_test_package.TestParsePrefixError, "netip_test.go", 1610);
        registry.Add("TestPrefix", netip_test_package.TestPrefix, "netip_test.go", 1463);
        registry.Add("TestPrefixCompare", netip_test_package.TestPrefixCompare, "netip_test.go", 1108);
        registry.Add("TestPrefixContains", netip_package.TestPrefixContains, "netip_pkg_test.go", 150);
        registry.Add("TestPrefixFromInvalidBits", netip_test_package.TestPrefixFromInvalidBits, "netip_test.go", 1557);
        registry.Add("TestPrefixIsSingleIP", netip_test_package.TestPrefixIsSingleIP, "netip_test.go", 1678);
        registry.Add("TestPrefixMarshalTextString", netip_test_package.TestPrefixMarshalTextString, "netip_test.go", 534);
        registry.Add("TestPrefixMarshalUnmarshal", netip_test_package.TestPrefixMarshalUnmarshal, "netip_test.go", 1333);
        registry.Add("TestPrefixMarshalUnmarshalBinary", netip_test_package.TestPrefixMarshalUnmarshalBinary, "netip_test.go", 571);
        registry.Add("TestPrefixMasked", netip_test_package.TestPrefixMasked, "netip_test.go", 1431);
        registry.Add("TestPrefixMasking", netip_test_package.TestPrefixMasking, "netip_test.go", 1199);
        registry.Add("TestPrefixOverlaps", netip_test_package.TestPrefixOverlaps, "netip_test.go", 2064);
        registry.Add("TestPrefixString", netip_test_package.TestPrefixString, "netip_test.go", 2269);
        registry.Add("TestPrefixUnmarshalTextNonZero", netip_test_package.TestPrefixUnmarshalTextNonZero, "netip_test.go", 1367);
        registry.Add("TestPrefixValid", netip_package.TestPrefixValid, "netip_pkg_test.go", 20);
        registry.Add("TestUint128AddSub", netip_package.TestUint128AddSub, "uint128_test.go", 11);
        return TestHost.Run(registry, args);
    }
}
