// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("time", new string[]
        {
            "embed.go",
            "example_test.go",
            "export_android_test.go",
            "export_test.go",
            "export_windows_test.go",
            "format.go",
            "format_rfc3339.go",
            "format_test.go",
            "genzabbrs.go",
            "internal_test.go",
            "mono_test.go",
            "sleep.go",
            "sleep_test.go",
            "sys_plan9.go",
            "sys_unix.go",
            "sys_windows.go",
            "testdata/2020b_Europe_Berlin",
            "testdata/2021a_America_Nuuk",
            "testdata/2021a_Asia_Gaza",
            "testdata/2021a_Europe_Dublin",
            "tick.go",
            "tick_test.go",
            "time.go",
            "time_test.go",
            "tzdata_test.go",
            "zoneinfo.go",
            "zoneinfo_abbrs_windows.go",
            "zoneinfo_android.go",
            "zoneinfo_android_test.go",
            "zoneinfo_goroot.go",
            "zoneinfo_ios.go",
            "zoneinfo_js.go",
            "zoneinfo_plan9.go",
            "zoneinfo_read.go",
            "zoneinfo_test.go",
            "zoneinfo_unix.go",
            "zoneinfo_unix_test.go",
            "zoneinfo_wasip1.go",
            "zoneinfo_windows.go",
            "zoneinfo_windows_test.go",
        }, new string[]
        {
            "testdata",
            "tzdata",
        });
        registry.Add("Test12AMIsMidnight", time_test_package.Test12AMIsMidnight, "format_test.go", 747);
        registry.Add("Test12PMIsNoon", time_test_package.Test12PMIsNoon, "format_test.go", 730);
        registry.Add("TestAddDate", time_test_package.TestAddDate, "time_test.go", 676);
        registry.Add("TestAddToExactSecond", time_test_package.TestAddToExactSecond, "time_test.go", 712);
        registry.Add("TestAdjustTimers", time_test_package.TestAdjustTimers, "sleep_test.go", 724);
        registry.Add("TestAfter", time_test_package.TestAfter, "sleep_test.go", 320);
        registry.Add("TestAfterFunc", time_test_package.TestAfterFunc, "sleep_test.go", 75);
        registry.Add("TestAfterFuncStarvation", time_test_package.TestAfterFuncStarvation, "sleep_test.go", 139);
        registry.Add("TestAfterQueuing", time_test_package.TestAfterQueuing, "sleep_test.go", 420);
        registry.Add("TestAfterStop", time_test_package.TestAfterStop, "sleep_test.go", 355);
        registry.Add("TestAfterTick", time_test_package.TestAfterTick, "sleep_test.go", 333);
        registry.Add("TestAfterTimes", time_test_package.TestAfterTimes, "tick_test.go", 660);
        registry.Add("TestAppendInt", time_test_package.TestAppendInt, "format_test.go", 93);
        registry.Add("TestAusZoneAbbr", time_test_package.TestAusZoneAbbr, "zoneinfo_windows_test.go", 33);
        registry.Add("TestBadLocationErrMsg", time_test_package.TestBadLocationErrMsg, "zoneinfo_test.go", 40);
        registry.Add("TestChan", time_test_package.TestChan, "tick_test.go", 309);
        registry.Add("TestConcurrentTimerReset", time_test_package.TestConcurrentTimerReset, "time_test.go", 1696);
        registry.Add("TestConcurrentTimerResetStop", time_test_package.TestConcurrentTimerResetStop, "time_test.go", 1714);
        registry.Add("TestCountMallocs", time_test_package.TestCountMallocs, "time_test.go", 1060);
        registry.Add("TestDate", time_test_package.TestDate, "time_test.go", 651);
        registry.Add("TestDaysIn", time_test_package.TestDaysIn, "time_test.go", 699);
        registry.Add("TestDefaultLoc", time_test_package.TestDefaultLoc, "time_test.go", 1403);
        registry.Add("TestDurationAbs", time_test_package.TestDurationAbs, "time_test.go", 1310);
        registry.Add("TestDurationHours", time_test_package.TestDurationHours, "time_test.go", 1226);
        registry.Add("TestDurationMicroseconds", time_test_package.TestDurationMicroseconds, "time_test.go", 1157);
        registry.Add("TestDurationMilliseconds", time_test_package.TestDurationMilliseconds, "time_test.go", 1173);
        registry.Add("TestDurationMinutes", time_test_package.TestDurationMinutes, "time_test.go", 1207);
        registry.Add("TestDurationNanoseconds", time_test_package.TestDurationNanoseconds, "time_test.go", 1141);
        registry.Add("TestDurationRound", time_test_package.TestDurationRound, "time_test.go", 1286);
        registry.Add("TestDurationSeconds", time_test_package.TestDurationSeconds, "time_test.go", 1188);
        registry.Add("TestDurationString", time_test_package.TestDurationString, "time_test.go", 609);
        registry.Add("TestDurationTruncate", time_test_package.TestDurationTruncate, "time_test.go", 1253);
        registry.Add("TestEarlyLocation", time_test_package.TestEarlyLocation, "zoneinfo_test.go", 160);
        registry.Add("TestEmbeddedTZData", time_test_package.TestEmbeddedTZData, "tzdata_test.go", 19);
        registry.Add("TestEnvVarUsage", time_test_package.TestEnvVarUsage, "zoneinfo_test.go", 23);
        registry.Add("TestFirstZone", time_test_package.TestFirstZone, "zoneinfo_test.go", 81);
        registry.Add("TestFormat", time_test_package.TestFormat, "format_test.go", 178);
        registry.Add("TestFormatAndParse", time_test_package.TestFormatAndParse, "format_test.go", 551);
        registry.Add("TestFormatFractionalSecondSeparators", time_test_package.TestFormatFractionalSecondSeparators, "format_test.go", 933);
        registry.Add("TestFormatSecondsInTimeZone", time_test_package.TestFormatSecondsInTimeZone, "format_test.go", 822);
        registry.Add("TestFormatShortYear", time_test_package.TestFormatShortYear, "format_test.go", 224);
        registry.Add("TestFormatSingleDigits", time_test_package.TestFormatSingleDigits, "format_test.go", 215);
        registry.Add("TestGoString", time_test_package.TestGoString, "format_test.go", 205);
        registry.Add("TestHasMonotonicClock", time_test_package.TestHasMonotonicClock, "mono_test.go", 13);
        registry.Add("TestISOWeek", time_test_package.TestISOWeek, "time_test.go", 461);
        registry.Add("TestInvalidTimeGob", time_test_package.TestInvalidTimeGob, "time_test.go", 764);
        registry.Add("TestIssue5745", time_test_package.TestIssue5745, "sleep_test.go", 607);
        registry.Add("TestLoadFixed", time_test_package.TestLoadFixed, "time_test.go", 1075);
        registry.Add("TestLoadLocationFromTZData", time_test_package.TestLoadLocationFromTZData, "zoneinfo_test.go", 131);
        registry.Add("TestLoadLocationFromTZDataSlim", time_test_package.TestLoadLocationFromTZDataSlim, "zoneinfo_test.go", 230);
        registry.Add("TestLoadLocationValidatesNames", time_test_package.TestLoadLocationValidatesNames, "zoneinfo_test.go", 50);
        registry.Add("TestLoadLocationZipFile", time_test_package.TestLoadLocationZipFile, "format_test.go", 484);
        registry.Add("TestLocationNames", time_test_package.TestLocationNames, "zoneinfo_test.go", 122);
        registry.Add("TestLocationRace", time_test_package.TestLocationRace, "time_test.go", 1029);
        registry.Add("TestLongAdjustTimers", time_test_package.TestLongAdjustTimers, "tick_test.go", 153);
        registry.Add("TestMalformedTZData", time_test_package.TestMalformedTZData, "zoneinfo_test.go", 180);
        registry.Add("TestManualTicker", time_test_package.TestManualTicker, "tick_test.go", 651);
        registry.Add("TestMarshalBinaryVersion2", time_test_package.TestMarshalBinaryVersion2, "time_test.go", 1622);
        registry.Add("TestMarshalBinaryZeroTime", time_test_package.TestMarshalBinaryZeroTime, "time_test.go", 1607);
        registry.Add("TestMarshalInvalidTimes", time_test_package.TestMarshalInvalidTimes, "time_test.go", 858);
        registry.Add("TestMidnightIs12AM", time_test_package.TestMidnightIs12AM, "format_test.go", 717);
        registry.Add("TestMinutesInTimeZone", time_test_package.TestMinutesInTimeZone, "format_test.go", 778);
        registry.Add("TestMissingZone", time_test_package.TestMissingZone, "format_test.go", 766);
        registry.Add("TestMonotonicAdd", time_test_package.TestMonotonicAdd, "mono_test.go", 61);
        registry.Add("TestMonotonicOverflow", time_test_package.TestMonotonicOverflow, "mono_test.go", 203);
        registry.Add("TestMonotonicString", time_test_package.TestMonotonicString, "mono_test.go", 265);
        registry.Add("TestMonotonicSub", time_test_package.TestMonotonicSub, "mono_test.go", 117);
        registry.Add("TestNanosecondsToLocalTime", time_test_package.TestNanosecondsToLocalTime, "time_test.go", 156);
        registry.Add("TestNanosecondsToUTC", time_test_package.TestNanosecondsToUTC, "time_test.go", 122);
        registry.Add("TestNanosecondsToUTCAndBack", time_test_package.TestNanosecondsToUTCAndBack, "time_test.go", 187);
        registry.Add("TestNewTickerLtZeroDuration", time_test_package.TestNewTickerLtZeroDuration, "tick_test.go", 133);
        registry.Add("TestNextStdChunk", time_test_package.TestNextStdChunk, "format_test.go", 27);
        registry.Add("TestNoonIs12PM", time_test_package.TestNoonIs12PM, "format_test.go", 704);
        registry.Add("TestNotGobEncodableTime", time_test_package.TestNotGobEncodableTime, "time_test.go", 787);
        registry.Add("TestOverflowPeriodRuntimeTimer", time_test_package.TestOverflowPeriodRuntimeTimer, "sleep_test.go", 625);
        registry.Add("TestOverflowSleep", time_test_package.TestOverflowSleep, "sleep_test.go", 578);
        registry.Add("TestParse", time_test_package.TestParse, "format_test.go", 358);
        registry.Add("TestParseDayOutOfRange", time_test_package.TestParseDayOutOfRange, "format_test.go", 403);
        registry.Add("TestParseDuration", time_test_package.TestParseDuration, "time_test.go", 953);
        registry.Add("TestParseDurationErrors", time_test_package.TestParseDurationErrors, "time_test.go", 991);
        registry.Add("TestParseDurationRoundTrip", time_test_package.TestParseDurationRoundTrip, "time_test.go", 1002);
        registry.Add("TestParseErrors", time_test_package.TestParseErrors, "format_test.go", 693);
        registry.Add("TestParseFractionalSecondsLongerThanNineDigits", time_test_package.TestParseFractionalSecondsLongerThanNineDigits, "format_test.go", 980);
        registry.Add("TestParseInLocation", time_test_package.TestParseInLocation, "format_test.go", 431);
        registry.Add("TestParseMonthOutOfRange", time_test_package.TestParseMonthOutOfRange, "format_test.go", 881);
        registry.Add("TestParseSecondsInTimeZone", time_test_package.TestParseSecondsInTimeZone, "format_test.go", 808);
        registry.Add("TestParseTimeZone", time_test_package.TestParseTimeZone, "format_test.go", 622);
        registry.Add("TestParseYday", time_test_package.TestParseYday, "format_test.go", 898);
        registry.Add("TestQuote", time_test_package.TestQuote, "format_test.go", 912);
        registry.Add("TestRFC3339Conversion", time_test_package.TestRFC3339Conversion, "format_test.go", 83);
        registry.Add("TestReadFileLimit", time_test_package.TestReadFileLimit, "time_test.go", 1680);
        registry.Add("TestReset", time_test_package.TestReset, "sleep_test.go", 552);
        registry.Add("TestRubyParse", time_test_package.TestRubyParse, "format_test.go", 503);
        registry.Add("TestSecondsToLocalTime", time_test_package.TestSecondsToLocalTime, "time_test.go", 139);
        registry.Add("TestSecondsToUTC", time_test_package.TestSecondsToUTC, "time_test.go", 105);
        registry.Add("TestSecondsToUTCAndBack", time_test_package.TestSecondsToUTCAndBack, "time_test.go", 173);
        registry.Add("TestSleep", time_test_package.TestSleep, "sleep_test.go", 57);
        registry.Add("TestSleepZeroDeadlock", time_test_package.TestSleepZeroDeadlock, "sleep_test.go", 505);
        registry.Add("TestStd0xParseError", time_test_package.TestStd0xParseError, "format_test.go", 852);
        registry.Add("TestSub", time_test_package.TestSub, "time_test.go", 1122);
        registry.Add("TestTeardown", time_test_package.TestTeardown, "tick_test.go", 110);
        registry.Add("TestTick", time_test_package.TestTick, "tick_test.go", 125);
        registry.Add("TestTickTimes", time_test_package.TestTickTimes, "tick_test.go", 680);
        registry.Add("TestTicker", time_test_package.TestTicker, "tick_test.go", 15);
        registry.Add("TestTickerConcurrentStress", time_test_package.TestTickerConcurrentStress, "sleep_test.go", 112);
        registry.Add("TestTickerResetLtZeroDuration", time_test_package.TestTickerResetLtZeroDuration, "tick_test.go", 143);
        registry.Add("TestTickerStopWithDirectInitialization", time_test_package.TestTickerStopWithDirectInitialization, "tick_test.go", 103);
        registry.Add("TestTickerStress", time_test_package.TestTickerStress, "sleep_test.go", 93);
        registry.Add("TestTimeAddSecOverflow", time_test_package.TestTimeAddSecOverflow, "time_test.go", 1771);
        registry.Add("TestTimeGob", time_test_package.TestTimeGob, "time_test.go", 738);
        registry.Add("TestTimeIsDST", time_test_package.TestTimeIsDST, "time_test.go", 1735);
        registry.Add("TestTimeJSON", time_test_package.TestTimeJSON, "time_test.go", 810);
        registry.Add("TestTimeWithZoneTransition", time_test_package.TestTimeWithZoneTransition, "time_test.go", 1797);
        registry.Add("TestTimerGC", time_test_package.TestTimerGC, "tick_test.go", 264);
        registry.Add("TestTimerModifiedEarlier", time_test_package.TestTimerModifiedEarlier, "sleep_test.go", 685);
        registry.Add("TestTimerStopStress", time_test_package.TestTimerStopStress, "sleep_test.go", 488);
        registry.Add("TestToEnglishName", time_test_package.TestToEnglishName, "zoneinfo_windows_test.go", 39);
        registry.Add("TestTruncateRound", time_test_package.TestTruncateRound, "time_test.go", 270);
        registry.Add("TestTzset", time_test_package.TestTzset, "zoneinfo_test.go", 254);
        registry.Add("TestTzsetName", time_test_package.TestTzsetName, "zoneinfo_test.go", 283);
        registry.Add("TestTzsetOffset", time_test_package.TestTzsetOffset, "zoneinfo_test.go", 304);
        registry.Add("TestTzsetRule", time_test_package.TestTzsetRule, "zoneinfo_test.go", 328);
        registry.Add("TestUSPacificZoneAbbr", time_test_package.TestUSPacificZoneAbbr, "zoneinfo_windows_test.go", 27);
        registry.Add("TestUnderscoreTwoThousand", time_test_package.TestUnderscoreTwoThousand, "format_test.go", 833);
        registry.Add("TestUnixMicro", time_test_package.TestUnixMicro, "time_test.go", 217);
        registry.Add("TestUnixMilli", time_test_package.TestUnixMilli, "time_test.go", 206);
        registry.Add("TestUnmarshalInvalidTimes", time_test_package.TestUnmarshalInvalidTimes, "time_test.go", 826);
        registry.Add("TestUnmarshalTextAllocations", time_test_package.TestUnmarshalTextAllocations, "time_test.go", 1653);
        registry.Add("TestVersion3", time_test_package.TestVersion3, "zoneinfo_test.go", 69);
        registry.Add("TestWeekdayString", time_test_package.TestWeekdayString, "time_test.go", 1671);
        registry.Add("TestYearDay", time_test_package.TestYearDay, "time_test.go", 564);
        registry.Add("TestZeroMonthString", time_test_package.TestZeroMonthString, "time_test.go", 1664);
        registry.Add("TestZeroTimer", time_test_package.TestZeroTimer, "sleep_test.go", 652);
        registry.Add("TestZeroTimerResetPanics", time_test_package.TestZeroTimerResetPanics, "sleep_test.go", 639);
        registry.Add("TestZeroTimerStopPanics", time_test_package.TestZeroTimerStopPanics, "sleep_test.go", 645);
        registry.Add("TestZoneBounds", time_test_package.TestZoneBounds, "time_test.go", 1838);
        registry.Add("TestZoneData", time_test_package.TestZoneData, "time_test.go", 27);
        return TestHost.Run(registry, args);
    }
}
