// Code generated by go2cs. DO NOT EDIT.
// Test-variant package-level variable initialization ordered to match Go's
// dependency order (types.Info.InitOrder) — see package_init.cs. Each initᴛ
// method lives beside its variable's declaration in the converted test file.
namespace go;

partial class time_internal_test_package {
    static time_internal_test_package() {
        initᴛParseTimeZone();
        initᴛErrLocation();
        initᴛLoadTzinfo();
        initᴛNextStdChunk();
        initᴛTzset();
        initᴛQuote();
        initᴛAppendFormatAny();
        initᴛAppendFormatRFC3339();
        initᴛParseAny();
        initᴛParseRFC3339();
        initᴛorigPlatformZoneSources();
        initᴛDisablePlatformSources();
        initᴛDaysIn();
        initᴛMinMonoTime();
        initᴛMaxMonoTime();
    }
} // end time_internal_test_package
