// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.image;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("image/jpeg", new string[]
        {
            "../testdata/triangle-001.gif",
            "../testdata/video-001.221212.jpeg",
            "../testdata/video-001.221212.png",
            "../testdata/video-001.5bpp.gif",
            "../testdata/video-001.cmyk.jpeg",
            "../testdata/video-001.cmyk.png",
            "../testdata/video-001.gif",
            "../testdata/video-001.interlaced.gif",
            "../testdata/video-001.jpeg",
            "../testdata/video-001.jpeg",
            "../testdata/video-001.png",
            "../testdata/video-001.png",
            "../testdata/video-001.progressive.jpeg",
            "../testdata/video-001.progressive.jpeg",
            "../testdata/video-001.progressive.truncated.jpeg",
            "../testdata/video-001.progressive.truncated.png",
            "../testdata/video-001.q50.410.jpeg",
            "../testdata/video-001.q50.410.progressive.jpeg",
            "../testdata/video-001.q50.411.jpeg",
            "../testdata/video-001.q50.411.progressive.jpeg",
            "../testdata/video-001.q50.420.jpeg",
            "../testdata/video-001.q50.420.progressive.jpeg",
            "../testdata/video-001.q50.422.jpeg",
            "../testdata/video-001.q50.422.progressive.jpeg",
            "../testdata/video-001.q50.440.jpeg",
            "../testdata/video-001.q50.440.progressive.jpeg",
            "../testdata/video-001.q50.444.jpeg",
            "../testdata/video-001.q50.444.progressive.jpeg",
            "../testdata/video-001.restart2.jpeg",
            "../testdata/video-001.restart2.jpeg",
            "../testdata/video-001.rgb.jpeg",
            "../testdata/video-001.rgb.png",
            "../testdata/video-001.separate.dc.progression.jpeg",
            "../testdata/video-001.separate.dc.progression.progressive.jpeg",
            "../testdata/video-005.gray.gif",
            "../testdata/video-005.gray.jpeg",
            "../testdata/video-005.gray.png",
            "../testdata/video-005.gray.q50.2x2.jpeg",
            "../testdata/video-005.gray.q50.2x2.progressive.jpeg",
            "../testdata/video-005.gray.q50.jpeg",
            "../testdata/video-005.gray.q50.jpeg",
            "../testdata/video-005.gray.q50.progressive.jpeg",
            "dct_test.go",
            "fdct.go",
            "fuzz_test.go",
            "huffman.go",
            "idct.go",
            "reader.go",
            "reader_test.go",
            "scan.go",
            "writer.go",
            "writer_test.go",
        });
        registry.Add("TestBadRestartMarker", jpeg_internal_test_package.TestBadRestartMarker, "reader_test.go", 507);
        registry.Add("TestDCT", jpeg_internal_test_package.TestDCT, "dct_test.go", 35);
        registry.Add("TestDecodeEOF", jpeg_internal_test_package.TestDecodeEOF, "reader_test.go", 119);
        registry.Add("TestDecodeProgressive", jpeg_internal_test_package.TestDecodeProgressive, "reader_test.go", 25);
        registry.Add("TestEncodeYCbCr", jpeg_internal_test_package.TestEncodeYCbCr, "writer_test.go", 212);
        registry.Add("TestExtraneousData", jpeg_internal_test_package.TestExtraneousData, "reader_test.go", 433);
        registry.Add("TestIssue56724", jpeg_internal_test_package.TestIssue56724, "reader_test.go", 493);
        registry.Add("TestLargeImageWithShortData", jpeg_internal_test_package.TestLargeImageWithShortData, "reader_test.go", 211);
        registry.Add("TestPaddedRSTMarker", jpeg_internal_test_package.TestPaddedRSTMarker, "reader_test.go", 264);
        registry.Add("TestTruncatedSOSDataDoesntPanic", jpeg_internal_test_package.TestTruncatedSOSDataDoesntPanic, "reader_test.go", 191);
        registry.Add("TestUnscaledQuant", jpeg_internal_test_package.TestUnscaledQuant, "writer_test.go", 72);
        registry.Add("TestWriteGrayscale", jpeg_internal_test_package.TestWriteGrayscale, "writer_test.go", 166);
        registry.Add("TestWriter", jpeg_internal_test_package.TestWriter, "writer_test.go", 131);
        registry.Add("TestZigUnzig", jpeg_internal_test_package.TestZigUnzig, "writer_test.go", 34);
        return TestHost.Run(registry, args);
    }
}
