// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/dsa", new string[]
        {
            "dsa.go",
            "dsa_test.go",
        });
        registry.Add("TestParameterGeneration", dsa_internal_test_package.TestParameterGeneration, "dsa_test.go", 65);
        registry.Add("TestSignAndVerify", dsa_internal_test_package.TestSignAndVerify, "dsa_test.go", 84);
        registry.Add("TestSignAndVerifyWithBadPublicKey", dsa_internal_test_package.TestSignAndVerifyWithBadPublicKey, "dsa_test.go", 100);
        registry.Add("TestSigningWithDegenerateKeys", dsa_internal_test_package.TestSigningWithDegenerateKeys, "dsa_test.go", 115);
        return TestHost.Run(registry, args);
    }
}
