// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.database;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("database/sql", new string[]
        {
            "convert.go",
            "convert_test.go",
            "ctxutil.go",
            "example_cli_test.go",
            "example_service_test.go",
            "example_test.go",
            "fakedb_test.go",
            "sql.go",
            "sql_test.go",
        }, new string[]
        {
            "driver",
        });
        registry.Add("TestBadDriver", sql_internal_test_package.TestBadDriver, "sql_test.go", 4644);
        registry.Add("TestBogusPreboundParameters", sql_internal_test_package.TestBogusPreboundParameters, "sql_test.go", 988);
        registry.Add("TestCloseConnBeforeStmts", sql_internal_test_package.TestCloseConnBeforeStmts, "sql_test.go", 2530);
        registry.Add("TestCloseStmtBeforeRows", sql_internal_test_package.TestCloseStmtBeforeRows, "sql_test.go", 1628);
        registry.Add("TestConcurrency", sql_internal_test_package.TestConcurrency, "sql_test.go", 3822);
        registry.Add("TestConnExpiresFreshOutOfPool", sql_internal_test_package.TestConnExpiresFreshOutOfPool, "sql_test.go", 2917);
        registry.Add("TestConnIsValid", sql_internal_test_package.TestConnIsValid, "sql_test.go", 1586);
        registry.Add("TestConnMaxLifetime", sql_internal_test_package.TestConnMaxLifetime, "sql_test.go", 2344);
        registry.Add("TestConnQuery", sql_internal_test_package.TestConnQuery, "sql_test.go", 1373);
        registry.Add("TestConnRaw", sql_internal_test_package.TestConnRaw, "sql_test.go", 1401);
        registry.Add("TestConnRequestSet", sql_internal_test_package.TestConnRequestSet, "sql_test.go", 4849);
        registry.Add("TestConnTx", sql_internal_test_package.TestConnTx, "sql_test.go", 1546);
        registry.Add("TestConnectionLeak", sql_internal_test_package.TestConnectionLeak, "sql_test.go", 3844);
        registry.Add("TestContextCancelBetweenNextAndErr", sql_internal_test_package.TestContextCancelBetweenNextAndErr, "sql_test.go", 4525);
        registry.Add("TestContextCancelDuringRawBytesScan", sql_internal_test_package.TestContextCancelDuringRawBytesScan, "sql_test.go", 4436);
        registry.Add("TestConversions", sql_internal_test_package.TestConversions, "convert_test.go", 212);
        registry.Add("TestCursorFake", sql_internal_test_package.TestCursorFake, "sql_test.go", 1449);
        registry.Add("TestDecimal", sql_internal_test_package.TestDecimal, "convert_test.go", 571);
        registry.Add("TestDriverArgs", sql_internal_test_package.TestDriverArgs, "convert_test.go", 434);
        registry.Add("TestDriverArgsWrapsErrors", sql_internal_test_package.TestDriverArgsWrapsErrors, "sql_test.go", 4403);
        registry.Add("TestDriverPanic", sql_internal_test_package.TestDriverPanic, "sql_test.go", 98);
        registry.Add("TestDrivers", sql_internal_test_package.TestDrivers, "fakedb_test.go", 219);
        registry.Add("TestErrBadConnReconnect", sql_internal_test_package.TestErrBadConnReconnect, "sql_test.go", 3079);
        registry.Add("TestExec", sql_internal_test_package.TestExec, "sql_test.go", 1001);
        registry.Add("TestGenericNullStringParam", sql_internal_test_package.TestGenericNullStringParam, "sql_test.go", 1801);
        registry.Add("TestGrabConnAllocs", sql_internal_test_package.TestGrabConnAllocs, "sql_test.go", 4817);
        registry.Add("TestInvalidNilValues", sql_internal_test_package.TestInvalidNilValues, "sql_test.go", 1495);
        registry.Add("TestIssue18429", sql_internal_test_package.TestIssue18429, "sql_test.go", 3655);
        registry.Add("TestIssue18719", sql_internal_test_package.TestIssue18719, "sql_test.go", 3748);
        registry.Add("TestIssue20160", sql_internal_test_package.TestIssue20160, "sql_test.go", 3704);
        registry.Add("TestIssue20575", sql_internal_test_package.TestIssue20575, "sql_test.go", 3015);
        registry.Add("TestIssue20622", sql_internal_test_package.TestIssue20622, "sql_test.go", 3043);
        registry.Add("TestIssue20647", sql_internal_test_package.TestIssue20647, "sql_test.go", 3785);
        registry.Add("TestIssue2542Deadlock", sql_internal_test_package.TestIssue2542Deadlock, "sql_test.go", 1616);
        registry.Add("TestIssue4902", sql_internal_test_package.TestIssue4902, "sql_test.go", 1968);
        registry.Add("TestIssue6081", sql_internal_test_package.TestIssue6081, "sql_test.go", 3599);
        registry.Add("TestIssue6651", sql_internal_test_package.TestIssue6651, "sql_test.go", 1748);
        registry.Add("TestManyErrBadConn", sql_internal_test_package.TestManyErrBadConn, "sql_test.go", 2680);
        registry.Add("TestMaxIdleConns", sql_internal_test_package.TestMaxIdleConns, "sql_test.go", 2022);
        registry.Add("TestMaxIdleTime", sql_internal_test_package.TestMaxIdleTime, "sql_test.go", 3978);
        registry.Add("TestMaxOpenConns", sql_internal_test_package.TestMaxOpenConns, "sql_test.go", 2051);
        registry.Add("TestMaxOpenConnsOnBusy", sql_internal_test_package.TestMaxOpenConnsOnBusy, "sql_test.go", 2167);
        registry.Add("TestMultiResultSetQuery", sql_internal_test_package.TestMultiResultSetQuery, "sql_test.go", 503);
        registry.Add("TestNamedValueChecker", sql_internal_test_package.TestNamedValueChecker, "sql_test.go", 4137);
        registry.Add("TestNamedValueCheckerSkip", sql_internal_test_package.TestNamedValueCheckerSkip, "sql_test.go", 4187);
        registry.Add("TestNilErrorAfterClose", sql_internal_test_package.TestNilErrorAfterClose, "sql_test.go", 4544);
        registry.Add("TestNullBoolParam", sql_internal_test_package.TestNullBoolParam, "sql_test.go", 1873);
        registry.Add("TestNullByteParam", sql_internal_test_package.TestNullByteParam, "sql_test.go", 1849);
        registry.Add("TestNullByteSlice", sql_internal_test_package.TestNullByteSlice, "sql_test.go", 1653);
        registry.Add("TestNullFloat64Param", sql_internal_test_package.TestNullFloat64Param, "sql_test.go", 1861);
        registry.Add("TestNullInt16Param", sql_internal_test_package.TestNullInt16Param, "sql_test.go", 1837);
        registry.Add("TestNullInt32Param", sql_internal_test_package.TestNullInt32Param, "sql_test.go", 1825);
        registry.Add("TestNullInt64Param", sql_internal_test_package.TestNullInt64Param, "sql_test.go", 1813);
        registry.Add("TestNullString", sql_internal_test_package.TestNullString, "convert_test.go", 284);
        registry.Add("TestNullStringParam", sql_internal_test_package.TestNullStringParam, "sql_test.go", 1789);
        registry.Add("TestNullTimeParam", sql_internal_test_package.TestNullTimeParam, "sql_test.go", 1885);
        registry.Add("TestOpenConnector", sql_internal_test_package.TestOpenConnector, "sql_test.go", 4214);
        registry.Add("TestOpenDB", sql_internal_test_package.TestOpenDB, "sql_test.go", 91);
        registry.Add("TestParentStmtOutlivesTxStmt", sql_internal_test_package.TestParentStmtOutlivesTxStmt, "sql_test.go", 1188);
        registry.Add("TestPendingConnsAfterErr", sql_internal_test_package.TestPendingConnsAfterErr, "sql_test.go", 2220);
        registry.Add("TestPing", sql_internal_test_package.TestPing, "sql_test.go", 4687);
        registry.Add("TestPointerParamsAndScans", sql_internal_test_package.TestPointerParamsAndScans, "sql_test.go", 1679);
        registry.Add("TestPoolExhaustOnCancel", sql_internal_test_package.TestPoolExhaustOnCancel, "sql_test.go", 624);
        registry.Add("TestQuery", sql_internal_test_package.TestQuery, "sql_test.go", 256);
        registry.Add("TestQueryContext", sql_internal_test_package.TestQueryContext, "sql_test.go", 302);
        registry.Add("TestQueryContextWait", sql_internal_test_package.TestQueryContextWait, "sql_test.go", 413);
        registry.Add("TestQueryExecContextOnly", sql_internal_test_package.TestQueryExecContextOnly, "sql_test.go", 4291);
        registry.Add("TestQueryNamedArg", sql_internal_test_package.TestQueryNamedArg, "sql_test.go", 577);
        registry.Add("TestQueryRow", sql_internal_test_package.TestQueryRow, "sql_test.go", 778);
        registry.Add("TestQueryRowClosingStmt", sql_internal_test_package.TestQueryRowClosingStmt, "sql_test.go", 1711);
        registry.Add("TestQueryRowNilScanDest", sql_internal_test_package.TestQueryRowNilScanDest, "sql_test.go", 1957);
        registry.Add("TestRawBytesAllocs", sql_internal_test_package.TestRawBytesAllocs, "convert_test.go", 335);
        registry.Add("TestRawBytesReuse", sql_internal_test_package.TestRawBytesReuse, "sql_test.go", 4573);
        registry.Add("TestRowErr", sql_internal_test_package.TestRowErr, "sql_test.go", 828);
        registry.Add("TestRowsCloseError", sql_internal_test_package.TestRowsCloseError, "sql_test.go", 2631);
        registry.Add("TestRowsCloseOrder", sql_internal_test_package.TestRowsCloseOrder, "sql_test.go", 2585);
        registry.Add("TestRowsColumnTypes", sql_internal_test_package.TestRowsColumnTypes, "sql_test.go", 728);
        registry.Add("TestRowsColumns", sql_internal_test_package.TestRowsColumns, "sql_test.go", 708);
        registry.Add("TestRowsImplicitClose", sql_internal_test_package.TestRowsImplicitClose, "sql_test.go", 2603);
        registry.Add("TestRowsScanProperlyWrapsErrors", sql_internal_test_package.TestRowsScanProperlyWrapsErrors, "sql_test.go", 4367);
        registry.Add("TestSimultaneousQueries", sql_internal_test_package.TestSimultaneousQueries, "sql_test.go", 1999);
        registry.Add("TestSingleOpenConn", sql_internal_test_package.TestSingleOpenConn, "sql_test.go", 2301);
        registry.Add("TestStatementClose", sql_internal_test_package.TestStatementClose, "sql_test.go", 941);
        registry.Add("TestStatementErrorAfterClose", sql_internal_test_package.TestStatementErrorAfterClose, "sql_test.go", 877);
        registry.Add("TestStatementQueryRow", sql_internal_test_package.TestStatementQueryRow, "sql_test.go", 895);
        registry.Add("TestStatementQueryRowConcurrent", sql_internal_test_package.TestStatementQueryRowConcurrent, "sql_test.go", 959);
        registry.Add("TestStats", sql_internal_test_package.TestStats, "sql_test.go", 2324);
        registry.Add("TestStatsMaxIdleClosedTen", sql_internal_test_package.TestStatsMaxIdleClosedTen, "sql_test.go", 3922);
        registry.Add("TestStatsMaxIdleClosedZero", sql_internal_test_package.TestStatsMaxIdleClosedZero, "sql_test.go", 3896);
        registry.Add("TestStmtCloseDeps", sql_internal_test_package.TestStmtCloseDeps, "sql_test.go", 2435);
        registry.Add("TestStmtCloseOrder", sql_internal_test_package.TestStmtCloseOrder, "sql_test.go", 2664);
        registry.Add("TestTxCannotCommitAfterRollback", sql_internal_test_package.TestTxCannotCommitAfterRollback, "sql_test.go", 2818);
        registry.Add("TestTxContextWait", sql_internal_test_package.TestTxContextWait, "sql_test.go", 448);
        registry.Add("TestTxContextWaitNoDiscard", sql_internal_test_package.TestTxContextWaitNoDiscard, "sql_test.go", 454);
        registry.Add("TestTxEndBadConn", sql_internal_test_package.TestTxEndBadConn, "sql_test.go", 3185);
        registry.Add("TestTxErrBadConn", sql_internal_test_package.TestTxErrBadConn, "sql_test.go", 1342);
        registry.Add("TestTxPrepare", sql_internal_test_package.TestTxPrepare, "sql_test.go", 1043);
        registry.Add("TestTxQuery", sql_internal_test_package.TestTxQuery, "sql_test.go", 1292);
        registry.Add("TestTxQueryInvalid", sql_internal_test_package.TestTxQueryInvalid, "sql_test.go", 1324);
        registry.Add("TestTxRollbackCommitErr", sql_internal_test_package.TestTxRollbackCommitErr, "sql_test.go", 846);
        registry.Add("TestTxStmt", sql_internal_test_package.TestTxStmt, "sql_test.go", 1070);
        registry.Add("TestTxStmtClosedRePrepares", sql_internal_test_package.TestTxStmtClosedRePrepares, "sql_test.go", 1143);
        registry.Add("TestTxStmtDeadlock", sql_internal_test_package.TestTxStmtDeadlock, "sql_test.go", 2886);
        registry.Add("TestTxStmtFromTxStmtRePrepares", sql_internal_test_package.TestTxStmtFromTxStmtRePrepares, "sql_test.go", 1239);
        registry.Add("TestTxStmtPreparedOnce", sql_internal_test_package.TestTxStmtPreparedOnce, "sql_test.go", 1099);
        registry.Add("TestTypedString", sql_internal_test_package.TestTypedString, "sql_test.go", 4708);
        registry.Add("TestUnsupportedOptions", sql_internal_test_package.TestUnsupportedOptions, "sql_test.go", 492);
        registry.Add("TestUserDefinedBytes", sql_internal_test_package.TestUserDefinedBytes, "convert_test.go", 408);
        registry.Add("TestValueConverters", sql_internal_test_package.TestValueConverters, "convert_test.go", 313);
        return TestHost.Run(registry, args);
    }
}
