// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.database;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("database/sql", new string[]
        {
            "convert.go",
            "convert_test.go",
            "ctxutil.go",
            "example_cli_test.go",
            "example_service_test.go",
            "example_test.go",
            "fakedb_test.go",
            "sql.go",
            "sql_test.go",
        }, new string[]
        {
            "driver",
        });
        registry.Add("TestBadDriver", sql_internal_test_package.TestBadDriver, "sql_test.go", 4692);
        registry.Add("TestBogusPreboundParameters", sql_internal_test_package.TestBogusPreboundParameters, "sql_test.go", 989);
        registry.Add("TestCloseConnBeforeStmts", sql_internal_test_package.TestCloseConnBeforeStmts, "sql_test.go", 2531);
        registry.Add("TestCloseStmtBeforeRows", sql_internal_test_package.TestCloseStmtBeforeRows, "sql_test.go", 1629);
        registry.Add("TestConcurrency", sql_internal_test_package.TestConcurrency, "sql_test.go", 3823);
        registry.Add("TestConnExpiresFreshOutOfPool", sql_internal_test_package.TestConnExpiresFreshOutOfPool, "sql_test.go", 2918);
        registry.Add("TestConnIsValid", sql_internal_test_package.TestConnIsValid, "sql_test.go", 1587);
        registry.Add("TestConnMaxLifetime", sql_internal_test_package.TestConnMaxLifetime, "sql_test.go", 2345);
        registry.Add("TestConnQuery", sql_internal_test_package.TestConnQuery, "sql_test.go", 1374);
        registry.Add("TestConnRaw", sql_internal_test_package.TestConnRaw, "sql_test.go", 1402);
        registry.Add("TestConnRequestSet", sql_internal_test_package.TestConnRequestSet, "sql_test.go", 4897);
        registry.Add("TestConnTx", sql_internal_test_package.TestConnTx, "sql_test.go", 1547);
        registry.Add("TestConnectionLeak", sql_internal_test_package.TestConnectionLeak, "sql_test.go", 3845);
        registry.Add("TestContextCancelBetweenNextAndErr", sql_internal_test_package.TestContextCancelBetweenNextAndErr, "sql_test.go", 4522);
        registry.Add("TestContextCancelDuringRawBytesScan", sql_internal_test_package.TestContextCancelDuringRawBytesScan, "sql_test.go", 4437);
        registry.Add("TestContextCancelDuringScan", sql_internal_test_package.TestContextCancelDuringScan, "sql_test.go", 4547);
        registry.Add("TestConversions", sql_internal_test_package.TestConversions, "convert_test.go", 212);
        registry.Add("TestCursorFake", sql_internal_test_package.TestCursorFake, "sql_test.go", 1450);
        registry.Add("TestDecimal", sql_internal_test_package.TestDecimal, "convert_test.go", 571);
        registry.Add("TestDriverArgs", sql_internal_test_package.TestDriverArgs, "convert_test.go", 434);
        registry.Add("TestDriverArgsWrapsErrors", sql_internal_test_package.TestDriverArgsWrapsErrors, "sql_test.go", 4404);
        registry.Add("TestDriverPanic", sql_internal_test_package.TestDriverPanic, "sql_test.go", 99);
        registry.Add("TestDrivers", sql_internal_test_package.TestDrivers, "fakedb_test.go", 217);
        registry.Add("TestErrBadConnReconnect", sql_internal_test_package.TestErrBadConnReconnect, "sql_test.go", 3080);
        registry.Add("TestExec", sql_internal_test_package.TestExec, "sql_test.go", 1002);
        registry.Add("TestGenericNullStringParam", sql_internal_test_package.TestGenericNullStringParam, "sql_test.go", 1802);
        registry.Add("TestGrabConnAllocs", sql_internal_test_package.TestGrabConnAllocs, "sql_test.go", 4865);
        registry.Add("TestInvalidNilValues", sql_internal_test_package.TestInvalidNilValues, "sql_test.go", 1496);
        registry.Add("TestIssue18429", sql_internal_test_package.TestIssue18429, "sql_test.go", 3656);
        registry.Add("TestIssue18719", sql_internal_test_package.TestIssue18719, "sql_test.go", 3749);
        registry.Add("TestIssue20160", sql_internal_test_package.TestIssue20160, "sql_test.go", 3705);
        registry.Add("TestIssue20575", sql_internal_test_package.TestIssue20575, "sql_test.go", 3016);
        registry.Add("TestIssue20622", sql_internal_test_package.TestIssue20622, "sql_test.go", 3044);
        registry.Add("TestIssue20647", sql_internal_test_package.TestIssue20647, "sql_test.go", 3786);
        registry.Add("TestIssue2542Deadlock", sql_internal_test_package.TestIssue2542Deadlock, "sql_test.go", 1617);
        registry.Add("TestIssue4902", sql_internal_test_package.TestIssue4902, "sql_test.go", 1969);
        registry.Add("TestIssue6081", sql_internal_test_package.TestIssue6081, "sql_test.go", 3600);
        registry.Add("TestIssue6651", sql_internal_test_package.TestIssue6651, "sql_test.go", 1749);
        registry.Add("TestManyErrBadConn", sql_internal_test_package.TestManyErrBadConn, "sql_test.go", 2681);
        registry.Add("TestMaxIdleConns", sql_internal_test_package.TestMaxIdleConns, "sql_test.go", 2023);
        registry.Add("TestMaxIdleTime", sql_internal_test_package.TestMaxIdleTime, "sql_test.go", 3979);
        registry.Add("TestMaxOpenConns", sql_internal_test_package.TestMaxOpenConns, "sql_test.go", 2052);
        registry.Add("TestMaxOpenConnsOnBusy", sql_internal_test_package.TestMaxOpenConnsOnBusy, "sql_test.go", 2168);
        registry.Add("TestMultiResultSetQuery", sql_internal_test_package.TestMultiResultSetQuery, "sql_test.go", 504);
        registry.Add("TestNamedValueChecker", sql_internal_test_package.TestNamedValueChecker, "sql_test.go", 4138);
        registry.Add("TestNamedValueCheckerSkip", sql_internal_test_package.TestNamedValueCheckerSkip, "sql_test.go", 4188);
        registry.Add("TestNilErrorAfterClose", sql_internal_test_package.TestNilErrorAfterClose, "sql_test.go", 4596);
        registry.Add("TestNullBoolParam", sql_internal_test_package.TestNullBoolParam, "sql_test.go", 1874);
        registry.Add("TestNullByteParam", sql_internal_test_package.TestNullByteParam, "sql_test.go", 1850);
        registry.Add("TestNullByteSlice", sql_internal_test_package.TestNullByteSlice, "sql_test.go", 1654);
        registry.Add("TestNullFloat64Param", sql_internal_test_package.TestNullFloat64Param, "sql_test.go", 1862);
        registry.Add("TestNullInt16Param", sql_internal_test_package.TestNullInt16Param, "sql_test.go", 1838);
        registry.Add("TestNullInt32Param", sql_internal_test_package.TestNullInt32Param, "sql_test.go", 1826);
        registry.Add("TestNullInt64Param", sql_internal_test_package.TestNullInt64Param, "sql_test.go", 1814);
        registry.Add("TestNullString", sql_internal_test_package.TestNullString, "convert_test.go", 284);
        registry.Add("TestNullStringParam", sql_internal_test_package.TestNullStringParam, "sql_test.go", 1790);
        registry.Add("TestNullTimeParam", sql_internal_test_package.TestNullTimeParam, "sql_test.go", 1886);
        registry.Add("TestOpenConnector", sql_internal_test_package.TestOpenConnector, "sql_test.go", 4215);
        registry.Add("TestOpenDB", sql_internal_test_package.TestOpenDB, "sql_test.go", 92);
        registry.Add("TestParentStmtOutlivesTxStmt", sql_internal_test_package.TestParentStmtOutlivesTxStmt, "sql_test.go", 1189);
        registry.Add("TestPendingConnsAfterErr", sql_internal_test_package.TestPendingConnsAfterErr, "sql_test.go", 2221);
        registry.Add("TestPing", sql_internal_test_package.TestPing, "sql_test.go", 4735);
        registry.Add("TestPointerParamsAndScans", sql_internal_test_package.TestPointerParamsAndScans, "sql_test.go", 1680);
        registry.Add("TestPoolExhaustOnCancel", sql_internal_test_package.TestPoolExhaustOnCancel, "sql_test.go", 625);
        registry.Add("TestQuery", sql_internal_test_package.TestQuery, "sql_test.go", 257);
        registry.Add("TestQueryContext", sql_internal_test_package.TestQueryContext, "sql_test.go", 303);
        registry.Add("TestQueryContextWait", sql_internal_test_package.TestQueryContextWait, "sql_test.go", 414);
        registry.Add("TestQueryExecContextOnly", sql_internal_test_package.TestQueryExecContextOnly, "sql_test.go", 4292);
        registry.Add("TestQueryNamedArg", sql_internal_test_package.TestQueryNamedArg, "sql_test.go", 578);
        registry.Add("TestQueryRow", sql_internal_test_package.TestQueryRow, "sql_test.go", 779);
        registry.Add("TestQueryRowClosingStmt", sql_internal_test_package.TestQueryRowClosingStmt, "sql_test.go", 1712);
        registry.Add("TestQueryRowNilScanDest", sql_internal_test_package.TestQueryRowNilScanDest, "sql_test.go", 1958);
        registry.Add("TestRawBytesAllocs", sql_internal_test_package.TestRawBytesAllocs, "convert_test.go", 335);
        registry.Add("TestRawBytesReuse", sql_internal_test_package.TestRawBytesReuse, "sql_test.go", 4625);
        registry.Add("TestRowErr", sql_internal_test_package.TestRowErr, "sql_test.go", 829);
        registry.Add("TestRowsCloseError", sql_internal_test_package.TestRowsCloseError, "sql_test.go", 2632);
        registry.Add("TestRowsCloseOrder", sql_internal_test_package.TestRowsCloseOrder, "sql_test.go", 2586);
        registry.Add("TestRowsColumnTypes", sql_internal_test_package.TestRowsColumnTypes, "sql_test.go", 729);
        registry.Add("TestRowsColumns", sql_internal_test_package.TestRowsColumns, "sql_test.go", 709);
        registry.Add("TestRowsImplicitClose", sql_internal_test_package.TestRowsImplicitClose, "sql_test.go", 2604);
        registry.Add("TestRowsScanProperlyWrapsErrors", sql_internal_test_package.TestRowsScanProperlyWrapsErrors, "sql_test.go", 4368);
        registry.Add("TestSimultaneousQueries", sql_internal_test_package.TestSimultaneousQueries, "sql_test.go", 2000);
        registry.Add("TestSingleOpenConn", sql_internal_test_package.TestSingleOpenConn, "sql_test.go", 2302);
        registry.Add("TestStatementClose", sql_internal_test_package.TestStatementClose, "sql_test.go", 942);
        registry.Add("TestStatementErrorAfterClose", sql_internal_test_package.TestStatementErrorAfterClose, "sql_test.go", 878);
        registry.Add("TestStatementQueryRow", sql_internal_test_package.TestStatementQueryRow, "sql_test.go", 896);
        registry.Add("TestStatementQueryRowConcurrent", sql_internal_test_package.TestStatementQueryRowConcurrent, "sql_test.go", 960);
        registry.Add("TestStats", sql_internal_test_package.TestStats, "sql_test.go", 2325);
        registry.Add("TestStatsMaxIdleClosedTen", sql_internal_test_package.TestStatsMaxIdleClosedTen, "sql_test.go", 3923);
        registry.Add("TestStatsMaxIdleClosedZero", sql_internal_test_package.TestStatsMaxIdleClosedZero, "sql_test.go", 3897);
        registry.Add("TestStmtCloseDeps", sql_internal_test_package.TestStmtCloseDeps, "sql_test.go", 2436);
        registry.Add("TestStmtCloseOrder", sql_internal_test_package.TestStmtCloseOrder, "sql_test.go", 2665);
        registry.Add("TestTxCannotCommitAfterRollback", sql_internal_test_package.TestTxCannotCommitAfterRollback, "sql_test.go", 2819);
        registry.Add("TestTxContextWait", sql_internal_test_package.TestTxContextWait, "sql_test.go", 449);
        registry.Add("TestTxContextWaitNoDiscard", sql_internal_test_package.TestTxContextWaitNoDiscard, "sql_test.go", 455);
        registry.Add("TestTxEndBadConn", sql_internal_test_package.TestTxEndBadConn, "sql_test.go", 3186);
        registry.Add("TestTxErrBadConn", sql_internal_test_package.TestTxErrBadConn, "sql_test.go", 1343);
        registry.Add("TestTxPrepare", sql_internal_test_package.TestTxPrepare, "sql_test.go", 1044);
        registry.Add("TestTxQuery", sql_internal_test_package.TestTxQuery, "sql_test.go", 1293);
        registry.Add("TestTxQueryInvalid", sql_internal_test_package.TestTxQueryInvalid, "sql_test.go", 1325);
        registry.Add("TestTxRollbackCommitErr", sql_internal_test_package.TestTxRollbackCommitErr, "sql_test.go", 847);
        registry.Add("TestTxStmt", sql_internal_test_package.TestTxStmt, "sql_test.go", 1071);
        registry.Add("TestTxStmtClosedRePrepares", sql_internal_test_package.TestTxStmtClosedRePrepares, "sql_test.go", 1144);
        registry.Add("TestTxStmtDeadlock", sql_internal_test_package.TestTxStmtDeadlock, "sql_test.go", 2887);
        registry.Add("TestTxStmtFromTxStmtRePrepares", sql_internal_test_package.TestTxStmtFromTxStmtRePrepares, "sql_test.go", 1240);
        registry.Add("TestTxStmtPreparedOnce", sql_internal_test_package.TestTxStmtPreparedOnce, "sql_test.go", 1100);
        registry.Add("TestTypedString", sql_internal_test_package.TestTypedString, "sql_test.go", 4756);
        registry.Add("TestUnsupportedOptions", sql_internal_test_package.TestUnsupportedOptions, "sql_test.go", 493);
        registry.Add("TestUserDefinedBytes", sql_internal_test_package.TestUserDefinedBytes, "convert_test.go", 408);
        registry.Add("TestValueConverters", sql_internal_test_package.TestValueConverters, "convert_test.go", 313);
        return TestHost.Run(registry, args);
    }
}
