// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.net.http;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("net/http/cgi", new string[]
        {
            "cgi_main.go",
            "child.go",
            "child_test.go",
            "host.go",
            "host_test.go",
            "integration_test.go",
        });
        registry.Add("Test500WithEmptyHeaders", cgi_internal_test_package.Test500WithEmptyHeaders, "integration_test.go", 193);
        registry.Add("Test500WithNoContentType", cgi_internal_test_package.Test500WithNoContentType, "integration_test.go", 192);
        registry.Add("Test500WithNoHeaders", cgi_internal_test_package.Test500WithNoHeaders, "integration_test.go", 191);
        registry.Add("TestCGIBasicGet", cgi_internal_test_package.TestCGIBasicGet, "host_test.go", 103);
        registry.Add("TestCGIBasicGetAbsPath", cgi_internal_test_package.TestCGIBasicGetAbsPath, "host_test.go", 171);
        registry.Add("TestCGIBasicPost", cgi_internal_test_package.TestCGIBasicPost, "host_test.go", 283);
        registry.Add("TestCGIEnvIPv6", cgi_internal_test_package.TestCGIEnvIPv6, "host_test.go", 138);
        registry.Add("TestCGIPostChunked", cgi_internal_test_package.TestCGIPostChunked, "host_test.go", 310);
        registry.Add("TestChildContentType", cgi_internal_test_package.TestChildContentType, "integration_test.go", 146);
        registry.Add("TestChildOnlyHeaders", cgi_internal_test_package.TestChildOnlyHeaders, "integration_test.go", 114);
        registry.Add("TestCopyError", cgi_internal_test_package.TestCopyError, "host_test.go", 369);
        registry.Add("TestDir", cgi_internal_test_package.TestDir, "host_test.go", 432);
        registry.Add("TestDropProxyHeader", cgi_internal_test_package.TestDropProxyHeader, "host_test.go", 245);
        registry.Add("TestDupHeaders", cgi_internal_test_package.TestDupHeaders, "host_test.go", 222);
        registry.Add("TestEnvOverride", cgi_internal_test_package.TestEnvOverride, "host_test.go", 457);
        registry.Add("TestHandlerStderr", cgi_internal_test_package.TestHandlerStderr, "host_test.go", 480);
        registry.Add("TestHostingOurselves", cgi_internal_test_package.TestHostingOurselves, "integration_test.go", 27);
        registry.Add("TestInternalRedirect", cgi_internal_test_package.TestInternalRedirect, "host_test.go", 346);
        registry.Add("TestKillChildAfterCopyError", cgi_internal_test_package.TestKillChildAfterCopyError, "integration_test.go", 93);
        registry.Add("TestNilRequestBody", cgi_internal_test_package.TestNilRequestBody, "integration_test.go", 132);
        registry.Add("TestPathInfo", cgi_internal_test_package.TestPathInfo, "host_test.go", 189);
        registry.Add("TestPathInfoDirRoot", cgi_internal_test_package.TestPathInfoDirRoot, "host_test.go", 206);
        registry.Add("TestPathInfoNoRoot", cgi_internal_test_package.TestPathInfoNoRoot, "host_test.go", 267);
        registry.Add("TestRedirect", cgi_internal_test_package.TestRedirect, "host_test.go", 331);
        registry.Add("TestRemoveLeadingDuplicates", cgi_internal_test_package.TestRemoveLeadingDuplicates, "host_test.go", 497);
        registry.Add("TestRequest", cgi_internal_test_package.TestRequest, "child_test.go", 18);
        registry.Add("TestRequestWithTLS", cgi_internal_test_package.TestRequestWithTLS, "child_test.go", 74);
        registry.Add("TestRequestWithoutHost", cgi_internal_test_package.TestRequestWithoutHost, "child_test.go", 97);
        registry.Add("TestRequestWithoutRemotePort", cgi_internal_test_package.TestRequestWithoutRemotePort, "child_test.go", 139);
        registry.Add("TestRequestWithoutRequestURI", cgi_internal_test_package.TestRequestWithoutRequestURI, "child_test.go", 117);
        registry.Add("TestResponse", cgi_internal_test_package.TestResponse, "child_test.go", 157);
        registry.SetTestMain(cgi_internal_test_package.TestMain);
        return TestHost.Run(registry, args);
    }
}
