// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.debug;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("debug/gosym", new string[]
        {
            "pclntab.go",
            "pclntab_test.go",
            "symtab.go",
            "symtab_test.go",
            "testdata/main.go",
            "testdata/pclinetest.h",
            "testdata/pclinetest.s",
            "testdata/pcln115.gz",
        }, new string[]
        {
            "testdata",
        });
        registry.Add("TestGenericNames", gosym_internal_test_package.TestGenericNames, "symtab_test.go", 36);
        registry.Add("TestIssue29551", gosym_internal_test_package.TestIssue29551, "symtab_test.go", 64);
        registry.Add("TestLineAline", gosym_internal_test_package.TestLineAline, "pclntab_test.go", 161);
        registry.Add("TestLineFromAline", gosym_internal_test_package.TestLineFromAline, "pclntab_test.go", 112);
        registry.Add("TestPCLine", gosym_internal_test_package.TestPCLine, "pclntab_test.go", 204);
        registry.Add("TestRemotePackage", gosym_internal_test_package.TestRemotePackage, "symtab_test.go", 55);
        registry.Add("TestStandardLibPackage", gosym_internal_test_package.TestStandardLibPackage, "symtab_test.go", 18);
        registry.Add("TestStandardLibPathPackage", gosym_internal_test_package.TestStandardLibPathPackage, "symtab_test.go", 27);
        registry.Add("TestSymVersion", gosym_internal_test_package.TestSymVersion, "pclntab_test.go", 271);
        return TestHost.Run(registry, args);
    }
}
