// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/sha1", new string[]
        {
            "example_test.go",
            "fallback_test.go",
            "issue15617_test.go",
            "sha1.go",
            "sha1_test.go",
            "sha1block.go",
            "sha1block_amd64.go",
            "sha1block_arm64.go",
            "sha1block_decl.go",
            "sha1block_generic.go",
            "sha1block_s390x.go",
        });
        registry.Add("TestAllocations", sha1_internal_test_package.TestAllocations, "sha1_test.go", 221);
        registry.Add("TestBlockGeneric", sha1_internal_test_package.TestBlockGeneric, "sha1_test.go", 148);
        registry.Add("TestBlockSize", sha1_internal_test_package.TestBlockSize, "sha1_test.go", 140);
        registry.Add("TestGolden", sha1_internal_test_package.TestGolden, "sha1_test.go", 62);
        registry.Add("TestGoldenMarshal", sha1_internal_test_package.TestGoldenMarshal, "sha1_test.go", 99);
        registry.Add("TestLargeHashes", sha1_internal_test_package.TestLargeHashes, "sha1_test.go", 200);
        registry.Add("TestSHA1Hash", sha1_internal_test_package.TestSHA1Hash, "sha1_test.go", 238);
        registry.Add("TestSize", sha1_internal_test_package.TestSize, "sha1_test.go", 133);
        return TestHost.Run(registry, args);
    }
}
