// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal.syscall.windows;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/syscall/windows/registry", new string[]
        {
            "export_test.go",
            "key.go",
            "mksyscall.go",
            "registry_test.go",
            "syscall.go",
            "value.go",
            "zsyscall_windows.go",
        });
        registry.Add("TestCreateOpenDeleteKey", registry_test_package.TestCreateOpenDeleteKey, "registry_test.go", 53);
        registry.Add("TestExpandString", registry_test_package.TestExpandString, "registry_test.go", 525);
        registry.Add("TestGetMUIStringValue", registry_test_package.TestGetMUIStringValue, "registry_test.go", 601);
        registry.Add("TestInvalidValues", registry_test_package.TestInvalidValues, "registry_test.go", 536);
        registry.Add("TestReadSubKeyNames", registry_test_package.TestReadSubKeyNames, "registry_test.go", 30);
        registry.Add("TestValues", registry_test_package.TestValues, "registry_test.go", 493);
        return TestHost.Run(registry, args);
    }
}
