// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("internal/sync", new string[]
        {
            "export_test.go",
            "hashtriemap.go",
            "hashtriemap_bench_test.go",
            "hashtriemap_test.go",
            "mutex.go",
            "runtime.go",
        });
        registry.Add("TestConcurrentCache", sync_test_package.TestConcurrentCache, "hashtriemap_test.go", 933);
        registry.Add("TestHashTrieMap", sync_test_package.TestHashTrieMap, "hashtriemap_test.go", 18);
        registry.Add("TestHashTrieMapBadHash", sync_test_package.TestHashTrieMapBadHash, "hashtriemap_test.go", 25);
        registry.Add("TestHashTrieMapTruncHash", sync_test_package.TestHashTrieMapTruncHash, "hashtriemap_test.go", 31);
        return TestHost.Run(registry, args);
    }
}
