// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.go.@internal;

using global::go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("go/internal/srcimporter", new string[]
        {
            "srcimporter.go",
            "srcimporter_test.go",
            "testdata/issue20855/issue20855.go",
            "testdata/issue23092/issue23092.go",
            "testdata/issue24392/issue24392.go",
        }, new string[]
        {
            "testdata",
        });
        registry.Add("TestCgo", srcimporter_internal_test_package.TestCgo, "srcimporter_test.go", 242);
        registry.Add("TestImportStdLib", srcimporter_internal_test_package.TestImportStdLib, "srcimporter_test.go", 85);
        registry.Add("TestImportedTypes", srcimporter_internal_test_package.TestImportedTypes, "srcimporter_test.go", 111);
        registry.Add("TestIssue20855", srcimporter_internal_test_package.TestIssue20855, "srcimporter_test.go", 197);
        registry.Add("TestIssue23092", srcimporter_internal_test_package.TestIssue23092, "srcimporter_test.go", 233);
        registry.Add("TestIssue24392", srcimporter_internal_test_package.TestIssue24392, "srcimporter_test.go", 238);
        registry.Add("TestReimport", srcimporter_internal_test_package.TestReimport, "srcimporter_test.go", 181);
        registry.SetTestMain(srcimporter_internal_test_package.TestMain);
        return TestHost.Run(registry, args);
    }
}
