// Copyright 2022 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by 'go generate' DO NOT EDIT.
//go:generate ./mkstd.sh
[assembly: global::go.GoPositionMap("go/doc/comment/std.go", "std.cs", "")]

namespace go.go.doc;

partial class comment_package {

internal static slice<@string> stdPkgs = new @string[]{
    "bufio"u8,
    "bytes"u8,
    "cmp"u8,
    "context"u8,
    "crypto"u8,
    "embed"u8,
    "encoding"u8,
    "errors"u8,
    "expvar"u8,
    "flag"u8,
    "fmt"u8,
    "hash"u8,
    "html"u8,
    "image"u8,
    "io"u8,
    "iter"u8,
    "log"u8,
    "maps"u8,
    "math"u8,
    "mime"u8,
    "net"u8,
    "os"u8,
    "path"u8,
    "plugin"u8,
    "reflect"u8,
    "regexp"u8,
    "runtime"u8,
    "slices"u8,
    "sort"u8,
    "strconv"u8,
    "strings"u8,
    "structs"u8,
    "sync"u8,
    "syscall"u8,
    "testing"u8,
    "time"u8,
    "unicode"u8,
    "unique"u8,
    "unsafe"u8
}.slice();

} // end comment_package
