using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using go.golib;
using static go.builtin;
using static go.runtime_package;

// Round 4's MARKED shapes: the converter's wrappers read their receivers through golib's wrapperRecv /
// panicwrapRecv, which raise the wrapper's own panic on a nil receiver. That marker is what runtime.Callers
// keys the wrapper frame on.
namespace go;

internal static partial class panicframesprobe_package
{
    // A PROMOTED value method's wrapper, as the converter now emits it. Go for (*OuterV).IM(nil):
    // gopanic | panicmem | sigpanic | (*OuterV).IM | owner.
    internal static readonly Func<ж<OuterV>, nint> promotedWrapperMarked =
        ((Func<ж<OuterV>, nint>)([GoWrapper("(*OuterV).IM")] (p0) => IM(wrapperRecv(p0).Value)));

    [MethodImpl(MethodImplOptions.NoInlining)]
    internal static List<string> nilThroughMarkedPromotedWrapper()
    {
        List<string> got = [];
        GoFrame ᒐ = default;
        try {
            defer(() => { recover(); got = callersHere(); }, ref ᒐ);
            got = [promotedWrapperMarked(null!).ToString()];
        }
        catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
        finally { ᒐ.Run(); }
        return got;
    }

    // The wrapper frame's POSITION: Go's autogenerated wrapper reports <autogenerated>:1.
    [MethodImpl(MethodImplOptions.NoInlining)]
    internal static List<(string function, string file, long line)> nilThroughInterfaceWrapperWithFiles()
    {
        List<(string function, string file, long line)> got = [];
        GoFrame ᒐ = default;
        try {
            defer(() => {
                recover();
                slice<uintptr> pcs = new(64);
                pcs = pcs[..(int)Callers(0, pcs)];
                var iterator = CallersFrames(pcs);

                while (true)
                {
                    var (frame, more) = iterator.Next();

                    if (frame.PC == 0 && !more)
                        break;

                    got.Add(((string)frame.Function, (string)frame.File, frame.Line));

                    if (!more)
                        break;
                }
            }, ref ᒐ);
            wrapperprobe_package.interfaceWrapper(null!);
        }
        catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
        finally { ᒐ.Run(); }
        return got;
    }

    // The receiver as the converter passes it: Go's `nil` is golib's `nil`, whose conversion to ж<T> is the
    // canonical NilBox, a NON-null box (runtime's TestStackWrapperStackPanic/panicwrap calls `wrapper(nil)`).
    [MethodImpl(MethodImplOptions.NoInlining)]
    internal static List<string> nilBoxThroughPointerWrapper()
    {
        List<string> got = [];
        GoFrame ᒐ = default;
        try {
            defer(() => { recoveredPanicwrap = recover(); got = callersHere(); }, ref ᒐ);
            got = [pointerWrapper(nil).ToString()];
        }
        catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
        finally { ᒐ.Run(); }
        return got;
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    internal static List<string> nilBoxThroughMarkedPromotedWrapper()
    {
        List<string> got = [];
        GoFrame ᒐ = default;
        try {
            defer(() => { recover(); got = callersHere(); }, ref ᒐ);
            got = [promotedWrapperMarked(nil).ToString()];
        }
        catch (Exception ᒐex) when (GoFrame.IsPanic(ᒐex, out PanicException? ᒐp)) { GoFrame.Capture(ᒐp); }
        finally { ᒐ.Run(); }
        return got;
    }
}
