// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/internal/nistec", new string[]
        {
            "generate.go",
            "nistec.go",
            "nistec_test.go",
            "p224.go",
            "p224_sqrt.go",
            "p256.go",
            "p256_asm.go",
            "p256_asm_table_test.go",
            "p256_ordinv.go",
            "p256_ordinv_noasm.go",
            "p256_ordinv_test.go",
            "p384.go",
            "p521.go",
        }, new string[]
        {
            "fiat",
        });
        registry.Add("TestAllocations", nistec_test_package.TestAllocations, "nistec_test.go", 18);
        registry.Add("TestEquivalents", nistec_test_package.TestEquivalents, "nistec_test.go", 109);
        registry.Add("TestScalarMult", nistec_test_package.TestScalarMult, "nistec_test.go", 161);
        return TestHost.Run(registry, args);
    }
}
