// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.crypto;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("crypto/pbkdf2", new string[]
        {
            "pbkdf2.go",
            "pbkdf2_test.go",
        });
        registry.Add("TestMaxKeyLength", pbkdf2_test_package.TestMaxKeyLength, "pbkdf2_test.go", 225);
        registry.Add("TestPBKDF2ServiceIndicator", pbkdf2_test_package.TestPBKDF2ServiceIndicator, "pbkdf2_test.go", 188);
        registry.Add("TestWithHMACSHA1", pbkdf2_test_package.TestWithHMACSHA1, "pbkdf2_test.go", 157);
        registry.Add("TestWithHMACSHA256", pbkdf2_test_package.TestWithHMACSHA256, "pbkdf2_test.go", 161);
        registry.Add("TestZeroKeyLength", pbkdf2_test_package.TestZeroKeyLength, "pbkdf2_test.go", 244);
        return TestHost.Run(registry, args);
    }
}
