// mkerrors.sh -m64
// Code generated by the command above; DO NOT EDIT.
// Created by cgo -godefs - DO NOT EDIT
// cgo -godefs -- -m64 _const.go
//go:build amd64 && linux
namespace go;

partial class syscall_package {

public static UntypedInt AF_ALG => 0x26;
public static UntypedInt AF_APPLETALK => 0x5;
public static UntypedInt AF_ASH => 0x12;
public static UntypedInt AF_ATMPVC => 0x8;
public static UntypedInt AF_ATMSVC => 0x14;
public static UntypedInt AF_AX25 => 0x3;
public static UntypedInt AF_BLUETOOTH => 0x1f;
public static UntypedInt AF_BRIDGE => 0x7;
public static UntypedInt AF_CAIF => 0x25;
public static UntypedInt AF_CAN => 0x1d;
public static UntypedInt AF_DECnet => 0xc;
public static UntypedInt AF_ECONET => 0x13;
public static UntypedInt AF_FILE => 0x1;
public static UntypedInt AF_IEEE802154 => 0x24;
public static UntypedInt AF_INET => 0x2;
public static UntypedInt AF_INET6 => 0xa;
public static UntypedInt AF_IPX => 0x4;
public static UntypedInt AF_IRDA => 0x17;
public static UntypedInt AF_ISDN => 0x22;
public static UntypedInt AF_IUCV => 0x20;
public static UntypedInt AF_KEY => 0xf;
public static UntypedInt AF_LLC => 0x1a;
public static UntypedInt AF_LOCAL => 0x1;
public static UntypedInt AF_MAX => 0x27;
public static UntypedInt AF_NETBEUI => 0xd;
public static UntypedInt AF_NETLINK => 0x10;
public static UntypedInt AF_NETROM => 0x6;
public static UntypedInt AF_PACKET => 0x11;
public static UntypedInt AF_PHONET => 0x23;
public static UntypedInt AF_PPPOX => 0x18;
public static UntypedInt AF_RDS => 0x15;
public static UntypedInt AF_ROSE => 0xb;
public static UntypedInt AF_ROUTE => 0x10;
public static UntypedInt AF_RXRPC => 0x21;
public static UntypedInt AF_SECURITY => 0xe;
public static UntypedInt AF_SNA => 0x16;
public static UntypedInt AF_TIPC => 0x1e;
public static UntypedInt AF_UNIX => 0x1;
public static UntypedInt AF_UNSPEC => 0x0;
public static UntypedInt AF_WANPIPE => 0x19;
public static UntypedInt AF_X25 => 0x9;
public static UntypedInt ARPHRD_ADAPT => 0x108;
public static UntypedInt ARPHRD_APPLETLK => 0x8;
public static UntypedInt ARPHRD_ARCNET => 0x7;
public static UntypedInt ARPHRD_ASH => 0x30d;
public static UntypedInt ARPHRD_ATM => 0x13;
public static UntypedInt ARPHRD_AX25 => 0x3;
public static UntypedInt ARPHRD_BIF => 0x307;
public static UntypedInt ARPHRD_CHAOS => 0x5;
public static UntypedInt ARPHRD_CISCO => 0x201;
public static UntypedInt ARPHRD_CSLIP => 0x101;
public static UntypedInt ARPHRD_CSLIP6 => 0x103;
public static UntypedInt ARPHRD_DDCMP => 0x205;
public static UntypedInt ARPHRD_DLCI => 0xf;
public static UntypedInt ARPHRD_ECONET => 0x30e;
public static UntypedInt ARPHRD_EETHER => 0x2;
public static UntypedInt ARPHRD_ETHER => 0x1;
public static UntypedInt ARPHRD_EUI64 => 0x1b;
public static UntypedInt ARPHRD_FCAL => 0x311;
public static UntypedInt ARPHRD_FCFABRIC => 0x313;
public static UntypedInt ARPHRD_FCPL => 0x312;
public static UntypedInt ARPHRD_FCPP => 0x310;
public static UntypedInt ARPHRD_FDDI => 0x306;
public static UntypedInt ARPHRD_FRAD => 0x302;
public static UntypedInt ARPHRD_HDLC => 0x201;
public static UntypedInt ARPHRD_HIPPI => 0x30c;
public static UntypedInt ARPHRD_HWX25 => 0x110;
public static UntypedInt ARPHRD_IEEE1394 => 0x18;
public static UntypedInt ARPHRD_IEEE802 => 0x6;
public static UntypedInt ARPHRD_IEEE80211 => 0x321;
public static UntypedInt ARPHRD_IEEE80211_PRISM => 0x322;
public static UntypedInt ARPHRD_IEEE80211_RADIOTAP => 0x323;
public static UntypedInt ARPHRD_IEEE802154 => 0x324;
public static UntypedInt ARPHRD_IEEE802154_PHY => 0x325;
public static UntypedInt ARPHRD_IEEE802_TR => 0x320;
public static UntypedInt ARPHRD_INFINIBAND => 0x20;
public static UntypedInt ARPHRD_IPDDP => 0x309;
public static UntypedInt ARPHRD_IPGRE => 0x30a;
public static UntypedInt ARPHRD_IRDA => 0x30f;
public static UntypedInt ARPHRD_LAPB => 0x204;
public static UntypedInt ARPHRD_LOCALTLK => 0x305;
public static UntypedInt ARPHRD_LOOPBACK => 0x304;
public static UntypedInt ARPHRD_METRICOM => 0x17;
public static UntypedInt ARPHRD_NETROM => 0x0;
public static UntypedInt ARPHRD_NONE => 0xfffe;
public static UntypedInt ARPHRD_PIMREG => 0x30b;
public static UntypedInt ARPHRD_PPP => 0x200;
public static UntypedInt ARPHRD_PRONET => 0x4;
public static UntypedInt ARPHRD_RAWHDLC => 0x206;
public static UntypedInt ARPHRD_ROSE => 0x10e;
public static UntypedInt ARPHRD_RSRVD => 0x104;
public static UntypedInt ARPHRD_SIT => 0x308;
public static UntypedInt ARPHRD_SKIP => 0x303;
public static UntypedInt ARPHRD_SLIP => 0x100;
public static UntypedInt ARPHRD_SLIP6 => 0x102;
public static UntypedInt ARPHRD_TUNNEL => 0x300;
public static UntypedInt ARPHRD_TUNNEL6 => 0x301;
public static UntypedInt ARPHRD_VOID => 0xffff;
public static UntypedInt ARPHRD_X25 => 0x10f;
public static UntypedInt BPF_A => 0x10;
public static UntypedInt BPF_ABS => 0x20;
public static UntypedInt BPF_ADD => 0x0;
public static UntypedInt BPF_ALU => 0x4;
public static UntypedInt BPF_AND => 0x50;
public static UntypedInt BPF_B => 0x10;
public static UntypedInt BPF_DIV => 0x30;
public static UntypedInt BPF_H => 0x8;
public static UntypedInt BPF_IMM => 0x0;
public static UntypedInt BPF_IND => 0x40;
public static UntypedInt BPF_JA => 0x0;
public static UntypedInt BPF_JEQ => 0x10;
public static UntypedInt BPF_JGE => 0x30;
public static UntypedInt BPF_JGT => 0x20;
public static UntypedInt BPF_JMP => 0x5;
public static UntypedInt BPF_JSET => 0x40;
public static UntypedInt BPF_K => 0x0;
public static UntypedInt BPF_LD => 0x0;
public static UntypedInt BPF_LDX => 0x1;
public static UntypedInt BPF_LEN => 0x80;
public static UntypedInt BPF_LSH => 0x60;
public static UntypedInt BPF_MAJOR_VERSION => 0x1;
public static UntypedInt BPF_MAXINSNS => 0x1000;
public static UntypedInt BPF_MEM => 0x60;
public static UntypedInt BPF_MEMWORDS => 0x10;
public static UntypedInt BPF_MINOR_VERSION => 0x1;
public static UntypedInt BPF_MISC => 0x7;
public static UntypedInt BPF_MSH => 0xa0;
public static UntypedInt BPF_MUL => 0x20;
public static UntypedInt BPF_NEG => 0x80;
public static UntypedInt BPF_OR => 0x40;
public static UntypedInt BPF_RET => 0x6;
public static UntypedInt BPF_RSH => 0x70;
public static UntypedInt BPF_ST => 0x2;
public static UntypedInt BPF_STX => 0x3;
public static UntypedInt BPF_SUB => 0x10;
public static UntypedInt BPF_TAX => 0x0;
public static UntypedInt BPF_TXA => 0x80;
public static UntypedInt BPF_W => 0x0;
public static UntypedInt BPF_X => 0x8;
public static UntypedInt DT_BLK => 0x6;
public static UntypedInt DT_CHR => 0x2;
public static UntypedInt DT_DIR => 0x4;
public static UntypedInt DT_FIFO => 0x1;
public static UntypedInt DT_LNK => 0xa;
public static UntypedInt DT_REG => 0x8;
public static UntypedInt DT_SOCK => 0xc;
public static UntypedInt DT_UNKNOWN => 0x0;
public static UntypedInt DT_WHT => 0xe;
public static UntypedInt EPOLLERR => 0x8;
public static UntypedInt EPOLLET => /* -0x80000000 */ -2147483648;
public static UntypedInt EPOLLHUP => 0x10;
public static UntypedInt EPOLLIN => 0x1;
public static UntypedInt EPOLLMSG => 0x400;
public static UntypedInt EPOLLONESHOT => 0x40000000;
public static UntypedInt EPOLLOUT => 0x4;
public static UntypedInt EPOLLPRI => 0x2;
public static UntypedInt EPOLLRDBAND => 0x80;
public static UntypedInt EPOLLRDHUP => 0x2000;
public static UntypedInt EPOLLRDNORM => 0x40;
public static UntypedInt EPOLLWRBAND => 0x200;
public static UntypedInt EPOLLWRNORM => 0x100;
public static UntypedInt EPOLL_CLOEXEC => 0x80000;
public static UntypedInt EPOLL_CTL_ADD => 0x1;
public static UntypedInt EPOLL_CTL_DEL => 0x2;
public static UntypedInt EPOLL_CTL_MOD => 0x3;
public static UntypedInt EPOLL_NONBLOCK => 0x800;
public static UntypedInt ETH_P_1588 => 0x88f7;
public static UntypedInt ETH_P_8021Q => 0x8100;
public static UntypedInt ETH_P_802_2 => 0x4;
public static UntypedInt ETH_P_802_3 => 0x1;
public static UntypedInt ETH_P_AARP => 0x80f3;
public static UntypedInt ETH_P_ALL => 0x3;
public static UntypedInt ETH_P_AOE => 0x88a2;
public static UntypedInt ETH_P_ARCNET => 0x1a;
public static UntypedInt ETH_P_ARP => 0x806;
public static UntypedInt ETH_P_ATALK => 0x809b;
public static UntypedInt ETH_P_ATMFATE => 0x8884;
public static UntypedInt ETH_P_ATMMPOA => 0x884c;
public static UntypedInt ETH_P_AX25 => 0x2;
public static UntypedInt ETH_P_BPQ => 0x8ff;
public static UntypedInt ETH_P_CAIF => 0xf7;
public static UntypedInt ETH_P_CAN => 0xc;
public static UntypedInt ETH_P_CONTROL => 0x16;
public static UntypedInt ETH_P_CUST => 0x6006;
public static UntypedInt ETH_P_DDCMP => 0x6;
public static UntypedInt ETH_P_DEC => 0x6000;
public static UntypedInt ETH_P_DIAG => 0x6005;
public static UntypedInt ETH_P_DNA_DL => 0x6001;
public static UntypedInt ETH_P_DNA_RC => 0x6002;
public static UntypedInt ETH_P_DNA_RT => 0x6003;
public static UntypedInt ETH_P_DSA => 0x1b;
public static UntypedInt ETH_P_ECONET => 0x18;
public static UntypedInt ETH_P_EDSA => 0xdada;
public static UntypedInt ETH_P_FCOE => 0x8906;
public static UntypedInt ETH_P_FIP => 0x8914;
public static UntypedInt ETH_P_HDLC => 0x19;
public static UntypedInt ETH_P_IEEE802154 => 0xf6;
public static UntypedInt ETH_P_IEEEPUP => 0xa00;
public static UntypedInt ETH_P_IEEEPUPAT => 0xa01;
public static UntypedInt ETH_P_IP => 0x800;
public static UntypedInt ETH_P_IPV6 => 0x86dd;
public static UntypedInt ETH_P_IPX => 0x8137;
public static UntypedInt ETH_P_IRDA => 0x17;
public static UntypedInt ETH_P_LAT => 0x6004;
public static UntypedInt ETH_P_LINK_CTL => 0x886c;
public static UntypedInt ETH_P_LOCALTALK => 0x9;
public static UntypedInt ETH_P_LOOP => 0x60;
public static UntypedInt ETH_P_MOBITEX => 0x15;
public static UntypedInt ETH_P_MPLS_MC => 0x8848;
public static UntypedInt ETH_P_MPLS_UC => 0x8847;
public static UntypedInt ETH_P_PAE => 0x888e;
public static UntypedInt ETH_P_PAUSE => 0x8808;
public static UntypedInt ETH_P_PHONET => 0xf5;
public static UntypedInt ETH_P_PPPTALK => 0x10;
public static UntypedInt ETH_P_PPP_DISC => 0x8863;
public static UntypedInt ETH_P_PPP_MP => 0x8;
public static UntypedInt ETH_P_PPP_SES => 0x8864;
public static UntypedInt ETH_P_PUP => 0x200;
public static UntypedInt ETH_P_PUPAT => 0x201;
public static UntypedInt ETH_P_RARP => 0x8035;
public static UntypedInt ETH_P_SCA => 0x6007;
public static UntypedInt ETH_P_SLOW => 0x8809;
public static UntypedInt ETH_P_SNAP => 0x5;
public static UntypedInt ETH_P_TEB => 0x6558;
public static UntypedInt ETH_P_TIPC => 0x88ca;
public static UntypedInt ETH_P_TRAILER => 0x1c;
public static UntypedInt ETH_P_TR_802_2 => 0x11;
public static UntypedInt ETH_P_WAN_PPP => 0x7;
public static UntypedInt ETH_P_WCCP => 0x883e;
public static UntypedInt ETH_P_X25 => 0x805;
public static UntypedInt FD_CLOEXEC => 0x1;
public static UntypedInt FD_SETSIZE => 0x400;
public static UntypedInt F_DUPFD => 0x0;
public static UntypedInt F_DUPFD_CLOEXEC => 0x406;
public static UntypedInt F_EXLCK => 0x4;
public static UntypedInt F_GETFD => 0x1;
public static UntypedInt F_GETFL => 0x3;
public static UntypedInt F_GETLEASE => 0x401;
public static UntypedInt F_GETLK => 0x5;
public static UntypedInt F_GETLK64 => 0x5;
public static UntypedInt F_GETOWN => 0x9;
public static UntypedInt F_GETOWN_EX => 0x10;
public static UntypedInt F_GETPIPE_SZ => 0x408;
public static UntypedInt F_GETSIG => 0xb;
public static UntypedInt F_LOCK => 0x1;
public static UntypedInt F_NOTIFY => 0x402;
public static UntypedInt F_OK => 0x0;
public static UntypedInt F_RDLCK => 0x0;
public static UntypedInt F_SETFD => 0x2;
public static UntypedInt F_SETFL => 0x4;
public static UntypedInt F_SETLEASE => 0x400;
public static UntypedInt F_SETLK => 0x6;
public static UntypedInt F_SETLK64 => 0x6;
public static UntypedInt F_SETLKW => 0x7;
public static UntypedInt F_SETLKW64 => 0x7;
public static UntypedInt F_SETOWN => 0x8;
public static UntypedInt F_SETOWN_EX => 0xf;
public static UntypedInt F_SETPIPE_SZ => 0x407;
public static UntypedInt F_SETSIG => 0xa;
public static UntypedInt F_SHLCK => 0x8;
public static UntypedInt F_TEST => 0x3;
public static UntypedInt F_TLOCK => 0x2;
public static UntypedInt F_ULOCK => 0x0;
public static UntypedInt F_UNLCK => 0x2;
public static UntypedInt F_WRLCK => 0x1;
public static UntypedInt ICMPV6_FILTER => 0x1;
public static UntypedInt IFA_F_DADFAILED => 0x8;
public static UntypedInt IFA_F_DEPRECATED => 0x20;
public static UntypedInt IFA_F_HOMEADDRESS => 0x10;
public static UntypedInt IFA_F_NODAD => 0x2;
public static UntypedInt IFA_F_OPTIMISTIC => 0x4;
public static UntypedInt IFA_F_PERMANENT => 0x80;
public static UntypedInt IFA_F_SECONDARY => 0x1;
public static UntypedInt IFA_F_TEMPORARY => 0x1;
public static UntypedInt IFA_F_TENTATIVE => 0x40;
public static UntypedInt IFA_MAX => 0x7;
public static UntypedInt IFF_ALLMULTI => 0x200;
public static UntypedInt IFF_AUTOMEDIA => 0x4000;
public static UntypedInt IFF_BROADCAST => 0x2;
public static UntypedInt IFF_DEBUG => 0x4;
public static UntypedInt IFF_DYNAMIC => 0x8000;
public static UntypedInt IFF_LOOPBACK => 0x8;
public static UntypedInt IFF_MASTER => 0x400;
public static UntypedInt IFF_MULTICAST => 0x1000;
public static UntypedInt IFF_NOARP => 0x80;
public static UntypedInt IFF_NOTRAILERS => 0x20;
public static UntypedInt IFF_NO_PI => 0x1000;
public static UntypedInt IFF_ONE_QUEUE => 0x2000;
public static UntypedInt IFF_POINTOPOINT => 0x10;
public static UntypedInt IFF_PORTSEL => 0x2000;
public static UntypedInt IFF_PROMISC => 0x100;
public static UntypedInt IFF_RUNNING => 0x40;
public static UntypedInt IFF_SLAVE => 0x800;
public static UntypedInt IFF_TAP => 0x2;
public static UntypedInt IFF_TUN => 0x1;
public static UntypedInt IFF_TUN_EXCL => 0x8000;
public static UntypedInt IFF_UP => 0x1;
public static UntypedInt IFF_VNET_HDR => 0x4000;
public static UntypedInt IFNAMSIZ => 0x10;
public static UntypedInt IN_ACCESS => 0x1;
public static UntypedInt IN_ALL_EVENTS => 0xfff;
public static UntypedInt IN_ATTRIB => 0x4;
public static UntypedInt IN_CLASSA_HOST => 0xffffff;
public static UntypedInt IN_CLASSA_MAX => 0x80;
public static UntypedInt IN_CLASSA_NET => 0xff000000;
public static UntypedInt IN_CLASSA_NSHIFT => 0x18;
public static UntypedInt IN_CLASSB_HOST => 0xffff;
public static UntypedInt IN_CLASSB_MAX => 0x10000;
public static UntypedInt IN_CLASSB_NET => 0xffff0000;
public static UntypedInt IN_CLASSB_NSHIFT => 0x10;
public static UntypedInt IN_CLASSC_HOST => 0xff;
public static UntypedInt IN_CLASSC_NET => 0xffffff00;
public static UntypedInt IN_CLASSC_NSHIFT => 0x8;
public static UntypedInt IN_CLOEXEC => 0x80000;
public static UntypedInt IN_CLOSE => 0x18;
public static UntypedInt IN_CLOSE_NOWRITE => 0x10;
public static UntypedInt IN_CLOSE_WRITE => 0x8;
public static UntypedInt IN_CREATE => 0x100;
public static UntypedInt IN_DELETE => 0x200;
public static UntypedInt IN_DELETE_SELF => 0x400;
public static UntypedInt IN_DONT_FOLLOW => 0x2000000;
public static UntypedInt IN_EXCL_UNLINK => 0x4000000;
public static UntypedInt IN_IGNORED => 0x8000;
public static UntypedInt IN_ISDIR => 0x40000000;
public static UntypedInt IN_LOOPBACKNET => 0x7f;
public static UntypedInt IN_MASK_ADD => 0x20000000;
public static UntypedInt IN_MODIFY => 0x2;
public static UntypedInt IN_MOVE => 0xc0;
public static UntypedInt IN_MOVED_FROM => 0x40;
public static UntypedInt IN_MOVED_TO => 0x80;
public static UntypedInt IN_MOVE_SELF => 0x800;
public static UntypedInt IN_NONBLOCK => 0x800;
public static UntypedInt IN_ONESHOT => 0x80000000;
public static UntypedInt IN_ONLYDIR => 0x1000000;
public static UntypedInt IN_OPEN => 0x20;
public static UntypedInt IN_Q_OVERFLOW => 0x4000;
public static UntypedInt IN_UNMOUNT => 0x2000;
public static UntypedInt IPPROTO_AH => 0x33;
public static UntypedInt IPPROTO_COMP => 0x6c;
public static UntypedInt IPPROTO_DCCP => 0x21;
public static UntypedInt IPPROTO_DSTOPTS => 0x3c;
public static UntypedInt IPPROTO_EGP => 0x8;
public static UntypedInt IPPROTO_ENCAP => 0x62;
public static UntypedInt IPPROTO_ESP => 0x32;
public static UntypedInt IPPROTO_FRAGMENT => 0x2c;
public static UntypedInt IPPROTO_GRE => 0x2f;
public static UntypedInt IPPROTO_HOPOPTS => 0x0;
public static UntypedInt IPPROTO_ICMP => 0x1;
public static UntypedInt IPPROTO_ICMPV6 => 0x3a;
public static UntypedInt IPPROTO_IDP => 0x16;
public static UntypedInt IPPROTO_IGMP => 0x2;
public static UntypedInt IPPROTO_IP => 0x0;
public static UntypedInt IPPROTO_IPIP => 0x4;
public static UntypedInt IPPROTO_IPV6 => 0x29;
public static UntypedInt IPPROTO_MTP => 0x5c;
public static UntypedInt IPPROTO_NONE => 0x3b;
public static UntypedInt IPPROTO_PIM => 0x67;
public static UntypedInt IPPROTO_PUP => 0xc;
public static UntypedInt IPPROTO_RAW => 0xff;
public static UntypedInt IPPROTO_ROUTING => 0x2b;
public static UntypedInt IPPROTO_RSVP => 0x2e;
public static UntypedInt IPPROTO_SCTP => 0x84;
public static UntypedInt IPPROTO_TCP => 0x6;
public static UntypedInt IPPROTO_TP => 0x1d;
public static UntypedInt IPPROTO_UDP => 0x11;
public static UntypedInt IPPROTO_UDPLITE => 0x88;
public static UntypedInt IPV6_2292DSTOPTS => 0x4;
public static UntypedInt IPV6_2292HOPLIMIT => 0x8;
public static UntypedInt IPV6_2292HOPOPTS => 0x3;
public static UntypedInt IPV6_2292PKTINFO => 0x2;
public static UntypedInt IPV6_2292PKTOPTIONS => 0x6;
public static UntypedInt IPV6_2292RTHDR => 0x5;
public static UntypedInt IPV6_ADDRFORM => 0x1;
public static UntypedInt IPV6_ADD_MEMBERSHIP => 0x14;
public static UntypedInt IPV6_AUTHHDR => 0xa;
public static UntypedInt IPV6_CHECKSUM => 0x7;
public static UntypedInt IPV6_DROP_MEMBERSHIP => 0x15;
public static UntypedInt IPV6_DSTOPTS => 0x3b;
public static UntypedInt IPV6_HOPLIMIT => 0x34;
public static UntypedInt IPV6_HOPOPTS => 0x36;
public static UntypedInt IPV6_IPSEC_POLICY => 0x22;
public static UntypedInt IPV6_JOIN_ANYCAST => 0x1b;
public static UntypedInt IPV6_JOIN_GROUP => 0x14;
public static UntypedInt IPV6_LEAVE_ANYCAST => 0x1c;
public static UntypedInt IPV6_LEAVE_GROUP => 0x15;
public static UntypedInt IPV6_MTU => 0x18;
public static UntypedInt IPV6_MTU_DISCOVER => 0x17;
public static UntypedInt IPV6_MULTICAST_HOPS => 0x12;
public static UntypedInt IPV6_MULTICAST_IF => 0x11;
public static UntypedInt IPV6_MULTICAST_LOOP => 0x13;
public static UntypedInt IPV6_NEXTHOP => 0x9;
public static UntypedInt IPV6_PKTINFO => 0x32;
public static UntypedInt IPV6_PMTUDISC_DO => 0x2;
public static UntypedInt IPV6_PMTUDISC_DONT => 0x0;
public static UntypedInt IPV6_PMTUDISC_PROBE => 0x3;
public static UntypedInt IPV6_PMTUDISC_WANT => 0x1;
public static UntypedInt IPV6_RECVDSTOPTS => 0x3a;
public static UntypedInt IPV6_RECVERR => 0x19;
public static UntypedInt IPV6_RECVHOPLIMIT => 0x33;
public static UntypedInt IPV6_RECVHOPOPTS => 0x35;
public static UntypedInt IPV6_RECVPKTINFO => 0x31;
public static UntypedInt IPV6_RECVRTHDR => 0x38;
public static UntypedInt IPV6_RECVTCLASS => 0x42;
public static UntypedInt IPV6_ROUTER_ALERT => 0x16;
public static UntypedInt IPV6_RTHDR => 0x39;
public static UntypedInt IPV6_RTHDRDSTOPTS => 0x37;
public static UntypedInt IPV6_RTHDR_LOOSE => 0x0;
public static UntypedInt IPV6_RTHDR_STRICT => 0x1;
public static UntypedInt IPV6_RTHDR_TYPE_0 => 0x0;
public static UntypedInt IPV6_RXDSTOPTS => 0x3b;
public static UntypedInt IPV6_RXHOPOPTS => 0x36;
public static UntypedInt IPV6_TCLASS => 0x43;
public static UntypedInt IPV6_UNICAST_HOPS => 0x10;
public static UntypedInt IPV6_V6ONLY => 0x1a;
public static UntypedInt IPV6_XFRM_POLICY => 0x23;
public static UntypedInt IP_ADD_MEMBERSHIP => 0x23;
public static UntypedInt IP_ADD_SOURCE_MEMBERSHIP => 0x27;
public static UntypedInt IP_BLOCK_SOURCE => 0x26;
public static UntypedInt IP_DEFAULT_MULTICAST_LOOP => 0x1;
public static UntypedInt IP_DEFAULT_MULTICAST_TTL => 0x1;
public static UntypedInt IP_DF => 0x4000;
public static UntypedInt IP_DROP_MEMBERSHIP => 0x24;
public static UntypedInt IP_DROP_SOURCE_MEMBERSHIP => 0x28;
public static UntypedInt IP_FREEBIND => 0xf;
public static UntypedInt IP_HDRINCL => 0x3;
public static UntypedInt IP_IPSEC_POLICY => 0x10;
public static UntypedInt IP_MAXPACKET => 0xffff;
public static UntypedInt IP_MAX_MEMBERSHIPS => 0x14;
public static UntypedInt IP_MF => 0x2000;
public static UntypedInt IP_MINTTL => 0x15;
public static UntypedInt IP_MSFILTER => 0x29;
public static UntypedInt IP_MSS => 0x240;
public static UntypedInt IP_MTU => 0xe;
public static UntypedInt IP_MTU_DISCOVER => 0xa;
public static UntypedInt IP_MULTICAST_IF => 0x20;
public static UntypedInt IP_MULTICAST_LOOP => 0x22;
public static UntypedInt IP_MULTICAST_TTL => 0x21;
public static UntypedInt IP_OFFMASK => 0x1fff;
public static UntypedInt IP_OPTIONS => 0x4;
public static UntypedInt IP_ORIGDSTADDR => 0x14;
public static UntypedInt IP_PASSSEC => 0x12;
public static UntypedInt IP_PKTINFO => 0x8;
public static UntypedInt IP_PKTOPTIONS => 0x9;
public static UntypedInt IP_PMTUDISC => 0xa;
public static UntypedInt IP_PMTUDISC_DO => 0x2;
public static UntypedInt IP_PMTUDISC_DONT => 0x0;
public static UntypedInt IP_PMTUDISC_PROBE => 0x3;
public static UntypedInt IP_PMTUDISC_WANT => 0x1;
public static UntypedInt IP_RECVERR => 0xb;
public static UntypedInt IP_RECVOPTS => 0x6;
public static UntypedInt IP_RECVORIGDSTADDR => 0x14;
public static UntypedInt IP_RECVRETOPTS => 0x7;
public static UntypedInt IP_RECVTOS => 0xd;
public static UntypedInt IP_RECVTTL => 0xc;
public static UntypedInt IP_RETOPTS => 0x7;
public static UntypedInt IP_RF => 0x8000;
public static UntypedInt IP_ROUTER_ALERT => 0x5;
public static UntypedInt IP_TOS => 0x1;
public static UntypedInt IP_TRANSPARENT => 0x13;
public static UntypedInt IP_TTL => 0x2;
public static UntypedInt IP_UNBLOCK_SOURCE => 0x25;
public static UntypedInt IP_XFRM_POLICY => 0x11;
public static UntypedInt LINUX_REBOOT_CMD_CAD_OFF => 0x0;
public static UntypedInt LINUX_REBOOT_CMD_CAD_ON => 0x89abcdef;
public static UntypedInt LINUX_REBOOT_CMD_HALT => 0xcdef0123;
public static UntypedInt LINUX_REBOOT_CMD_KEXEC => 0x45584543;
public static UntypedInt LINUX_REBOOT_CMD_POWER_OFF => 0x4321fedc;
public static UntypedInt LINUX_REBOOT_CMD_RESTART => 0x1234567;
public static UntypedInt LINUX_REBOOT_CMD_RESTART2 => 0xa1b2c3d4;
public static UntypedInt LINUX_REBOOT_CMD_SW_SUSPEND => 0xd000fce2;
public static UntypedInt LINUX_REBOOT_MAGIC1 => 0xfee1dead;
public static UntypedInt LINUX_REBOOT_MAGIC2 => 0x28121969;
public static UntypedInt LOCK_EX => 0x2;
public static UntypedInt LOCK_NB => 0x4;
public static UntypedInt LOCK_SH => 0x1;
public static UntypedInt LOCK_UN => 0x8;
public static UntypedInt MADV_DOFORK => 0xb;
public static UntypedInt MADV_DONTFORK => 0xa;
public static UntypedInt MADV_DONTNEED => 0x4;
public static UntypedInt MADV_HUGEPAGE => 0xe;
public static UntypedInt MADV_HWPOISON => 0x64;
public static UntypedInt MADV_MERGEABLE => 0xc;
public static UntypedInt MADV_NOHUGEPAGE => 0xf;
public static UntypedInt MADV_NORMAL => 0x0;
public static UntypedInt MADV_RANDOM => 0x1;
public static UntypedInt MADV_REMOVE => 0x9;
public static UntypedInt MADV_SEQUENTIAL => 0x2;
public static UntypedInt MADV_UNMERGEABLE => 0xd;
public static UntypedInt MADV_WILLNEED => 0x3;
public static UntypedInt MAP_32BIT => 0x40;
public static UntypedInt MAP_ANON => 0x20;
public static UntypedInt MAP_ANONYMOUS => 0x20;
public static UntypedInt MAP_DENYWRITE => 0x800;
public static UntypedInt MAP_EXECUTABLE => 0x1000;
public static UntypedInt MAP_FILE => 0x0;
public static UntypedInt MAP_FIXED => 0x10;
public static UntypedInt MAP_GROWSDOWN => 0x100;
public static UntypedInt MAP_HUGETLB => 0x40000;
public static UntypedInt MAP_LOCKED => 0x2000;
public static UntypedInt MAP_NONBLOCK => 0x10000;
public static UntypedInt MAP_NORESERVE => 0x4000;
public static UntypedInt MAP_POPULATE => 0x8000;
public static UntypedInt MAP_PRIVATE => 0x2;
public static UntypedInt MAP_SHARED => 0x1;
public static UntypedInt MAP_STACK => 0x20000;
public static UntypedInt MAP_TYPE => 0xf;
public static UntypedInt MCL_CURRENT => 0x1;
public static UntypedInt MCL_FUTURE => 0x2;
public static UntypedInt MNT_DETACH => 0x2;
public static UntypedInt MNT_EXPIRE => 0x4;
public static UntypedInt MNT_FORCE => 0x1;
public static UntypedInt MSG_CMSG_CLOEXEC => 0x40000000;
public static UntypedInt MSG_CONFIRM => 0x800;
public static UntypedInt MSG_CTRUNC => 0x8;
public static UntypedInt MSG_DONTROUTE => 0x4;
public static UntypedInt MSG_DONTWAIT => 0x40;
public static UntypedInt MSG_EOR => 0x80;
public static UntypedInt MSG_ERRQUEUE => 0x2000;
public static UntypedInt MSG_FASTOPEN => 0x20000000;
public static UntypedInt MSG_FIN => 0x200;
public static UntypedInt MSG_MORE => 0x8000;
public static UntypedInt MSG_NOSIGNAL => 0x4000;
public static UntypedInt MSG_OOB => 0x1;
public static UntypedInt MSG_PEEK => 0x2;
public static UntypedInt MSG_PROXY => 0x10;
public static UntypedInt MSG_RST => 0x1000;
public static UntypedInt MSG_SYN => 0x400;
public static UntypedInt MSG_TRUNC => 0x20;
public static UntypedInt MSG_TRYHARD => 0x4;
public static UntypedInt MSG_WAITALL => 0x100;
public static UntypedInt MSG_WAITFORONE => 0x10000;
public static UntypedInt MS_ACTIVE => 0x40000000;
public static UntypedInt MS_ASYNC => 0x1;
public static UntypedInt MS_BIND => 0x1000;
public static UntypedInt MS_DIRSYNC => 0x80;
public static UntypedInt MS_INVALIDATE => 0x2;
public static UntypedInt MS_I_VERSION => 0x800000;
public static UntypedInt MS_KERNMOUNT => 0x400000;
public static UntypedInt MS_MANDLOCK => 0x40;
public static UntypedInt MS_MGC_MSK => 0xffff0000;
public static UntypedInt MS_MGC_VAL => 0xc0ed0000;
public static UntypedInt MS_MOVE => 0x2000;
public static UntypedInt MS_NOATIME => 0x400;
public static UntypedInt MS_NODEV => 0x4;
public static UntypedInt MS_NODIRATIME => 0x800;
public static UntypedInt MS_NOEXEC => 0x8;
public static UntypedInt MS_NOSUID => 0x2;
public static UntypedInt MS_NOUSER => /* -0x80000000 */ -2147483648;
public static UntypedInt MS_POSIXACL => 0x10000;
public static UntypedInt MS_PRIVATE => 0x40000;
public static UntypedInt MS_RDONLY => 0x1;
public static UntypedInt MS_REC => 0x4000;
public static UntypedInt MS_RELATIME => 0x200000;
public static UntypedInt MS_REMOUNT => 0x20;
public static UntypedInt MS_RMT_MASK => 0x800051;
public static UntypedInt MS_SHARED => 0x100000;
public static UntypedInt MS_SILENT => 0x8000;
public static UntypedInt MS_SLAVE => 0x80000;
public static UntypedInt MS_STRICTATIME => 0x1000000;
public static UntypedInt MS_SYNC => 0x4;
public static UntypedInt MS_SYNCHRONOUS => 0x10;
public static UntypedInt MS_UNBINDABLE => 0x20000;
public static UntypedInt NAME_MAX => 0xff;
public static UntypedInt NETLINK_ADD_MEMBERSHIP => 0x1;
public static UntypedInt NETLINK_AUDIT => 0x9;
public static UntypedInt NETLINK_BROADCAST_ERROR => 0x4;
public static UntypedInt NETLINK_CONNECTOR => 0xb;
public static UntypedInt NETLINK_DNRTMSG => 0xe;
public static UntypedInt NETLINK_DROP_MEMBERSHIP => 0x2;
public static UntypedInt NETLINK_ECRYPTFS => 0x13;
public static UntypedInt NETLINK_FIB_LOOKUP => 0xa;
public static UntypedInt NETLINK_FIREWALL => 0x3;
public static UntypedInt NETLINK_GENERIC => 0x10;
public static UntypedInt NETLINK_INET_DIAG => 0x4;
public static UntypedInt NETLINK_IP6_FW => 0xd;
public static UntypedInt NETLINK_ISCSI => 0x8;
public static UntypedInt NETLINK_KOBJECT_UEVENT => 0xf;
public static UntypedInt NETLINK_NETFILTER => 0xc;
public static UntypedInt NETLINK_NFLOG => 0x5;
public static UntypedInt NETLINK_NO_ENOBUFS => 0x5;
public static UntypedInt NETLINK_PKTINFO => 0x3;
public static UntypedInt NETLINK_ROUTE => 0x0;
public static UntypedInt NETLINK_SCSITRANSPORT => 0x12;
public static UntypedInt NETLINK_SELINUX => 0x7;
public static UntypedInt NETLINK_UNUSED => 0x1;
public static UntypedInt NETLINK_USERSOCK => 0x2;
public static UntypedInt NETLINK_XFRM => 0x6;
public static UntypedInt NLA_ALIGNTO => 0x4;
public static UntypedInt NLA_F_NESTED => 0x8000;
public static UntypedInt NLA_F_NET_BYTEORDER => 0x4000;
public static UntypedInt NLA_HDRLEN => 0x4;
public static UntypedInt NLMSG_ALIGNTO => 0x4;
public static UntypedInt NLMSG_DONE => 0x3;
public static UntypedInt NLMSG_ERROR => 0x2;
public static UntypedInt NLMSG_HDRLEN => 0x10;
public static UntypedInt NLMSG_MIN_TYPE => 0x10;
public static UntypedInt NLMSG_NOOP => 0x1;
public static UntypedInt NLMSG_OVERRUN => 0x4;
public static UntypedInt NLM_F_ACK => 0x4;
public static UntypedInt NLM_F_APPEND => 0x800;
public static UntypedInt NLM_F_ATOMIC => 0x400;
public static UntypedInt NLM_F_CREATE => 0x400;
public static UntypedInt NLM_F_DUMP => 0x300;
public static UntypedInt NLM_F_ECHO => 0x8;
public static UntypedInt NLM_F_EXCL => 0x200;
public static UntypedInt NLM_F_MATCH => 0x200;
public static UntypedInt NLM_F_MULTI => 0x2;
public static UntypedInt NLM_F_REPLACE => 0x100;
public static UntypedInt NLM_F_REQUEST => 0x1;
public static UntypedInt NLM_F_ROOT => 0x100;
public static UntypedInt O_ACCMODE => 0x3;
public static UntypedInt O_APPEND => 0x400;
public static UntypedInt O_ASYNC => 0x2000;
public static UntypedInt O_CLOEXEC => 0x80000;
public static UntypedInt O_CREAT => 0x40;
public static UntypedInt O_DIRECT => 0x4000;
public static UntypedInt O_DIRECTORY => 0x10000;
public static UntypedInt O_DSYNC => 0x1000;
public static UntypedInt O_EXCL => 0x80;
public static UntypedInt O_FSYNC => 0x101000;
public static UntypedInt O_LARGEFILE => 0x0;
public static UntypedInt O_NDELAY => 0x800;
public static UntypedInt O_NOATIME => 0x40000;
public static UntypedInt O_NOCTTY => 0x100;
public static UntypedInt O_NOFOLLOW => 0x20000;
public static UntypedInt O_NONBLOCK => 0x800;
public static UntypedInt O_RDONLY => 0x0;
public static UntypedInt O_RDWR => 0x2;
public static UntypedInt O_RSYNC => 0x101000;
public static UntypedInt O_SYNC => 0x101000;
public static UntypedInt O_TRUNC => 0x200;
public static UntypedInt O_WRONLY => 0x1;
public static UntypedInt PACKET_ADD_MEMBERSHIP => 0x1;
public static UntypedInt PACKET_BROADCAST => 0x1;
public static UntypedInt PACKET_DROP_MEMBERSHIP => 0x2;
public static UntypedInt PACKET_FASTROUTE => 0x6;
public static UntypedInt PACKET_HOST => 0x0;
public static UntypedInt PACKET_LOOPBACK => 0x5;
public static UntypedInt PACKET_MR_ALLMULTI => 0x2;
public static UntypedInt PACKET_MR_MULTICAST => 0x0;
public static UntypedInt PACKET_MR_PROMISC => 0x1;
public static UntypedInt PACKET_MULTICAST => 0x2;
public static UntypedInt PACKET_OTHERHOST => 0x3;
public static UntypedInt PACKET_OUTGOING => 0x4;
public static UntypedInt PACKET_RECV_OUTPUT => 0x3;
public static UntypedInt PACKET_RX_RING => 0x5;
public static UntypedInt PACKET_STATISTICS => 0x6;
public static UntypedInt PRIO_PGRP => 0x1;
public static UntypedInt PRIO_PROCESS => 0x0;
public static UntypedInt PRIO_USER => 0x2;
public static UntypedInt PROT_EXEC => 0x4;
public static UntypedInt PROT_GROWSDOWN => 0x1000000;
public static UntypedInt PROT_GROWSUP => 0x2000000;
public static UntypedInt PROT_NONE => 0x0;
public static UntypedInt PROT_READ => 0x1;
public static UntypedInt PROT_WRITE => 0x2;
public static UntypedInt PR_CAPBSET_DROP => 0x18;
public static UntypedInt PR_CAPBSET_READ => 0x17;
public static UntypedInt PR_ENDIAN_BIG => 0x0;
public static UntypedInt PR_ENDIAN_LITTLE => 0x1;
public static UntypedInt PR_ENDIAN_PPC_LITTLE => 0x2;
public static UntypedInt PR_FPEMU_NOPRINT => 0x1;
public static UntypedInt PR_FPEMU_SIGFPE => 0x2;
public static UntypedInt PR_FP_EXC_ASYNC => 0x2;
public static UntypedInt PR_FP_EXC_DISABLED => 0x0;
public static UntypedInt PR_FP_EXC_DIV => 0x10000;
public static UntypedInt PR_FP_EXC_INV => 0x100000;
public static UntypedInt PR_FP_EXC_NONRECOV => 0x1;
public static UntypedInt PR_FP_EXC_OVF => 0x20000;
public static UntypedInt PR_FP_EXC_PRECISE => 0x3;
public static UntypedInt PR_FP_EXC_RES => 0x80000;
public static UntypedInt PR_FP_EXC_SW_ENABLE => 0x80;
public static UntypedInt PR_FP_EXC_UND => 0x40000;
public static UntypedInt PR_GET_DUMPABLE => 0x3;
public static UntypedInt PR_GET_ENDIAN => 0x13;
public static UntypedInt PR_GET_FPEMU => 0x9;
public static UntypedInt PR_GET_FPEXC => 0xb;
public static UntypedInt PR_GET_KEEPCAPS => 0x7;
public static UntypedInt PR_GET_NAME => 0x10;
public static UntypedInt PR_GET_PDEATHSIG => 0x2;
public static UntypedInt PR_GET_SECCOMP => 0x15;
public static UntypedInt PR_GET_SECUREBITS => 0x1b;
public static UntypedInt PR_GET_TIMERSLACK => 0x1e;
public static UntypedInt PR_GET_TIMING => 0xd;
public static UntypedInt PR_GET_TSC => 0x19;
public static UntypedInt PR_GET_UNALIGN => 0x5;
public static UntypedInt PR_MCE_KILL => 0x21;
public static UntypedInt PR_MCE_KILL_CLEAR => 0x0;
public static UntypedInt PR_MCE_KILL_DEFAULT => 0x2;
public static UntypedInt PR_MCE_KILL_EARLY => 0x1;
public static UntypedInt PR_MCE_KILL_GET => 0x22;
public static UntypedInt PR_MCE_KILL_LATE => 0x0;
public static UntypedInt PR_MCE_KILL_SET => 0x1;
public static UntypedInt PR_SET_DUMPABLE => 0x4;
public static UntypedInt PR_SET_ENDIAN => 0x14;
public static UntypedInt PR_SET_FPEMU => 0xa;
public static UntypedInt PR_SET_FPEXC => 0xc;
public static UntypedInt PR_SET_KEEPCAPS => 0x8;
public static UntypedInt PR_SET_NAME => 0xf;
public static UntypedInt PR_SET_PDEATHSIG => 0x1;
public static UntypedInt PR_SET_PTRACER => 0x59616d61;
public static UntypedInt PR_SET_SECCOMP => 0x16;
public static UntypedInt PR_SET_SECUREBITS => 0x1c;
public static UntypedInt PR_SET_TIMERSLACK => 0x1d;
public static UntypedInt PR_SET_TIMING => 0xe;
public static UntypedInt PR_SET_TSC => 0x1a;
public static UntypedInt PR_SET_UNALIGN => 0x6;
public static UntypedInt PR_TASK_PERF_EVENTS_DISABLE => 0x1f;
public static UntypedInt PR_TASK_PERF_EVENTS_ENABLE => 0x20;
public static UntypedInt PR_TIMING_STATISTICAL => 0x0;
public static UntypedInt PR_TIMING_TIMESTAMP => 0x1;
public static UntypedInt PR_TSC_ENABLE => 0x1;
public static UntypedInt PR_TSC_SIGSEGV => 0x2;
public static UntypedInt PR_UNALIGN_NOPRINT => 0x1;
public static UntypedInt PR_UNALIGN_SIGBUS => 0x2;
public static UntypedInt PTRACE_ARCH_PRCTL => 0x1e;
public static UntypedInt PTRACE_ATTACH => 0x10;
public static UntypedInt PTRACE_CONT => 0x7;
public static UntypedInt PTRACE_DETACH => 0x11;
public static UntypedInt PTRACE_EVENT_CLONE => 0x3;
public static UntypedInt PTRACE_EVENT_EXEC => 0x4;
public static UntypedInt PTRACE_EVENT_EXIT => 0x6;
public static UntypedInt PTRACE_EVENT_FORK => 0x1;
public static UntypedInt PTRACE_EVENT_VFORK => 0x2;
public static UntypedInt PTRACE_EVENT_VFORK_DONE => 0x5;
public static UntypedInt PTRACE_GETEVENTMSG => 0x4201;
public static UntypedInt PTRACE_GETFPREGS => 0xe;
public static UntypedInt PTRACE_GETFPXREGS => 0x12;
public static UntypedInt PTRACE_GETREGS => 0xc;
public static UntypedInt PTRACE_GETREGSET => 0x4204;
public static UntypedInt PTRACE_GETSIGINFO => 0x4202;
public static UntypedInt PTRACE_GET_THREAD_AREA => 0x19;
public static UntypedInt PTRACE_KILL => 0x8;
public static UntypedInt PTRACE_OLDSETOPTIONS => 0x15;
public static UntypedInt PTRACE_O_MASK => 0x7f;
public static UntypedInt PTRACE_O_TRACECLONE => 0x8;
public static UntypedInt PTRACE_O_TRACEEXEC => 0x10;
public static UntypedInt PTRACE_O_TRACEEXIT => 0x40;
public static UntypedInt PTRACE_O_TRACEFORK => 0x2;
public static UntypedInt PTRACE_O_TRACESYSGOOD => 0x1;
public static UntypedInt PTRACE_O_TRACEVFORK => 0x4;
public static UntypedInt PTRACE_O_TRACEVFORKDONE => 0x20;
public static UntypedInt PTRACE_PEEKDATA => 0x2;
public static UntypedInt PTRACE_PEEKTEXT => 0x1;
public static UntypedInt PTRACE_PEEKUSR => 0x3;
public static UntypedInt PTRACE_POKEDATA => 0x5;
public static UntypedInt PTRACE_POKETEXT => 0x4;
public static UntypedInt PTRACE_POKEUSR => 0x6;
public static UntypedInt PTRACE_SETFPREGS => 0xf;
public static UntypedInt PTRACE_SETFPXREGS => 0x13;
public static UntypedInt PTRACE_SETOPTIONS => 0x4200;
public static UntypedInt PTRACE_SETREGS => 0xd;
public static UntypedInt PTRACE_SETREGSET => 0x4205;
public static UntypedInt PTRACE_SETSIGINFO => 0x4203;
public static UntypedInt PTRACE_SET_THREAD_AREA => 0x1a;
public static UntypedInt PTRACE_SINGLEBLOCK => 0x21;
public static UntypedInt PTRACE_SINGLESTEP => 0x9;
public static UntypedInt PTRACE_SYSCALL => 0x18;
public static UntypedInt PTRACE_SYSEMU => 0x1f;
public static UntypedInt PTRACE_SYSEMU_SINGLESTEP => 0x20;
public static UntypedInt PTRACE_TRACEME => 0x0;
public static UntypedInt RLIMIT_AS => 0x9;
public static UntypedInt RLIMIT_CORE => 0x4;
public static UntypedInt RLIMIT_CPU => 0x0;
public static UntypedInt RLIMIT_DATA => 0x2;
public static UntypedInt RLIMIT_FSIZE => 0x1;
public static UntypedInt RLIMIT_NOFILE => 0x7;
public static UntypedInt RLIMIT_STACK => 0x3;
public static UntypedInt RLIM_INFINITY => /* -0x1 */ -1;
public static UntypedInt RTAX_ADVMSS => 0x8;
public static UntypedInt RTAX_CWND => 0x7;
public static UntypedInt RTAX_FEATURES => 0xc;
public static UntypedInt RTAX_FEATURE_ALLFRAG => 0x8;
public static UntypedInt RTAX_FEATURE_ECN => 0x1;
public static UntypedInt RTAX_FEATURE_SACK => 0x2;
public static UntypedInt RTAX_FEATURE_TIMESTAMP => 0x4;
public static UntypedInt RTAX_HOPLIMIT => 0xa;
public static UntypedInt RTAX_INITCWND => 0xb;
public static UntypedInt RTAX_INITRWND => 0xe;
public static UntypedInt RTAX_LOCK => 0x1;
public static UntypedInt RTAX_MAX => 0xe;
public static UntypedInt RTAX_MTU => 0x2;
public static UntypedInt RTAX_REORDERING => 0x9;
public static UntypedInt RTAX_RTO_MIN => 0xd;
public static UntypedInt RTAX_RTT => 0x4;
public static UntypedInt RTAX_RTTVAR => 0x5;
public static UntypedInt RTAX_SSTHRESH => 0x6;
public static UntypedInt RTAX_UNSPEC => 0x0;
public static UntypedInt RTAX_WINDOW => 0x3;
public static UntypedInt RTA_ALIGNTO => 0x4;
public static UntypedInt RTA_MAX => 0x10;
public static UntypedInt RTCF_DIRECTSRC => 0x4000000;
public static UntypedInt RTCF_DOREDIRECT => 0x1000000;
public static UntypedInt RTCF_LOG => 0x2000000;
public static UntypedInt RTCF_MASQ => 0x400000;
public static UntypedInt RTCF_NAT => 0x800000;
public static UntypedInt RTCF_VALVE => 0x200000;
public static UntypedInt RTF_ADDRCLASSMASK => 0xf8000000;
public static UntypedInt RTF_ADDRCONF => 0x40000;
public static UntypedInt RTF_ALLONLINK => 0x20000;
public static UntypedInt RTF_BROADCAST => 0x10000000;
public static UntypedInt RTF_CACHE => 0x1000000;
public static UntypedInt RTF_DEFAULT => 0x10000;
public static UntypedInt RTF_DYNAMIC => 0x10;
public static UntypedInt RTF_FLOW => 0x2000000;
public static UntypedInt RTF_GATEWAY => 0x2;
public static UntypedInt RTF_HOST => 0x4;
public static UntypedInt RTF_INTERFACE => 0x40000000;
public static UntypedInt RTF_IRTT => 0x100;
public static UntypedInt RTF_LINKRT => 0x100000;
public static UntypedInt RTF_LOCAL => 0x80000000;
public static UntypedInt RTF_MODIFIED => 0x20;
public static UntypedInt RTF_MSS => 0x40;
public static UntypedInt RTF_MTU => 0x40;
public static UntypedInt RTF_MULTICAST => 0x20000000;
public static UntypedInt RTF_NAT => 0x8000000;
public static UntypedInt RTF_NOFORWARD => 0x1000;
public static UntypedInt RTF_NONEXTHOP => 0x200000;
public static UntypedInt RTF_NOPMTUDISC => 0x4000;
public static UntypedInt RTF_POLICY => 0x4000000;
public static UntypedInt RTF_REINSTATE => 0x8;
public static UntypedInt RTF_REJECT => 0x200;
public static UntypedInt RTF_STATIC => 0x400;
public static UntypedInt RTF_THROW => 0x2000;
public static UntypedInt RTF_UP => 0x1;
public static UntypedInt RTF_WINDOW => 0x80;
public static UntypedInt RTF_XRESOLVE => 0x800;
public static UntypedInt RTM_BASE => 0x10;
public static UntypedInt RTM_DELACTION => 0x31;
public static UntypedInt RTM_DELADDR => 0x15;
public static UntypedInt RTM_DELADDRLABEL => 0x49;
public static UntypedInt RTM_DELLINK => 0x11;
public static UntypedInt RTM_DELNEIGH => 0x1d;
public static UntypedInt RTM_DELQDISC => 0x25;
public static UntypedInt RTM_DELROUTE => 0x19;
public static UntypedInt RTM_DELRULE => 0x21;
public static UntypedInt RTM_DELTCLASS => 0x29;
public static UntypedInt RTM_DELTFILTER => 0x2d;
public static UntypedInt RTM_F_CLONED => 0x200;
public static UntypedInt RTM_F_EQUALIZE => 0x400;
public static UntypedInt RTM_F_NOTIFY => 0x100;
public static UntypedInt RTM_F_PREFIX => 0x800;
public static UntypedInt RTM_GETACTION => 0x32;
public static UntypedInt RTM_GETADDR => 0x16;
public static UntypedInt RTM_GETADDRLABEL => 0x4a;
public static UntypedInt RTM_GETANYCAST => 0x3e;
public static UntypedInt RTM_GETDCB => 0x4e;
public static UntypedInt RTM_GETLINK => 0x12;
public static UntypedInt RTM_GETMULTICAST => 0x3a;
public static UntypedInt RTM_GETNEIGH => 0x1e;
public static UntypedInt RTM_GETNEIGHTBL => 0x42;
public static UntypedInt RTM_GETQDISC => 0x26;
public static UntypedInt RTM_GETROUTE => 0x1a;
public static UntypedInt RTM_GETRULE => 0x22;
public static UntypedInt RTM_GETTCLASS => 0x2a;
public static UntypedInt RTM_GETTFILTER => 0x2e;
public static UntypedInt RTM_MAX => 0x4f;
public static UntypedInt RTM_NEWACTION => 0x30;
public static UntypedInt RTM_NEWADDR => 0x14;
public static UntypedInt RTM_NEWADDRLABEL => 0x48;
public static UntypedInt RTM_NEWLINK => 0x10;
public static UntypedInt RTM_NEWNDUSEROPT => 0x44;
public static UntypedInt RTM_NEWNEIGH => 0x1c;
public static UntypedInt RTM_NEWNEIGHTBL => 0x40;
public static UntypedInt RTM_NEWPREFIX => 0x34;
public static UntypedInt RTM_NEWQDISC => 0x24;
public static UntypedInt RTM_NEWROUTE => 0x18;
public static UntypedInt RTM_NEWRULE => 0x20;
public static UntypedInt RTM_NEWTCLASS => 0x28;
public static UntypedInt RTM_NEWTFILTER => 0x2c;
public static UntypedInt RTM_NR_FAMILIES => 0x10;
public static UntypedInt RTM_NR_MSGTYPES => 0x40;
public static UntypedInt RTM_SETDCB => 0x4f;
public static UntypedInt RTM_SETLINK => 0x13;
public static UntypedInt RTM_SETNEIGHTBL => 0x43;
public static UntypedInt RTNH_ALIGNTO => 0x4;
public static UntypedInt RTNH_F_DEAD => 0x1;
public static UntypedInt RTNH_F_ONLINK => 0x4;
public static UntypedInt RTNH_F_PERVASIVE => 0x2;
public static UntypedInt RTN_MAX => 0xb;
public static UntypedInt RTPROT_BIRD => 0xc;
public static UntypedInt RTPROT_BOOT => 0x3;
public static UntypedInt RTPROT_DHCP => 0x10;
public static UntypedInt RTPROT_DNROUTED => 0xd;
public static UntypedInt RTPROT_GATED => 0x8;
public static UntypedInt RTPROT_KERNEL => 0x2;
public static UntypedInt RTPROT_MRT => 0xa;
public static UntypedInt RTPROT_NTK => 0xf;
public static UntypedInt RTPROT_RA => 0x9;
public static UntypedInt RTPROT_REDIRECT => 0x1;
public static UntypedInt RTPROT_STATIC => 0x4;
public static UntypedInt RTPROT_UNSPEC => 0x0;
public static UntypedInt RTPROT_XORP => 0xe;
public static UntypedInt RTPROT_ZEBRA => 0xb;
public static UntypedInt RT_CLASS_DEFAULT => 0xfd;
public static UntypedInt RT_CLASS_LOCAL => 0xff;
public static UntypedInt RT_CLASS_MAIN => 0xfe;
public static UntypedInt RT_CLASS_MAX => 0xff;
public static UntypedInt RT_CLASS_UNSPEC => 0x0;
public static UntypedInt RUSAGE_CHILDREN => /* -0x1 */ -1;
public static UntypedInt RUSAGE_SELF => 0x0;
public static UntypedInt RUSAGE_THREAD => 0x1;
public static UntypedInt SCM_CREDENTIALS => 0x2;
public static UntypedInt SCM_RIGHTS => 0x1;
public static UntypedInt SCM_TIMESTAMP => 0x1d;
public static UntypedInt SCM_TIMESTAMPING => 0x25;
public static UntypedInt SCM_TIMESTAMPNS => 0x23;
public static UntypedInt SHUT_RD => 0x0;
public static UntypedInt SHUT_RDWR => 0x2;
public static UntypedInt SHUT_WR => 0x1;
public static UntypedInt SIOCADDDLCI => 0x8980;
public static UntypedInt SIOCADDMULTI => 0x8931;
public static UntypedInt SIOCADDRT => 0x890b;
public static UntypedInt SIOCATMARK => 0x8905;
public static UntypedInt SIOCDARP => 0x8953;
public static UntypedInt SIOCDELDLCI => 0x8981;
public static UntypedInt SIOCDELMULTI => 0x8932;
public static UntypedInt SIOCDELRT => 0x890c;
public static UntypedInt SIOCDEVPRIVATE => 0x89f0;
public static UntypedInt SIOCDIFADDR => 0x8936;
public static UntypedInt SIOCDRARP => 0x8960;
public static UntypedInt SIOCGARP => 0x8954;
public static UntypedInt SIOCGIFADDR => 0x8915;
public static UntypedInt SIOCGIFBR => 0x8940;
public static UntypedInt SIOCGIFBRDADDR => 0x8919;
public static UntypedInt SIOCGIFCONF => 0x8912;
public static UntypedInt SIOCGIFCOUNT => 0x8938;
public static UntypedInt SIOCGIFDSTADDR => 0x8917;
public static UntypedInt SIOCGIFENCAP => 0x8925;
public static UntypedInt SIOCGIFFLAGS => 0x8913;
public static UntypedInt SIOCGIFHWADDR => 0x8927;
public static UntypedInt SIOCGIFINDEX => 0x8933;
public static UntypedInt SIOCGIFMAP => 0x8970;
public static UntypedInt SIOCGIFMEM => 0x891f;
public static UntypedInt SIOCGIFMETRIC => 0x891d;
public static UntypedInt SIOCGIFMTU => 0x8921;
public static UntypedInt SIOCGIFNAME => 0x8910;
public static UntypedInt SIOCGIFNETMASK => 0x891b;
public static UntypedInt SIOCGIFPFLAGS => 0x8935;
public static UntypedInt SIOCGIFSLAVE => 0x8929;
public static UntypedInt SIOCGIFTXQLEN => 0x8942;
public static UntypedInt SIOCGPGRP => 0x8904;
public static UntypedInt SIOCGRARP => 0x8961;
public static UntypedInt SIOCGSTAMP => 0x8906;
public static UntypedInt SIOCGSTAMPNS => 0x8907;
public static UntypedInt SIOCPROTOPRIVATE => 0x89e0;
public static UntypedInt SIOCRTMSG => 0x890d;
public static UntypedInt SIOCSARP => 0x8955;
public static UntypedInt SIOCSIFADDR => 0x8916;
public static UntypedInt SIOCSIFBR => 0x8941;
public static UntypedInt SIOCSIFBRDADDR => 0x891a;
public static UntypedInt SIOCSIFDSTADDR => 0x8918;
public static UntypedInt SIOCSIFENCAP => 0x8926;
public static UntypedInt SIOCSIFFLAGS => 0x8914;
public static UntypedInt SIOCSIFHWADDR => 0x8924;
public static UntypedInt SIOCSIFHWBROADCAST => 0x8937;
public static UntypedInt SIOCSIFLINK => 0x8911;
public static UntypedInt SIOCSIFMAP => 0x8971;
public static UntypedInt SIOCSIFMEM => 0x8920;
public static UntypedInt SIOCSIFMETRIC => 0x891e;
public static UntypedInt SIOCSIFMTU => 0x8922;
public static UntypedInt SIOCSIFNAME => 0x8923;
public static UntypedInt SIOCSIFNETMASK => 0x891c;
public static UntypedInt SIOCSIFPFLAGS => 0x8934;
public static UntypedInt SIOCSIFSLAVE => 0x8930;
public static UntypedInt SIOCSIFTXQLEN => 0x8943;
public static UntypedInt SIOCSPGRP => 0x8902;
public static UntypedInt SIOCSRARP => 0x8962;
public static UntypedInt SOCK_CLOEXEC => 0x80000;
public static UntypedInt SOCK_DCCP => 0x6;
public static UntypedInt SOCK_DGRAM => 0x2;
public static UntypedInt SOCK_NONBLOCK => 0x800;
public static UntypedInt SOCK_PACKET => 0xa;
public static UntypedInt SOCK_RAW => 0x3;
public static UntypedInt SOCK_RDM => 0x4;
public static UntypedInt SOCK_SEQPACKET => 0x5;
public static UntypedInt SOCK_STREAM => 0x1;
public static UntypedInt SOL_AAL => 0x109;
public static UntypedInt SOL_ATM => 0x108;
public static UntypedInt SOL_DECNET => 0x105;
public static UntypedInt SOL_ICMPV6 => 0x3a;
public static UntypedInt SOL_IP => 0x0;
public static UntypedInt SOL_IPV6 => 0x29;
public static UntypedInt SOL_IRDA => 0x10a;
public static UntypedInt SOL_PACKET => 0x107;
public static UntypedInt SOL_RAW => 0xff;
public static UntypedInt SOL_SOCKET => 0x1;
public static UntypedInt SOL_TCP => 0x6;
public static UntypedInt SOL_X25 => 0x106;
public static UntypedInt SOMAXCONN => 0x80;
public static UntypedInt SO_ACCEPTCONN => 0x1e;
public static UntypedInt SO_ATTACH_FILTER => 0x1a;
public static UntypedInt SO_BINDTODEVICE => 0x19;
public static UntypedInt SO_BROADCAST => 0x6;
public static UntypedInt SO_BSDCOMPAT => 0xe;
public static UntypedInt SO_DEBUG => 0x1;
public static UntypedInt SO_DETACH_FILTER => 0x1b;
public static UntypedInt SO_DOMAIN => 0x27;
public static UntypedInt SO_DONTROUTE => 0x5;
public static UntypedInt SO_ERROR => 0x4;
public static UntypedInt SO_KEEPALIVE => 0x9;
public static UntypedInt SO_LINGER => 0xd;
public static UntypedInt SO_MARK => 0x24;
public static UntypedInt SO_NO_CHECK => 0xb;
public static UntypedInt SO_OOBINLINE => 0xa;
public static UntypedInt SO_PASSCRED => 0x10;
public static UntypedInt SO_PASSSEC => 0x22;
public static UntypedInt SO_PEERCRED => 0x11;
public static UntypedInt SO_PEERNAME => 0x1c;
public static UntypedInt SO_PEERSEC => 0x1f;
public static UntypedInt SO_PRIORITY => 0xc;
public static UntypedInt SO_PROTOCOL => 0x26;
public static UntypedInt SO_RCVBUF => 0x8;
public static UntypedInt SO_RCVBUFFORCE => 0x21;
public static UntypedInt SO_RCVLOWAT => 0x12;
public static UntypedInt SO_RCVTIMEO => 0x14;
public static UntypedInt SO_REUSEADDR => 0x2;
public static UntypedInt SO_RXQ_OVFL => 0x28;
public static UntypedInt SO_SECURITY_AUTHENTICATION => 0x16;
public static UntypedInt SO_SECURITY_ENCRYPTION_NETWORK => 0x18;
public static UntypedInt SO_SECURITY_ENCRYPTION_TRANSPORT => 0x17;
public static UntypedInt SO_SNDBUF => 0x7;
public static UntypedInt SO_SNDBUFFORCE => 0x20;
public static UntypedInt SO_SNDLOWAT => 0x13;
public static UntypedInt SO_SNDTIMEO => 0x15;
public static UntypedInt SO_TIMESTAMP => 0x1d;
public static UntypedInt SO_TIMESTAMPING => 0x25;
public static UntypedInt SO_TIMESTAMPNS => 0x23;
public static UntypedInt SO_TYPE => 0x3;
public static UntypedInt S_BLKSIZE => 0x200;
public static UntypedInt S_IEXEC => 0x40;
public static UntypedInt S_IFBLK => 0x6000;
public static UntypedInt S_IFCHR => 0x2000;
public static UntypedInt S_IFDIR => 0x4000;
public static UntypedInt S_IFIFO => 0x1000;
public static UntypedInt S_IFLNK => 0xa000;
public static UntypedInt S_IFMT => 0xf000;
public static UntypedInt S_IFREG => 0x8000;
public static UntypedInt S_IFSOCK => 0xc000;
public static UntypedInt S_IREAD => 0x100;
public static UntypedInt S_IRGRP => 0x20;
public static UntypedInt S_IROTH => 0x4;
public static UntypedInt S_IRUSR => 0x100;
public static UntypedInt S_IRWXG => 0x38;
public static UntypedInt S_IRWXO => 0x7;
public static UntypedInt S_IRWXU => 0x1c0;
public static UntypedInt S_ISGID => 0x400;
public static UntypedInt S_ISUID => 0x800;
public static UntypedInt S_ISVTX => 0x200;
public static UntypedInt S_IWGRP => 0x10;
public static UntypedInt S_IWOTH => 0x2;
public static UntypedInt S_IWRITE => 0x80;
public static UntypedInt S_IWUSR => 0x80;
public static UntypedInt S_IXGRP => 0x8;
public static UntypedInt S_IXOTH => 0x1;
public static UntypedInt S_IXUSR => 0x40;
public static UntypedInt TCIFLUSH => 0x0;
public static UntypedInt TCIOFLUSH => 0x2;
public static UntypedInt TCOFLUSH => 0x1;
public static UntypedInt TCP_CONGESTION => 0xd;
public static UntypedInt TCP_CORK => 0x3;
public static UntypedInt TCP_DEFER_ACCEPT => 0x9;
public static UntypedInt TCP_INFO => 0xb;
public static UntypedInt TCP_KEEPCNT => 0x6;
public static UntypedInt TCP_KEEPIDLE => 0x4;
public static UntypedInt TCP_KEEPINTVL => 0x5;
public static UntypedInt TCP_LINGER2 => 0x8;
public static UntypedInt TCP_MAXSEG => 0x2;
public static UntypedInt TCP_MAXWIN => 0xffff;
public static UntypedInt TCP_MAX_WINSHIFT => 0xe;
public static UntypedInt TCP_MD5SIG => 0xe;
public static UntypedInt TCP_MD5SIG_MAXKEYLEN => 0x50;
public static UntypedInt TCP_MSS => 0x200;
public static UntypedInt TCP_NODELAY => 0x1;
public static UntypedInt TCP_QUICKACK => 0xc;
public static UntypedInt TCP_SYNCNT => 0x7;
public static UntypedInt TCP_WINDOW_CLAMP => 0xa;
public static UntypedInt TIOCCBRK => 0x5428;
public static UntypedInt TIOCCONS => 0x541d;
public static UntypedInt TIOCEXCL => 0x540c;
public static UntypedInt TIOCGDEV => 0x80045432;
public static UntypedInt TIOCGETD => 0x5424;
public static UntypedInt TIOCGICOUNT => 0x545d;
public static UntypedInt TIOCGLCKTRMIOS => 0x5456;
public static UntypedInt TIOCGPGRP => 0x540f;
public static UntypedInt TIOCGPTN => 0x80045430;
public static UntypedInt TIOCGRS485 => 0x542e;
public static UntypedInt TIOCGSERIAL => 0x541e;
public static UntypedInt TIOCGSID => 0x5429;
public static UntypedInt TIOCGSOFTCAR => 0x5419;
public static UntypedInt TIOCGWINSZ => 0x5413;
public static UntypedInt TIOCINQ => 0x541b;
public static UntypedInt TIOCLINUX => 0x541c;
public static UntypedInt TIOCMBIC => 0x5417;
public static UntypedInt TIOCMBIS => 0x5416;
public static UntypedInt TIOCMGET => 0x5415;
public static UntypedInt TIOCMIWAIT => 0x545c;
public static UntypedInt TIOCMSET => 0x5418;
public static UntypedInt TIOCM_CAR => 0x40;
public static UntypedInt TIOCM_CD => 0x40;
public static UntypedInt TIOCM_CTS => 0x20;
public static UntypedInt TIOCM_DSR => 0x100;
public static UntypedInt TIOCM_DTR => 0x2;
public static UntypedInt TIOCM_LE => 0x1;
public static UntypedInt TIOCM_RI => 0x80;
public static UntypedInt TIOCM_RNG => 0x80;
public static UntypedInt TIOCM_RTS => 0x4;
public static UntypedInt TIOCM_SR => 0x10;
public static UntypedInt TIOCM_ST => 0x8;
public static UntypedInt TIOCNOTTY => 0x5422;
public static UntypedInt TIOCNXCL => 0x540d;
public static UntypedInt TIOCOUTQ => 0x5411;
public static UntypedInt TIOCPKT => 0x5420;
public static UntypedInt TIOCPKT_DATA => 0x0;
public static UntypedInt TIOCPKT_DOSTOP => 0x20;
public static UntypedInt TIOCPKT_FLUSHREAD => 0x1;
public static UntypedInt TIOCPKT_FLUSHWRITE => 0x2;
public static UntypedInt TIOCPKT_IOCTL => 0x40;
public static UntypedInt TIOCPKT_NOSTOP => 0x10;
public static UntypedInt TIOCPKT_START => 0x8;
public static UntypedInt TIOCPKT_STOP => 0x4;
public static UntypedInt TIOCSBRK => 0x5427;
public static UntypedInt TIOCSCTTY => 0x540e;
public static UntypedInt TIOCSERCONFIG => 0x5453;
public static UntypedInt TIOCSERGETLSR => 0x5459;
public static UntypedInt TIOCSERGETMULTI => 0x545a;
public static UntypedInt TIOCSERGSTRUCT => 0x5458;
public static UntypedInt TIOCSERGWILD => 0x5454;
public static UntypedInt TIOCSERSETMULTI => 0x545b;
public static UntypedInt TIOCSERSWILD => 0x5455;
public static UntypedInt TIOCSER_TEMT => 0x1;
public static UntypedInt TIOCSETD => 0x5423;
public static UntypedInt TIOCSIG => 0x40045436;
public static UntypedInt TIOCSLCKTRMIOS => 0x5457;
public static UntypedInt TIOCSPGRP => 0x5410;
public static UntypedInt TIOCSPTLCK => 0x40045431;
public static UntypedInt TIOCSRS485 => 0x542f;
public static UntypedInt TIOCSSERIAL => 0x541f;
public static UntypedInt TIOCSSOFTCAR => 0x541a;
public static UntypedInt TIOCSTI => 0x5412;
public static UntypedInt TIOCSWINSZ => 0x5414;
public static UntypedInt TUNATTACHFILTER => 0x401054d5;
public static UntypedInt TUNDETACHFILTER => 0x401054d6;
public static UntypedInt TUNGETFEATURES => 0x800454cf;
public static UntypedInt TUNGETIFF => 0x800454d2;
public static UntypedInt TUNGETSNDBUF => 0x800454d3;
public static UntypedInt TUNGETVNETHDRSZ => 0x800454d7;
public static UntypedInt TUNSETDEBUG => 0x400454c9;
public static UntypedInt TUNSETGROUP => 0x400454ce;
public static UntypedInt TUNSETIFF => 0x400454ca;
public static UntypedInt TUNSETLINK => 0x400454cd;
public static UntypedInt TUNSETNOCSUM => 0x400454c8;
public static UntypedInt TUNSETOFFLOAD => 0x400454d0;
public static UntypedInt TUNSETOWNER => 0x400454cc;
public static UntypedInt TUNSETPERSIST => 0x400454cb;
public static UntypedInt TUNSETSNDBUF => 0x400454d4;
public static UntypedInt TUNSETTXFILTER => 0x400454d1;
public static UntypedInt TUNSETVNETHDRSZ => 0x400454d8;
public static UntypedInt WALL => 0x40000000;
public static UntypedInt WCLONE => 0x80000000;
public static UntypedInt WCONTINUED => 0x8;
public static UntypedInt WEXITED => 0x4;
public static UntypedInt WNOHANG => 0x1;
public static UntypedInt WNOTHREAD => 0x20000000;
public static UntypedInt WNOWAIT => 0x1000000;
public static UntypedInt WORDSIZE => 0x40;
public static UntypedInt WSTOPPED => 0x2;
public static UntypedInt WUNTRACED => 0x2;

// Errors
public static Errno E2BIG => /* Errno(0x7) */ 7;

public static Errno EACCES => /* Errno(0xd) */ 13;

public static Errno EADDRINUSE => /* Errno(0x62) */ 98;

public static Errno EADDRNOTAVAIL => /* Errno(0x63) */ 99;

public static Errno EADV => /* Errno(0x44) */ 68;

public static Errno EAFNOSUPPORT => /* Errno(0x61) */ 97;

public static Errno EAGAIN => /* Errno(0xb) */ 11;

public static Errno EALREADY => /* Errno(0x72) */ 114;

public static Errno EBADE => /* Errno(0x34) */ 52;

public static Errno EBADF => /* Errno(0x9) */ 9;

public static Errno EBADFD => /* Errno(0x4d) */ 77;

public static Errno EBADMSG => /* Errno(0x4a) */ 74;

public static Errno EBADR => /* Errno(0x35) */ 53;

public static Errno EBADRQC => /* Errno(0x38) */ 56;

public static Errno EBADSLT => /* Errno(0x39) */ 57;

public static Errno EBFONT => /* Errno(0x3b) */ 59;

public static Errno EBUSY => /* Errno(0x10) */ 16;

public static Errno ECANCELED => /* Errno(0x7d) */ 125;

public static Errno ECHILD => /* Errno(0xa) */ 10;

public static Errno ECHRNG => /* Errno(0x2c) */ 44;

public static Errno ECOMM => /* Errno(0x46) */ 70;

public static Errno ECONNABORTED => /* Errno(0x67) */ 103;

public static Errno ECONNREFUSED => /* Errno(0x6f) */ 111;

public static Errno ECONNRESET => /* Errno(0x68) */ 104;

public static Errno EDEADLK => /* Errno(0x23) */ 35;

public static Errno EDEADLOCK => /* Errno(0x23) */ 35;

public static Errno EDESTADDRREQ => /* Errno(0x59) */ 89;

public static Errno EDOM => /* Errno(0x21) */ 33;

public static Errno EDOTDOT => /* Errno(0x49) */ 73;

public static Errno EDQUOT => /* Errno(0x7a) */ 122;

public static Errno EEXIST => /* Errno(0x11) */ 17;

public static Errno EFAULT => /* Errno(0xe) */ 14;

public static Errno EFBIG => /* Errno(0x1b) */ 27;

public static Errno EHOSTDOWN => /* Errno(0x70) */ 112;

public static Errno EHOSTUNREACH => /* Errno(0x71) */ 113;

public static Errno EIDRM => /* Errno(0x2b) */ 43;

public static Errno EILSEQ => /* Errno(0x54) */ 84;

public static Errno EINPROGRESS => /* Errno(0x73) */ 115;

public static Errno EINTR => /* Errno(0x4) */ 4;

public static Errno EINVAL => /* Errno(0x16) */ 22;

public static Errno EIO => /* Errno(0x5) */ 5;

public static Errno EISCONN => /* Errno(0x6a) */ 106;

public static Errno EISDIR => /* Errno(0x15) */ 21;

public static Errno EISNAM => /* Errno(0x78) */ 120;

public static Errno EKEYEXPIRED => /* Errno(0x7f) */ 127;

public static Errno EKEYREJECTED => /* Errno(0x81) */ 129;

public static Errno EKEYREVOKED => /* Errno(0x80) */ 128;

public static Errno EL2HLT => /* Errno(0x33) */ 51;

public static Errno EL2NSYNC => /* Errno(0x2d) */ 45;

public static Errno EL3HLT => /* Errno(0x2e) */ 46;

public static Errno EL3RST => /* Errno(0x2f) */ 47;

public static Errno ELIBACC => /* Errno(0x4f) */ 79;

public static Errno ELIBBAD => /* Errno(0x50) */ 80;

public static Errno ELIBEXEC => /* Errno(0x53) */ 83;

public static Errno ELIBMAX => /* Errno(0x52) */ 82;

public static Errno ELIBSCN => /* Errno(0x51) */ 81;

public static Errno ELNRNG => /* Errno(0x30) */ 48;

public static Errno ELOOP => /* Errno(0x28) */ 40;

public static Errno EMEDIUMTYPE => /* Errno(0x7c) */ 124;

public static Errno EMFILE => /* Errno(0x18) */ 24;

public static Errno EMLINK => /* Errno(0x1f) */ 31;

public static Errno EMSGSIZE => /* Errno(0x5a) */ 90;

public static Errno EMULTIHOP => /* Errno(0x48) */ 72;

public static Errno ENAMETOOLONG => /* Errno(0x24) */ 36;

public static Errno ENAVAIL => /* Errno(0x77) */ 119;

public static Errno ENETDOWN => /* Errno(0x64) */ 100;

public static Errno ENETRESET => /* Errno(0x66) */ 102;

public static Errno ENETUNREACH => /* Errno(0x65) */ 101;

public static Errno ENFILE => /* Errno(0x17) */ 23;

public static Errno ENOANO => /* Errno(0x37) */ 55;

public static Errno ENOBUFS => /* Errno(0x69) */ 105;

public static Errno ENOCSI => /* Errno(0x32) */ 50;

public static Errno ENODATA => /* Errno(0x3d) */ 61;

public static Errno ENODEV => /* Errno(0x13) */ 19;

public static Errno ENOENT => /* Errno(0x2) */ 2;

public static Errno ENOEXEC => /* Errno(0x8) */ 8;

public static Errno ENOKEY => /* Errno(0x7e) */ 126;

public static Errno ENOLCK => /* Errno(0x25) */ 37;

public static Errno ENOLINK => /* Errno(0x43) */ 67;

public static Errno ENOMEDIUM => /* Errno(0x7b) */ 123;

public static Errno ENOMEM => /* Errno(0xc) */ 12;

public static Errno ENOMSG => /* Errno(0x2a) */ 42;

public static Errno ENONET => /* Errno(0x40) */ 64;

public static Errno ENOPKG => /* Errno(0x41) */ 65;

public static Errno ENOPROTOOPT => /* Errno(0x5c) */ 92;

public static Errno ENOSPC => /* Errno(0x1c) */ 28;

public static Errno ENOSR => /* Errno(0x3f) */ 63;

public static Errno ENOSTR => /* Errno(0x3c) */ 60;

public static Errno ENOSYS => /* Errno(0x26) */ 38;

public static Errno ENOTBLK => /* Errno(0xf) */ 15;

public static Errno ENOTCONN => /* Errno(0x6b) */ 107;

public static Errno ENOTDIR => /* Errno(0x14) */ 20;

public static Errno ENOTEMPTY => /* Errno(0x27) */ 39;

public static Errno ENOTNAM => /* Errno(0x76) */ 118;

public static Errno ENOTRECOVERABLE => /* Errno(0x83) */ 131;

public static Errno ENOTSOCK => /* Errno(0x58) */ 88;

public static Errno ENOTSUP => /* Errno(0x5f) */ 95;

public static Errno ENOTTY => /* Errno(0x19) */ 25;

public static Errno ENOTUNIQ => /* Errno(0x4c) */ 76;

public static Errno ENXIO => /* Errno(0x6) */ 6;

public static Errno EOPNOTSUPP => /* Errno(0x5f) */ 95;

public static Errno EOVERFLOW => /* Errno(0x4b) */ 75;

public static Errno EOWNERDEAD => /* Errno(0x82) */ 130;

public static Errno EPERM => /* Errno(0x1) */ 1;

public static Errno EPFNOSUPPORT => /* Errno(0x60) */ 96;

public static Errno EPIPE => /* Errno(0x20) */ 32;

public static Errno EPROTO => /* Errno(0x47) */ 71;

public static Errno EPROTONOSUPPORT => /* Errno(0x5d) */ 93;

public static Errno EPROTOTYPE => /* Errno(0x5b) */ 91;

public static Errno ERANGE => /* Errno(0x22) */ 34;

public static Errno EREMCHG => /* Errno(0x4e) */ 78;

public static Errno EREMOTE => /* Errno(0x42) */ 66;

public static Errno EREMOTEIO => /* Errno(0x79) */ 121;

public static Errno ERESTART => /* Errno(0x55) */ 85;

public static Errno ERFKILL => /* Errno(0x84) */ 132;

public static Errno EROFS => /* Errno(0x1e) */ 30;

public static Errno ESHUTDOWN => /* Errno(0x6c) */ 108;

public static Errno ESOCKTNOSUPPORT => /* Errno(0x5e) */ 94;

public static Errno ESPIPE => /* Errno(0x1d) */ 29;

public static Errno ESRCH => /* Errno(0x3) */ 3;

public static Errno ESRMNT => /* Errno(0x45) */ 69;

public static Errno ESTALE => /* Errno(0x74) */ 116;

public static Errno ESTRPIPE => /* Errno(0x56) */ 86;

public static Errno ETIME => /* Errno(0x3e) */ 62;

public static Errno ETIMEDOUT => /* Errno(0x6e) */ 110;

public static Errno ETOOMANYREFS => /* Errno(0x6d) */ 109;

public static Errno ETXTBSY => /* Errno(0x1a) */ 26;

public static Errno EUCLEAN => /* Errno(0x75) */ 117;

public static Errno EUNATCH => /* Errno(0x31) */ 49;

public static Errno EUSERS => /* Errno(0x57) */ 87;

public static Errno EWOULDBLOCK => /* Errno(0xb) */ 11;

public static Errno EXDEV => /* Errno(0x12) */ 18;

public static Errno EXFULL => /* Errno(0x36) */ 54;

// Signals
public static ΔSignal SIGABRT => /* Signal(0x6) */ 6;

public static ΔSignal SIGALRM => /* Signal(0xe) */ 14;

public static ΔSignal SIGBUS => /* Signal(0x7) */ 7;

public static ΔSignal SIGCHLD => /* Signal(0x11) */ 17;

public static ΔSignal SIGCLD => /* Signal(0x11) */ 17;

public static ΔSignal SIGCONT => /* Signal(0x12) */ 18;

public static ΔSignal SIGFPE => /* Signal(0x8) */ 8;

public static ΔSignal SIGHUP => /* Signal(0x1) */ 1;

public static ΔSignal SIGILL => /* Signal(0x4) */ 4;

public static ΔSignal SIGINT => /* Signal(0x2) */ 2;

public static ΔSignal SIGIO => /* Signal(0x1d) */ 29;

public static ΔSignal SIGIOT => /* Signal(0x6) */ 6;

public static ΔSignal SIGKILL => /* Signal(0x9) */ 9;

public static ΔSignal SIGPIPE => /* Signal(0xd) */ 13;

public static ΔSignal SIGPOLL => /* Signal(0x1d) */ 29;

public static ΔSignal SIGPROF => /* Signal(0x1b) */ 27;

public static ΔSignal SIGPWR => /* Signal(0x1e) */ 30;

public static ΔSignal SIGQUIT => /* Signal(0x3) */ 3;

public static ΔSignal SIGSEGV => /* Signal(0xb) */ 11;

public static ΔSignal SIGSTKFLT => /* Signal(0x10) */ 16;

public static ΔSignal SIGSTOP => /* Signal(0x13) */ 19;

public static ΔSignal SIGSYS => /* Signal(0x1f) */ 31;

public static ΔSignal SIGTERM => /* Signal(0xf) */ 15;

public static ΔSignal SIGTRAP => /* Signal(0x5) */ 5;

public static ΔSignal SIGTSTP => /* Signal(0x14) */ 20;

public static ΔSignal SIGTTIN => /* Signal(0x15) */ 21;

public static ΔSignal SIGTTOU => /* Signal(0x16) */ 22;

public static ΔSignal SIGUNUSED => /* Signal(0x1f) */ 31;

public static ΔSignal SIGURG => /* Signal(0x17) */ 23;

public static ΔSignal SIGUSR1 => /* Signal(0xa) */ 10;

public static ΔSignal SIGUSR2 => /* Signal(0xc) */ 12;

public static ΔSignal SIGVTALRM => /* Signal(0x1a) */ 26;

public static ΔSignal SIGWINCH => /* Signal(0x1c) */ 28;

public static ΔSignal SIGXCPU => /* Signal(0x18) */ 24;

public static ΔSignal SIGXFSZ => /* Signal(0x19) */ 25;

// Error table
internal static array<@string> errors = new array<@string>(133){
    [1] = "operation not permitted"u8,
    [2] = "no such file or directory"u8,
    [3] = "no such process"u8,
    [4] = "interrupted system call"u8,
    [5] = "input/output error"u8,
    [6] = "no such device or address"u8,
    [7] = "argument list too long"u8,
    [8] = "exec format error"u8,
    [9] = "bad file descriptor"u8,
    [10] = "no child processes"u8,
    [11] = "resource temporarily unavailable"u8,
    [12] = "cannot allocate memory"u8,
    [13] = "permission denied"u8,
    [14] = "bad address"u8,
    [15] = "block device required"u8,
    [16] = "device or resource busy"u8,
    [17] = "file exists"u8,
    [18] = "invalid cross-device link"u8,
    [19] = "no such device"u8,
    [20] = "not a directory"u8,
    [21] = "is a directory"u8,
    [22] = "invalid argument"u8,
    [23] = "too many open files in system"u8,
    [24] = "too many open files"u8,
    [25] = "inappropriate ioctl for device"u8,
    [26] = "text file busy"u8,
    [27] = "file too large"u8,
    [28] = "no space left on device"u8,
    [29] = "illegal seek"u8,
    [30] = "read-only file system"u8,
    [31] = "too many links"u8,
    [32] = "broken pipe"u8,
    [33] = "numerical argument out of domain"u8,
    [34] = "numerical result out of range"u8,
    [35] = "resource deadlock avoided"u8,
    [36] = "file name too long"u8,
    [37] = "no locks available"u8,
    [38] = "function not implemented"u8,
    [39] = "directory not empty"u8,
    [40] = "too many levels of symbolic links"u8,
    [42] = "no message of desired type"u8,
    [43] = "identifier removed"u8,
    [44] = "channel number out of range"u8,
    [45] = "level 2 not synchronized"u8,
    [46] = "level 3 halted"u8,
    [47] = "level 3 reset"u8,
    [48] = "link number out of range"u8,
    [49] = "protocol driver not attached"u8,
    [50] = "no CSI structure available"u8,
    [51] = "level 2 halted"u8,
    [52] = "invalid exchange"u8,
    [53] = "invalid request descriptor"u8,
    [54] = "exchange full"u8,
    [55] = "no anode"u8,
    [56] = "invalid request code"u8,
    [57] = "invalid slot"u8,
    [59] = "bad font file format"u8,
    [60] = "device not a stream"u8,
    [61] = "no data available"u8,
    [62] = "timer expired"u8,
    [63] = "out of streams resources"u8,
    [64] = "machine is not on the network"u8,
    [65] = "package not installed"u8,
    [66] = "object is remote"u8,
    [67] = "link has been severed"u8,
    [68] = "advertise error"u8,
    [69] = "srmount error"u8,
    [70] = "communication error on send"u8,
    [71] = "protocol error"u8,
    [72] = "multihop attempted"u8,
    [73] = "RFS specific error"u8,
    [74] = "bad message"u8,
    [75] = "value too large for defined data type"u8,
    [76] = "name not unique on network"u8,
    [77] = "file descriptor in bad state"u8,
    [78] = "remote address changed"u8,
    [79] = "can not access a needed shared library"u8,
    [80] = "accessing a corrupted shared library"u8,
    [81] = ".lib section in a.out corrupted"u8,
    [82] = "attempting to link in too many shared libraries"u8,
    [83] = "cannot exec a shared library directly"u8,
    [84] = "invalid or incomplete multibyte or wide character"u8,
    [85] = "interrupted system call should be restarted"u8,
    [86] = "streams pipe error"u8,
    [87] = "too many users"u8,
    [88] = "socket operation on non-socket"u8,
    [89] = "destination address required"u8,
    [90] = "message too long"u8,
    [91] = "protocol wrong type for socket"u8,
    [92] = "protocol not available"u8,
    [93] = "protocol not supported"u8,
    [94] = "socket type not supported"u8,
    [95] = "operation not supported"u8,
    [96] = "protocol family not supported"u8,
    [97] = "address family not supported by protocol"u8,
    [98] = "address already in use"u8,
    [99] = "cannot assign requested address"u8,
    [100] = "network is down"u8,
    [101] = "network is unreachable"u8,
    [102] = "network dropped connection on reset"u8,
    [103] = "software caused connection abort"u8,
    [104] = "connection reset by peer"u8,
    [105] = "no buffer space available"u8,
    [106] = "transport endpoint is already connected"u8,
    [107] = "transport endpoint is not connected"u8,
    [108] = "cannot send after transport endpoint shutdown"u8,
    [109] = "too many references: cannot splice"u8,
    [110] = "connection timed out"u8,
    [111] = "connection refused"u8,
    [112] = "host is down"u8,
    [113] = "no route to host"u8,
    [114] = "operation already in progress"u8,
    [115] = "operation now in progress"u8,
    [116] = "stale NFS file handle"u8,
    [117] = "structure needs cleaning"u8,
    [118] = "not a XENIX named type file"u8,
    [119] = "no XENIX semaphores available"u8,
    [120] = "is a named type file"u8,
    [121] = "remote I/O error"u8,
    [122] = "disk quota exceeded"u8,
    [123] = "no medium found"u8,
    [124] = "wrong medium type"u8,
    [125] = "operation canceled"u8,
    [126] = "required key not available"u8,
    [127] = "key has expired"u8,
    [128] = "key has been revoked"u8,
    [129] = "key was rejected by service"u8,
    [130] = "owner died"u8,
    [131] = "state not recoverable"u8,
    [132] = "operation not possible due to RF-kill"u8
};

// Signal table
internal static array<@string> signals = new array<@string>(32){
    [1] = "hangup"u8,
    [2] = "interrupt"u8,
    [3] = "quit"u8,
    [4] = "illegal instruction"u8,
    [5] = "trace/breakpoint trap"u8,
    [6] = "aborted"u8,
    [7] = "bus error"u8,
    [8] = "floating point exception"u8,
    [9] = "killed"u8,
    [10] = "user defined signal 1"u8,
    [11] = "segmentation fault"u8,
    [12] = "user defined signal 2"u8,
    [13] = "broken pipe"u8,
    [14] = "alarm clock"u8,
    [15] = "terminated"u8,
    [16] = "stack fault"u8,
    [17] = "child exited"u8,
    [18] = "continued"u8,
    [19] = "stopped (signal)"u8,
    [20] = "stopped"u8,
    [21] = "stopped (tty input)"u8,
    [22] = "stopped (tty output)"u8,
    [23] = "urgent I/O condition"u8,
    [24] = "CPU time limit exceeded"u8,
    [25] = "file size limit exceeded"u8,
    [26] = "virtual timer expired"u8,
    [27] = "profiling timer expired"u8,
    [28] = "window changed"u8,
    [29] = "I/O possible"u8,
    [30] = "power failure"u8,
    [31] = "bad system call"u8
};

} // end syscall_package
