// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("hash", new string[]
        {
            "example_test.go",
            "hash.go",
            "marshal_test.go",
        }, new string[]
        {
            "adler32",
            "crc32",
            "crc64",
            "fnv",
            "maphash",
        });
        registry.Add("TestMarshalHash", hash_test_package.TestMarshalHash, "marshal_test.go", 59);
        return TestHost.Run(registry, args);
    }
}
