// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.index;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("index/suffixarray", new string[]
        {
            "../../testdata/Isaac.Newton-Opticks.txt",
            "example_test.go",
            "gen.go",
            "sais.go",
            "sais2.go",
            "suffixarray.go",
            "suffixarray_test.go",
        });
        registry.Add("TestIndex32", suffixarray_internal_test_package.TestIndex32, "suffixarray_test.go", 306);
        registry.Add("TestIndex64", suffixarray_internal_test_package.TestIndex64, "suffixarray_test.go", 310);
        registry.Add("TestNew32", suffixarray_internal_test_package.TestNew32, "suffixarray_test.go", 318);
        registry.Add("TestNew64", suffixarray_internal_test_package.TestNew64, "suffixarray_test.go", 330);
        return TestHost.Run(registry, args);
    }
}
