// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.os.exec.@internal;

using go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("os/exec/internal/fdtest", new string[]
        {
            "exists_plan9.go",
            "exists_test.go",
            "exists_unix.go",
            "exists_windows.go",
        });
        registry.Add("TestExists", fdtest_internal_test_package.TestExists, "exists_test.go", 13);
        return TestHost.Run(registry, args);
    }
}
