// Code generated by go2cs test conversion. DO NOT EDIT.
namespace go.go;

using global::go.testing_runtime;

internal static class Go2CsTestHost
{
    public static int Main(string[] args)
    {
        TestRegistry registry = new("go/importer", new string[]
        {
            "importer.go",
            "importer_test.go",
        });
        registry.Add("TestForCompiler", importer_internal_test_package.TestForCompiler, "importer_test.go", 22);
        registry.SetTestMain(importer_internal_test_package.TestMain);
        return TestHost.Run(registry, args);
    }
}
